// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EffectiveRate struct {
	TenantID      int64
	BaseCurrency  string
	QuoteCurrency string
	Rate          pgtype.Numeric
	ConfirmedByID int64
	ConfirmedBy   string
	ConfirmedAt   pgtype.Timestamptz
	Remark        string
}

type FxAnomaly struct {
	ID            int64
	QuoteCurrency string
	NewRate       pgtype.Numeric
	PrevRate      pgtype.Numeric
	DeviationPct  pgtype.Numeric
	Source        string
	DetectedAt    pgtype.Timestamptz
	Note          string
}

type FxRate struct {
	ID            int64
	BaseCurrency  string
	QuoteCurrency string
	Rate          pgtype.Numeric
	RateDate      pgtype.Date
	Source        string
	CreatedBy     int64
	Note          string
	FetchedAt     pgtype.Timestamptz
}
