<template>
 <section v-loading="busy" class="customer-offer">
  <el-alert v-if="error" :title="error" type="error" :closable="false" show-icon />
  <template v-if="offer">
   <div class="offer-toolbar"><div><h3>给客户的报价 <el-tag>{{statusLabel}}</el-tag></h3><p>{{offer.canEdit?'采购单价和物流费用由上游提交，销售选择报价依据并确定最终客户价。':'已按客户确认的成交内容保留报价。'}}</p></div><div class="actions"><el-button @click="load">刷新上游报价</el-button><el-button :disabled="!offer.revision" @click="download">导出客户报价 PDF</el-button><el-button v-if="offer.canEdit" type="primary" @click="save">保存报价</el-button><el-button v-if="offer.canEdit" type="success" @click="confirm">客户已确认</el-button><el-button v-if="offer.contractId&&offer.contractId!=='0'" type="primary" @click="goContract">打开外销合同</el-button></div></div>
   <div class="source-summary"><div><span>已提交工厂报价</span><strong>{{factoryQuoteCount}} 份</strong><small>选择后自动带入对应产品的工厂单价</small></div><div><span>已提交物流报价</span><strong>{{logisticsQuotes.length}} 份</strong><small>费用由物流计算完成，勾选后带入候选方案</small></div><div><span>已选客户运输方案</span><strong>{{offer.body.transports.length}} 份</strong><small>可调整最终展示给客户的费用</small></div></div>
   <el-form label-position="top" :disabled="!offer.canEdit" class="offer-fields">
    <el-form-item label="客户"><el-autocomplete v-model="offer.body.customer" :fetch-suggestions="suggestCustomers" placeholder="选择或输入客户" @select="chooseCustomer" @input="offer.body.customerId='';offer.body.contactId=''"/></el-form-item><el-form-item label="联系人"><el-autocomplete v-model="offer.body.contact" :fetch-suggestions="suggestContacts" placeholder="选择或输入联系人" @select="chooseContact" @input="offer.body.contactId=''"/></el-form-item>
    <el-form-item label="报价币种"><el-input v-model="offer.body.currency" maxlength="3" /></el-form-item><el-form-item label="交货日期"><el-date-picker v-model="offer.body.delivery" value-format="YYYY-MM-DD" type="date" /></el-form-item><el-form-item label="有效期至"><el-date-picker v-model="offer.body.validUntil" value-format="YYYY-MM-DD" type="date" /></el-form-item>
    <el-form-item label="贸易条件"><el-input v-model="offer.body.incoterm" /></el-form-item><el-form-item label="装货港"><el-input v-model="offer.body.loadingPort" /></el-form-item><el-form-item label="目的港"><el-input v-model="offer.body.destinationPort" /></el-form-item><el-form-item label="付款条件"><el-input v-model="offer.body.payment" /></el-form-item><el-form-item label="备注"><el-input v-model="offer.body.remark" type="textarea" :rows="2" /></el-form-item>
   </el-form>
   <div class="table-tools"><el-input v-model="search" placeholder="搜索成交产品或规格" clearable /><strong>{{offer.body.lines.length}} 项 · 产品合计 {{offer.body.currency}} {{offer.body.total||'尚未保存'}}</strong><el-button v-if="offer.canEdit" @click="addProduct">添加成交产品</el-button></div>
   <el-table :data="visibleLines" stripe max-height="470" row-key="id">
    <el-table-column type="expand"><template #default="{row}"><el-descriptions :column="3" border><el-descriptions-item v-for="(value,key) in row.customFields" :key="key" :label="offer.source.body.template?.fields.find(f=>f.fieldKey===String(key))?.displayName||String(key)"><el-input v-if="offer.canEdit" v-model="row.customFields[key]"/><span v-else>{{value||'—'}}</span></el-descriptions-item></el-descriptions></template></el-table-column>
    <el-table-column label="产品 / 规格" min-width="190" fixed><template #default="{row}"><el-input v-if="offer.canEdit" v-model="row.product" /><strong v-else>{{row.product}}</strong><el-input v-if="offer.canEdit" v-model="row.specification" placeholder="规格" /><div v-else>{{row.specification}}</div></template></el-table-column>
    <el-table-column label="成交数量" width="125"><template #default="{row}"><el-input v-if="offer.canEdit" v-model="row.quantity" inputmode="decimal" /><span v-else>{{row.quantity}}</span></template></el-table-column>
    <el-table-column label="单位" width="85"><template #default="{row}"><el-input v-if="offer.canEdit" v-model="row.unit" /><span v-else>{{row.unit}}</span></template></el-table-column>
    <el-table-column label="工厂报价参考" min-width="175"><template #default="{row}"><el-select v-if="offer.canEdit" v-model="row.factoryQuoteId" clearable placeholder="选择工厂报价" @change="selectFactory(row)"><el-option v-for="q in factoriesFor(offer.source.quotes,row.id)" :key="q.id" :value="q.id" :label="`${q.body.company} · ${q.body.currency} ${q.body.prices.find(p=>p.productId===row.id)?.price}`" /></el-select><span v-else>{{offer.source.quotes.find(q=>q.id===row.factoryQuoteId)?.body.company||'—'}}</span></template></el-table-column>
    <el-table-column label="销售单价" width="140"><template #default="{row}"><el-input v-if="offer.canEdit" v-model="row.unitPrice" inputmode="decimal" /><strong v-else>{{row.unitPrice}}</strong><small v-if="row.calculatedPrice">计算参考 {{row.calculatedPrice}}</small></template></el-table-column>
    <el-table-column label="金额" width="140"><template #default="{row}">{{chargeSubtotal(row.unitPrice,row.quantity)||'—'}}</template></el-table-column>
    <el-table-column v-if="offer.canEdit" label="操作" width="160" fixed="right"><template #default="{row}"><el-button link type="primary" @click="calculationLine=row">计算客户价</el-button><el-button link type="danger" @click="removeProduct(row)">移除</el-button></template></el-table-column>
   </el-table>
   <el-pagination v-model:current-page="page" :total="filteredLines.length" :page-size="20" layout="total,prev,pager,next" />
    <div class="section-heading"><div><h3>已提交物流报价</h3><p>物流提交后直接显示在这里。勾选需要提供给客户比较的报价；单币种费用合计会自动带入。</p></div><el-tag effect="plain">{{logisticsQuotes.length}} 份</el-tag></div>
    <el-table :data="logisticsQuotes" max-height="330" stripe empty-text="物流尚未提交报价">
     <el-table-column label="选用" width="72"><template #default="{row}"><el-checkbox v-if="offer.canEdit" :model-value="hasTransport(row.id)" @change="toggleTransport(row,!!$event)"/><span v-else>{{hasTransport(row.id)?'已选':'—'}}</span></template></el-table-column>
     <el-table-column label="物流报价" min-width="210"><template #default="{row}"><strong>{{sourceQuoteTitle(row)}}</strong><small>{{sourceQuoteRoute(row)}}</small></template></el-table-column>
     <el-table-column label="物流已算费用" min-width="190"><template #default="{row}"><strong>{{sourceQuoteTotals(row)}}</strong><small>{{row.body.charges?.length||0}} 项费用明细</small></template></el-table-column>
     <el-table-column label="适用货物" min-width="180"><template #default="{row}">{{sourceQuoteCargo(row)}}</template></el-table-column>
     <el-table-column label="提交人 / 时间" min-width="190"><template #default="{row}">{{row.author||'—'}}<small>{{displayTime(row.submittedAt)}}</small></template></el-table-column>
    </el-table>
    <div v-if="offer.body.transports.length" class="section-heading selected-heading"><div><h3>给客户的候选运输报价</h3><p>这里只调整对客显示内容；客户确认后再填写接受方案对应的成交产品数量。</p></div></div>
    <el-table v-if="offer.body.transports.length" :data="offer.body.transports" max-height="330" stripe>
    <el-table-column label="方案" min-width="180"><template #default="{row}"><el-input v-model="row.title" :disabled="!offer.canEdit" /></template></el-table-column><el-table-column label="对客费用币种" width="130"><template #default="{row}"><el-input v-model="row.currency" :disabled="!offer.canEdit" /></template></el-table-column><el-table-column label="对客费用" width="140"><template #default="{row}"><el-input v-model="row.price" :disabled="!offer.canEdit" placeholder="单独展示" /></template></el-table-column>
    <el-table-column label="客户接受" width="120"><template #default="{row}"><el-switch v-model="row.accepted" :disabled="!offer.canEdit" /></template></el-table-column><el-table-column label="分配产品数量" width="160"><template #default="{row}"><el-button link type="primary" @click="transport=row">{{Object.keys(row.quantities||{}).length}} 项 · 查看分配</el-button></template></el-table-column>
   </el-table>
  </template>
  <el-drawer :model-value="!!calculationLine" title="客户报价公式" size="min(520px,94vw)" @close="calculationLine=null">
   <template v-if="calculationLine"><el-form label-position="top"><el-form-item label="公司报价公式"><el-select v-model="calculationLine.calculation.formula"><el-option v-for="(name,i) in formulaNames" :key="i" :value="i+1" :label="name" /></el-select></el-form-item><el-alert title="工厂单价由所选采购报价自动带入；物流已计算的费用合计在页面下方直接选择。这里只补充公式无法从上游确定的参数。" type="info" :closable="false"/><el-form-item v-for="f in calculationFields" :key="f.key" :label="f.label"><el-input v-model="calculationLine.calculation[f.key]" inputmode="decimal" :disabled="f.key==='factory'&&!!calculationLine.factoryQuoteId" /></el-form-item></el-form><el-button type="primary" @click="calculate">按公式计算客户单价</el-button><p>计算后仍可直接调整最终售价，内部公式不会出现在 PDF 中。</p></template>
  </el-drawer>
  <el-drawer :model-value="!!transport" title="方案对应的成交产品" size="min(660px,94vw)" @close="transport=null"><template v-if="transport&&offer"><el-input v-model="allocationSearch" placeholder="搜索产品" clearable/><el-table :data="offer.body.lines.filter(l=>!allocationSearch||l.product.includes(allocationSearch))" max-height="560"><el-table-column prop="product" label="产品"/><el-table-column prop="quantity" label="成交数量"/><el-table-column label="本方案数量"><template #default="{row}"><el-input :model-value="transport.quantities[row.id]||''" :disabled="!offer.canEdit" @update:model-value="setAllocation(row.id,$event)" /></template></el-table-column></el-table></template></el-drawer>
 </section>
</template>
<script setup lang="ts">
import {computed,ref,watch} from 'vue'
import {useRouter} from 'vue-router'
import {ElMessage,ElMessageBox} from 'element-plus'
import {get,post} from '../api'
import {blankProduct,chargeSubtotal} from '../lib/inquiryWorkspace'
import {emptyCalculation,factoriesFor,type Offer,type OfferLine,type Transport,type Calculation} from '../lib/customerOffer'
import type {Quote} from '../lib/inquiryWorkspace'
 const props=defineProps<{caseId:string;sourceVersion?:string}>(),router=useRouter(),offer=ref<Offer|null>(null),busy=ref(false),error=ref(''),search=ref(''),page=ref(1),calculationLine=ref<OfferLine|null>(null),transport=ref<Transport|null>(null),allocationSearch=ref('')
 const filteredLines=computed(()=>offer.value?.body.lines.filter(l=>!search.value||`${l.product} ${l.specification}`.includes(search.value))||[]),visibleLines=computed(()=>filteredLines.value.slice((page.value-1)*20,page.value*20)),statusLabel=computed(()=>({PENDING:'待报价',QUOTED:'已报价',CONFIRMED:'客户已确认'}[offer.value?.status||'PENDING']))
 const factoryQuoteCount=computed(()=>offer.value?.source.quotes.filter(q=>q.kind==='PROCUREMENT').length||0)
 const logisticsQuotes=computed(()=>offer.value?.source.quotes.filter(q=>q.kind==='LOGISTICS')||[])
const formulaNames=['CFR · FOB 人民币','CFR · FOB 美元','CFR · 工厂 + 内陆 + 港杂','CFR · 工厂 + 加工 + 全程费用','FOB · 工厂 + 加工 + 国内费用']
const calculationFields:{key:Exclude<keyof Calculation,'formula'>;label:string}[]=[{key:'factory',label:'工厂 / FOB 单价（公式 2 为 USD，其余为 RMB）'},{key:'slitting',label:'分条费 RMB / 销售单位'},{key:'shortHaul',label:'短导费 RMB / 销售单位'},{key:'inland',label:'内陆运费 RMB / 销售单位'},{key:'port',label:'港区港杂费 RMB / 销售单位'},{key:'ocean',label:'海运费 USD / 销售单位'},{key:'days',label:'资金利息天数'},{key:'mtPerUnit',label:'每个销售单位的吨数（MT 填 1）'}]
type CustomerOption={id:string;name:string;code:string;value:string}
type ContactOption={id:string;name:string;value:string;isPrimary:boolean}
const customers=ref<CustomerOption[]>([]),contacts=ref<ContactOption[]>([])
async function suggestCustomers(query:string,done:(rows:CustomerOption[])=>void){try{if(!customers.value.length){const r=await get<{customers:CustomerOption[]}>('/sourcing-customer-options',{page_size:500});customers.value=r.customers.map(c=>({...c,value:c.name}))}done(customers.value.filter(c=>`${c.name} ${c.code}`.toLowerCase().includes(query.toLowerCase())).slice(0,50))}catch{done([])}}
async function suggestContacts(query:string,done:(rows:ContactOption[])=>void){try{if(!offer.value?.body.customerId){done([]);return}const r=await get<{contacts:ContactOption[]}>(`/sourcing-customer-options/${offer.value.body.customerId}/contacts`);contacts.value=r.contacts.map(c=>({...c,value:c.name}));done(contacts.value.filter(c=>c.name.toLowerCase().includes(query.toLowerCase())))}catch{done([])}}
function chooseCustomer(c:CustomerOption){if(!offer.value)return;offer.value.body.customerId=c.id;offer.value.body.customer=c.name;offer.value.body.contact='';offer.value.body.contactId='';contacts.value=[]}
function chooseContact(c:ContactOption){if(!offer.value)return;offer.value.body.contactId=c.id;offer.value.body.contact=c.name}
async function command(action:string){return post<Offer>('/customer-offer',{action,caseId:props.caseId,revision:offer.value?.revision||0,lineId:calculationLine.value?.id,body:offer.value?.body})}
async function load(){busy.value=true;error.value='';try{offer.value=await command('get');offer.value.body.transports??=[];offer.value.body.lines.forEach(l=>l.calculation={...emptyCalculation(),...l.calculation})}catch{error.value='客户报价加载失败，请重试'}finally{busy.value=false}}
async function save(){if(busy.value)return;busy.value=true;try{offer.value=await command('save');ElMessage.success('客户报价已保存')}catch{}finally{busy.value=false}}
async function confirm(){if(busy.value)return;try{await ElMessageBox.confirm('将按当前成交产品、数量、价格和接受方案生成外销合同，确认后保留此份报价。','客户已确认',{confirmButtonText:'确认成交',cancelButtonText:'继续修改'});busy.value=true;offer.value=await command('save');offer.value=await command('confirm');goContract()}catch{}finally{busy.value=false}}
function goContract(){if(offer.value)router.push({path:'/contracts',query:{id:offer.value.contractId}})}
async function download(){if(busy.value)return;busy.value=true;try{if(offer.value?.canEdit)offer.value=await command('save');const file=await post<{fileData:string;fileName:string}>('/customer-offer',{action:'pdf',caseId:props.caseId});const data=Uint8Array.from(atob(file.fileData),c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([data],{type:'application/pdf'})),a=document.createElement('a');a.href=url;a.download=file.fileName;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch{}finally{busy.value=false}}
async function calculate(){if(busy.value||!offer.value)return;busy.value=true;try{const lineId=calculationLine.value?.id;offer.value=await command('calculate');calculationLine.value=offer.value.body.lines.find(l=>l.id===lineId)||null;ElMessage.success('已计算；可继续调整销售单价')}catch{}finally{busy.value=false}}
 function selectFactory(line:OfferLine){const q=offer.value?.source.quotes.find(q=>q.id===line.factoryQuoteId);if(q)line.calculation.factory=q.body.prices.find(p=>p.productId===line.id)?.price||''}
function addProduct(){if(!offer.value)return;offer.value.body.lines.push({...blankProduct(),id:crypto.randomUUID(),factoryQuoteId:'',calculation:emptyCalculation(),calculatedPrice:'',unitPrice:'',amount:''});search.value='';page.value=Math.ceil(offer.value.body.lines.length/20)}
function removeProduct(line:OfferLine){if(!offer.value)return;offer.value.body.lines=offer.value.body.lines.filter(l=>l.id!==line.id);offer.value.body.transports.forEach(t=>delete t.quantities[line.id]);page.value=Math.min(page.value,Math.max(1,Math.ceil(filteredLines.value.length/20)))}
 function sourceQuoteTitle(q:Quote){return q.body.company||q.body.carrier||`物流报价 ${q.id}`}
 function sourceQuoteRoute(q:Quote){return [q.body.route,q.body.carrier,q.body.loadingPort&&q.body.destinationPort?`${q.body.loadingPort} → ${q.body.destinationPort}`:''].filter(Boolean).join(' · ')||'未填写航线信息'}
 function sourceQuoteTotals(q:Quote){const entries=Object.entries(q.body.totals||{});return entries.length?entries.map(([currency,value])=>`${currency} ${value}`).join('；'):'费用未填写'}
 function sourceQuoteCargo(q:Quote){if(!offer.value||!q.body.cargoIds?.length)return '整批货物';const names=q.body.cargoIds.map(id=>offer.value!.body.lines.find(line=>line.id===id)?.product).filter(Boolean);return names.length?names.join('、'):'整批货物'}
 function displayTime(value:string){if(!value)return '—';const date=new Date(value);return Number.isNaN(date.getTime())?value:date.toLocaleString('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false})}
 function hasTransport(id:string){return !!offer.value?.body.transports.some(row=>row.quoteId===id)}
 function transportFromQuote(q:Quote):Transport{const totals=Object.entries(q.body.totals||{}),single=totals.length===1?totals[0]:undefined;return{quoteId:q.id,title:q.body.route||q.body.carrier||q.body.company||`物流报价 ${q.id}`,currency:single?.[0]||offer.value?.body.currency||'USD',price:single?.[1]||'',remark:'',accepted:false,quantities:{}}}
 function toggleTransport(q:Quote,yes:boolean){if(!offer.value)return;if(yes&&!hasTransport(q.id))offer.value.body.transports.push(transportFromQuote(q));if(!yes)offer.value.body.transports=offer.value.body.transports.filter(row=>row.quoteId!==q.id)}
function setAllocation(id:string,value:string){if(!transport.value)return;if(value.trim())transport.value.quantities[id]=value;else delete transport.value.quantities[id]}
 watch(search,()=>page.value=1);watch(()=>[props.caseId,props.sourceVersion],load,{immediate:true})
</script>
<style scoped>
.customer-offer{padding:18px;background:white;border:1px solid #dbe5ed;border-radius:12px}.offer-toolbar,.table-tools,.section-heading{display:flex;justify-content:space-between;align-items:center;gap:14px;margin-bottom:18px}.actions{display:flex;gap:8px;flex-wrap:wrap}.actions .el-button{margin:0}h3{color:#173e53;margin:0 0 10px}p,small{color:#637889}small{display:block;margin-top:5px}.offer-fields{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:0 16px}.source-summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin:0 0 20px}.source-summary>div{display:flex;flex-direction:column;padding:14px 16px;border:1px solid #d8e5ec;border-radius:10px;background:#f6fafc}.source-summary strong{margin-top:5px;font-size:22px;color:#0f6078}.selected-heading{margin-top:24px}.table-tools>.el-input{max-width:300px}.el-pagination{margin:14px 0 24px}.el-table .el-input+.el-input{margin-top:6px}.el-alert{margin-bottom:18px}@media(max-width:1100px){.offer-fields{grid-template-columns:repeat(3,minmax(0,1fr))}.offer-toolbar{align-items:flex-start;flex-direction:column}}@media(max-width:760px){.source-summary{grid-template-columns:1fr}}@media(max-width:640px){.offer-fields{grid-template-columns:1fr 1fr}.table-tools,.section-heading{align-items:flex-start;flex-direction:column}}
</style>
