<template>
  <section v-loading="loading">
    <div class="toolbar"><span class="hint">上传供应商资质、证书等附件，可设置到期提醒。</span><el-button v-if="canWrite" type="primary" @click="open()">上传文件</el-button></div>
    <el-table :data="current" empty-text="暂无供应商资料">
      <el-table-column label="文件" min-width="240"><template #default="{row}"><el-button v-if="previewable(row)" link type="primary" class="filename" @click="preview(row)">{{row.fileName}}</el-button><span v-else>{{row.fileName}}</span><span class="size">{{formatSize(row.sizeBytes)}}</span></template></el-table-column>
      <el-table-column label="提醒日期" min-width="190"><template #default="{row}">{{reminderLabel(row)}}</template></el-table-column>
      <el-table-column label="操作" width="150"><template #default="{row}"><el-dropdown trigger="click" @command="(command:string)=>action(command,row)"><el-button class="more-button">更多操作 <span>▼</span></el-button><template #dropdown><el-dropdown-menu><el-dropdown-item command="download">下载</el-dropdown-item><el-dropdown-item v-if="canWrite" command="remind">设置提醒</el-dropdown-item><el-dropdown-item v-if="canWrite" command="delete" divided>删除</el-dropdown-item></el-dropdown-menu></template></el-dropdown></template></el-table-column>
    </el-table>
    <el-dialog v-model="dialog" :title="editing?'设置提醒':'上传供应商资料'" width="min(440px,92vw)" append-to-body>
      <el-form label-position="top">
        <el-form-item v-if="!editing" label="文件" required><input :key="fileKey" type="file" aria-label="选择文件" @change="selectFile"><span class="hint upload-hint">图片、PDF 等，单个文件最大 10 MB</span></el-form-item>
        <p v-else>{{editing.fileName}}</p>
        <el-form-item label="提醒日期（可选）"><el-date-picker v-model="reminderDate" type="date" value-format="YYYY-MM-DD" placeholder="选择提醒负责人更新的日期" clearable style="width:100%" /></el-form-item>
        <p class="hint">到期时提醒该供应商负责人和系统最高权限用户。</p>
      </el-form>
      <template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">{{editing?'保存':'上传'}}</el-button></template>
    </el-dialog>
    <el-dialog v-model="previewOpen" title="附件预览" width="85%" append-to-body destroy-on-close @closed="releasePreview"><CustomerDocumentPdf v-if="previewBlob&&previewIsPDF" :source="previewBlob"/><img v-else-if="previewURL" :src="previewURL" alt="供应商附件" class="image-preview"></el-dialog>
  </section>
</template>
<script setup lang="ts">
import {computed,onBeforeUnmount,onMounted,ref} from 'vue';import{ElMessage,ElMessageBox}from'element-plus';import{del,get,http}from'../api';import CustomerDocumentPdf from './CustomerDocumentPdf.vue';import{announceReminderChanged}from'../lib/homeReminders';import type{CustomerDocument}from'../lib/customerDocuments'
const props=defineProps<{supplierId:string;canWrite:boolean}>();const loading=ref(false),saving=ref(false),dialog=ref(false),fileKey=ref(0),docs=ref<CustomerDocument[]>([]),editing=ref<CustomerDocument|null>(null),selected=ref<File|null>(null),reminderDate=ref(''),now=ref(new Date()),previewOpen=ref(false),previewURL=ref(''),previewIsPDF=ref(false),previewBlob=ref<Blob|null>(null);let timer:ReturnType<typeof setInterval>|undefined
const endpoint=computed(()=>`/suppliers/${props.supplierId}/documents`),current=computed(()=>docs.value.filter(d=>d.current));async function load(){loading.value=true;try{docs.value=(await get<{documents:CustomerDocument[]}>(endpoint.value)).documents||[]}finally{loading.value=false}}
function reminderOn(d:CustomerDocument){if(!d.reminderEnabled||!d.expiresOn)return'';const date=new Date(d.expiresOn+'T00:00:00Z');date.setUTCDate(date.getUTCDate()-d.remindDays);return date.toISOString().slice(0,10)}function reminderLabel(d:CustomerDocument){const date=reminderOn(d);return !date?'未设置':date<=now.value.toISOString().slice(0,10)?date+' · 已到提醒时间':date}
function open(d?:CustomerDocument){editing.value=d||null;reminderDate.value=d?reminderOn(d):'';selected.value=null;fileKey.value++;dialog.value=true}function selectFile(e:Event){selected.value=(e.target as HTMLInputElement).files?.[0]||null}
async function save(){if(!editing.value&&!selected.value){ElMessage.warning('请选择文件');return}if(selected.value&&(!selected.value.size||selected.value.size>10*1024*1024)){ElMessage.warning('请选择不超过 10 MB 的非空文件');return}const body=new FormData();body.set('title',selected.value?.name||editing.value?.fileName||'附件');body.set('remark',editing.value?.remark||'');body.set('expiresOn',reminderDate.value||'');body.set('remindDays','0');body.set('reminderEnabled',String(Boolean(reminderDate.value)));if(editing.value)body.set('replacesId',editing.value.id);if(selected.value)body.set('file',selected.value);saving.value=true;try{await http.post(endpoint.value,body,{timeout:120000});dialog.value=false;ElMessage.success('供应商资料已保存');announceReminderChanged();await load()}finally{saving.value=false}}
async function action(command:string,d:CustomerDocument){if(command==='download'){await download(d);return}if(command==='remind'){open(d);return}if(command!=='delete')return;try{await ElMessageBox.confirm('确定删除该附件吗？','删除附件',{type:'warning'})}catch{return}await del(`${endpoint.value}/${d.id}`);ElMessage.success('附件已删除');announceReminderChanged();await load()}
function previewable(d:CustomerDocument){return['application/pdf','image/jpeg','image/png','image/gif','image/webp'].includes(d.contentType)}async function blob(d:CustomerDocument){return(await http.get<Blob>(`${endpoint.value}/${d.id}/file`,{responseType:'blob',timeout:120000})).data}async function download(d:CustomerDocument){const b=await blob(d),url=URL.createObjectURL(b),a=document.createElement('a');a.href=url;a.download=d.fileName;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}function releasePreview(){if(previewURL.value)URL.revokeObjectURL(previewURL.value);previewURL.value='';previewBlob.value=null}async function preview(d:CustomerDocument){const b=await blob(d);releasePreview();previewURL.value=URL.createObjectURL(b);previewBlob.value=b;previewIsPDF.value=d.contentType==='application/pdf';previewOpen.value=true}function formatSize(v:string){const n=Number(v);return n>=1048576?`${(n/1048576).toFixed(1)} MB`:`${Math.ceil(n/1024)} KB`}
onMounted(()=>{void load();timer=setInterval(()=>now.value=new Date(),60000)});onBeforeUnmount(()=>{clearInterval(timer);releasePreview()})
</script>
<style scoped>.toolbar{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:16px}.hint,.size{color:#8492a6;font-size:13px}.size{margin-left:12px}.upload-hint{display:block;width:100%;margin-top:8px}.more-button span{font-size:10px;margin-left:5px}.filename{height:auto;white-space:normal;text-align:left}.image-preview{display:block;max-width:100%;max-height:70vh;margin:auto}</style>
