// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CreditRating struct {
	ID            int64
	TenantID      int64
	PartyType     string
	PartyID       int64
	Grade         string
	PreviousGrade string
	Basis         string
	Evidence      []byte
	RatedBy       int64
	RatedByName   string
	RatedAt       pgtype.Timestamptz
}

type Customer struct {
	ID               int64
	TenantID         int64
	Code             string
	Name             string
	Country          string
	Address          string
	Currency         string
	PaymentTerm      string
	Remark           string
	Status           string
	CreatedAt        pgtype.Timestamptz
	CreatedBy        int64
	UpdatedAt        pgtype.Timestamptz
	UpdatedBy        int64
	CountryCode      string
	ShortName        string
	EnglishName      string
	CustomerType     string
	Industry         string
	Source           string
	Tags             []string
	Website          string
	PrimaryLanguage  string
	Timezone         string
	RegisteredName   string
	RegistrationNo   string
	TaxID            string
	InvoiceTitle     string
	InvoiceTaxNo     string
	InvoiceRemark    string
	PaymentDays      int32
	CreditLimitMinor int64
	CreditCurrency   string
	CreditStatus     string
	BusinessStatus   string
	CreditGrade      string
	CreditGradedAt   pgtype.Timestamptz
}

type CustomerAddress struct {
	ID          int64
	TenantID    int64
	CustomerID  int64
	AddressType string
	CountryCode string
	State       string
	City        string
	PostalCode  string
	AddressLine string
	IsDefault   bool
	SortOrder   int32
	Status      string
	CreatedAt   pgtype.Timestamptz
	CreatedBy   int64
	UpdatedAt   pgtype.Timestamptz
	UpdatedBy   int64
}

type CustomerChangeLog struct {
	ID           int64
	TenantID     int64
	CustomerID   int64
	Action       string
	Section      string
	Summary      string
	BeforeData   []byte
	AfterData    []byte
	OperatorID   int64
	OperatorName string
	CreatedAt    pgtype.Timestamptz
}

type CustomerContact struct {
	ID               int64
	TenantID         int64
	CustomerID       int64
	Name             string
	Title            string
	Email            string
	Phone            string
	IsPrimary        bool
	SortOrder        int32
	Department       string
	Mobile           string
	InstantMessaging string
	Language         string
	Remark           string
	Status           string
	CreatedAt        pgtype.Timestamptz
	CreatedBy        int64
	UpdatedAt        pgtype.Timestamptz
	UpdatedBy        int64
	EmailPermission  string
	EmailCategories  []string
}

type CustomerOwner struct {
	ID                 int64
	TenantID           int64
	CustomerID         int64
	EmployeeID         int64
	EmployeeName       string
	ResponsibilityCode string
	StartDate          pgtype.Date
	EndDate            pgtype.Date
	Status             string
	CreatedAt          pgtype.Timestamptz
	CreatedBy          int64
	UpdatedAt          pgtype.Timestamptz
	UpdatedBy          int64
	IsPrimary          bool
}

type Factory struct {
	ID            int64
	TenantID      int64
	SupplierID    int64
	Code          string
	NameZh        string
	NameEn        string
	ShortName     string
	CountryCode   string
	Timezone      string
	StateProvince string
	City          string
	District      string
	PostalCode    string
	Address       string
	Status        string
	Remark        string
	CreatedAt     pgtype.Timestamptz
	CreatedBy     int64
	UpdatedAt     pgtype.Timestamptz
	UpdatedBy     int64
}

type FactoryCapability struct {
	ID              int64
	TenantID        int64
	FactoryID       int64
	ProductCategory string
	Process         string
	MonthlyCapacity pgtype.Numeric
	CapacityUnit    string
	Moq             pgtype.Numeric
	LeadTimeDays    int32
	PeriodLabel     string
	ConfirmedOn     pgtype.Date
	Remark          string
	CreatedAt       pgtype.Timestamptz
	CreatedBy       int64
	UpdatedAt       pgtype.Timestamptz
	UpdatedBy       int64
}

type FactoryCertificate struct {
	ID            int64
	TenantID      int64
	FactoryID     int64
	Name          string
	CertificateNo string
	IssuedOn      pgtype.Date
	ExpiresOn     pgtype.Date
	Status        string
	FileKey       string
	Remark        string
	CreatedAt     pgtype.Timestamptz
	CreatedBy     int64
	UpdatedAt     pgtype.Timestamptz
	UpdatedBy     int64
}

type FactoryChangeLog struct {
	ID           int64
	TenantID     int64
	FactoryID    int64
	Action       string
	Section      string
	Summary      string
	BeforeData   []byte
	AfterData    []byte
	OperatorID   int64
	OperatorName string
	CreatedAt    pgtype.Timestamptz
}

type FactoryContact struct {
	ID         int64
	TenantID   int64
	FactoryID  int64
	Name       string
	Department string
	Title      string
	Phone      string
	Email      string
	IsPrimary  bool
	Status     string
	Remark     string
	CreatedAt  pgtype.Timestamptz
	CreatedBy  int64
	UpdatedAt  pgtype.Timestamptz
	UpdatedBy  int64
}

type FactoryOwner struct {
	ID                 int64
	TenantID           int64
	FactoryID          int64
	EmployeeID         int64
	EmployeeName       string
	ResponsibilityCode string
	IsPrimary          bool
	StartDate          pgtype.Date
	EndDate            pgtype.Date
	Status             string
	CreatedAt          pgtype.Timestamptz
	CreatedBy          int64
	UpdatedAt          pgtype.Timestamptz
	UpdatedBy          int64
}

type NumberRule struct {
	ID       int64
	TenantID int64
	BizType  string
	Prefix   string
	Period   string
	SeqLen   int32
}

type NumberSequence struct {
	TenantID  int64
	BizType   string
	PeriodKey string
	NextSeq   int64
}

type OptionItem struct {
	ID        int64
	TenantID  int64
	Category  string
	Code      string
	Label     string
	SortOrder int32
	Status    string
}

type Port struct {
	ID             int64
	TenantID       int64
	Unlocode       string
	NameZh         string
	NameEn         string
	CountryCode    string
	City           string
	Timezone       string
	Aliases        []string
	Status         string
	Remark         string
	Version        int32
	CreatedAt      pgtype.Timestamptz
	CreatedBy      int64
	CreatedByName  string
	UpdatedAt      pgtype.Timestamptz
	UpdatedBy      int64
	UpdatedByName  string
	PortType       string
	AdminArea      string
	Latitude       float64
	Longitude      float64
	HasCoordinates bool
	IsFavorite     bool
}

type PortChangeLog struct {
	ID           int64
	TenantID     int64
	PortID       int64
	Action       string
	BeforeData   []byte
	AfterData    []byte
	OperatorID   int64
	OperatorName string
	CreatedAt    pgtype.Timestamptz
}

type Supplier struct {
	ID                int64
	TenantID          int64
	Code              string
	Name              string
	Country           string
	Address           string
	Currency          string
	ContactName       string
	ContactPhone      string
	ContactEmail      string
	Remark            string
	Status            string
	CreatedAt         pgtype.Timestamptz
	CreatedBy         int64
	UpdatedAt         pgtype.Timestamptz
	UpdatedBy         int64
	NameZh            string
	NameEn            string
	ShortName         string
	CountryCode       string
	TaxID             string
	RegisteredAddress string
	PaymentTerm       string
	BusinessTypes     []string
	CreditGrade       string
	CreditGradedAt    pgtype.Timestamptz
}

type SupplierChangeLog struct {
	ID           int64
	TenantID     int64
	SupplierID   int64
	Action       string
	Section      string
	Summary      string
	BeforeData   []byte
	AfterData    []byte
	OperatorID   int64
	OperatorName string
	CreatedAt    pgtype.Timestamptz
}

type SupplierContact struct {
	ID         int64
	TenantID   int64
	SupplierID int64
	Name       string
	Department string
	Title      string
	Phone      string
	Email      string
	IsPrimary  bool
	Status     string
	Remark     string
	CreatedAt  pgtype.Timestamptz
	CreatedBy  int64
	UpdatedAt  pgtype.Timestamptz
	UpdatedBy  int64
}

type SupplierOwner struct {
	ID                 int64
	TenantID           int64
	SupplierID         int64
	EmployeeID         int64
	EmployeeName       string
	ResponsibilityCode string
	IsPrimary          bool
	StartDate          pgtype.Date
	EndDate            pgtype.Date
	Status             string
	CreatedAt          pgtype.Timestamptz
	CreatedBy          int64
	UpdatedAt          pgtype.Timestamptz
	UpdatedBy          int64
}
