$ErrorActionPreference='Stop'
$base='http://127.0.0.1:28282';$password='D5-Acceptance-2026!'
function Login([string]$email,[string]$secret){$s=[Microsoft.PowerShell.Commands.WebRequestSession]::new();Invoke-RestMethod "$base/api/auth/login" -Method Post -ContentType 'application/json' -Body (@{email=$email;password=$secret}|ConvertTo-Json) -WebSession $s|Out-Null;return $s}
function Api($s,[string]$method,[string]$path,$body){$h=@{};foreach($c in $s.Cookies.GetCookies([uri]$base)){if($c.Name -eq 'erp_csrf'){$h['X-CSRF-Token']=$c.Value}};$a=@{Uri="$base/api$path";Method=$method;WebSession=$s;Headers=$h;ContentType='application/json'};if($null-ne$body){$a.Body=$body|ConvertTo-Json -Depth 20 -Compress};return (Invoke-RestMethod @a).data}
$admin=Login 'admin@d5.example.test' 'admin123';$roles=(Api $admin GET '/roles' $null).roles;$people=@{}
foreach($pair in @(@('P1','BUYER'),@('Q1','QUALITY_INSPECTOR'),@('L1','LOGISTICS'),@('S1','SALES'),@('B1','BOSS'))){$name=$pair[0];$email="$($name.ToLower())@d5.example.test";$employee=@((Api $admin GET "/employees?keyword=$name&size=100" $null).employees)|Where-Object code -eq "D5-$name"|Select-Object -First 1;if(!$employee){$employee=(Api $admin POST '/employees' @{code="D5-$name";name=$name;email=$email;departmentId='1';initialPassword=$password;username=$email}).employee};$role=$roles|Where-Object code -eq $pair[1]|Select-Object -First 1;if(!$role){throw "Missing role $($pair[1])"};Api $admin POST "/employees/$($employee.id)/roles" @{roleIds=@([string]$role.id)}|Out-Null;docker exec erp-d5-20260910-postgres-1 psql -U erp_iam -d erp_iam -c "UPDATE employees SET email_verified_at=now() WHERE tenant_id=1 AND id=$($employee.id)"|Out-Null;$people[$name]=@{id=$employee.id;email=$email}}
$buyer=$people.P1.id
$sql="DO `$`$ DECLARE r bigint; p bigint; BEGIN IF NOT EXISTS(SELECT 1 FROM purchase_orders WHERE tenant_id=1 AND po_no='PO-D5-ACCEPT-001') THEN INSERT INTO purchase_requirements(tenant_id,contract_id,contract_no,contract_version_id,contract_item_id,product_id,product_code,product_name,uom_id,uom_code,required_qty,ordered_qty,status,owner_id) VALUES(1,5001,'CT-D5-ACCEPT',1,5001,101,'COIL','冷轧卷',1,'MT',10,10,'ORDERED',$buyer) RETURNING id INTO r; INSERT INTO purchase_orders(tenant_id,po_no,supplier_id,supplier_code,supplier_name,currency,total_amount,expected_date,status,buyer_id,buyer_name,ordered_at,business_type) VALUES(1,'PO-D5-ACCEPT-001',901,'D5-F01','D5 验收工厂','CNY',50000,'2026-10-20','ORDERED',$buyer,'P1',now(),'PROCUREMENT') RETURNING id INTO p; INSERT INTO purchase_order_items(tenant_id,po_id,requirement_id,product_id,product_code,product_name,spec,uom_id,uom_code,qty,unit_price,amount) VALUES(1,p,r,101,'COIL','冷轧卷','Q235 / 1.2×1250mm',1,'MT',10,5000,50000); END IF; END `$`$;";docker exec erp-d5-20260910-postgres-1 psql -U erp_procurement -d erp_procurement -c $sql|Out-Null
$e=[ordered]@{frontend='http://127.0.0.1:25375';gateway=$base;password=$password;accounts=@{buyer=$people.P1.email;quality=$people.Q1.email;logistics=$people.L1.email;sales=$people.S1.email;boss=$people.B1.email};fixture=@{purchaseOrder='PO-D5-ACCEPT-001';quantity='10 MT'}};$e|ConvertTo-Json -Depth 6|Set-Content (Join-Path $PSScriptRoot 'accounts.json') -Encoding utf8
Write-Output 'D5 acceptance accounts and purchase order ready.'
