// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OutboxEvent struct {
	ID            int64
	TenantID      int64
	AggregateType string
	AggregateID   string
	EventType     string
	Payload       []byte
	TraceID       *string
	CreatedAt     pgtype.Timestamptz
	PublishedAt   pgtype.Timestamptz
	Attempts      int32
	LastError     *string
}

type ShippingSchedule struct {
	ID                    int64
	TenantID              int64
	ScheduleNo            string
	ContractID            *int64
	ContractNo            string
	CustomerID            *int64
	CustomerName          string
	CarrierForwarder      string
	VesselName            string
	VoyageNo              string
	PortOfLoading         string
	PortOfDischarge       string
	Etd                   pgtype.Date
	Atd                   pgtype.Date
	Eta                   pgtype.Date
	Ata                   pgtype.Date
	ResponsibleEmployeeID int64
	ResponsibleName       string
	Status                string
	Remark                string
	CreatedBy             int64
	CreatedByName         string
	CreatedAt             pgtype.Timestamptz
	UpdatedBy             int64
	UpdatedByName         string
	UpdatedAt             pgtype.Timestamptz
}

type ShippingScheduleChange struct {
	ID           int64
	TenantID     int64
	ScheduleID   int64
	ChangeType   string
	FieldName    string
	OldValue     string
	NewValue     string
	Reason       string
	OperatorID   int64
	OperatorName string
	CreatedAt    pgtype.Timestamptz
}
