// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customer_selection.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptCustomerSelection = `-- name: AcceptCustomerSelection :execrows
UPDATE sourcing_customer_selections SET status='CUSTOMER_CONFIRMED',customer_contact=$1,
 customer_decided_at=$2::text::timestamptz,customer_decision_note=$3,updated_at=now()
WHERE tenant_id=$4 AND id=$5 AND status='AWAITING_CUSTOMER_CONFIRMATION'
`

type AcceptCustomerSelectionParams struct {
	CustomerContact   string
	CustomerDecidedAt string
	DecisionNote      string
	TenantID          int64
	ID                int64
}

func (q *Queries) AcceptCustomerSelection(ctx context.Context, arg AcceptCustomerSelectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, acceptCustomerSelection,
		arg.CustomerContact,
		arg.CustomerDecidedAt,
		arg.DecisionNote,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeReadyCustomerSelections = `-- name: CompleteReadyCustomerSelections :exec
UPDATE sourcing_customer_selections s
SET status='AWAITING_CUSTOMER_CONFIRMATION',final_rechecked_at=now(),updated_at=now()
WHERE s.tenant_id=$1 AND s.status='INTENT_RECHECK_PENDING'
  AND NOT EXISTS (SELECT 1 FROM sourcing_final_recheck_tasks t
                  WHERE t.tenant_id=s.tenant_id AND t.selection_id=s.id AND t.status='OPEN')
`

func (q *Queries) CompleteReadyCustomerSelections(ctx context.Context, tenantID int64) error {
	_, err := q.db.Exec(ctx, completeReadyCustomerSelections, tenantID)
	return err
}

const createCustomerSelection = `-- name: CreateCustomerSelection :one
INSERT INTO sourcing_customer_selections(tenant_id,case_id,sales_plan_id,selection_no,version_no,
 requirement_version_no,status,customer_contact,confirmation_note,customer_confirmed_at,created_by,created_by_name)
VALUES($1,$2,$3,
 'CS-'||to_char(current_date,'YYYYMMDD')||'-'||lpad(nextval('sourcing_customer_selection_no_seq')::text,6,'0'),
 (SELECT coalesce(max(version_no),0)+1 FROM sourcing_customer_selections
  WHERE tenant_id=$1 AND case_id=$2),
 $4,'INTENT_RECHECK_PENDING',$5,
 $6,$7::text::timestamptz,
 $8,$9)
RETURNING id
`

type CreateCustomerSelectionParams struct {
	TenantID             int64
	CaseID               int64
	SalesPlanID          int64
	RequirementVersionNo int32
	CustomerContact      string
	ConfirmationNote     string
	CustomerConfirmedAt  string
	CreatedBy            int64
	CreatedByName        string
}

func (q *Queries) CreateCustomerSelection(ctx context.Context, arg CreateCustomerSelectionParams) (int64, error) {
	row := q.db.QueryRow(ctx, createCustomerSelection,
		arg.TenantID,
		arg.CaseID,
		arg.SalesPlanID,
		arg.RequirementVersionNo,
		arg.CustomerContact,
		arg.ConfirmationNote,
		arg.CustomerConfirmedAt,
		arg.CreatedBy,
		arg.CreatedByName,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createCustomerSelectionItem = `-- name: CreateCustomerSelectionItem :one
INSERT INTO sourcing_customer_selection_items(tenant_id,selection_id,sales_plan_item_id,sourcing_line_id,
 procurement_plan_item_id,supplier_quote_line_id,shipping_plan_item_id,shipping_option_line_id,
 product_name,confirmed_qty,uom_code,customer_currency,customer_unit_price,promised_delivery_date,line_note,
 supplier_id,supplier_name,factory_id,factory_name,shipment_group_key,customer_managed_shipping)
VALUES($1,$2,$3,$4,
 $5,$6,
 NULL,NULL,
 $7,$8::text::numeric,$9,
 $10,$11::text::numeric,
 nullif($12::text,'')::date,$13,
 $14,$15,$16,$17,
 $18,$19)
RETURNING id
`

type CreateCustomerSelectionItemParams struct {
	TenantID                int64
	SelectionID             int64
	SalesPlanItemID         int64
	SourcingLineID          int64
	ProcurementPlanItemID   int64
	SupplierQuoteLineID     int64
	ProductName             string
	ConfirmedQty            string
	UomCode                 string
	CustomerCurrency        string
	CustomerUnitPrice       string
	PromisedDeliveryDate    string
	LineNote                string
	SupplierID              int64
	SupplierName            string
	FactoryID               int64
	FactoryName             string
	ShipmentGroupKey        string
	CustomerManagedShipping bool
}

func (q *Queries) CreateCustomerSelectionItem(ctx context.Context, arg CreateCustomerSelectionItemParams) (int64, error) {
	row := q.db.QueryRow(ctx, createCustomerSelectionItem,
		arg.TenantID,
		arg.SelectionID,
		arg.SalesPlanItemID,
		arg.SourcingLineID,
		arg.ProcurementPlanItemID,
		arg.SupplierQuoteLineID,
		arg.ProductName,
		arg.ConfirmedQty,
		arg.UomCode,
		arg.CustomerCurrency,
		arg.CustomerUnitPrice,
		arg.PromisedDeliveryDate,
		arg.LineNote,
		arg.SupplierID,
		arg.SupplierName,
		arg.FactoryID,
		arg.FactoryName,
		arg.ShipmentGroupKey,
		arg.CustomerManagedShipping,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createCustomerSelectionShipment = `-- name: CreateCustomerSelectionShipment :one
INSERT INTO sourcing_customer_selection_shipments(tenant_id,selection_id,shipment_group_key,
 sales_shipping_option_id,shipping_option_id,carrier_forwarder,service_option_name,
 shipping_employee_id,shipping_employee_name,customer_currency,customer_freight_amount,charge_basis,
 port_of_loading,port_of_discharge,estimated_departure,estimated_arrival,valid_until,customer_note)
VALUES($1,$2,$3,
 $4,$5,$6,
 $7,$8,$9,
 $10,$11::text::numeric,$12,
 $13,$14,nullif($15::text,'')::date,
 nullif($16::text,'')::date,nullif($17::text,'')::date,
 $18) RETURNING id
`

type CreateCustomerSelectionShipmentParams struct {
	TenantID              int64
	SelectionID           int64
	ShipmentGroupKey      string
	SalesShippingOptionID int64
	ShippingOptionID      int64
	CarrierForwarder      string
	ServiceOptionName     string
	ShippingEmployeeID    int64
	ShippingEmployeeName  string
	CustomerCurrency      string
	CustomerFreightAmount string
	ChargeBasis           string
	PortOfLoading         string
	PortOfDischarge       string
	EstimatedDeparture    string
	EstimatedArrival      string
	ValidUntil            string
	CustomerNote          string
}

func (q *Queries) CreateCustomerSelectionShipment(ctx context.Context, arg CreateCustomerSelectionShipmentParams) (int64, error) {
	row := q.db.QueryRow(ctx, createCustomerSelectionShipment,
		arg.TenantID,
		arg.SelectionID,
		arg.ShipmentGroupKey,
		arg.SalesShippingOptionID,
		arg.ShippingOptionID,
		arg.CarrierForwarder,
		arg.ServiceOptionName,
		arg.ShippingEmployeeID,
		arg.ShippingEmployeeName,
		arg.CustomerCurrency,
		arg.CustomerFreightAmount,
		arg.ChargeBasis,
		arg.PortOfLoading,
		arg.PortOfDischarge,
		arg.EstimatedDeparture,
		arg.EstimatedArrival,
		arg.ValidUntil,
		arg.CustomerNote,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createFinalProcurementRecheckTask = `-- name: CreateFinalProcurementRecheckTask :exec
INSERT INTO sourcing_final_recheck_tasks(tenant_id,selection_id,selection_item_id,task_domain,procurement_rework_id)
VALUES($1,$2,$3,'PROCUREMENT',$4)
`

type CreateFinalProcurementRecheckTaskParams struct {
	TenantID            int64
	SelectionID         int64
	SelectionItemID     *int64
	ProcurementReworkID *int64
}

func (q *Queries) CreateFinalProcurementRecheckTask(ctx context.Context, arg CreateFinalProcurementRecheckTaskParams) error {
	_, err := q.db.Exec(ctx, createFinalProcurementRecheckTask,
		arg.TenantID,
		arg.SelectionID,
		arg.SelectionItemID,
		arg.ProcurementReworkID,
	)
	return err
}

const createFinalShipmentRecheckTask = `-- name: CreateFinalShipmentRecheckTask :exec
INSERT INTO sourcing_final_recheck_tasks(tenant_id,selection_id,selection_shipment_id,task_domain,shipping_rework_id)
VALUES($1,$2,$3,'SHIPPING',$4)
`

type CreateFinalShipmentRecheckTaskParams struct {
	TenantID            int64
	SelectionID         int64
	SelectionShipmentID *int64
	ShippingReworkID    *int64
}

func (q *Queries) CreateFinalShipmentRecheckTask(ctx context.Context, arg CreateFinalShipmentRecheckTaskParams) error {
	_, err := q.db.Exec(ctx, createFinalShipmentRecheckTask,
		arg.TenantID,
		arg.SelectionID,
		arg.SelectionShipmentID,
		arg.ShippingReworkID,
	)
	return err
}

const createFinalShippingRecheckTask = `-- name: CreateFinalShippingRecheckTask :exec
INSERT INTO sourcing_final_recheck_tasks(tenant_id,selection_id,selection_item_id,task_domain,shipping_rework_id)
VALUES($1,$2,$3,'SHIPPING',$4)
`

type CreateFinalShippingRecheckTaskParams struct {
	TenantID         int64
	SelectionID      int64
	SelectionItemID  *int64
	ShippingReworkID *int64
}

func (q *Queries) CreateFinalShippingRecheckTask(ctx context.Context, arg CreateFinalShippingRecheckTaskParams) error {
	_, err := q.db.Exec(ctx, createFinalShippingRecheckTask,
		arg.TenantID,
		arg.SelectionID,
		arg.SelectionItemID,
		arg.ShippingReworkID,
	)
	return err
}

const customerSelectionCandidate = `-- name: CustomerSelectionCandidate :one
SELECT spi.id AS sales_plan_item_id,spi.sourcing_line_id,spi.procurement_plan_item_id,
 spi.product_name,spi.quoted_qty::text,spi.uom_code,
 spi.customer_currency,spi.customer_unit_price::text,
 coalesce(spi.promised_delivery_date::text,'')::text AS promised_delivery_date,spi.line_note,
 ppi.supplier_quote_line_id,ppi.buyer_id,ppi.buyer_name,ppi.supplier_id,ppi.supplier_name,
 ppi.available_qty::text AS available_qty,
 coalesce(ppi.factory_id,0)::bigint AS factory_id,ppi.factory_name,sl.port AS required_destination_port
FROM sourcing_sales_plan_items spi
JOIN sourcing_sales_plans sp ON sp.id=spi.plan_id AND sp.tenant_id=spi.tenant_id
JOIN procurement_plan_items ppi ON ppi.id=spi.procurement_plan_item_id AND ppi.tenant_id=spi.tenant_id
JOIN sourcing_lines sl ON sl.id=spi.sourcing_line_id AND sl.tenant_id=spi.tenant_id
WHERE spi.tenant_id=$1 AND sp.case_id=$2 AND sp.id=$3 AND spi.id=$4
  AND sp.status='PRESENTED' AND sp.valid_until>=current_date
`

type CustomerSelectionCandidateParams struct {
	TenantID int64
	CaseID   int64
	ID       int64
	ID_2     int64
}

type CustomerSelectionCandidateRow struct {
	SalesPlanItemID         int64
	SourcingLineID          int64
	ProcurementPlanItemID   int64
	ProductName             string
	SpiQuotedQty            string
	UomCode                 string
	CustomerCurrency        string
	SpiCustomerUnitPrice    string
	PromisedDeliveryDate    string
	LineNote                string
	SupplierQuoteLineID     int64
	BuyerID                 int64
	BuyerName               string
	SupplierID              int64
	SupplierName            string
	AvailableQty            string
	FactoryID               int64
	FactoryName             string
	RequiredDestinationPort string
}

func (q *Queries) CustomerSelectionCandidate(ctx context.Context, arg CustomerSelectionCandidateParams) (CustomerSelectionCandidateRow, error) {
	row := q.db.QueryRow(ctx, customerSelectionCandidate,
		arg.TenantID,
		arg.CaseID,
		arg.ID,
		arg.ID_2,
	)
	var i CustomerSelectionCandidateRow
	err := row.Scan(
		&i.SalesPlanItemID,
		&i.SourcingLineID,
		&i.ProcurementPlanItemID,
		&i.ProductName,
		&i.SpiQuotedQty,
		&i.UomCode,
		&i.CustomerCurrency,
		&i.SpiCustomerUnitPrice,
		&i.PromisedDeliveryDate,
		&i.LineNote,
		&i.SupplierQuoteLineID,
		&i.BuyerID,
		&i.BuyerName,
		&i.SupplierID,
		&i.SupplierName,
		&i.AvailableQty,
		&i.FactoryID,
		&i.FactoryName,
		&i.RequiredDestinationPort,
	)
	return i, err
}

const customerShipmentCandidate = `-- name: CustomerShipmentCandidate :one
SELECT sso.id,sso.shipping_option_id,sso.carrier_forwarder,sso.service_option_name,
 sso.shipping_employee_id,sso.shipping_employee_name,sso.customer_currency,
 sso.customer_freight_amount::text,sso.charge_basis,sso.port_of_loading,sso.port_of_discharge,
 coalesce(sso.estimated_departure::text,'')::text AS estimated_departure,
 coalesce(sso.estimated_arrival::text,'')::text AS estimated_arrival,
 coalesce(sso.valid_until::text,'')::text AS valid_until,sso.customer_note
FROM sourcing_sales_shipping_options sso
JOIN sourcing_sales_plans sp ON sp.tenant_id=sso.tenant_id AND sp.id=sso.plan_id
WHERE sso.tenant_id=$1 AND sp.case_id=$2 AND sp.id=$3 AND sso.id=$4
  AND sp.status='PRESENTED' AND sp.valid_until>=current_date
  AND (sso.valid_until IS NULL OR sso.valid_until>=current_date)
`

type CustomerShipmentCandidateParams struct {
	TenantID int64
	CaseID   int64
	ID       int64
	ID_2     int64
}

type CustomerShipmentCandidateRow struct {
	ID                       int64
	ShippingOptionID         int64
	CarrierForwarder         string
	ServiceOptionName        string
	ShippingEmployeeID       int64
	ShippingEmployeeName     string
	CustomerCurrency         string
	SsoCustomerFreightAmount string
	ChargeBasis              string
	PortOfLoading            string
	PortOfDischarge          string
	EstimatedDeparture       string
	EstimatedArrival         string
	ValidUntil               string
	CustomerNote             string
}

func (q *Queries) CustomerShipmentCandidate(ctx context.Context, arg CustomerShipmentCandidateParams) (CustomerShipmentCandidateRow, error) {
	row := q.db.QueryRow(ctx, customerShipmentCandidate,
		arg.TenantID,
		arg.CaseID,
		arg.ID,
		arg.ID_2,
	)
	var i CustomerShipmentCandidateRow
	err := row.Scan(
		&i.ID,
		&i.ShippingOptionID,
		&i.CarrierForwarder,
		&i.ServiceOptionName,
		&i.ShippingEmployeeID,
		&i.ShippingEmployeeName,
		&i.CustomerCurrency,
		&i.SsoCustomerFreightAmount,
		&i.ChargeBasis,
		&i.PortOfLoading,
		&i.PortOfDischarge,
		&i.EstimatedDeparture,
		&i.EstimatedArrival,
		&i.ValidUntil,
		&i.CustomerNote,
	)
	return i, err
}

const customerShipmentCandidateLines = `-- name: CustomerShipmentCandidateLines :many
SELECT sourcing_line_id,shipping_plan_item_id,shipping_option_line_id,product_name,
 quoted_qty::text,uom_code
FROM sourcing_sales_shipping_option_lines
WHERE tenant_id=$1 AND sales_shipping_option_id=$2 ORDER BY sourcing_line_id
`

type CustomerShipmentCandidateLinesParams struct {
	TenantID              int64
	SalesShippingOptionID int64
}

type CustomerShipmentCandidateLinesRow struct {
	SourcingLineID       int64
	ShippingPlanItemID   int64
	ShippingOptionLineID int64
	ProductName          string
	QuotedQty            string
	UomCode              string
}

func (q *Queries) CustomerShipmentCandidateLines(ctx context.Context, arg CustomerShipmentCandidateLinesParams) ([]CustomerShipmentCandidateLinesRow, error) {
	rows, err := q.db.Query(ctx, customerShipmentCandidateLines, arg.TenantID, arg.SalesShippingOptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomerShipmentCandidateLinesRow
	for rows.Next() {
		var i CustomerShipmentCandidateLinesRow
		if err := rows.Scan(
			&i.SourcingLineID,
			&i.ShippingPlanItemID,
			&i.ShippingOptionLineID,
			&i.ProductName,
			&i.QuotedQty,
			&i.UomCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFinalTaskByProcurementRework = `-- name: GetFinalTaskByProcurementRework :one
SELECT t.id,i.confirmed_qty::text AS customer_intent_qty
FROM sourcing_final_recheck_tasks t
JOIN sourcing_customer_selection_items i ON i.tenant_id=t.tenant_id AND i.id=t.selection_item_id
WHERE t.tenant_id=$1 AND t.procurement_rework_id=$2 AND t.status='OPEN'
`

type GetFinalTaskByProcurementReworkParams struct {
	TenantID            int64
	ProcurementReworkID *int64
}

type GetFinalTaskByProcurementReworkRow struct {
	ID                int64
	CustomerIntentQty string
}

func (q *Queries) GetFinalTaskByProcurementRework(ctx context.Context, arg GetFinalTaskByProcurementReworkParams) (GetFinalTaskByProcurementReworkRow, error) {
	row := q.db.QueryRow(ctx, getFinalTaskByProcurementRework, arg.TenantID, arg.ProcurementReworkID)
	var i GetFinalTaskByProcurementReworkRow
	err := row.Scan(&i.ID, &i.CustomerIntentQty)
	return i, err
}

const getFinalTaskByShippingRework = `-- name: GetFinalTaskByShippingRework :one
SELECT id FROM sourcing_final_recheck_tasks WHERE tenant_id=$1 AND shipping_rework_id=$2 AND status='OPEN'
`

type GetFinalTaskByShippingReworkParams struct {
	TenantID         int64
	ShippingReworkID *int64
}

func (q *Queries) GetFinalTaskByShippingRework(ctx context.Context, arg GetFinalTaskByShippingReworkParams) (int64, error) {
	row := q.db.QueryRow(ctx, getFinalTaskByShippingRework, arg.TenantID, arg.ShippingReworkID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const invalidateActiveCustomerSelections = `-- name: InvalidateActiveCustomerSelections :exec
UPDATE sourcing_customer_selections
SET status='INVALIDATED',invalidated_at=now(),invalidated_reason=$1,updated_at=now()
WHERE tenant_id=$2 AND case_id=$3
  AND status IN ('INTENT_RECHECK_PENDING','AWAITING_CUSTOMER_CONFIRMATION','CUSTOMER_CONFIRMED')
`

type InvalidateActiveCustomerSelectionsParams struct {
	Reason   string
	TenantID int64
	CaseID   int64
}

func (q *Queries) InvalidateActiveCustomerSelections(ctx context.Context, arg InvalidateActiveCustomerSelectionsParams) error {
	_, err := q.db.Exec(ctx, invalidateActiveCustomerSelections, arg.Reason, arg.TenantID, arg.CaseID)
	return err
}

const invalidateExpiredCustomerSelections = `-- name: InvalidateExpiredCustomerSelections :exec
UPDATE sourcing_customer_selections s
SET status='INVALIDATED',invalidated_at=now(),
    invalidated_reason='客户沟通方案已超过有效期',updated_at=now()
FROM sourcing_sales_plans sp
WHERE s.tenant_id=$1 AND s.case_id=$2
  AND sp.tenant_id=s.tenant_id AND sp.id=s.sales_plan_id
  AND s.status IN ('INTENT_RECHECK_PENDING','AWAITING_CUSTOMER_CONFIRMATION','CUSTOMER_CONFIRMED')
  AND sp.valid_until<current_date
`

type InvalidateExpiredCustomerSelectionsParams struct {
	TenantID int64
	CaseID   int64
}

func (q *Queries) InvalidateExpiredCustomerSelections(ctx context.Context, arg InvalidateExpiredCustomerSelectionsParams) error {
	_, err := q.db.Exec(ctx, invalidateExpiredCustomerSelections, arg.TenantID, arg.CaseID)
	return err
}

const linkCustomerSelectionShipmentItem = `-- name: LinkCustomerSelectionShipmentItem :exec
INSERT INTO sourcing_customer_selection_shipment_items(tenant_id,selection_shipment_id,selection_item_id)
VALUES($1,$2,$3)
`

type LinkCustomerSelectionShipmentItemParams struct {
	TenantID            int64
	SelectionShipmentID int64
	SelectionItemID     int64
}

func (q *Queries) LinkCustomerSelectionShipmentItem(ctx context.Context, arg LinkCustomerSelectionShipmentItemParams) error {
	_, err := q.db.Exec(ctx, linkCustomerSelectionShipmentItem, arg.TenantID, arg.SelectionShipmentID, arg.SelectionItemID)
	return err
}

const listCustomerSelectionItems = `-- name: ListCustomerSelectionItems :many
SELECT id,sales_plan_item_id,sourcing_line_id,procurement_plan_item_id,supplier_quote_line_id,
 coalesce(shipping_plan_item_id,0)::bigint AS shipping_plan_item_id,
 coalesce(shipping_option_line_id,0)::bigint AS shipping_option_line_id,
 product_name,confirmed_qty::text,uom_code,customer_currency,customer_unit_price::text,
 coalesce(promised_delivery_date::text,'')::text AS promised_delivery_date,line_note,
 supplier_id,supplier_name,factory_id,factory_name,shipment_group_key,customer_managed_shipping,
 coalesce(final_customer_currency,'')::text AS final_customer_currency,
 coalesce(final_customer_unit_price::text,'')::text AS final_customer_unit_price,
 final_customer_payment_terms,final_customer_incoterm,
 coalesce(final_customer_required_date::text,'')::text AS final_customer_required_date
FROM sourcing_customer_selection_items WHERE tenant_id=$1 AND selection_id=$2 ORDER BY id
`

type ListCustomerSelectionItemsParams struct {
	TenantID    int64
	SelectionID int64
}

type ListCustomerSelectionItemsRow struct {
	ID                        int64
	SalesPlanItemID           int64
	SourcingLineID            int64
	ProcurementPlanItemID     int64
	SupplierQuoteLineID       int64
	ShippingPlanItemID        int64
	ShippingOptionLineID      int64
	ProductName               string
	ConfirmedQty              string
	UomCode                   string
	CustomerCurrency          string
	CustomerUnitPrice         string
	PromisedDeliveryDate      string
	LineNote                  string
	SupplierID                int64
	SupplierName              string
	FactoryID                 int64
	FactoryName               string
	ShipmentGroupKey          string
	CustomerManagedShipping   bool
	FinalCustomerCurrency     string
	FinalCustomerUnitPrice    string
	FinalCustomerPaymentTerms string
	FinalCustomerIncoterm     string
	FinalCustomerRequiredDate string
}

func (q *Queries) ListCustomerSelectionItems(ctx context.Context, arg ListCustomerSelectionItemsParams) ([]ListCustomerSelectionItemsRow, error) {
	rows, err := q.db.Query(ctx, listCustomerSelectionItems, arg.TenantID, arg.SelectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomerSelectionItemsRow
	for rows.Next() {
		var i ListCustomerSelectionItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.SalesPlanItemID,
			&i.SourcingLineID,
			&i.ProcurementPlanItemID,
			&i.SupplierQuoteLineID,
			&i.ShippingPlanItemID,
			&i.ShippingOptionLineID,
			&i.ProductName,
			&i.ConfirmedQty,
			&i.UomCode,
			&i.CustomerCurrency,
			&i.CustomerUnitPrice,
			&i.PromisedDeliveryDate,
			&i.LineNote,
			&i.SupplierID,
			&i.SupplierName,
			&i.FactoryID,
			&i.FactoryName,
			&i.ShipmentGroupKey,
			&i.CustomerManagedShipping,
			&i.FinalCustomerCurrency,
			&i.FinalCustomerUnitPrice,
			&i.FinalCustomerPaymentTerms,
			&i.FinalCustomerIncoterm,
			&i.FinalCustomerRequiredDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomerSelectionShipmentItemIDs = `-- name: ListCustomerSelectionShipmentItemIDs :many
SELECT selection_item_id FROM sourcing_customer_selection_shipment_items
WHERE tenant_id=$1 AND selection_shipment_id=$2 ORDER BY selection_item_id
`

type ListCustomerSelectionShipmentItemIDsParams struct {
	TenantID            int64
	SelectionShipmentID int64
}

func (q *Queries) ListCustomerSelectionShipmentItemIDs(ctx context.Context, arg ListCustomerSelectionShipmentItemIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listCustomerSelectionShipmentItemIDs, arg.TenantID, arg.SelectionShipmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var selection_item_id int64
		if err := rows.Scan(&selection_item_id); err != nil {
			return nil, err
		}
		items = append(items, selection_item_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomerSelectionShipments = `-- name: ListCustomerSelectionShipments :many
SELECT id,shipment_group_key,sales_shipping_option_id,shipping_option_id,carrier_forwarder,
 service_option_name,shipping_employee_id,shipping_employee_name,customer_currency,
 customer_freight_amount::text,charge_basis,port_of_loading,port_of_discharge,
 coalesce(estimated_departure::text,'')::text AS estimated_departure,
 coalesce(estimated_arrival::text,'')::text AS estimated_arrival,
 coalesce(valid_until::text,'')::text AS valid_until,customer_note,
 coalesce(final_customer_currency,'')::text AS final_customer_currency,
 coalesce(final_customer_freight_amount::text,'')::text AS final_customer_freight_amount
FROM sourcing_customer_selection_shipments
WHERE tenant_id=$1 AND selection_id=$2 ORDER BY id
`

type ListCustomerSelectionShipmentsParams struct {
	TenantID    int64
	SelectionID int64
}

type ListCustomerSelectionShipmentsRow struct {
	ID                         int64
	ShipmentGroupKey           string
	SalesShippingOptionID      int64
	ShippingOptionID           int64
	CarrierForwarder           string
	ServiceOptionName          string
	ShippingEmployeeID         int64
	ShippingEmployeeName       string
	CustomerCurrency           string
	CustomerFreightAmount      string
	ChargeBasis                string
	PortOfLoading              string
	PortOfDischarge            string
	EstimatedDeparture         string
	EstimatedArrival           string
	ValidUntil                 string
	CustomerNote               string
	FinalCustomerCurrency      string
	FinalCustomerFreightAmount string
}

func (q *Queries) ListCustomerSelectionShipments(ctx context.Context, arg ListCustomerSelectionShipmentsParams) ([]ListCustomerSelectionShipmentsRow, error) {
	rows, err := q.db.Query(ctx, listCustomerSelectionShipments, arg.TenantID, arg.SelectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomerSelectionShipmentsRow
	for rows.Next() {
		var i ListCustomerSelectionShipmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ShipmentGroupKey,
			&i.SalesShippingOptionID,
			&i.ShippingOptionID,
			&i.CarrierForwarder,
			&i.ServiceOptionName,
			&i.ShippingEmployeeID,
			&i.ShippingEmployeeName,
			&i.CustomerCurrency,
			&i.CustomerFreightAmount,
			&i.ChargeBasis,
			&i.PortOfLoading,
			&i.PortOfDischarge,
			&i.EstimatedDeparture,
			&i.EstimatedArrival,
			&i.ValidUntil,
			&i.CustomerNote,
			&i.FinalCustomerCurrency,
			&i.FinalCustomerFreightAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomerSelections = `-- name: ListCustomerSelections :many
SELECT id,case_id,sales_plan_id,selection_no,version_no,requirement_version_no,status,
 customer_contact,confirmation_note,customer_confirmed_at,created_by,created_by_name,created_at,
 coalesce(final_rechecked_at::text,'')::text AS final_rechecked_at,
 coalesce(customer_decided_at::text,'')::text AS customer_decided_at,customer_decision_note,
 coalesce(invalidated_at::text,'')::text AS invalidated_at,invalidated_reason
FROM sourcing_customer_selections WHERE tenant_id=$1 AND case_id=$2 ORDER BY version_no DESC
`

type ListCustomerSelectionsParams struct {
	TenantID int64
	CaseID   int64
}

type ListCustomerSelectionsRow struct {
	ID                   int64
	CaseID               int64
	SalesPlanID          int64
	SelectionNo          string
	VersionNo            int32
	RequirementVersionNo int32
	Status               string
	CustomerContact      string
	ConfirmationNote     string
	CustomerConfirmedAt  pgtype.Timestamptz
	CreatedBy            int64
	CreatedByName        string
	CreatedAt            pgtype.Timestamptz
	FinalRecheckedAt     string
	CustomerDecidedAt    string
	CustomerDecisionNote string
	InvalidatedAt        string
	InvalidatedReason    string
}

func (q *Queries) ListCustomerSelections(ctx context.Context, arg ListCustomerSelectionsParams) ([]ListCustomerSelectionsRow, error) {
	rows, err := q.db.Query(ctx, listCustomerSelections, arg.TenantID, arg.CaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomerSelectionsRow
	for rows.Next() {
		var i ListCustomerSelectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.SalesPlanID,
			&i.SelectionNo,
			&i.VersionNo,
			&i.RequirementVersionNo,
			&i.Status,
			&i.CustomerContact,
			&i.ConfirmationNote,
			&i.CustomerConfirmedAt,
			&i.CreatedBy,
			&i.CreatedByName,
			&i.CreatedAt,
			&i.FinalRecheckedAt,
			&i.CustomerDecidedAt,
			&i.CustomerDecisionNote,
			&i.InvalidatedAt,
			&i.InvalidatedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFinalRecheckTasks = `-- name: ListFinalRecheckTasks :many
SELECT id,coalesce(selection_item_id,0)::bigint AS selection_item_id,
 coalesce(selection_shipment_id,0)::bigint AS selection_shipment_id,
 task_domain,coalesce(procurement_rework_id,0)::bigint AS procurement_rework_id,
 coalesce(shipping_rework_id,0)::bigint AS shipping_rework_id,status,
 coalesce(resolved_at::text,'')::text AS resolved_at,result_note,
 coalesce(resolved_by,0)::bigint AS resolved_by,resolved_by_name,
 coalesce(final_currency,'')::text AS final_currency,
 coalesce(final_unit_price::text,'')::text AS final_unit_price,
 coalesce(final_available_qty::text,'')::text AS final_available_qty,
 coalesce(final_lead_time,0)::int AS final_lead_time,
 coalesce(final_delivery_date::text,'')::text AS final_delivery_date,
 final_payment_terms,final_incoterm,coalesce(final_valid_until::text,'')::text AS final_valid_until,
 coalesce(final_freight_amount::text,'')::text AS final_freight_amount,
 coalesce(final_estimated_departure::text,'')::text AS final_estimated_departure,
 coalesce(final_estimated_arrival::text,'')::text AS final_estimated_arrival
FROM sourcing_final_recheck_tasks WHERE tenant_id=$1 AND selection_id=$2 ORDER BY selection_item_id,task_domain
`

type ListFinalRecheckTasksParams struct {
	TenantID    int64
	SelectionID int64
}

type ListFinalRecheckTasksRow struct {
	ID                      int64
	SelectionItemID         int64
	SelectionShipmentID     int64
	TaskDomain              string
	ProcurementReworkID     int64
	ShippingReworkID        int64
	Status                  string
	ResolvedAt              string
	ResultNote              string
	ResolvedBy              int64
	ResolvedByName          string
	FinalCurrency           string
	FinalUnitPrice          string
	FinalAvailableQty       string
	FinalLeadTime           int32
	FinalDeliveryDate       string
	FinalPaymentTerms       string
	FinalIncoterm           string
	FinalValidUntil         string
	FinalFreightAmount      string
	FinalEstimatedDeparture string
	FinalEstimatedArrival   string
}

func (q *Queries) ListFinalRecheckTasks(ctx context.Context, arg ListFinalRecheckTasksParams) ([]ListFinalRecheckTasksRow, error) {
	rows, err := q.db.Query(ctx, listFinalRecheckTasks, arg.TenantID, arg.SelectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFinalRecheckTasksRow
	for rows.Next() {
		var i ListFinalRecheckTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.SelectionItemID,
			&i.SelectionShipmentID,
			&i.TaskDomain,
			&i.ProcurementReworkID,
			&i.ShippingReworkID,
			&i.Status,
			&i.ResolvedAt,
			&i.ResultNote,
			&i.ResolvedBy,
			&i.ResolvedByName,
			&i.FinalCurrency,
			&i.FinalUnitPrice,
			&i.FinalAvailableQty,
			&i.FinalLeadTime,
			&i.FinalDeliveryDate,
			&i.FinalPaymentTerms,
			&i.FinalIncoterm,
			&i.FinalValidUntil,
			&i.FinalFreightAmount,
			&i.FinalEstimatedDeparture,
			&i.FinalEstimatedArrival,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectCustomerSelection = `-- name: RejectCustomerSelection :execrows
UPDATE sourcing_customer_selections SET status='CUSTOMER_REJECTED',customer_contact=$1,
 customer_decided_at=$2::text::timestamptz,customer_decision_note=$3,updated_at=now()
WHERE tenant_id=$4 AND id=$5 AND status='AWAITING_CUSTOMER_CONFIRMATION'
`

type RejectCustomerSelectionParams struct {
	CustomerContact   string
	CustomerDecidedAt string
	DecisionNote      string
	TenantID          int64
	ID                int64
}

func (q *Queries) RejectCustomerSelection(ctx context.Context, arg RejectCustomerSelectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, rejectCustomerSelection,
		arg.CustomerContact,
		arg.CustomerDecidedAt,
		arg.DecisionNote,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolveFinalTaskByProcurementRework = `-- name: ResolveFinalTaskByProcurementRework :exec
UPDATE sourcing_final_recheck_tasks SET status='RESOLVED',resolved_at=now(),result_note=$1,
 resolved_by=$2,resolved_by_name=$3,final_currency=$4,
 final_unit_price=$5::text::numeric,final_available_qty=$6::text::numeric,
 final_lead_time=$7,final_delivery_date=$8::text::date,
 final_payment_terms=$9,final_incoterm=$10,
 final_valid_until=$11::text::date
WHERE tenant_id=$12 AND procurement_rework_id=$13 AND status='OPEN'
`

type ResolveFinalTaskByProcurementReworkParams struct {
	ResultNote          string
	ResolvedBy          *int64
	ResolvedByName      string
	FinalCurrency       *string
	FinalUnitPrice      string
	FinalAvailableQty   string
	FinalLeadTime       *int32
	FinalDeliveryDate   string
	FinalPaymentTerms   string
	FinalIncoterm       string
	FinalValidUntil     string
	TenantID            int64
	ProcurementReworkID *int64
}

func (q *Queries) ResolveFinalTaskByProcurementRework(ctx context.Context, arg ResolveFinalTaskByProcurementReworkParams) error {
	_, err := q.db.Exec(ctx, resolveFinalTaskByProcurementRework,
		arg.ResultNote,
		arg.ResolvedBy,
		arg.ResolvedByName,
		arg.FinalCurrency,
		arg.FinalUnitPrice,
		arg.FinalAvailableQty,
		arg.FinalLeadTime,
		arg.FinalDeliveryDate,
		arg.FinalPaymentTerms,
		arg.FinalIncoterm,
		arg.FinalValidUntil,
		arg.TenantID,
		arg.ProcurementReworkID,
	)
	return err
}

const resolveFinalTaskByShippingRework = `-- name: ResolveFinalTaskByShippingRework :exec
UPDATE sourcing_final_recheck_tasks SET status='RESOLVED',resolved_at=now(),result_note=$1,
 resolved_by=$2,resolved_by_name=$3,final_currency=$4,
 final_freight_amount=$5::text::numeric,
 final_estimated_departure=$6::text::date,
 final_estimated_arrival=$7::text::date,
 final_valid_until=$8::text::date
WHERE tenant_id=$9 AND shipping_rework_id=$10 AND status='OPEN'
`

type ResolveFinalTaskByShippingReworkParams struct {
	ResultNote              string
	ResolvedBy              *int64
	ResolvedByName          string
	FinalCurrency           *string
	FinalFreightAmount      string
	FinalEstimatedDeparture string
	FinalEstimatedArrival   string
	FinalValidUntil         string
	TenantID                int64
	ShippingReworkID        *int64
}

func (q *Queries) ResolveFinalTaskByShippingRework(ctx context.Context, arg ResolveFinalTaskByShippingReworkParams) error {
	_, err := q.db.Exec(ctx, resolveFinalTaskByShippingRework,
		arg.ResultNote,
		arg.ResolvedBy,
		arg.ResolvedByName,
		arg.FinalCurrency,
		arg.FinalFreightAmount,
		arg.FinalEstimatedDeparture,
		arg.FinalEstimatedArrival,
		arg.FinalValidUntil,
		arg.TenantID,
		arg.ShippingReworkID,
	)
	return err
}

const setFinalCustomerItemPrice = `-- name: SetFinalCustomerItemPrice :exec
UPDATE sourcing_customer_selection_items SET final_customer_currency=$1,
 final_customer_unit_price=$2::text::numeric,
 final_customer_payment_terms=$3,
 final_customer_incoterm=$4,
 final_customer_required_date=$5::text::date
WHERE tenant_id=$6 AND selection_id=$7 AND id=$8
`

type SetFinalCustomerItemPriceParams struct {
	FinalCustomerCurrency     *string
	FinalCustomerUnitPrice    string
	FinalCustomerPaymentTerms string
	FinalCustomerIncoterm     string
	FinalCustomerRequiredDate string
	TenantID                  int64
	SelectionID               int64
	ID                        int64
}

func (q *Queries) SetFinalCustomerItemPrice(ctx context.Context, arg SetFinalCustomerItemPriceParams) error {
	_, err := q.db.Exec(ctx, setFinalCustomerItemPrice,
		arg.FinalCustomerCurrency,
		arg.FinalCustomerUnitPrice,
		arg.FinalCustomerPaymentTerms,
		arg.FinalCustomerIncoterm,
		arg.FinalCustomerRequiredDate,
		arg.TenantID,
		arg.SelectionID,
		arg.ID,
	)
	return err
}

const setFinalCustomerShipmentPrice = `-- name: SetFinalCustomerShipmentPrice :exec
UPDATE sourcing_customer_selection_shipments SET final_customer_currency=$1,final_customer_freight_amount=$2::text::numeric
WHERE tenant_id=$3 AND selection_id=$4 AND id=$5
`

type SetFinalCustomerShipmentPriceParams struct {
	FinalCustomerCurrency      *string
	FinalCustomerFreightAmount string
	TenantID                   int64
	SelectionID                int64
	ID                         int64
}

func (q *Queries) SetFinalCustomerShipmentPrice(ctx context.Context, arg SetFinalCustomerShipmentPriceParams) error {
	_, err := q.db.Exec(ctx, setFinalCustomerShipmentPrice,
		arg.FinalCustomerCurrency,
		arg.FinalCustomerFreightAmount,
		arg.TenantID,
		arg.SelectionID,
		arg.ID,
	)
	return err
}
