// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customer_selection.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeReadyCustomerSelections = `-- name: CompleteReadyCustomerSelections :exec
UPDATE sourcing_customer_selections s
SET status='FINAL_RECHECKED',final_rechecked_at=now(),updated_at=now()
WHERE s.tenant_id=$1 AND s.status='FINAL_RECHECK_PENDING'
  AND NOT EXISTS (SELECT 1 FROM sourcing_final_recheck_tasks t
                  WHERE t.tenant_id=s.tenant_id AND t.selection_id=s.id AND t.status='OPEN')
`

func (q *Queries) CompleteReadyCustomerSelections(ctx context.Context, tenantID int64) error {
	_, err := q.db.Exec(ctx, completeReadyCustomerSelections, tenantID)
	return err
}

const createCustomerSelection = `-- name: CreateCustomerSelection :one
INSERT INTO sourcing_customer_selections(tenant_id,case_id,sales_plan_id,selection_no,version_no,
 requirement_version_no,status,customer_contact,confirmation_note,customer_confirmed_at,created_by,created_by_name)
VALUES($1,$2,$3,
 'CS-'||to_char(current_date,'YYYYMMDD')||'-'||lpad(nextval('sourcing_customer_selection_no_seq')::text,6,'0'),
 (SELECT coalesce(max(version_no),0)+1 FROM sourcing_customer_selections
  WHERE tenant_id=$1 AND case_id=$2),
 $4,'FINAL_RECHECK_PENDING',$5,
 $6,$7::text::timestamptz,
 $8,$9)
RETURNING id
`

type CreateCustomerSelectionParams struct {
	TenantID             int64
	CaseID               int64
	SalesPlanID          int64
	RequirementVersionNo int32
	CustomerContact      string
	ConfirmationNote     string
	CustomerConfirmedAt  string
	CreatedBy            int64
	CreatedByName        string
}

func (q *Queries) CreateCustomerSelection(ctx context.Context, arg CreateCustomerSelectionParams) (int64, error) {
	row := q.db.QueryRow(ctx, createCustomerSelection,
		arg.TenantID,
		arg.CaseID,
		arg.SalesPlanID,
		arg.RequirementVersionNo,
		arg.CustomerContact,
		arg.ConfirmationNote,
		arg.CustomerConfirmedAt,
		arg.CreatedBy,
		arg.CreatedByName,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createCustomerSelectionItem = `-- name: CreateCustomerSelectionItem :one
INSERT INTO sourcing_customer_selection_items(tenant_id,selection_id,sales_plan_item_id,sourcing_line_id,
 procurement_plan_item_id,supplier_quote_line_id,shipping_plan_item_id,shipping_option_line_id,
 product_name,confirmed_qty,uom_code,customer_currency,customer_unit_price,promised_delivery_date,line_note)
VALUES($1,$2,$3,$4,
 $5,$6,
 nullif($7::bigint,0),nullif($8::bigint,0),
 $9,$10::text::numeric,$11,
 $12,$13::text::numeric,
 nullif($14::text,'')::date,$15)
RETURNING id
`

type CreateCustomerSelectionItemParams struct {
	TenantID              int64
	SelectionID           int64
	SalesPlanItemID       int64
	SourcingLineID        int64
	ProcurementPlanItemID int64
	SupplierQuoteLineID   int64
	ShippingPlanItemID    int64
	ShippingOptionLineID  int64
	ProductName           string
	ConfirmedQty          string
	UomCode               string
	CustomerCurrency      string
	CustomerUnitPrice     string
	PromisedDeliveryDate  string
	LineNote              string
}

func (q *Queries) CreateCustomerSelectionItem(ctx context.Context, arg CreateCustomerSelectionItemParams) (int64, error) {
	row := q.db.QueryRow(ctx, createCustomerSelectionItem,
		arg.TenantID,
		arg.SelectionID,
		arg.SalesPlanItemID,
		arg.SourcingLineID,
		arg.ProcurementPlanItemID,
		arg.SupplierQuoteLineID,
		arg.ShippingPlanItemID,
		arg.ShippingOptionLineID,
		arg.ProductName,
		arg.ConfirmedQty,
		arg.UomCode,
		arg.CustomerCurrency,
		arg.CustomerUnitPrice,
		arg.PromisedDeliveryDate,
		arg.LineNote,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createFinalProcurementRecheckTask = `-- name: CreateFinalProcurementRecheckTask :exec
INSERT INTO sourcing_final_recheck_tasks(tenant_id,selection_id,selection_item_id,task_domain,procurement_rework_id)
VALUES($1,$2,$3,'PROCUREMENT',$4)
`

type CreateFinalProcurementRecheckTaskParams struct {
	TenantID            int64
	SelectionID         int64
	SelectionItemID     int64
	ProcurementReworkID *int64
}

func (q *Queries) CreateFinalProcurementRecheckTask(ctx context.Context, arg CreateFinalProcurementRecheckTaskParams) error {
	_, err := q.db.Exec(ctx, createFinalProcurementRecheckTask,
		arg.TenantID,
		arg.SelectionID,
		arg.SelectionItemID,
		arg.ProcurementReworkID,
	)
	return err
}

const createFinalShippingRecheckTask = `-- name: CreateFinalShippingRecheckTask :exec
INSERT INTO sourcing_final_recheck_tasks(tenant_id,selection_id,selection_item_id,task_domain,shipping_rework_id)
VALUES($1,$2,$3,'SHIPPING',$4)
`

type CreateFinalShippingRecheckTaskParams struct {
	TenantID         int64
	SelectionID      int64
	SelectionItemID  int64
	ShippingReworkID *int64
}

func (q *Queries) CreateFinalShippingRecheckTask(ctx context.Context, arg CreateFinalShippingRecheckTaskParams) error {
	_, err := q.db.Exec(ctx, createFinalShippingRecheckTask,
		arg.TenantID,
		arg.SelectionID,
		arg.SelectionItemID,
		arg.ShippingReworkID,
	)
	return err
}

const customerSelectionCandidate = `-- name: CustomerSelectionCandidate :one
SELECT spi.id AS sales_plan_item_id,spi.sourcing_line_id,spi.procurement_plan_item_id,
 spi.shipping_plan_item_id,spi.product_name,spi.quoted_qty::text,spi.uom_code,
 spi.customer_currency,spi.customer_unit_price::text,
 coalesce(spi.promised_delivery_date::text,'')::text AS promised_delivery_date,spi.line_note,
 ppi.supplier_quote_line_id,ppi.buyer_id,ppi.buyer_name,ppi.supplier_id,ppi.supplier_name,
 coalesce(sspi.shipping_option_line_id,0)::bigint AS shipping_option_line_id,
 coalesce(sspi.shipping_employee_id,0)::bigint AS shipping_employee_id,
 coalesce(sspi.shipping_employee_name,'')::text AS shipping_employee_name,
 coalesce(sspi.carrier_forwarder,'')::text AS carrier_forwarder
FROM sourcing_sales_plan_items spi
JOIN sourcing_sales_plans sp ON sp.id=spi.plan_id AND sp.tenant_id=spi.tenant_id
JOIN procurement_plan_items ppi ON ppi.id=spi.procurement_plan_item_id AND ppi.tenant_id=spi.tenant_id
LEFT JOIN sourcing_shipping_plan_items sspi ON sspi.id=spi.shipping_plan_item_id AND sspi.tenant_id=spi.tenant_id
WHERE spi.tenant_id=$1 AND sp.case_id=$2 AND sp.id=$3 AND spi.id=$4
  AND sp.status='PRESENTED' AND sp.valid_until>=current_date
`

type CustomerSelectionCandidateParams struct {
	TenantID int64
	CaseID   int64
	ID       int64
	ID_2     int64
}

type CustomerSelectionCandidateRow struct {
	SalesPlanItemID       int64
	SourcingLineID        int64
	ProcurementPlanItemID int64
	ShippingPlanItemID    *int64
	ProductName           string
	SpiQuotedQty          string
	UomCode               string
	CustomerCurrency      string
	SpiCustomerUnitPrice  string
	PromisedDeliveryDate  string
	LineNote              string
	SupplierQuoteLineID   int64
	BuyerID               int64
	BuyerName             string
	SupplierID            int64
	SupplierName          string
	ShippingOptionLineID  int64
	ShippingEmployeeID    int64
	ShippingEmployeeName  string
	CarrierForwarder      string
}

func (q *Queries) CustomerSelectionCandidate(ctx context.Context, arg CustomerSelectionCandidateParams) (CustomerSelectionCandidateRow, error) {
	row := q.db.QueryRow(ctx, customerSelectionCandidate,
		arg.TenantID,
		arg.CaseID,
		arg.ID,
		arg.ID_2,
	)
	var i CustomerSelectionCandidateRow
	err := row.Scan(
		&i.SalesPlanItemID,
		&i.SourcingLineID,
		&i.ProcurementPlanItemID,
		&i.ShippingPlanItemID,
		&i.ProductName,
		&i.SpiQuotedQty,
		&i.UomCode,
		&i.CustomerCurrency,
		&i.SpiCustomerUnitPrice,
		&i.PromisedDeliveryDate,
		&i.LineNote,
		&i.SupplierQuoteLineID,
		&i.BuyerID,
		&i.BuyerName,
		&i.SupplierID,
		&i.SupplierName,
		&i.ShippingOptionLineID,
		&i.ShippingEmployeeID,
		&i.ShippingEmployeeName,
		&i.CarrierForwarder,
	)
	return i, err
}

const invalidateActiveCustomerSelections = `-- name: InvalidateActiveCustomerSelections :exec
UPDATE sourcing_customer_selections
SET status='INVALIDATED',invalidated_at=now(),invalidated_reason=$1,updated_at=now()
WHERE tenant_id=$2 AND case_id=$3
  AND status IN ('FINAL_RECHECK_PENDING','FINAL_RECHECKED')
`

type InvalidateActiveCustomerSelectionsParams struct {
	Reason   string
	TenantID int64
	CaseID   int64
}

func (q *Queries) InvalidateActiveCustomerSelections(ctx context.Context, arg InvalidateActiveCustomerSelectionsParams) error {
	_, err := q.db.Exec(ctx, invalidateActiveCustomerSelections, arg.Reason, arg.TenantID, arg.CaseID)
	return err
}

const invalidateExpiredCustomerSelections = `-- name: InvalidateExpiredCustomerSelections :exec
UPDATE sourcing_customer_selections s
SET status='INVALIDATED',invalidated_at=now(),
    invalidated_reason='客户沟通方案已超过有效期',updated_at=now()
FROM sourcing_sales_plans sp
WHERE s.tenant_id=$1 AND s.case_id=$2
  AND sp.tenant_id=s.tenant_id AND sp.id=s.sales_plan_id
  AND s.status IN ('FINAL_RECHECK_PENDING','FINAL_RECHECKED')
  AND sp.valid_until<current_date
`

type InvalidateExpiredCustomerSelectionsParams struct {
	TenantID int64
	CaseID   int64
}

func (q *Queries) InvalidateExpiredCustomerSelections(ctx context.Context, arg InvalidateExpiredCustomerSelectionsParams) error {
	_, err := q.db.Exec(ctx, invalidateExpiredCustomerSelections, arg.TenantID, arg.CaseID)
	return err
}

const listCustomerSelectionItems = `-- name: ListCustomerSelectionItems :many
SELECT id,sales_plan_item_id,sourcing_line_id,procurement_plan_item_id,supplier_quote_line_id,
 coalesce(shipping_plan_item_id,0)::bigint AS shipping_plan_item_id,
 coalesce(shipping_option_line_id,0)::bigint AS shipping_option_line_id,
 product_name,confirmed_qty::text,uom_code,customer_currency,customer_unit_price::text,
 coalesce(promised_delivery_date::text,'')::text AS promised_delivery_date,line_note
FROM sourcing_customer_selection_items WHERE tenant_id=$1 AND selection_id=$2 ORDER BY id
`

type ListCustomerSelectionItemsParams struct {
	TenantID    int64
	SelectionID int64
}

type ListCustomerSelectionItemsRow struct {
	ID                    int64
	SalesPlanItemID       int64
	SourcingLineID        int64
	ProcurementPlanItemID int64
	SupplierQuoteLineID   int64
	ShippingPlanItemID    int64
	ShippingOptionLineID  int64
	ProductName           string
	ConfirmedQty          string
	UomCode               string
	CustomerCurrency      string
	CustomerUnitPrice     string
	PromisedDeliveryDate  string
	LineNote              string
}

func (q *Queries) ListCustomerSelectionItems(ctx context.Context, arg ListCustomerSelectionItemsParams) ([]ListCustomerSelectionItemsRow, error) {
	rows, err := q.db.Query(ctx, listCustomerSelectionItems, arg.TenantID, arg.SelectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomerSelectionItemsRow
	for rows.Next() {
		var i ListCustomerSelectionItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.SalesPlanItemID,
			&i.SourcingLineID,
			&i.ProcurementPlanItemID,
			&i.SupplierQuoteLineID,
			&i.ShippingPlanItemID,
			&i.ShippingOptionLineID,
			&i.ProductName,
			&i.ConfirmedQty,
			&i.UomCode,
			&i.CustomerCurrency,
			&i.CustomerUnitPrice,
			&i.PromisedDeliveryDate,
			&i.LineNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomerSelections = `-- name: ListCustomerSelections :many
SELECT id,case_id,sales_plan_id,selection_no,version_no,requirement_version_no,status,
 customer_contact,confirmation_note,customer_confirmed_at,created_by,created_by_name,created_at,
 coalesce(final_rechecked_at::text,'')::text AS final_rechecked_at,
 coalesce(invalidated_at::text,'')::text AS invalidated_at,invalidated_reason
FROM sourcing_customer_selections WHERE tenant_id=$1 AND case_id=$2 ORDER BY version_no DESC
`

type ListCustomerSelectionsParams struct {
	TenantID int64
	CaseID   int64
}

type ListCustomerSelectionsRow struct {
	ID                   int64
	CaseID               int64
	SalesPlanID          int64
	SelectionNo          string
	VersionNo            int32
	RequirementVersionNo int32
	Status               string
	CustomerContact      string
	ConfirmationNote     string
	CustomerConfirmedAt  pgtype.Timestamptz
	CreatedBy            int64
	CreatedByName        string
	CreatedAt            pgtype.Timestamptz
	FinalRecheckedAt     string
	InvalidatedAt        string
	InvalidatedReason    string
}

func (q *Queries) ListCustomerSelections(ctx context.Context, arg ListCustomerSelectionsParams) ([]ListCustomerSelectionsRow, error) {
	rows, err := q.db.Query(ctx, listCustomerSelections, arg.TenantID, arg.CaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomerSelectionsRow
	for rows.Next() {
		var i ListCustomerSelectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.SalesPlanID,
			&i.SelectionNo,
			&i.VersionNo,
			&i.RequirementVersionNo,
			&i.Status,
			&i.CustomerContact,
			&i.ConfirmationNote,
			&i.CustomerConfirmedAt,
			&i.CreatedBy,
			&i.CreatedByName,
			&i.CreatedAt,
			&i.FinalRecheckedAt,
			&i.InvalidatedAt,
			&i.InvalidatedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFinalRecheckTasks = `-- name: ListFinalRecheckTasks :many
SELECT id,selection_item_id,task_domain,coalesce(procurement_rework_id,0)::bigint AS procurement_rework_id,
 coalesce(shipping_rework_id,0)::bigint AS shipping_rework_id,status,
 coalesce(resolved_at::text,'')::text AS resolved_at
FROM sourcing_final_recheck_tasks WHERE tenant_id=$1 AND selection_id=$2 ORDER BY selection_item_id,task_domain
`

type ListFinalRecheckTasksParams struct {
	TenantID    int64
	SelectionID int64
}

type ListFinalRecheckTasksRow struct {
	ID                  int64
	SelectionItemID     int64
	TaskDomain          string
	ProcurementReworkID int64
	ShippingReworkID    int64
	Status              string
	ResolvedAt          string
}

func (q *Queries) ListFinalRecheckTasks(ctx context.Context, arg ListFinalRecheckTasksParams) ([]ListFinalRecheckTasksRow, error) {
	rows, err := q.db.Query(ctx, listFinalRecheckTasks, arg.TenantID, arg.SelectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFinalRecheckTasksRow
	for rows.Next() {
		var i ListFinalRecheckTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.SelectionItemID,
			&i.TaskDomain,
			&i.ProcurementReworkID,
			&i.ShippingReworkID,
			&i.Status,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveFinalTaskByProcurementRework = `-- name: ResolveFinalTaskByProcurementRework :exec
UPDATE sourcing_final_recheck_tasks SET status='RESOLVED',resolved_at=now()
WHERE tenant_id=$1 AND procurement_rework_id=$2 AND status='OPEN'
`

type ResolveFinalTaskByProcurementReworkParams struct {
	TenantID            int64
	ProcurementReworkID *int64
}

func (q *Queries) ResolveFinalTaskByProcurementRework(ctx context.Context, arg ResolveFinalTaskByProcurementReworkParams) error {
	_, err := q.db.Exec(ctx, resolveFinalTaskByProcurementRework, arg.TenantID, arg.ProcurementReworkID)
	return err
}

const resolveFinalTaskByShippingRework = `-- name: ResolveFinalTaskByShippingRework :exec
UPDATE sourcing_final_recheck_tasks SET status='RESOLVED',resolved_at=now()
WHERE tenant_id=$1 AND shipping_rework_id=$2 AND status='OPEN'
`

type ResolveFinalTaskByShippingReworkParams struct {
	TenantID         int64
	ShippingReworkID *int64
}

func (q *Queries) ResolveFinalTaskByShippingRework(ctx context.Context, arg ResolveFinalTaskByShippingReworkParams) error {
	_, err := q.db.Exec(ctx, resolveFinalTaskByShippingRework, arg.TenantID, arg.ShippingReworkID)
	return err
}
