// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: factory_sourcing.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFactoryRFQ = `-- name: CreateFactoryRFQ :one
INSERT INTO factory_rfqs (tenant_id, case_id, rfq_no, supplier_id, supplier_code, supplier_name,
 factory_id, factory_code, factory_name, contact_email, currency, response_due_at, created_by, created_by_name,
 inquiry_channel, contact_name, contact_value, contacted_at, inquiry_note, round_no)
VALUES ($1, $2,
 'RFQ-' || to_char(current_date,'YYYYMMDD') || '-' || lpad(nextval('factory_rfq_no_seq')::text,6,'0'),
 $3, $4, $5,
 $6, $7, $8, $9,
 $10, nullif($11::text,'')::date,
 $12, $13, $14, $15,
 $16, nullif($17::text,'')::timestamptz, $18, $19)
RETURNING id, rfq_no
`

type CreateFactoryRFQParams struct {
	TenantID       int64
	CaseID         int64
	SupplierID     int64
	SupplierCode   string
	SupplierName   string
	FactoryID      int64
	FactoryCode    string
	FactoryName    string
	ContactEmail   string
	Currency       string
	ResponseDueAt  string
	CreatedBy      int64
	CreatedByName  string
	InquiryChannel string
	ContactName    string
	ContactValue   string
	ContactedAt    string
	InquiryNote    string
	RoundNo        int32
}

type CreateFactoryRFQRow struct {
	ID    int64
	RfqNo string
}

func (q *Queries) CreateFactoryRFQ(ctx context.Context, arg CreateFactoryRFQParams) (CreateFactoryRFQRow, error) {
	row := q.db.QueryRow(ctx, createFactoryRFQ,
		arg.TenantID,
		arg.CaseID,
		arg.SupplierID,
		arg.SupplierCode,
		arg.SupplierName,
		arg.FactoryID,
		arg.FactoryCode,
		arg.FactoryName,
		arg.ContactEmail,
		arg.Currency,
		arg.ResponseDueAt,
		arg.CreatedBy,
		arg.CreatedByName,
		arg.InquiryChannel,
		arg.ContactName,
		arg.ContactValue,
		arg.ContactedAt,
		arg.InquiryNote,
		arg.RoundNo,
	)
	var i CreateFactoryRFQRow
	err := row.Scan(&i.ID, &i.RfqNo)
	return i, err
}

const createFactoryRFQLine = `-- name: CreateFactoryRFQLine :exec
INSERT INTO factory_rfq_lines (tenant_id, factory_rfq_id, sourcing_line_id, line_no, qty, uom_code, spec_snapshot)
SELECT $1, $2, sl.id, sl.line_no, sl.quantity, sl.quantity_unit,
 concat_ws(' / ', nullif(sl.material_standard,''), nullif(sl.grade,''), nullif(sl.thickness,''), nullif(sl.width,''), nullif(sl.length_or_form,''))
FROM sourcing_lines sl
WHERE sl.tenant_id=$1 AND sl.case_id=$3 AND sl.id=$4
  AND sl.quantity IS NOT NULL AND sl.quantity > 0
`

type CreateFactoryRFQLineParams struct {
	TenantID       int64
	FactoryRfqID   int64
	CaseID         int64
	SourcingLineID int64
}

func (q *Queries) CreateFactoryRFQLine(ctx context.Context, arg CreateFactoryRFQLineParams) error {
	_, err := q.db.Exec(ctx, createFactoryRFQLine,
		arg.TenantID,
		arg.FactoryRfqID,
		arg.CaseID,
		arg.SourcingLineID,
	)
	return err
}

const createSupplierQuote = `-- name: CreateSupplierQuote :one
INSERT INTO supplier_quotes (tenant_id,factory_rfq_id,supplier_quote_no,quoted_at,valid_until,currency,
 payment_terms,delivery,remark,source,created_by,version_no,confirmation_status,evidence_note)
VALUES ($1,$2,
 'SQ-' || to_char(current_date,'YYYYMMDD') || '-' || lpad(nextval('supplier_quote_no_seq')::text,6,'0'),
 nullif($3::text,'')::date,nullif($4::text,'')::date,
 $5,$6,$7,$8,$9,$10,
 (SELECT coalesce(max(version_no),0)+1 FROM supplier_quotes WHERE tenant_id=$1 AND factory_rfq_id=$2),
 $11,$12)
RETURNING id,supplier_quote_no,version_no
`

type CreateSupplierQuoteParams struct {
	TenantID           int64
	FactoryRfqID       int64
	QuotedAt           string
	ValidUntil         string
	Currency           string
	PaymentTerms       string
	Delivery           string
	Remark             string
	Source             string
	CreatedBy          int64
	ConfirmationStatus string
	EvidenceNote       string
}

type CreateSupplierQuoteRow struct {
	ID              int64
	SupplierQuoteNo string
	VersionNo       int32
}

func (q *Queries) CreateSupplierQuote(ctx context.Context, arg CreateSupplierQuoteParams) (CreateSupplierQuoteRow, error) {
	row := q.db.QueryRow(ctx, createSupplierQuote,
		arg.TenantID,
		arg.FactoryRfqID,
		arg.QuotedAt,
		arg.ValidUntil,
		arg.Currency,
		arg.PaymentTerms,
		arg.Delivery,
		arg.Remark,
		arg.Source,
		arg.CreatedBy,
		arg.ConfirmationStatus,
		arg.EvidenceNote,
	)
	var i CreateSupplierQuoteRow
	err := row.Scan(&i.ID, &i.SupplierQuoteNo, &i.VersionNo)
	return i, err
}

const createSupplierQuoteLine = `-- name: CreateSupplierQuoteLine :exec
INSERT INTO supplier_quote_lines (tenant_id,supplier_quote_id,sourcing_line_id,qty,unit_price,amount,moq,lead_time,remark)
VALUES ($1,$2,$3,$4::text::numeric,
 $5::text::numeric,($4::text::numeric*$5::text::numeric)::numeric(18,2),
 nullif($6::text,'')::numeric,$7,$8)
`

type CreateSupplierQuoteLineParams struct {
	TenantID        int64
	SupplierQuoteID int64
	SourcingLineID  int64
	Qty             string
	UnitPrice       string
	Moq             string
	LeadTime        string
	Remark          string
}

func (q *Queries) CreateSupplierQuoteLine(ctx context.Context, arg CreateSupplierQuoteLineParams) error {
	_, err := q.db.Exec(ctx, createSupplierQuoteLine,
		arg.TenantID,
		arg.SupplierQuoteID,
		arg.SourcingLineID,
		arg.Qty,
		arg.UnitPrice,
		arg.Moq,
		arg.LeadTime,
		arg.Remark,
	)
	return err
}

const factoryRFQCase = `-- name: FactoryRFQCase :one
SELECT case_id FROM factory_rfqs WHERE tenant_id=$1 AND id=$2
`

type FactoryRFQCaseParams struct {
	TenantID int64
	ID       int64
}

func (q *Queries) FactoryRFQCase(ctx context.Context, arg FactoryRFQCaseParams) (int64, error) {
	row := q.db.QueryRow(ctx, factoryRFQCase, arg.TenantID, arg.ID)
	var case_id int64
	err := row.Scan(&case_id)
	return case_id, err
}

const factoryRFQForQuote = `-- name: FactoryRFQForQuote :one
SELECT id,case_id,currency,status,created_by FROM factory_rfqs WHERE tenant_id=$1 AND id=$2 FOR UPDATE
`

type FactoryRFQForQuoteParams struct {
	TenantID int64
	ID       int64
}

type FactoryRFQForQuoteRow struct {
	ID        int64
	CaseID    int64
	Currency  string
	Status    string
	CreatedBy int64
}

func (q *Queries) FactoryRFQForQuote(ctx context.Context, arg FactoryRFQForQuoteParams) (FactoryRFQForQuoteRow, error) {
	row := q.db.QueryRow(ctx, factoryRFQForQuote, arg.TenantID, arg.ID)
	var i FactoryRFQForQuoteRow
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.Currency,
		&i.Status,
		&i.CreatedBy,
	)
	return i, err
}

const factoryRFQLines = `-- name: FactoryRFQLines :many
SELECT sourcing_line_id,qty::text,uom_code,spec_snapshot FROM factory_rfq_lines
WHERE tenant_id=$1 AND factory_rfq_id=$2 ORDER BY line_no
`

type FactoryRFQLinesParams struct {
	TenantID     int64
	FactoryRfqID int64
}

type FactoryRFQLinesRow struct {
	SourcingLineID int64
	Qty            string
	UomCode        string
	SpecSnapshot   string
}

func (q *Queries) FactoryRFQLines(ctx context.Context, arg FactoryRFQLinesParams) ([]FactoryRFQLinesRow, error) {
	rows, err := q.db.Query(ctx, factoryRFQLines, arg.TenantID, arg.FactoryRfqID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FactoryRFQLinesRow
	for rows.Next() {
		var i FactoryRFQLinesRow
		if err := rows.Scan(
			&i.SourcingLineID,
			&i.Qty,
			&i.UomCode,
			&i.SpecSnapshot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFactoryRFQDocument = `-- name: GetFactoryRFQDocument :one
SELECT id,rfq_no,supplier_name,contact_email,currency,
 coalesce(response_due_at::text,'')::text AS response_due_at
FROM factory_rfqs WHERE tenant_id=$1 AND id=$2
`

type GetFactoryRFQDocumentParams struct {
	TenantID int64
	ID       int64
}

type GetFactoryRFQDocumentRow struct {
	ID            int64
	RfqNo         string
	SupplierName  string
	ContactEmail  string
	Currency      string
	ResponseDueAt string
}

func (q *Queries) GetFactoryRFQDocument(ctx context.Context, arg GetFactoryRFQDocumentParams) (GetFactoryRFQDocumentRow, error) {
	row := q.db.QueryRow(ctx, getFactoryRFQDocument, arg.TenantID, arg.ID)
	var i GetFactoryRFQDocumentRow
	err := row.Scan(
		&i.ID,
		&i.RfqNo,
		&i.SupplierName,
		&i.ContactEmail,
		&i.Currency,
		&i.ResponseDueAt,
	)
	return i, err
}

const listFactoryRFQs = `-- name: ListFactoryRFQs :many
SELECT r.id,r.case_id,r.rfq_no,r.supplier_id,r.supplier_code,r.supplier_name,
 r.factory_id,r.factory_code,r.factory_name,r.contact_email,
 r.currency,coalesce(r.response_due_at::text,'')::text AS response_due_at,r.status,r.created_at,r.created_by,r.created_by_name,
 r.inquiry_channel,r.contact_name,r.contact_value,coalesce(r.contacted_at::text,'')::text AS contacted_at,r.inquiry_note,r.round_no,
 (SELECT count(*)::int FROM factory_rfq_lines fl WHERE fl.tenant_id=r.tenant_id AND fl.factory_rfq_id=r.id) AS line_count,
 ARRAY(SELECT fl.sourcing_line_id FROM factory_rfq_lines fl WHERE fl.tenant_id=r.tenant_id AND fl.factory_rfq_id=r.id ORDER BY fl.line_no)::bigint[] AS sourcing_line_ids
FROM factory_rfqs r
WHERE r.tenant_id=$1 AND r.case_id=$2
ORDER BY r.created_at DESC
`

type ListFactoryRFQsParams struct {
	TenantID int64
	CaseID   int64
}

type ListFactoryRFQsRow struct {
	ID              int64
	CaseID          int64
	RfqNo           string
	SupplierID      int64
	SupplierCode    string
	SupplierName    string
	FactoryID       int64
	FactoryCode     string
	FactoryName     string
	ContactEmail    string
	Currency        string
	ResponseDueAt   string
	Status          string
	CreatedAt       pgtype.Timestamptz
	CreatedBy       int64
	CreatedByName   string
	InquiryChannel  string
	ContactName     string
	ContactValue    string
	ContactedAt     string
	InquiryNote     string
	RoundNo         int32
	LineCount       int32
	SourcingLineIds []int64
}

func (q *Queries) ListFactoryRFQs(ctx context.Context, arg ListFactoryRFQsParams) ([]ListFactoryRFQsRow, error) {
	rows, err := q.db.Query(ctx, listFactoryRFQs, arg.TenantID, arg.CaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFactoryRFQsRow
	for rows.Next() {
		var i ListFactoryRFQsRow
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.RfqNo,
			&i.SupplierID,
			&i.SupplierCode,
			&i.SupplierName,
			&i.FactoryID,
			&i.FactoryCode,
			&i.FactoryName,
			&i.ContactEmail,
			&i.Currency,
			&i.ResponseDueAt,
			&i.Status,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.CreatedByName,
			&i.InquiryChannel,
			&i.ContactName,
			&i.ContactValue,
			&i.ContactedAt,
			&i.InquiryNote,
			&i.RoundNo,
			&i.LineCount,
			&i.SourcingLineIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverdueFactoryRFQs = `-- name: ListOverdueFactoryRFQs :many
SELECT r.id, r.rfq_no, r.case_id, c.case_no, r.supplier_name,
       r.response_due_at::text AS response_due_at,
       (current_date - r.response_due_at)::int AS overdue_days
FROM factory_rfqs r
JOIN sourcing_cases c ON c.id = r.case_id AND c.tenant_id = r.tenant_id
WHERE r.tenant_id = $1::bigint
  AND r.status IN ('SENT', 'PARTIALLY_QUOTED')
  AND r.response_due_at < current_date
  AND ($2::bool
       OR c.owner_id = ANY($3::bigint[]))
ORDER BY r.response_due_at, r.id
LIMIT $4::int
`

type ListOverdueFactoryRFQsParams struct {
	TenantID   int64
	VisibleAll bool
	VisibleIds []int64
	RowLimit   int32
}

type ListOverdueFactoryRFQsRow struct {
	ID            int64
	RfqNo         string
	CaseID        int64
	CaseNo        string
	SupplierName  string
	ResponseDueAt string
	OverdueDays   int32
}

// 工作台的今日重点（B4）：过了回复期限还没报价的询价。围栏沿用询价
// 案件的属主可见性——工作台只是列表的另一个入口，不是另一套权限。
func (q *Queries) ListOverdueFactoryRFQs(ctx context.Context, arg ListOverdueFactoryRFQsParams) ([]ListOverdueFactoryRFQsRow, error) {
	rows, err := q.db.Query(ctx, listOverdueFactoryRFQs,
		arg.TenantID,
		arg.VisibleAll,
		arg.VisibleIds,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOverdueFactoryRFQsRow
	for rows.Next() {
		var i ListOverdueFactoryRFQsRow
		if err := rows.Scan(
			&i.ID,
			&i.RfqNo,
			&i.CaseID,
			&i.CaseNo,
			&i.SupplierName,
			&i.ResponseDueAt,
			&i.OverdueDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplierQuoteComparison = `-- name: ListSupplierQuoteComparison :many
SELECT q.id AS quote_id,l.id AS quote_line_id,q.supplier_quote_no,q.factory_rfq_id,r.supplier_id,r.supplier_name,q.currency,
 coalesce(q.quoted_at::text,'')::text AS quoted_at,coalesce(q.valid_until::text,'')::text AS valid_until,
 q.payment_terms,q.delivery,q.remark,q.source,q.version_no,q.confirmation_status,q.evidence_note,q.created_by,r.created_by_name,
 l.sourcing_line_id,l.qty::text,l.unit_price::text,
 l.amount::text,coalesce(l.moq::text,'')::text AS moq,l.lead_time,l.remark AS line_remark
FROM supplier_quotes q JOIN factory_rfqs r ON r.id=q.factory_rfq_id AND r.tenant_id=q.tenant_id
JOIN supplier_quote_lines l ON l.supplier_quote_id=q.id AND l.tenant_id=q.tenant_id
WHERE q.tenant_id=$1 AND r.case_id=$2
ORDER BY l.sourcing_line_id,l.unit_price,q.created_at
`

type ListSupplierQuoteComparisonParams struct {
	TenantID int64
	CaseID   int64
}

type ListSupplierQuoteComparisonRow struct {
	QuoteID            int64
	QuoteLineID        int64
	SupplierQuoteNo    string
	FactoryRfqID       int64
	SupplierID         int64
	SupplierName       string
	Currency           string
	QuotedAt           string
	ValidUntil         string
	PaymentTerms       string
	Delivery           string
	Remark             string
	Source             string
	VersionNo          int32
	ConfirmationStatus string
	EvidenceNote       string
	CreatedBy          int64
	CreatedByName      string
	SourcingLineID     int64
	LQty               string
	LUnitPrice         string
	LAmount            string
	Moq                string
	LeadTime           string
	LineRemark         string
}

func (q *Queries) ListSupplierQuoteComparison(ctx context.Context, arg ListSupplierQuoteComparisonParams) ([]ListSupplierQuoteComparisonRow, error) {
	rows, err := q.db.Query(ctx, listSupplierQuoteComparison, arg.TenantID, arg.CaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSupplierQuoteComparisonRow
	for rows.Next() {
		var i ListSupplierQuoteComparisonRow
		if err := rows.Scan(
			&i.QuoteID,
			&i.QuoteLineID,
			&i.SupplierQuoteNo,
			&i.FactoryRfqID,
			&i.SupplierID,
			&i.SupplierName,
			&i.Currency,
			&i.QuotedAt,
			&i.ValidUntil,
			&i.PaymentTerms,
			&i.Delivery,
			&i.Remark,
			&i.Source,
			&i.VersionNo,
			&i.ConfirmationStatus,
			&i.EvidenceNote,
			&i.CreatedBy,
			&i.CreatedByName,
			&i.SourcingLineID,
			&i.LQty,
			&i.LUnitPrice,
			&i.LAmount,
			&i.Moq,
			&i.LeadTime,
			&i.LineRemark,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFactoryRFQQuoted = `-- name: MarkFactoryRFQQuoted :exec
UPDATE factory_rfqs SET status='QUOTED',updated_at=now() WHERE tenant_id=$1 AND id=$2
`

type MarkFactoryRFQQuotedParams struct {
	TenantID int64
	ID       int64
}

func (q *Queries) MarkFactoryRFQQuoted(ctx context.Context, arg MarkFactoryRFQQuotedParams) error {
	_, err := q.db.Exec(ctx, markFactoryRFQQuoted, arg.TenantID, arg.ID)
	return err
}

const markFactoryRFQSent = `-- name: MarkFactoryRFQSent :execrows
UPDATE factory_rfqs SET status='SENT',updated_at=now()
WHERE tenant_id=$1 AND id=$2 AND status='DRAFT'
`

type MarkFactoryRFQSentParams struct {
	TenantID int64
	ID       int64
}

func (q *Queries) MarkFactoryRFQSent(ctx context.Context, arg MarkFactoryRFQSentParams) (int64, error) {
	result, err := q.db.Exec(ctx, markFactoryRFQSent, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markSourcingCaseQuotesReceived = `-- name: MarkSourcingCaseQuotesReceived :exec
UPDATE sourcing_cases SET status='QUOTES_RECEIVED',updated_at=now() WHERE tenant_id=$1 AND id=$2
`

type MarkSourcingCaseQuotesReceivedParams struct {
	TenantID int64
	ID       int64
}

func (q *Queries) MarkSourcingCaseQuotesReceived(ctx context.Context, arg MarkSourcingCaseQuotesReceivedParams) error {
	_, err := q.db.Exec(ctx, markSourcingCaseQuotesReceived, arg.TenantID, arg.ID)
	return err
}

const markSourcingCaseSourcing = `-- name: MarkSourcingCaseSourcing :exec
UPDATE sourcing_cases SET status='SOURCING',updated_at=now()
WHERE tenant_id=$1 AND id=$2 AND status='REVIEWING'
`

type MarkSourcingCaseSourcingParams struct {
	TenantID int64
	ID       int64
}

func (q *Queries) MarkSourcingCaseSourcing(ctx context.Context, arg MarkSourcingCaseSourcingParams) error {
	_, err := q.db.Exec(ctx, markSourcingCaseSourcing, arg.TenantID, arg.ID)
	return err
}

const updateFactoryRFQ = `-- name: UpdateFactoryRFQ :execrows
UPDATE factory_rfqs SET inquiry_channel=$1,
 contact_name=$2,contact_email=$3,
 contact_value=$4,
 contacted_at=nullif($5::text,'')::timestamptz,
 inquiry_note=$6,
 response_due_at=nullif($7::text,'')::date,updated_at=now()
WHERE tenant_id=$8 AND id=$9
  AND status IN ('DRAFT','SENT','PARTIALLY_QUOTED')
`

type UpdateFactoryRFQParams struct {
	InquiryChannel string
	ContactName    string
	ContactEmail   string
	ContactValue   string
	ContactedAt    string
	InquiryNote    string
	ResponseDueAt  string
	TenantID       int64
	ID             int64
}

func (q *Queries) UpdateFactoryRFQ(ctx context.Context, arg UpdateFactoryRFQParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateFactoryRFQ,
		arg.InquiryChannel,
		arg.ContactName,
		arg.ContactEmail,
		arg.ContactValue,
		arg.ContactedAt,
		arg.InquiryNote,
		arg.ResponseDueAt,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
