// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BankAccount struct {
	ID          int64
	TenantID    int64
	AccountNo   string
	AccountName string
	BankName    string
	Currency    string
	Status      string
	CreatedAt   pgtype.Timestamptz
}

type BankTransaction struct {
	ID                  int64
	TenantID            int64
	TxnDate             pgtype.Date
	Direction           string
	Amount              pgtype.Numeric
	Currency            string
	Counterparty        string
	BankRef             string
	Remark              string
	SourceFile          string
	ImportedByID        int64
	ImportedByName      string
	CreatedAt           pgtype.Timestamptz
	Ownership           string
	OwnershipDetail     string
	AccountID           int64
	CounterpartyAccount string
	RemittanceInfo      string
	Source              string
	TrustedRef          string
	Note                string
	ClaimedAmount       pgtype.Numeric
	AttachmentKey       string
	DeletedAt           pgtype.Timestamptz
	DeletedByID         int64
	DeletedByName       string
	DeleteReason        string
}

type CostCharge struct {
	ID              int64
	TenantID        int64
	ScenarioID      int64
	ChargeType      string
	Basis           string
	Description     string
	OriginPort      string
	DestinationPort string
	ContainerType   string
	Amount          pgtype.Numeric
	Currency        string
	ConvertedAmount pgtype.Numeric
	SourceFxRate    pgtype.Numeric
	TargetFxRate    pgtype.Numeric
	FxRateAt        pgtype.Timestamptz
	FxSource        string
	EffectiveAt     pgtype.Date
	ValidUntil      pgtype.Date
	Source          string
	Remark          string
}

type CostScenario struct {
	ID                     int64
	TenantID               int64
	CaseID                 int64
	ScenarioNo             string
	Currency               string
	AllocationBasis        string
	MarginType             string
	MarginValue            pgtype.Numeric
	FxRate                 pgtype.Numeric
	FxRateAt               pgtype.Timestamptz
	FxSource               string
	FxBaseCurrency         string
	ProductTotal           pgtype.Numeric
	ChargeTotal            pgtype.Numeric
	LandedTotal            pgtype.Numeric
	MarginTotal            pgtype.Numeric
	CustomerTotal          pgtype.Numeric
	Status                 string
	CustomerQuotationID    *int64
	CustomerQuoteNo        string
	CreatedBy              int64
	CreatedByName          string
	ConfirmedBy            *int64
	ConfirmedByName        string
	ConfirmedAt            pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	ConfirmReason          string
	VersionNo              int32
	RequirementVersionNo   int32
	SubmittedToSalesBy     *int64
	SubmittedToSalesByName string
	SubmittedToSalesAt     pgtype.Timestamptz
}

type CostScenarioLine struct {
	ID                  int64
	TenantID            int64
	ScenarioID          int64
	SourcingLineID      int64
	SupplierQuoteLineID int64
	SupplierName        string
	ProductID           int64
	SkuID               *int64
	ProductName         string
	SpecSnapshot        string
	Qty                 pgtype.Numeric
	UomCode             string
	SourceCurrency      string
	SourceUnitPrice     pgtype.Numeric
	SourceFxRate        pgtype.Numeric
	TargetFxRate        pgtype.Numeric
	ProductCost         pgtype.Numeric
	AllocatedCharge     pgtype.Numeric
	LandedCost          pgtype.Numeric
	MarginAmount        pgtype.Numeric
	CustomerUnitPrice   pgtype.Numeric
	CustomerAmount      pgtype.Numeric
}

type FactoryRfq struct {
	ID             int64
	TenantID       int64
	CaseID         int64
	RfqNo          string
	SupplierID     int64
	SupplierCode   string
	SupplierName   string
	ContactEmail   string
	Currency       string
	ResponseDueAt  pgtype.Date
	Status         string
	CreatedBy      int64
	CreatedByName  string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	FactoryID      int64
	FactoryCode    string
	FactoryName    string
	InquiryChannel string
	ContactName    string
	ContactValue   string
	ContactedAt    pgtype.Timestamptz
	InquiryNote    string
	RoundNo        int32
}

type FactoryRfqLine struct {
	ID             int64
	TenantID       int64
	FactoryRfqID   int64
	SourcingLineID int64
	LineNo         int32
	Qty            pgtype.Numeric
	UomCode        string
	SpecSnapshot   string
}

type FailedEvent struct {
	ID            int64
	TenantID      int64
	EventID       string
	ConsumerGroup string
	Topic         string
	EventType     string
	AggregateID   string
	Payload       []byte
	Reason        string
	ParkedAt      pgtype.Timestamptz
}

type InquiryTemplate struct {
	ID            int64
	TenantID      int64
	TemplateCode  string
	Version       int32
	Name          string
	Description   string
	Status        string
	IsDefault     bool
	CreatedBy     int64
	CreatedByName string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type InquiryTemplateField struct {
	ID           int64
	TenantID     int64
	TemplateID   int64
	FieldKey     string
	DisplayName  string
	SortOrder    int32
	IsRequired   bool
	DefaultValue string
	DataType     string
	IsCustom     bool
}

type OutboxEvent struct {
	ID            int64
	TenantID      int64
	AggregateType string
	AggregateID   string
	EventType     string
	Payload       []byte
	TraceID       string
	CreatedAt     pgtype.Timestamptz
	PublishedAt   pgtype.Timestamptz
	Attempts      int32
	LastError     *string
}

type PaymentAllocation struct {
	ID              int64
	TenantID        int64
	PaymentID       *int64
	InvoiceID       *int64
	PoID            *int64
	Amount          pgtype.Numeric
	FeeAmount       pgtype.Numeric
	Currency        string
	ReversalOf      *int64
	ReverseReason   string
	AllocatedBy     int64
	AllocatedByName string
	AllocatedAt     pgtype.Timestamptz
	PaidAt          pgtype.Date
	Note            string
}

type ProcessedEvent struct {
	EventID       string
	ConsumerGroup string
	ProcessedAt   pgtype.Timestamptz
}

type ProcurementPlan struct {
	ID                     int64
	TenantID               int64
	CaseID                 int64
	PlanNo                 string
	VersionNo              int32
	RequirementVersionNo   int32
	Status                 string
	ManagerNote            string
	CreatedBy              int64
	CreatedByName          string
	ConfirmedBy            int64
	ConfirmedByName        string
	ConfirmedAt            pgtype.Timestamptz
	SubmittedToSalesBy     *int64
	SubmittedToSalesByName string
	SubmittedToSalesAt     pgtype.Timestamptz
	TargetSalesID          int64
	TargetSalesName        string
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type ProcurementPlanItem struct {
	ID                  int64
	TenantID            int64
	PlanID              int64
	SourcingLineID      int64
	SupplierQuoteLineID int64
	SelectionType       string
	Priority            int32
	Reason              string
	Risk                string
	SupplierID          int64
	SupplierName        string
	FactoryID           *int64
	FactoryName         string
	BuyerID             int64
	BuyerName           string
	ProductName         string
	Currency            string
	UnitPrice           pgtype.Numeric
	AvailableQty        pgtype.Numeric
	UomCode             string
	Moq                 pgtype.Numeric
	LeadTime            *int32
	PaymentTerms        string
	Incoterm            string
	ValidUntil          pgtype.Date
	QuoteVersionNo      int32
	CreatedAt           pgtype.Timestamptz
}

type ProcurementReworkRequest struct {
	ID                  int64
	TenantID            int64
	CaseID              int64
	PlanID              *int64
	SourcingLineID      *int64
	SupplierQuoteLineID *int64
	RequestType         string
	ScopeType           string
	AssignedBuyerID     *int64
	AssignedBuyerName   string
	SupplierID          *int64
	SupplierName        string
	ProductName         string
	Reason              string
	Status              string
	CreatedBy           int64
	CreatedByName       string
	CreatedAt           pgtype.Timestamptz
	ResolvedBy          *int64
	ResolvedByName      string
	ResolvedAt          pgtype.Timestamptz
	ResolutionNote      string
}

type PurchaseInspection struct {
	ID              int64
	TenantID        int64
	PoID            int64
	ReceiptID       int64
	PoItemID        *int64
	Result          string
	InspectedQty    pgtype.Numeric
	DefectQty       pgtype.Numeric
	Note            string
	Attachments     []byte
	Status          string
	Disposition     string
	DispositionNote string
	InspectedByID   int64
	InspectedByName string
	InspectedAt     pgtype.Timestamptz
	ResolvedByID    int64
	ResolvedByName  string
	ResolvedAt      pgtype.Timestamptz
}

type PurchaseOrder struct {
	ID                   int64
	TenantID             int64
	PoNo                 string
	SupplierID           int64
	SupplierCode         string
	SupplierName         string
	Currency             string
	TotalAmount          pgtype.Numeric
	ExpectedDate         pgtype.Date
	Status               string
	ApprovalInstanceID   *int64
	RejectReason         string
	CancelReason         string
	BuyerID              int64
	BuyerName            string
	Remark               string
	OrderedAt            pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	SendStatus           string
	SentTo               string
	SentAt               pgtype.Timestamptz
	SentByID             int64
	SentByName           string
	SendError            string
	SendTemplateVersion  string
	SendAttachmentNames  []byte
	ClosedAt             pgtype.Timestamptz
	ClosedByID           int64
	ClosedByName         string
	SourceQuotationID    int64
	SourceQuotationNo    string
	SourceCostScenarioID int64
	FactoryID            int64
	FactoryCode          string
	FactoryName          string
	FulfillmentMode      string
	DeliveryLocationType string
	DeliveryPortID       int64
	DeliveryPortCode     string
	DeliveryPortName     string
	WarehouseID          int64
	WarehouseName        string
	DeliveryAddress      string
	SourceChangeReason   string
	CloseNote            string
	ShortfallAction      string
	PayableDueDate       pgtype.Date
}

type PurchaseOrderDueChange struct {
	ID            int64
	TenantID      int64
	PoID          int64
	OldDueDate    pgtype.Date
	NewDueDate    pgtype.Date
	Reason        string
	ChangedByID   int64
	ChangedByName string
	CreatedAt     pgtype.Timestamptz
}

type PurchaseOrderImport struct {
	ID                 int64
	TenantID           int64
	ImportToken        string
	SourceType         string
	SourceMailID       int64
	SourceAttachmentID int64
	SourceFileName     string
	FileSha256         string
	PreviewRows        []byte
	Status             string
	PurchaseOrderID    *int64
	CreatedBy          int64
	CreatedAt          pgtype.Timestamptz
	ExpiresAt          pgtype.Timestamptz
	ConfirmedAt        pgtype.Timestamptz
}

type PurchaseOrderItem struct {
	ID            int64
	TenantID      int64
	PoID          int64
	RequirementID int64
	ProductID     int64
	SkuID         *int64
	ProductCode   string
	ProductName   string
	Spec          string
	UomID         int64
	UomCode       string
	Qty           pgtype.Numeric
	UnitPrice     pgtype.Numeric
	Amount        pgtype.Numeric
	ReceivedQty   pgtype.Numeric
}

type PurchaseOrderPaymentClosure struct {
	ID            int64
	TenantID      int64
	PoID          int64
	OpenAmount    pgtype.Numeric
	Category      string
	Note          string
	ClosedByID    int64
	ClosedByName  string
	CreatedAt     pgtype.Timestamptz
	RevokedAt     pgtype.Timestamptz
	RevokedByID   int64
	RevokedByName string
	RevokeReason  string
}

type PurchaseOrderReconFile struct {
	ID             int64
	TenantID       int64
	PoID           int64
	ObjectKey      string
	FileName       string
	Note           string
	UploadedByID   int64
	UploadedByName string
	CreatedAt      pgtype.Timestamptz
	RemovedAt      pgtype.Timestamptz
	RemovedByID    int64
	RemovedByName  string
}

type PurchaseOrderSendAttempt struct {
	ID               int64
	TenantID         int64
	PoID             int64
	RecipientEmail   string
	SenderEmployeeID int64
	SenderName       string
	Status           string
	CampaignID       int64
	CampaignNo       string
	AttachmentNames  []byte
	TemplateVersion  string
	ErrorMessage     string
	StartedAt        pgtype.Timestamptz
	CompletedAt      pgtype.Timestamptz
}

type PurchaseProductionMilestone struct {
	ID            int64
	TenantID      int64
	PoID          int64
	Node          string
	PlannedDate   pgtype.Date
	ActualDate    pgtype.Date
	OwnerID       int64
	OwnerName     string
	Remark        string
	Attachments   []byte
	UpdatedByID   int64
	UpdatedByName string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type PurchaseProductionReminder struct {
	ID               int64
	TenantID         int64
	PoID             int64
	MilestoneID      int64
	Node             string
	PlannedDate      pgtype.Date
	BuyerID          int64
	BuyerName        string
	RelatedContracts string
	Status           string
	CreatedAt        pgtype.Timestamptz
	ClosedAt         pgtype.Timestamptz
}

type PurchaseReceipt struct {
	ID           int64
	TenantID     int64
	PoID         int64
	ReceiptNo    string
	WarehouseID  int64
	OperatorID   int64
	OperatorName string
	Remark       string
	ReceivedAt   pgtype.Timestamptz
}

type PurchaseReceiptException struct {
	ID             int64
	TenantID       int64
	PoID           int64
	ReceiptID      *int64
	PoItemID       *int64
	ExceptionType  string
	Qty            pgtype.Numeric
	ActualProduct  string
	ActualUom      string
	Description    string
	Status         string
	Resolution     string
	ReportedByID   int64
	ReportedByName string
	ReportedAt     pgtype.Timestamptz
	ResolvedByID   int64
	ResolvedByName string
	ResolvedAt     pgtype.Timestamptz
}

type PurchaseReceiptItem struct {
	ID        int64
	TenantID  int64
	ReceiptID int64
	PoItemID  int64
	Qty       pgtype.Numeric
}

type PurchaseRequirement struct {
	ID                  int64
	TenantID            int64
	ContractID          int64
	ContractNo          string
	ContractVersionID   int64
	VersionNo           int32
	ContractItemID      int64
	CustomerName        string
	ProductID           int64
	SkuID               *int64
	ProductCode         string
	ProductName         string
	Spec                string
	UomID               int64
	UomCode             string
	RequiredQty         pgtype.Numeric
	OrderedQty          pgtype.Numeric
	RequiredDate        pgtype.Date
	Source              string
	Status              string
	ClosedReason        string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	ReceivedQty         pgtype.Numeric
	OwnerID             int64
	OwnerName           string
	QuotationID         int64
	QuotationNo         string
	CostScenarioID      int64
	CostScenarioNo      string
	SourcingCaseID      int64
	SourcingLineID      int64
	SupplierQuoteLineID int64
	SupplierID          int64
	SupplierCode        string
	SupplierName        string
	FactoryID           int64
	FactoryCode         string
	FactoryName         string
	SourceCurrency      string
	SourceUnitPrice     pgtype.Numeric
	Moq                 pgtype.Numeric
	LeadTime            string
}

type PurchaseSupplierConfirmation struct {
	ID                    int64
	TenantID              int64
	PoID                  int64
	Status                string
	ConfirmedDate         pgtype.Date
	ConfirmedExpectedDate pgtype.Date
	Remark                string
	ApprovalInstanceID    *int64
	CreatedByID           int64
	CreatedByName         string
	CreatedAt             pgtype.Timestamptz
}

type PurchaseSupplierConfirmationLine struct {
	ID                 int64
	TenantID           int64
	ConfirmationID     int64
	PoItemID           int64
	OriginalQty        pgtype.Numeric
	OriginalUnitPrice  pgtype.Numeric
	ConfirmedQty       pgtype.Numeric
	ConfirmedUnitPrice pgtype.Numeric
}

type SourcingCase struct {
	ID                     int64
	TenantID               int64
	CaseNo                 string
	Title                  string
	CustomerID             int64
	CustomerName           string
	ContactName            string
	ContactEmail           string
	SourceMailID           int64
	SourceAttachmentID     int64
	Status                 string
	OwnerID                int64
	OwnerName              string
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	SourceFileName         string
	SourceContentType      string
	SourceFileData         []byte
	InquiryTemplateID      int64
	InquiryTemplateCode    string
	InquiryTemplateVersion int32
	SourceFileKey          string
	HandoffStatus          string
	RequirementVersionNo   int32
	AcceptedBy             *int64
	AcceptedByName         string
	AcceptedAt             pgtype.Timestamptz
	ReturnedBy             *int64
	ReturnedByName         string
	ReturnedAt             pgtype.Timestamptz
	ReturnReason           string
	ReturnFields           []string
	ContactID              int64
}

type SourcingCaseChange struct {
	ID           int64
	TenantID     int64
	CaseID       int64
	Section      string
	Action       string
	EntityID     int64
	Summary      string
	BeforeJson   []byte
	AfterJson    []byte
	Reason       string
	OperatorID   int64
	OperatorName string
	CreatedAt    pgtype.Timestamptz
}

type SourcingCustomerFeedback struct {
	ID            int64
	TenantID      int64
	CaseID        int64
	SalesPlanID   int64
	ContactName   string
	Channel       string
	Result        string
	Summary       string
	ContactedAt   pgtype.Timestamptz
	CreatedBy     int64
	CreatedByName string
	CreatedAt     pgtype.Timestamptz
}

type SourcingLine struct {
	ID                 int64
	TenantID           int64
	CaseID             int64
	LineNo             int32
	RawText            string
	Product            string
	MaterialStandard   string
	Grade              string
	Thickness          string
	Width              string
	LengthOrForm       string
	SurfaceRequirement string
	Coating            string
	Tolerance          string
	CoilWeight         string
	CoilID             string
	Packaging          string
	Delivery           string
	PaymentTerms       string
	Incoterm           string
	Port               string
	QuantityUnit       string
	Remarks            string
	Quantity           pgtype.Numeric
	ProductID          int64
	SkuID              int64
	UomID              int64
	Decision           string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	DecidedBy          int64
	DecidedByName      string
	DecidedAt          pgtype.Timestamptz
	RevisionNo         int32
	CustomFields       []byte
}

type SourcingProcurementParticipant struct {
	ID                 int64
	TenantID           int64
	CaseID             int64
	EmployeeID         int64
	EmployeeName       string
	ParticipantRole    string
	Status             string
	PrimaryRequestedAt pgtype.Timestamptz
	JoinedAt           pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type SourcingSalesPlan struct {
	ID                   int64
	TenantID             int64
	CaseID               int64
	PlanNo               string
	VersionNo            int32
	RequirementVersionNo int32
	ProcurementPlanID    int64
	ShippingPlanID       *int64
	Status               string
	ValidUntil           pgtype.Date
	CustomerNote         string
	InternalNote         string
	CreatedBy            int64
	CreatedByName        string
	PresentedAt          pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type SourcingSalesPlanItem struct {
	ID                    int64
	TenantID              int64
	PlanID                int64
	SourcingLineID        int64
	ProcurementPlanItemID int64
	ShippingPlanItemID    *int64
	OptionType            string
	Priority              int32
	ProductName           string
	QuotedQty             pgtype.Numeric
	UomCode               string
	CustomerCurrency      string
	CustomerUnitPrice     pgtype.Numeric
	PromisedDeliveryDate  pgtype.Date
	LineNote              string
	CreatedAt             pgtype.Timestamptz
}

type SourcingShippingOption struct {
	ID                 int64
	TenantID           int64
	RequestID          int64
	CarrierForwarder   string
	PortOfLoading      string
	PortOfDischarge    string
	QuotedAt           pgtype.Date
	EstimatedDeparture pgtype.Date
	EstimatedArrival   pgtype.Date
	ValidUntil         pgtype.Date
	Note               string
	Status             string
	CreatedBy          int64
	CreatedByName      string
	CreatedAt          pgtype.Timestamptz
	VersionNo          int32
	ServiceOptionName  string
	SubmittedAt        pgtype.Timestamptz
}

type SourcingShippingOptionLine struct {
	ID                    int64
	TenantID              int64
	OptionID              int64
	SourcingLineID        int64
	LineNo                int32
	ProductSnapshot       string
	SpecificationSnapshot string
	Quantity              pgtype.Numeric
	QuantityUnit          string
	Currency              string
	ChargeBasis           string
	UnitRate              pgtype.Numeric
	TotalFreight          pgtype.Numeric
	Note                  string
}

type SourcingShippingParticipant struct {
	ID                 int64
	TenantID           int64
	RequestID          int64
	EmployeeID         int64
	EmployeeName       string
	ParticipantRole    string
	Status             string
	PrimaryRequestedAt pgtype.Timestamptz
	JoinedAt           pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type SourcingShippingPlan struct {
	ID                     int64
	TenantID               int64
	RequestID              int64
	PlanNo                 string
	VersionNo              int32
	RequirementVersionNo   int32
	Status                 string
	ManagerNote            string
	CreatedBy              int64
	CreatedByName          string
	ConfirmedAt            pgtype.Timestamptz
	SubmittedToSalesBy     *int64
	SubmittedToSalesByName string
	SubmittedToSalesAt     pgtype.Timestamptz
	TargetSalesID          int64
	TargetSalesName        string
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type SourcingShippingPlanItem struct {
	ID                   int64
	TenantID             int64
	PlanID               int64
	SourcingLineID       int64
	ShippingOptionLineID int64
	SelectionType        string
	Priority             int32
	Reason               string
	Risk                 string
	CarrierForwarder     string
	ServiceOptionName    string
	ShippingEmployeeID   int64
	ShippingEmployeeName string
	ProductName          string
	Currency             string
	ChargeBasis          string
	UnitRate             pgtype.Numeric
	TotalFreight         pgtype.Numeric
	PortOfLoading        string
	PortOfDischarge      string
	EstimatedDeparture   pgtype.Date
	EstimatedArrival     pgtype.Date
	ValidUntil           pgtype.Date
	QuoteVersionNo       int32
	CreatedAt            pgtype.Timestamptz
}

type SourcingShippingRequest struct {
	ID                   int64
	TenantID             int64
	CaseID               int64
	RequirementVersionNo int32
	Status               string
	CaseNo               string
	CaseTitle            string
	CustomerID           int64
	CustomerName         string
	SalesEmployeeID      int64
	SalesEmployeeName    string
	DestinationPort      string
	CargoSummary         string
	RequestedBy          int64
	RequestedByName      string
	RequestedAt          pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type SourcingShippingReworkRequest struct {
	ID                   int64
	TenantID             int64
	CaseID               int64
	SalesPlanID          *int64
	SourcingLineID       *int64
	ShippingOptionLineID *int64
	RequestType          string
	ScopeType            string
	AssignedShippingID   *int64
	AssignedShippingName string
	CarrierForwarder     string
	ProductName          string
	Reason               string
	Status               string
	CreatedBy            int64
	CreatedByName        string
	CreatedAt            pgtype.Timestamptz
	ResolvedBy           *int64
	ResolvedByName       string
	ResolvedAt           pgtype.Timestamptz
	ResolutionNote       string
}

type SupplierInvoice struct {
	ID            int64
	TenantID      int64
	SupplierID    int64
	SupplierCode  string
	SupplierName  string
	InvoiceNo     string
	InvoiceType   string
	Currency      string
	TotalAmount   pgtype.Numeric
	TaxAmount     pgtype.Numeric
	InvoiceDate   pgtype.Date
	DueDate       pgtype.Date
	MatchStatus   string
	MatchNote     string
	Status        string
	VoidReason    string
	AttachmentKey string
	CreatedByID   int64
	CreatedByName string
	CreatedAt     pgtype.Timestamptz
	BaseCurrency  string
	BaseAmount    pgtype.Numeric
	FxRate        pgtype.Numeric
}

type SupplierInvoiceLine struct {
	ID          int64
	TenantID    int64
	InvoiceID   int64
	PoID        *int64
	PoItemID    *int64
	Description string
	Qty         pgtype.Numeric
	UnitPrice   pgtype.Numeric
	Amount      pgtype.Numeric
}

type SupplierPayment struct {
	ID            int64
	TenantID      int64
	SupplierID    int64
	SupplierName  string
	PaymentNo     string
	PaymentType   string
	Currency      string
	Amount        pgtype.Numeric
	BaseCurrency  string
	BaseAmount    pgtype.Numeric
	FxRate        pgtype.Numeric
	PaidAt        pgtype.Date
	Method        string
	BankRef       string
	BankTxnID     *int64
	Remark        string
	CreatedByID   int64
	CreatedByName string
	CreatedAt     pgtype.Timestamptz
}

type SupplierQuote struct {
	ID                 int64
	TenantID           int64
	FactoryRfqID       int64
	SupplierQuoteNo    string
	QuotedAt           pgtype.Date
	ValidUntil         pgtype.Date
	Currency           string
	PaymentTerms       string
	Delivery           string
	Remark             string
	Source             string
	CreatedBy          int64
	CreatedAt          pgtype.Timestamptz
	VersionNo          int32
	ConfirmationStatus string
	EvidenceNote       string
	Incoterm           string
}

type SupplierQuoteLine struct {
	ID              int64
	TenantID        int64
	SupplierQuoteID int64
	SourcingLineID  int64
	Qty             pgtype.Numeric
	UnitPrice       pgtype.Numeric
	Amount          pgtype.Numeric
	Moq             pgtype.Numeric
	LeadTime        string
	Remark          string
}
