// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: purchase_order.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPurchaseOrderItemReceived = `-- name: AddPurchaseOrderItemReceived :exec
UPDATE purchase_order_items SET
    received_qty = received_qty + $1::text::numeric
WHERE tenant_id = $2::bigint AND id = $3::bigint
`

type AddPurchaseOrderItemReceivedParams struct {
	Qty      string
	TenantID int64
	ID       int64
}

func (q *Queries) AddPurchaseOrderItemReceived(ctx context.Context, arg AddPurchaseOrderItemReceivedParams) error {
	_, err := q.db.Exec(ctx, addPurchaseOrderItemReceived, arg.Qty, arg.TenantID, arg.ID)
	return err
}

const addRequirementOrdered = `-- name: AddRequirementOrdered :one
UPDATE purchase_requirements SET
    ordered_qty = ordered_qty + $1::text::numeric,
    status = CASE
                 WHEN ordered_qty + $1::text::numeric >= required_qty
                 THEN 'ORDERED' ELSE 'PARTIALLY_ORDERED'
             END,
    updated_at = now()
WHERE tenant_id = $2::bigint
  AND id = $3::bigint
  AND status IN ('PENDING', 'PARTIALLY_ORDERED')
  AND ordered_qty + $1::text::numeric <= required_qty
RETURNING ordered_qty::text AS ordered_qty, status
`

type AddRequirementOrderedParams struct {
	Qty      string
	TenantID int64
	ID       int64
}

type AddRequirementOrderedRow struct {
	OrderedQty string
	Status     string
}

// Ordering moves a requirement along. Fully covered means ORDERED; partly
// covered means somebody still has to buy the rest.
func (q *Queries) AddRequirementOrdered(ctx context.Context, arg AddRequirementOrderedParams) (AddRequirementOrderedRow, error) {
	row := q.db.QueryRow(ctx, addRequirementOrdered, arg.Qty, arg.TenantID, arg.ID)
	var i AddRequirementOrderedRow
	err := row.Scan(&i.OrderedQty, &i.Status)
	return i, err
}

const addRequirementReceived = `-- name: AddRequirementReceived :one
UPDATE purchase_requirements SET
    received_qty = received_qty + $1::text::numeric,
    status = CASE
                 WHEN received_qty + $1::text::numeric >= required_qty
                 THEN 'RECEIVED' ELSE status
             END,
    updated_at = now()
WHERE tenant_id = $2::bigint AND id = $3::bigint
RETURNING received_qty::text AS received_qty, status
`

type AddRequirementReceivedParams struct {
	Qty      string
	TenantID int64
	ID       int64
}

type AddRequirementReceivedRow struct {
	ReceivedQty string
	Status      string
}

// Goods turned up. This is the only path that closes a manually raised
// requirement: it has no contract behind it, so no amount of stock arriving
// for somebody else can ever satisfy it — only its own order being delivered.
func (q *Queries) AddRequirementReceived(ctx context.Context, arg AddRequirementReceivedParams) (AddRequirementReceivedRow, error) {
	row := q.db.QueryRow(ctx, addRequirementReceived, arg.Qty, arg.TenantID, arg.ID)
	var i AddRequirementReceivedRow
	err := row.Scan(&i.ReceivedQty, &i.Status)
	return i, err
}

const createPurchaseOrder = `-- name: CreatePurchaseOrder :one
INSERT INTO purchase_orders (
    tenant_id, po_no, supplier_id, supplier_code, supplier_name,
    currency, total_amount, expected_date, buyer_id, buyer_name, remark,
    source_quotation_id, source_quotation_no, source_cost_scenario_id,
    factory_id, factory_code, factory_name,
    fulfillment_mode, delivery_location_type,
    delivery_port_id, delivery_port_code, delivery_port_name,
    warehouse_id, warehouse_name, delivery_address, source_change_reason
) VALUES (
    $1::bigint,
    $2::text,
    $3::bigint,
    $4::text,
    $5::text,
    $6::text,
    $7::text::numeric,
    nullif($8::text, '')::date,
    $9::bigint,
    $10::text,
    $11::text,
    $12, $13, $14,
    $15, $16, $17,
    $18, $19,
    $20, $21, $22,
    $23, $24, $25, $26
)
RETURNING id, po_no, status, created_at
`

type CreatePurchaseOrderParams struct {
	TenantID             int64
	PoNo                 string
	SupplierID           int64
	SupplierCode         string
	SupplierName         string
	Currency             string
	TotalAmount          string
	ExpectedDate         string
	BuyerID              int64
	BuyerName            string
	Remark               string
	SourceQuotationID    int64
	SourceQuotationNo    string
	SourceCostScenarioID int64
	FactoryID            int64
	FactoryCode          string
	FactoryName          string
	FulfillmentMode      string
	DeliveryLocationType string
	DeliveryPortID       int64
	DeliveryPortCode     string
	DeliveryPortName     string
	WarehouseID          int64
	WarehouseName        string
	DeliveryAddress      string
	SourceChangeReason   string
}

type CreatePurchaseOrderRow struct {
	ID        int64
	PoNo      string
	Status    string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreatePurchaseOrder(ctx context.Context, arg CreatePurchaseOrderParams) (CreatePurchaseOrderRow, error) {
	row := q.db.QueryRow(ctx, createPurchaseOrder,
		arg.TenantID,
		arg.PoNo,
		arg.SupplierID,
		arg.SupplierCode,
		arg.SupplierName,
		arg.Currency,
		arg.TotalAmount,
		arg.ExpectedDate,
		arg.BuyerID,
		arg.BuyerName,
		arg.Remark,
		arg.SourceQuotationID,
		arg.SourceQuotationNo,
		arg.SourceCostScenarioID,
		arg.FactoryID,
		arg.FactoryCode,
		arg.FactoryName,
		arg.FulfillmentMode,
		arg.DeliveryLocationType,
		arg.DeliveryPortID,
		arg.DeliveryPortCode,
		arg.DeliveryPortName,
		arg.WarehouseID,
		arg.WarehouseName,
		arg.DeliveryAddress,
		arg.SourceChangeReason,
	)
	var i CreatePurchaseOrderRow
	err := row.Scan(
		&i.ID,
		&i.PoNo,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createPurchaseOrderItem = `-- name: CreatePurchaseOrderItem :one
INSERT INTO purchase_order_items (
    tenant_id, po_id, requirement_id, product_id, sku_id,
    product_code, product_name, spec, uom_id, uom_code, qty, unit_price, amount
) VALUES (
    $1::bigint,
    $2::bigint,
    $3::bigint,
    $4::bigint,
    nullif($5::bigint, 0),
    $6::text,
    $7::text,
    $8::text,
    $9::bigint,
    $10::text,
    $11::text::numeric,
    $12::text::numeric,
    $13::text::numeric
)
RETURNING id
`

type CreatePurchaseOrderItemParams struct {
	TenantID      int64
	PoID          int64
	RequirementID int64
	ProductID     int64
	SkuID         int64
	ProductCode   string
	ProductName   string
	Spec          string
	UomID         int64
	UomCode       string
	Qty           string
	UnitPrice     string
	Amount        string
}

func (q *Queries) CreatePurchaseOrderItem(ctx context.Context, arg CreatePurchaseOrderItemParams) (int64, error) {
	row := q.db.QueryRow(ctx, createPurchaseOrderItem,
		arg.TenantID,
		arg.PoID,
		arg.RequirementID,
		arg.ProductID,
		arg.SkuID,
		arg.ProductCode,
		arg.ProductName,
		arg.Spec,
		arg.UomID,
		arg.UomCode,
		arg.Qty,
		arg.UnitPrice,
		arg.Amount,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createPurchaseReceipt = `-- name: CreatePurchaseReceipt :one
INSERT INTO purchase_receipts (
    tenant_id, po_id, receipt_no, warehouse_id, operator_id, operator_name, remark
) VALUES (
    $1::bigint,
    $2::bigint,
    $3::text,
    $4::bigint,
    $5::bigint,
    $6::text,
    $7::text
)
RETURNING id, receipt_no, received_at
`

type CreatePurchaseReceiptParams struct {
	TenantID     int64
	PoID         int64
	ReceiptNo    string
	WarehouseID  int64
	OperatorID   int64
	OperatorName string
	Remark       string
}

type CreatePurchaseReceiptRow struct {
	ID         int64
	ReceiptNo  string
	ReceivedAt pgtype.Timestamptz
}

func (q *Queries) CreatePurchaseReceipt(ctx context.Context, arg CreatePurchaseReceiptParams) (CreatePurchaseReceiptRow, error) {
	row := q.db.QueryRow(ctx, createPurchaseReceipt,
		arg.TenantID,
		arg.PoID,
		arg.ReceiptNo,
		arg.WarehouseID,
		arg.OperatorID,
		arg.OperatorName,
		arg.Remark,
	)
	var i CreatePurchaseReceiptRow
	err := row.Scan(&i.ID, &i.ReceiptNo, &i.ReceivedAt)
	return i, err
}

const createPurchaseReceiptItem = `-- name: CreatePurchaseReceiptItem :exec
INSERT INTO purchase_receipt_items (tenant_id, receipt_id, po_item_id, qty)
VALUES (
    $1::bigint,
    $2::bigint,
    $3::bigint,
    $4::text::numeric
)
`

type CreatePurchaseReceiptItemParams struct {
	TenantID  int64
	ReceiptID int64
	PoItemID  int64
	Qty       string
}

func (q *Queries) CreatePurchaseReceiptItem(ctx context.Context, arg CreatePurchaseReceiptItemParams) error {
	_, err := q.db.Exec(ctx, createPurchaseReceiptItem,
		arg.TenantID,
		arg.ReceiptID,
		arg.PoItemID,
		arg.Qty,
	)
	return err
}

const deletePurchaseOrderItems = `-- name: DeletePurchaseOrderItems :exec
DELETE FROM purchase_order_items
WHERE tenant_id = $1::bigint AND po_id = $2::bigint
`

type DeletePurchaseOrderItemsParams struct {
	TenantID int64
	PoID     int64
}

func (q *Queries) DeletePurchaseOrderItems(ctx context.Context, arg DeletePurchaseOrderItemsParams) error {
	_, err := q.db.Exec(ctx, deletePurchaseOrderItems, arg.TenantID, arg.PoID)
	return err
}

const draftReservedQtyForRequirements = `-- name: DraftReservedQtyForRequirements :many
SELECT i.requirement_id, coalesce(sum(i.qty), 0)::text AS reserved_qty
FROM purchase_order_items i
JOIN purchase_orders o ON o.id = i.po_id AND o.tenant_id = i.tenant_id
WHERE i.tenant_id = $1::bigint
  AND i.requirement_id = ANY($2::bigint[])
  AND o.status IN ('DRAFT', 'REJECTED', 'PENDING_APPROVAL')
GROUP BY i.requirement_id
`

type DraftReservedQtyForRequirementsParams struct {
	TenantID int64
	Ids      []int64
}

type DraftReservedQtyForRequirementsRow struct {
	RequirementID int64
	ReservedQty   string
}

// Imported drafts reserve their demand until they are cancelled or ordered.
// This is deliberately read after RequirementsForOrder has locked the
// requirement rows, making simultaneous import confirmations serialize.
func (q *Queries) DraftReservedQtyForRequirements(ctx context.Context, arg DraftReservedQtyForRequirementsParams) ([]DraftReservedQtyForRequirementsRow, error) {
	rows, err := q.db.Query(ctx, draftReservedQtyForRequirements, arg.TenantID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DraftReservedQtyForRequirementsRow
	for rows.Next() {
		var i DraftReservedQtyForRequirementsRow
		if err := rows.Scan(&i.RequirementID, &i.ReservedQty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPurchaseOrder = `-- name: GetPurchaseOrder :one
SELECT
    o.id, o.po_no, o.supplier_id, o.supplier_code, o.supplier_name, o.currency,
    o.total_amount::text AS total_amount, o.status,
    coalesce(o.approval_instance_id, 0)::bigint AS approval_instance_id,
    o.reject_reason, o.cancel_reason, o.buyer_id, o.buyer_name, o.remark,
    coalesce(o.expected_date::text, '')::text AS expected_date,
    o.send_status, o.sent_to, o.sent_at, o.sent_by_name, o.send_error,
    o.ordered_at, o.created_at,
    coalesce(o.closed_at::text, '')::text AS closed_at, o.closed_by_name,
    coalesce((SELECT c.status FROM purchase_supplier_confirmations c
              WHERE c.tenant_id = o.tenant_id AND c.po_id = o.id
              ORDER BY c.created_at DESC, c.id DESC LIMIT 1), '')::text AS confirm_status,
    o.fulfillment_mode, o.delivery_location_type,
    coalesce(o.delivery_port_id, 0)::bigint AS delivery_port_id,
    o.delivery_port_code, o.delivery_port_name,
    coalesce(o.warehouse_id, 0)::bigint AS warehouse_id, o.warehouse_name,
    o.delivery_address, o.source_change_reason,
    coalesce(o.source_quotation_id, 0)::bigint AS source_quotation_id,
    o.source_quotation_no, coalesce(o.source_cost_scenario_id, 0)::bigint AS source_cost_scenario_id,
    coalesce(o.factory_id, 0)::bigint AS factory_id, o.factory_code, o.factory_name
FROM purchase_orders o
WHERE o.tenant_id = $1::bigint AND o.id = $2::bigint
`

type GetPurchaseOrderParams struct {
	TenantID int64
	ID       int64
}

type GetPurchaseOrderRow struct {
	ID                   int64
	PoNo                 string
	SupplierID           int64
	SupplierCode         string
	SupplierName         string
	Currency             string
	TotalAmount          string
	Status               string
	ApprovalInstanceID   int64
	RejectReason         string
	CancelReason         string
	BuyerID              int64
	BuyerName            string
	Remark               string
	ExpectedDate         string
	SendStatus           string
	SentTo               string
	SentAt               pgtype.Timestamptz
	SentByName           string
	SendError            string
	OrderedAt            pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	ClosedAt             string
	ClosedByName         string
	ConfirmStatus        string
	FulfillmentMode      string
	DeliveryLocationType string
	DeliveryPortID       int64
	DeliveryPortCode     string
	DeliveryPortName     string
	WarehouseID          int64
	WarehouseName        string
	DeliveryAddress      string
	SourceChangeReason   string
	SourceQuotationID    int64
	SourceQuotationNo    string
	SourceCostScenarioID int64
	FactoryID            int64
	FactoryCode          string
	FactoryName          string
}

func (q *Queries) GetPurchaseOrder(ctx context.Context, arg GetPurchaseOrderParams) (GetPurchaseOrderRow, error) {
	row := q.db.QueryRow(ctx, getPurchaseOrder, arg.TenantID, arg.ID)
	var i GetPurchaseOrderRow
	err := row.Scan(
		&i.ID,
		&i.PoNo,
		&i.SupplierID,
		&i.SupplierCode,
		&i.SupplierName,
		&i.Currency,
		&i.TotalAmount,
		&i.Status,
		&i.ApprovalInstanceID,
		&i.RejectReason,
		&i.CancelReason,
		&i.BuyerID,
		&i.BuyerName,
		&i.Remark,
		&i.ExpectedDate,
		&i.SendStatus,
		&i.SentTo,
		&i.SentAt,
		&i.SentByName,
		&i.SendError,
		&i.OrderedAt,
		&i.CreatedAt,
		&i.ClosedAt,
		&i.ClosedByName,
		&i.ConfirmStatus,
		&i.FulfillmentMode,
		&i.DeliveryLocationType,
		&i.DeliveryPortID,
		&i.DeliveryPortCode,
		&i.DeliveryPortName,
		&i.WarehouseID,
		&i.WarehouseName,
		&i.DeliveryAddress,
		&i.SourceChangeReason,
		&i.SourceQuotationID,
		&i.SourceQuotationNo,
		&i.SourceCostScenarioID,
		&i.FactoryID,
		&i.FactoryCode,
		&i.FactoryName,
	)
	return i, err
}

const getPurchaseOrderForUpdate = `-- name: GetPurchaseOrderForUpdate :one
SELECT id, po_no, supplier_id, supplier_code, supplier_name, currency,
       total_amount::text AS total_amount, status,
       coalesce(approval_instance_id, 0)::bigint AS approval_instance_id,
       buyer_id, buyer_name, remark,
       coalesce(expected_date::text, '')::text AS expected_date,
       coalesce(source_quotation_id, 0)::bigint AS source_quotation_id,
       source_quotation_no, coalesce(source_cost_scenario_id, 0)::bigint AS source_cost_scenario_id,
       fulfillment_mode, delivery_location_type,
       coalesce(delivery_port_id, 0)::bigint AS delivery_port_id,
       delivery_port_code, delivery_port_name,
       coalesce(warehouse_id, 0)::bigint AS warehouse_id, warehouse_name,
       delivery_address, source_change_reason
FROM purchase_orders
WHERE tenant_id = $1::bigint AND id = $2::bigint
FOR UPDATE
`

type GetPurchaseOrderForUpdateParams struct {
	TenantID int64
	ID       int64
}

type GetPurchaseOrderForUpdateRow struct {
	ID                   int64
	PoNo                 string
	SupplierID           int64
	SupplierCode         string
	SupplierName         string
	Currency             string
	TotalAmount          string
	Status               string
	ApprovalInstanceID   int64
	BuyerID              int64
	BuyerName            string
	Remark               string
	ExpectedDate         string
	SourceQuotationID    int64
	SourceQuotationNo    string
	SourceCostScenarioID int64
	FulfillmentMode      string
	DeliveryLocationType string
	DeliveryPortID       int64
	DeliveryPortCode     string
	DeliveryPortName     string
	WarehouseID          int64
	WarehouseName        string
	DeliveryAddress      string
	SourceChangeReason   string
}

func (q *Queries) GetPurchaseOrderForUpdate(ctx context.Context, arg GetPurchaseOrderForUpdateParams) (GetPurchaseOrderForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getPurchaseOrderForUpdate, arg.TenantID, arg.ID)
	var i GetPurchaseOrderForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.PoNo,
		&i.SupplierID,
		&i.SupplierCode,
		&i.SupplierName,
		&i.Currency,
		&i.TotalAmount,
		&i.Status,
		&i.ApprovalInstanceID,
		&i.BuyerID,
		&i.BuyerName,
		&i.Remark,
		&i.ExpectedDate,
		&i.SourceQuotationID,
		&i.SourceQuotationNo,
		&i.SourceCostScenarioID,
		&i.FulfillmentMode,
		&i.DeliveryLocationType,
		&i.DeliveryPortID,
		&i.DeliveryPortCode,
		&i.DeliveryPortName,
		&i.WarehouseID,
		&i.WarehouseName,
		&i.DeliveryAddress,
		&i.SourceChangeReason,
	)
	return i, err
}

const listPurchaseOrders = `-- name: ListPurchaseOrders :many
SELECT
    o.id, o.po_no, o.supplier_id, o.supplier_name, o.currency,
    o.total_amount::text AS total_amount, o.status, o.buyer_name, o.remark,
    o.reject_reason, o.cancel_reason,
    coalesce(o.expected_date::text, '')::text AS expected_date,
    o.send_status, o.sent_to, o.sent_at, o.sent_by_name, o.send_error,
    o.created_at,
    coalesce(o.closed_at::text, '')::text AS closed_at, o.closed_by_name,
    -- 最新一条工厂回签的状态（B5 尾巴）：「发了、工厂回没回」要在列表上
    -- 直接可见，不该藏在执行跟踪的页签里。空串 = 从未回签。
    coalesce((SELECT c.status FROM purchase_supplier_confirmations c
              WHERE c.tenant_id = o.tenant_id AND c.po_id = o.id
              ORDER BY c.created_at DESC, c.id DESC LIMIT 1), '')::text AS confirm_status,
    o.fulfillment_mode, o.delivery_location_type,
    coalesce(o.delivery_port_id, 0)::bigint AS delivery_port_id,
    o.delivery_port_code, o.delivery_port_name,
    coalesce(o.warehouse_id, 0)::bigint AS warehouse_id, o.warehouse_name,
    o.delivery_address,
    coalesce(o.source_quotation_id, 0)::bigint AS source_quotation_id,
    o.source_quotation_no, coalesce(o.source_cost_scenario_id, 0)::bigint AS source_cost_scenario_id,
    coalesce(o.factory_id, 0)::bigint AS factory_id, o.factory_code, o.factory_name,
    (SELECT count(*) FROM purchase_order_items i WHERE i.po_id = o.id) AS item_count,
    coalesce((SELECT sum(i.qty) FROM purchase_order_items i WHERE i.po_id = o.id), 0)::text AS total_qty,
    coalesce((SELECT sum(i.received_qty) FROM purchase_order_items i WHERE i.po_id = o.id), 0)::text AS received_qty,
    count(*) OVER () AS total
FROM purchase_orders o
WHERE o.tenant_id = $1::bigint
  -- Data scope: an order is visible when the caller's range covers its
  -- buyer. scope_all short-circuits so administrators never pay for a list.
  AND ($2::bool OR o.buyer_id = ANY($3::bigint[]))
  AND ($4::text = '' OR o.status = $4::text)
  -- 待正式发单：批下来了、还没发给供应商。工作台的行动数字（B4），
  -- 用列表自己的围栏，不另起一套统计。
  AND ($5::bool = false
       OR (o.status = 'ORDERED' AND o.send_status <> 'SENT'))
  AND ($6::text = ''
       OR o.po_no ILIKE '%' || $6::text || '%'
       OR o.supplier_name ILIKE '%' || $6::text || '%')
ORDER BY o.created_at DESC, o.id DESC
LIMIT $8::int OFFSET $7::int
`

type ListPurchaseOrdersParams struct {
	TenantID  int64
	ScopeAll  bool
	BuyerIds  []int64
	Status    string
	Unsent    bool
	Keyword   string
	RowOffset int32
	RowLimit  int32
}

type ListPurchaseOrdersRow struct {
	ID                   int64
	PoNo                 string
	SupplierID           int64
	SupplierName         string
	Currency             string
	TotalAmount          string
	Status               string
	BuyerName            string
	Remark               string
	RejectReason         string
	CancelReason         string
	ExpectedDate         string
	SendStatus           string
	SentTo               string
	SentAt               pgtype.Timestamptz
	SentByName           string
	SendError            string
	CreatedAt            pgtype.Timestamptz
	ClosedAt             string
	ClosedByName         string
	ConfirmStatus        string
	FulfillmentMode      string
	DeliveryLocationType string
	DeliveryPortID       int64
	DeliveryPortCode     string
	DeliveryPortName     string
	WarehouseID          int64
	WarehouseName        string
	DeliveryAddress      string
	SourceQuotationID    int64
	SourceQuotationNo    string
	SourceCostScenarioID int64
	FactoryID            int64
	FactoryCode          string
	FactoryName          string
	ItemCount            int64
	TotalQty             string
	ReceivedQty          string
	Total                int64
}

func (q *Queries) ListPurchaseOrders(ctx context.Context, arg ListPurchaseOrdersParams) ([]ListPurchaseOrdersRow, error) {
	rows, err := q.db.Query(ctx, listPurchaseOrders,
		arg.TenantID,
		arg.ScopeAll,
		arg.BuyerIds,
		arg.Status,
		arg.Unsent,
		arg.Keyword,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPurchaseOrdersRow
	for rows.Next() {
		var i ListPurchaseOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.PoNo,
			&i.SupplierID,
			&i.SupplierName,
			&i.Currency,
			&i.TotalAmount,
			&i.Status,
			&i.BuyerName,
			&i.Remark,
			&i.RejectReason,
			&i.CancelReason,
			&i.ExpectedDate,
			&i.SendStatus,
			&i.SentTo,
			&i.SentAt,
			&i.SentByName,
			&i.SendError,
			&i.CreatedAt,
			&i.ClosedAt,
			&i.ClosedByName,
			&i.ConfirmStatus,
			&i.FulfillmentMode,
			&i.DeliveryLocationType,
			&i.DeliveryPortID,
			&i.DeliveryPortCode,
			&i.DeliveryPortName,
			&i.WarehouseID,
			&i.WarehouseName,
			&i.DeliveryAddress,
			&i.SourceQuotationID,
			&i.SourceQuotationNo,
			&i.SourceCostScenarioID,
			&i.FactoryID,
			&i.FactoryCode,
			&i.FactoryName,
			&i.ItemCount,
			&i.TotalQty,
			&i.ReceivedQty,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchaseReceipts = `-- name: ListPurchaseReceipts :many
SELECT r.id, r.receipt_no, r.warehouse_id, r.operator_name, r.remark, r.received_at,
       coalesce(sum(ri.qty), 0)::text AS total_qty
FROM purchase_receipts r
LEFT JOIN purchase_receipt_items ri ON ri.receipt_id = r.id
WHERE r.tenant_id = $1::bigint AND r.po_id = $2::bigint
GROUP BY r.id
ORDER BY r.received_at DESC, r.id DESC
`

type ListPurchaseReceiptsParams struct {
	TenantID int64
	PoID     int64
}

type ListPurchaseReceiptsRow struct {
	ID           int64
	ReceiptNo    string
	WarehouseID  int64
	OperatorName string
	Remark       string
	ReceivedAt   pgtype.Timestamptz
	TotalQty     string
}

func (q *Queries) ListPurchaseReceipts(ctx context.Context, arg ListPurchaseReceiptsParams) ([]ListPurchaseReceiptsRow, error) {
	rows, err := q.db.Query(ctx, listPurchaseReceipts, arg.TenantID, arg.PoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPurchaseReceiptsRow
	for rows.Next() {
		var i ListPurchaseReceiptsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReceiptNo,
			&i.WarehouseID,
			&i.OperatorName,
			&i.Remark,
			&i.ReceivedAt,
			&i.TotalQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ordersForRequirement = `-- name: OrdersForRequirement :many
SELECT
    o.id, o.po_no, o.supplier_name, o.status, o.currency,
    coalesce(o.expected_date::text, '')::text AS expected_date,
    i.qty::text          AS qty,
    i.unit_price::text   AS unit_price,
    i.received_qty::text AS received_qty,
    o.created_at
FROM purchase_order_items i
JOIN purchase_orders o ON o.id = i.po_id
WHERE i.tenant_id = $1::bigint
  AND i.requirement_id = $2::bigint
ORDER BY o.created_at DESC, o.id DESC
`

type OrdersForRequirementParams struct {
	TenantID      int64
	RequirementID int64
}

type OrdersForRequirementRow struct {
	ID           int64
	PoNo         string
	SupplierName string
	Status       string
	Currency     string
	ExpectedDate string
	Qty          string
	UnitPrice    string
	ReceivedQty  string
	CreatedAt    pgtype.Timestamptz
}

// Which orders are covering this requirement, and how much of each has
// arrived. A buyer looking at an outstanding line needs to know whether it is
// unbought or merely undelivered — the two look identical on the list and
// call for completely different action.
func (q *Queries) OrdersForRequirement(ctx context.Context, arg OrdersForRequirementParams) ([]OrdersForRequirementRow, error) {
	rows, err := q.db.Query(ctx, ordersForRequirement, arg.TenantID, arg.RequirementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrdersForRequirementRow
	for rows.Next() {
		var i OrdersForRequirementRow
		if err := rows.Scan(
			&i.ID,
			&i.PoNo,
			&i.SupplierName,
			&i.Status,
			&i.Currency,
			&i.ExpectedDate,
			&i.Qty,
			&i.UnitPrice,
			&i.ReceivedQty,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purchaseOrderByInstance = `-- name: PurchaseOrderByInstance :one
SELECT id, po_no, status
FROM purchase_orders
WHERE tenant_id = $1::bigint
  AND approval_instance_id = $2::bigint
FOR UPDATE
`

type PurchaseOrderByInstanceParams struct {
	TenantID   int64
	InstanceID int64
}

type PurchaseOrderByInstanceRow struct {
	ID     int64
	PoNo   string
	Status string
}

// How a Kafka approval decision finds the order it belongs to.
func (q *Queries) PurchaseOrderByInstance(ctx context.Context, arg PurchaseOrderByInstanceParams) (PurchaseOrderByInstanceRow, error) {
	row := q.db.QueryRow(ctx, purchaseOrderByInstance, arg.TenantID, arg.InstanceID)
	var i PurchaseOrderByInstanceRow
	err := row.Scan(&i.ID, &i.PoNo, &i.Status)
	return i, err
}

const purchaseOrderItems = `-- name: PurchaseOrderItems :many
SELECT
    i.id, i.requirement_id, i.product_id, coalesce(i.sku_id, 0)::bigint AS sku_id,
    i.product_code, i.product_name, i.spec, i.uom_id, i.uom_code,
    i.qty::text          AS qty,
    i.unit_price::text   AS unit_price,
    i.amount::text       AS amount,
    i.received_qty::text AS received_qty,
    r.contract_no, r.customer_name, r.source,
    -- 合同负责人跟着明细走：单归执行采购员，谁谈的生意仍留在行上。
    r.owner_name AS contract_owner
FROM purchase_order_items i
JOIN purchase_requirements r ON r.id = i.requirement_id
WHERE i.tenant_id = $1::bigint AND i.po_id = $2::bigint
ORDER BY i.id
`

type PurchaseOrderItemsParams struct {
	TenantID int64
	PoID     int64
}

type PurchaseOrderItemsRow struct {
	ID            int64
	RequirementID int64
	ProductID     int64
	SkuID         int64
	ProductCode   string
	ProductName   string
	Spec          string
	UomID         int64
	UomCode       string
	Qty           string
	UnitPrice     string
	Amount        string
	ReceivedQty   string
	ContractNo    string
	CustomerName  string
	Source        string
	ContractOwner string
}

func (q *Queries) PurchaseOrderItems(ctx context.Context, arg PurchaseOrderItemsParams) ([]PurchaseOrderItemsRow, error) {
	rows, err := q.db.Query(ctx, purchaseOrderItems, arg.TenantID, arg.PoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseOrderItemsRow
	for rows.Next() {
		var i PurchaseOrderItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.RequirementID,
			&i.ProductID,
			&i.SkuID,
			&i.ProductCode,
			&i.ProductName,
			&i.Spec,
			&i.UomID,
			&i.UomCode,
			&i.Qty,
			&i.UnitPrice,
			&i.Amount,
			&i.ReceivedQty,
			&i.ContractNo,
			&i.CustomerName,
			&i.Source,
			&i.ContractOwner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purchaseOrderItemsForUpdate = `-- name: PurchaseOrderItemsForUpdate :many
SELECT id, requirement_id, product_id, coalesce(sku_id, 0)::bigint AS sku_id,
       product_code, product_name, uom_id, uom_code,
       qty::text          AS qty,
       unit_price::text   AS unit_price,
       received_qty::text AS received_qty
FROM purchase_order_items
WHERE tenant_id = $1::bigint AND po_id = $2::bigint
ORDER BY id
FOR UPDATE
`

type PurchaseOrderItemsForUpdateParams struct {
	TenantID int64
	PoID     int64
}

type PurchaseOrderItemsForUpdateRow struct {
	ID            int64
	RequirementID int64
	ProductID     int64
	SkuID         int64
	ProductCode   string
	ProductName   string
	UomID         int64
	UomCode       string
	Qty           string
	UnitPrice     string
	ReceivedQty   string
}

func (q *Queries) PurchaseOrderItemsForUpdate(ctx context.Context, arg PurchaseOrderItemsForUpdateParams) ([]PurchaseOrderItemsForUpdateRow, error) {
	rows, err := q.db.Query(ctx, purchaseOrderItemsForUpdate, arg.TenantID, arg.PoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseOrderItemsForUpdateRow
	for rows.Next() {
		var i PurchaseOrderItemsForUpdateRow
		if err := rows.Scan(
			&i.ID,
			&i.RequirementID,
			&i.ProductID,
			&i.SkuID,
			&i.ProductCode,
			&i.ProductName,
			&i.UomID,
			&i.UomCode,
			&i.Qty,
			&i.UnitPrice,
			&i.ReceivedQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purchaseOrderReceiptProgress = `-- name: PurchaseOrderReceiptProgress :one
SELECT
    count(*) FILTER (WHERE received_qty < qty) AS outstanding_lines,
    coalesce(sum(received_qty), 0)::text       AS received_total
FROM purchase_order_items
WHERE tenant_id = $1::bigint AND po_id = $2::bigint
`

type PurchaseOrderReceiptProgressParams struct {
	TenantID int64
	PoID     int64
}

type PurchaseOrderReceiptProgressRow struct {
	OutstandingLines int64
	ReceivedTotal    string
}

// Whether every line of an order has arrived. Computed from the lines rather
// than counted along the way, so a partial receipt entered twice cannot leave
// the header claiming a completeness the lines do not support.
func (q *Queries) PurchaseOrderReceiptProgress(ctx context.Context, arg PurchaseOrderReceiptProgressParams) (PurchaseOrderReceiptProgressRow, error) {
	row := q.db.QueryRow(ctx, purchaseOrderReceiptProgress, arg.TenantID, arg.PoID)
	var i PurchaseOrderReceiptProgressRow
	err := row.Scan(&i.OutstandingLines, &i.ReceivedTotal)
	return i, err
}

const releaseRequirementOrdered = `-- name: ReleaseRequirementOrdered :exec
UPDATE purchase_requirements SET
    ordered_qty = greatest(ordered_qty - $1::text::numeric, 0),
    status = CASE
                 WHEN status IN ('SUPERSEDED', 'CANCELLED') THEN status
                 WHEN greatest(ordered_qty - $1::text::numeric, 0) <= 0
                 THEN 'PENDING'
                 ELSE 'PARTIALLY_ORDERED'
             END,
    updated_at = now()
WHERE tenant_id = $2::bigint AND id = $3::bigint
`

type ReleaseRequirementOrderedParams struct {
	Qty      string
	TenantID int64
	ID       int64
}

// An order that was rejected or cancelled never happened. What it had claimed
// goes back on the buying list.
func (q *Queries) ReleaseRequirementOrdered(ctx context.Context, arg ReleaseRequirementOrderedParams) error {
	_, err := q.db.Exec(ctx, releaseRequirementOrdered, arg.Qty, arg.TenantID, arg.ID)
	return err
}

const reopenRequirement = `-- name: ReopenRequirement :one
UPDATE purchase_requirements SET
    status        = 'PENDING',
    closed_reason = '',
    updated_at    = now()
WHERE tenant_id = $1::bigint
  AND id = $2::bigint
  AND status IN ('CANCELLED', 'SUPERSEDED')
  AND ordered_qty = 0
RETURNING status
`

type ReopenRequirementParams struct {
	TenantID int64
	ID       int64
}

// Put a closed requirement back on the buying list.
//
// Only ones closed automatically or by hand without an order behind them.
// Once a buyer has ordered against it the row belongs to that order, and
// reopening would invite a second purchase of the same goods.
func (q *Queries) ReopenRequirement(ctx context.Context, arg ReopenRequirementParams) (string, error) {
	row := q.db.QueryRow(ctx, reopenRequirement, arg.TenantID, arg.ID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const requirementsForOrder = `-- name: RequirementsForOrder :many

SELECT
    id, contract_id, contract_no, contract_item_id, customer_name, source,
    product_id, coalesce(sku_id, 0)::bigint AS sku_id,
    product_code, product_name, spec, uom_id, uom_code, status,
    quotation_id, quotation_no, cost_scenario_id,
    supplier_id AS inherited_supplier_id, supplier_code AS inherited_supplier_code,
    supplier_name AS inherited_supplier_name,
    factory_id AS inherited_factory_id, factory_code AS inherited_factory_code,
    factory_name AS inherited_factory_name,
    source_currency, source_unit_price::text AS source_unit_price,
    required_qty::text                 AS required_qty,
    ordered_qty::text                  AS ordered_qty,
    (required_qty - ordered_qty)::text AS open_qty,
    coalesce(required_date::text, '')::text AS required_date
FROM purchase_requirements
WHERE tenant_id = $1::bigint
  AND id = ANY ($2::bigint[])
ORDER BY id
FOR UPDATE
`

type RequirementsForOrderParams struct {
	TenantID int64
	Ids      []int64
}

type RequirementsForOrderRow struct {
	ID                    int64
	ContractID            int64
	ContractNo            string
	ContractItemID        int64
	CustomerName          string
	Source                string
	ProductID             int64
	SkuID                 int64
	ProductCode           string
	ProductName           string
	Spec                  string
	UomID                 int64
	UomCode               string
	Status                string
	QuotationID           int64
	QuotationNo           string
	CostScenarioID        int64
	InheritedSupplierID   int64
	InheritedSupplierCode string
	InheritedSupplierName string
	InheritedFactoryID    int64
	InheritedFactoryCode  string
	InheritedFactoryName  string
	SourceCurrency        string
	SourceUnitPrice       string
	RequiredQty           string
	OrderedQty            string
	OpenQty               string
	RequiredDate          string
}

// Purchase orders. Same rule as the rest of the system: quantities and money
// cross the boundary as text, never float64.
// The lines a buyer picked, locked so two people cannot order the same
// outstanding quantity at the same time. open_qty is what is left to order —
// a requirement may be spread over several orders.
func (q *Queries) RequirementsForOrder(ctx context.Context, arg RequirementsForOrderParams) ([]RequirementsForOrderRow, error) {
	rows, err := q.db.Query(ctx, requirementsForOrder, arg.TenantID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RequirementsForOrderRow
	for rows.Next() {
		var i RequirementsForOrderRow
		if err := rows.Scan(
			&i.ID,
			&i.ContractID,
			&i.ContractNo,
			&i.ContractItemID,
			&i.CustomerName,
			&i.Source,
			&i.ProductID,
			&i.SkuID,
			&i.ProductCode,
			&i.ProductName,
			&i.Spec,
			&i.UomID,
			&i.UomCode,
			&i.Status,
			&i.QuotationID,
			&i.QuotationNo,
			&i.CostScenarioID,
			&i.InheritedSupplierID,
			&i.InheritedSupplierCode,
			&i.InheritedSupplierName,
			&i.InheritedFactoryID,
			&i.InheritedFactoryCode,
			&i.InheritedFactoryName,
			&i.SourceCurrency,
			&i.SourceUnitPrice,
			&i.RequiredQty,
			&i.OrderedQty,
			&i.OpenQty,
			&i.RequiredDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPurchaseOrderCancelled = `-- name: SetPurchaseOrderCancelled :exec
UPDATE purchase_orders SET
    status = 'CANCELLED', cancel_reason = $1::text, updated_at = now()
WHERE tenant_id = $2::bigint AND id = $3::bigint
`

type SetPurchaseOrderCancelledParams struct {
	Reason   string
	TenantID int64
	ID       int64
}

func (q *Queries) SetPurchaseOrderCancelled(ctx context.Context, arg SetPurchaseOrderCancelledParams) error {
	_, err := q.db.Exec(ctx, setPurchaseOrderCancelled, arg.Reason, arg.TenantID, arg.ID)
	return err
}

const setPurchaseOrderOrdered = `-- name: SetPurchaseOrderOrdered :exec
UPDATE purchase_orders SET status = 'ORDERED', ordered_at = now(), updated_at = now()
WHERE tenant_id = $1::bigint AND id = $2::bigint
`

type SetPurchaseOrderOrderedParams struct {
	TenantID int64
	ID       int64
}

func (q *Queries) SetPurchaseOrderOrdered(ctx context.Context, arg SetPurchaseOrderOrderedParams) error {
	_, err := q.db.Exec(ctx, setPurchaseOrderOrdered, arg.TenantID, arg.ID)
	return err
}

const setPurchaseOrderRejected = `-- name: SetPurchaseOrderRejected :exec
UPDATE purchase_orders SET
    status = 'REJECTED', reject_reason = $1::text, updated_at = now()
WHERE tenant_id = $2::bigint AND id = $3::bigint
`

type SetPurchaseOrderRejectedParams struct {
	Reason   string
	TenantID int64
	ID       int64
}

func (q *Queries) SetPurchaseOrderRejected(ctx context.Context, arg SetPurchaseOrderRejectedParams) error {
	_, err := q.db.Exec(ctx, setPurchaseOrderRejected, arg.Reason, arg.TenantID, arg.ID)
	return err
}

const setPurchaseOrderStatus = `-- name: SetPurchaseOrderStatus :exec
UPDATE purchase_orders SET status = $1::text, updated_at = now()
WHERE tenant_id = $2::bigint AND id = $3::bigint
`

type SetPurchaseOrderStatusParams struct {
	NewStatus string
	TenantID  int64
	ID        int64
}

func (q *Queries) SetPurchaseOrderStatus(ctx context.Context, arg SetPurchaseOrderStatusParams) error {
	_, err := q.db.Exec(ctx, setPurchaseOrderStatus, arg.NewStatus, arg.TenantID, arg.ID)
	return err
}

const setPurchaseOrderSubmitted = `-- name: SetPurchaseOrderSubmitted :exec
UPDATE purchase_orders SET
    status = 'PENDING_APPROVAL', approval_instance_id = $1::bigint,
    updated_at = now()
WHERE tenant_id = $2::bigint AND id = $3::bigint
`

type SetPurchaseOrderSubmittedParams struct {
	InstanceID int64
	TenantID   int64
	ID         int64
}

func (q *Queries) SetPurchaseOrderSubmitted(ctx context.Context, arg SetPurchaseOrderSubmittedParams) error {
	_, err := q.db.Exec(ctx, setPurchaseOrderSubmitted, arg.InstanceID, arg.TenantID, arg.ID)
	return err
}

const updatePurchaseOrderDraft = `-- name: UpdatePurchaseOrderDraft :one
UPDATE purchase_orders SET
    supplier_id = $1::bigint,
    supplier_code = $2::text,
    supplier_name = $3::text,
    currency = $4::text,
    total_amount = $5::text::numeric,
    expected_date = nullif($6::text, '')::date,
    buyer_id = $7::bigint,
    buyer_name = $8::text,
    remark = $9::text,
    fulfillment_mode = $10::text,
    delivery_location_type = $11::text,
    delivery_port_id = nullif($12::bigint, 0),
    delivery_port_code = $13::text,
    delivery_port_name = $14::text,
    -- 采购单表为兼容直接发往港口的模式，以 0 表示“不经过仓库”。
    -- 这里不能写成 NULL，否则恢复旧草稿时会违反 warehouse_id 的非空约束。
    warehouse_id = $15::bigint,
    warehouse_name = $16::text,
    delivery_address = $17::text,
    source_change_reason = $18::text,
    status = 'DRAFT',
    approval_instance_id = NULL,
    reject_reason = '',
    updated_at = now()
WHERE tenant_id = $19::bigint
  AND id = $20::bigint
  AND status IN ('DRAFT', 'REJECTED')
RETURNING id, po_no, status, created_at
`

type UpdatePurchaseOrderDraftParams struct {
	SupplierID           int64
	SupplierCode         string
	SupplierName         string
	Currency             string
	TotalAmount          string
	ExpectedDate         string
	BuyerID              int64
	BuyerName            string
	Remark               string
	FulfillmentMode      string
	DeliveryLocationType string
	DeliveryPortID       int64
	DeliveryPortCode     string
	DeliveryPortName     string
	WarehouseID          int64
	WarehouseName        string
	DeliveryAddress      string
	SourceChangeReason   string
	TenantID             int64
	ID                   int64
}

type UpdatePurchaseOrderDraftRow struct {
	ID        int64
	PoNo      string
	Status    string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) UpdatePurchaseOrderDraft(ctx context.Context, arg UpdatePurchaseOrderDraftParams) (UpdatePurchaseOrderDraftRow, error) {
	row := q.db.QueryRow(ctx, updatePurchaseOrderDraft,
		arg.SupplierID,
		arg.SupplierCode,
		arg.SupplierName,
		arg.Currency,
		arg.TotalAmount,
		arg.ExpectedDate,
		arg.BuyerID,
		arg.BuyerName,
		arg.Remark,
		arg.FulfillmentMode,
		arg.DeliveryLocationType,
		arg.DeliveryPortID,
		arg.DeliveryPortCode,
		arg.DeliveryPortName,
		arg.WarehouseID,
		arg.WarehouseName,
		arg.DeliveryAddress,
		arg.SourceChangeReason,
		arg.TenantID,
		arg.ID,
	)
	var i UpdatePurchaseOrderDraftRow
	err := row.Scan(
		&i.ID,
		&i.PoNo,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
