// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Outbound struct {
	ID              int64
	TenantID        int64
	OutboundNo      string
	OutboundType    string
	RefType         string
	RefID           int64
	RefNo           string
	CustomerName    string
	Status          string
	OperatorID      int64
	OperatorName    string
	Remark          string
	CancelledReason string
	ConfirmedAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

type OutboundItem struct {
	ID            int64
	TenantID      int64
	OutboundID    int64
	ReservationID int64
	RefLineID     int64
	ProductID     int64
	SkuID         int64
	ProductCode   string
	ProductName   string
	UomCode       string
	Qty           pgtype.Numeric
}

type OutboundItemStock struct {
	ID                int64
	TenantID          int64
	OutboundItemID    int64
	ReservationLineID int64
	StockID           int64
	WarehouseID       int64
	Qty               pgtype.Numeric
}

type OutboxEvent struct {
	ID            int64
	TenantID      int64
	AggregateType string
	AggregateID   string
	EventType     string
	Payload       []byte
	TraceID       string
	CreatedAt     pgtype.Timestamptz
	PublishedAt   pgtype.Timestamptz
	Attempts      int32
	LastError     *string
}

type ProcessedEvent struct {
	EventID       string
	ConsumerGroup string
	ProcessedAt   pgtype.Timestamptz
}

type Stock struct {
	ID           int64
	TenantID     int64
	WarehouseID  int64
	ProductID    int64
	SkuID        int64
	UomID        int64
	UomCode      string
	ProductCode  string
	ProductName  string
	OnHandQty    pgtype.Numeric
	ReservedQty  pgtype.Numeric
	LockedQty    pgtype.Numeric
	FrozenQty    pgtype.Numeric
	InTransitQty pgtype.Numeric
	AvailableQty pgtype.Numeric
	UpdatedAt    pgtype.Timestamptz
	CostCurrency string
	TotalCost    pgtype.Numeric
	AvgCost      pgtype.Numeric
}

type StockLedger struct {
	ID             int64
	TenantID       int64
	StockID        int64
	WarehouseID    int64
	SkuID          int64
	Movement       string
	Qty            pgtype.Numeric
	RefType        string
	RefID          int64
	RefNo          string
	OnHandAfter    pgtype.Numeric
	AvailableAfter pgtype.Numeric
	OperatorID     int64
	Remark         string
	OccurredAt     pgtype.Timestamptz
	UnitCost       pgtype.Numeric
	Amount         pgtype.Numeric
	AvgCostAfter   pgtype.Numeric
}

type StockLock struct {
	ID          int64
	TenantID    int64
	LockRefType string
	LockRefID   int64
	WarehouseID int64
	SkuID       int64
	Qty         pgtype.Numeric
	Status      string
	LockedAt    pgtype.Timestamptz
	ReleasedAt  pgtype.Timestamptz
}

type StockReservation struct {
	ID           int64
	TenantID     int64
	RefType      string
	RefID        int64
	RefLineID    int64
	RefNo        string
	ProductID    int64
	SkuID        int64
	DemandQty    pgtype.Numeric
	ReservedQty  pgtype.Numeric
	ShortageQty  pgtype.Numeric
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	VersionID    int64
	VersionNo    int32
	CustomerName string
	DeliveryDate string
	ProductCode  string
	ProductName  string
	UomID        int64
	UomCode      string
	LockedQty    pgtype.Numeric
	ShippedQty   pgtype.Numeric
}

type StockReservationLine struct {
	ID            int64
	TenantID      int64
	ReservationID int64
	StockID       int64
	WarehouseID   int64
	Qty           pgtype.Numeric
	CommittedQty  pgtype.Numeric
}

type Warehouse struct {
	ID             int64
	TenantID       int64
	Code           string
	Name           string
	WhType         string
	Address        string
	ManagerID      int64
	Status         string
	CreatedAt      pgtype.Timestamptz
	ProfileType    string
	CountryCode    string
	City           string
	Timezone       string
	Latitude       pgtype.Numeric
	Longitude      pgtype.Numeric
	AccountingMode string
	UpdatedAt      pgtype.Timestamptz
}

type WarehouseChangeHistory struct {
	ID            int64
	TenantID      int64
	WarehouseID   int64
	Action        string
	BeforeData    []byte
	AfterData     []byte
	Reason        string
	ChangedBy     *int64
	ChangedByName string
	ChangedAt     pgtype.Timestamptz
}

type WarehouseContact struct {
	ID          int64
	TenantID    int64
	WarehouseID int64
	ContactType string
	EmployeeID  *int64
	Name        string
	Phone       string
	Email       string
	IsPrimary   bool
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type WarehouseSetting struct {
	TenantID            int64
	UsageMode           string
	AllowDirectDelivery bool
	AllowInventory      bool
	DefaultWarehouseID  *int64
	UpdatedBy           *int64
	UpdatedAt           pgtype.Timestamptz
}

type WarehouseSettingsHistory struct {
	ID                  int64
	TenantID            int64
	UsageMode           string
	AllowDirectDelivery bool
	AllowInventory      bool
	DefaultWarehouseID  *int64
	ChangedBy           *int64
	ChangedAt           pgtype.Timestamptz
}
