// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbound.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const commitReservationLine = `-- name: CommitReservationLine :exec
UPDATE stock_reservation_lines
SET committed_qty = committed_qty + $1::text::numeric
WHERE tenant_id = $2::bigint AND id = $3::bigint
`

type CommitReservationLineParams struct {
	Qty      string
	TenantID int64
	ID       int64
}

func (q *Queries) CommitReservationLine(ctx context.Context, arg CommitReservationLineParams) error {
	_, err := q.db.Exec(ctx, commitReservationLine, arg.Qty, arg.TenantID, arg.ID)
	return err
}

const consumeLockOnOutbound = `-- name: ConsumeLockOnOutbound :one
WITH before AS (
    SELECT id, avg_cost, cost_currency
    FROM stocks
    WHERE tenant_id = $2::bigint AND id = $3::bigint
    FOR UPDATE
)
UPDATE stocks s SET
    on_hand_qty = s.on_hand_qty - $1::text::numeric,
    locked_qty  = s.locked_qty - $1::text::numeric,
    -- greatest() guards the last unit out: rounding across many movements can
    -- leave a few thousandths behind, and a negative cost pool would fail the
    -- CHECK and abort a shipment that is otherwise perfectly correct.
    total_cost  = greatest(s.total_cost - $1::text::numeric * b.avg_cost, 0),
    updated_at  = now()
FROM before b
WHERE s.id = b.id
RETURNING s.on_hand_qty::text AS on_hand_qty,
          s.available_qty::text AS available_qty,
          s.avg_cost::text AS avg_cost_after,
          b.avg_cost::text AS unit_cost,
          ($1::text::numeric * b.avg_cost)::text AS amount,
          b.cost_currency
`

type ConsumeLockOnOutboundParams struct {
	Qty      string
	TenantID int64
	ID       int64
}

type ConsumeLockOnOutboundRow struct {
	OnHandQty    string
	AvailableQty string
	AvgCostAfter string
	UnitCost     string
	Amount       string
	CostCurrency string
}

// The goods physically leave. on_hand and locked fall by the same amount, so
// availability does not move: what just shipped was never available.
//
// Value leaves with them, at the average the row carried a moment ago. The
// CTE captures that average before the update rewrites it — reading it
// afterwards would price the shipment at the average it produced, which is
// circular and wrong by exactly the amount that matters.
func (q *Queries) ConsumeLockOnOutbound(ctx context.Context, arg ConsumeLockOnOutboundParams) (ConsumeLockOnOutboundRow, error) {
	row := q.db.QueryRow(ctx, consumeLockOnOutbound, arg.Qty, arg.TenantID, arg.ID)
	var i ConsumeLockOnOutboundRow
	err := row.Scan(
		&i.OnHandQty,
		&i.AvailableQty,
		&i.AvgCostAfter,
		&i.UnitCost,
		&i.Amount,
		&i.CostCurrency,
	)
	return i, err
}

const convertReserveToLock = `-- name: ConvertReserveToLock :one
UPDATE stocks SET
    reserved_qty = reserved_qty - $1::text::numeric,
    locked_qty   = locked_qty + $1::text::numeric,
    updated_at   = now()
WHERE tenant_id = $2::bigint AND id = $3::bigint
RETURNING on_hand_qty::text AS on_hand_qty, available_qty::text AS available_qty,
          avg_cost::text AS avg_cost
`

type ConvertReserveToLockParams struct {
	Qty      string
	TenantID int64
	ID       int64
}

type ConvertReserveToLockRow struct {
	OnHandQty    string
	AvailableQty string
	AvgCost      string
}

// Layer 1 to layer 2. available_qty is generated from both columns, so moving
// quantity between them leaves availability untouched — which is the point:
// the goods were already off the market, they are now also off the shelf.
func (q *Queries) ConvertReserveToLock(ctx context.Context, arg ConvertReserveToLockParams) (ConvertReserveToLockRow, error) {
	row := q.db.QueryRow(ctx, convertReserveToLock, arg.Qty, arg.TenantID, arg.ID)
	var i ConvertReserveToLockRow
	err := row.Scan(&i.OnHandQty, &i.AvailableQty, &i.AvgCost)
	return i, err
}

const createOutbound = `-- name: CreateOutbound :one
INSERT INTO outbounds (
    tenant_id, outbound_no, outbound_type, ref_type, ref_id, ref_no,
    customer_name, operator_id, operator_name, remark
) VALUES (
    $1::bigint,
    $2::text,
    $3::text,
    $4::text,
    $5::bigint,
    $6::text,
    $7::text,
    $8::bigint,
    $9::text,
    $10::text
)
RETURNING id, outbound_no, status, created_at
`

type CreateOutboundParams struct {
	TenantID     int64
	OutboundNo   string
	OutboundType string
	RefType      string
	RefID        int64
	RefNo        string
	CustomerName string
	OperatorID   int64
	OperatorName string
	Remark       string
}

type CreateOutboundRow struct {
	ID         int64
	OutboundNo string
	Status     string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateOutbound(ctx context.Context, arg CreateOutboundParams) (CreateOutboundRow, error) {
	row := q.db.QueryRow(ctx, createOutbound,
		arg.TenantID,
		arg.OutboundNo,
		arg.OutboundType,
		arg.RefType,
		arg.RefID,
		arg.RefNo,
		arg.CustomerName,
		arg.OperatorID,
		arg.OperatorName,
		arg.Remark,
	)
	var i CreateOutboundRow
	err := row.Scan(
		&i.ID,
		&i.OutboundNo,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createOutboundItem = `-- name: CreateOutboundItem :one
INSERT INTO outbound_items (
    tenant_id, outbound_id, reservation_id, ref_line_id,
    product_id, sku_id, product_code, product_name, uom_code, qty
) VALUES (
    $1::bigint,
    $2::bigint,
    $3::bigint,
    $4::bigint,
    $5::bigint,
    $6::bigint,
    $7::text,
    $8::text,
    $9::text,
    $10::text::numeric
)
RETURNING id
`

type CreateOutboundItemParams struct {
	TenantID      int64
	OutboundID    int64
	ReservationID int64
	RefLineID     int64
	ProductID     int64
	SkuID         int64
	ProductCode   string
	ProductName   string
	UomCode       string
	Qty           string
}

func (q *Queries) CreateOutboundItem(ctx context.Context, arg CreateOutboundItemParams) (int64, error) {
	row := q.db.QueryRow(ctx, createOutboundItem,
		arg.TenantID,
		arg.OutboundID,
		arg.ReservationID,
		arg.RefLineID,
		arg.ProductID,
		arg.SkuID,
		arg.ProductCode,
		arg.ProductName,
		arg.UomCode,
		arg.Qty,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createOutboundItemStock = `-- name: CreateOutboundItemStock :exec
INSERT INTO outbound_item_stocks (
    tenant_id, outbound_item_id, reservation_line_id, stock_id, warehouse_id, qty
) VALUES (
    $1::bigint,
    $2::bigint,
    $3::bigint,
    $4::bigint,
    $5::bigint,
    $6::text::numeric
)
`

type CreateOutboundItemStockParams struct {
	TenantID          int64
	OutboundItemID    int64
	ReservationLineID int64
	StockID           int64
	WarehouseID       int64
	Qty               string
}

func (q *Queries) CreateOutboundItemStock(ctx context.Context, arg CreateOutboundItemStockParams) error {
	_, err := q.db.Exec(ctx, createOutboundItemStock,
		arg.TenantID,
		arg.OutboundItemID,
		arg.ReservationLineID,
		arg.StockID,
		arg.WarehouseID,
		arg.Qty,
	)
	return err
}

const getOutboundForUpdate = `-- name: GetOutboundForUpdate :one
SELECT id, outbound_no, outbound_type, ref_type, ref_id, ref_no,
       customer_name, status, operator_id, operator_name, remark
FROM outbounds
WHERE tenant_id = $1::bigint AND id = $2::bigint
FOR UPDATE
`

type GetOutboundForUpdateParams struct {
	TenantID int64
	ID       int64
}

type GetOutboundForUpdateRow struct {
	ID           int64
	OutboundNo   string
	OutboundType string
	RefType      string
	RefID        int64
	RefNo        string
	CustomerName string
	Status       string
	OperatorID   int64
	OperatorName string
	Remark       string
}

func (q *Queries) GetOutboundForUpdate(ctx context.Context, arg GetOutboundForUpdateParams) (GetOutboundForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getOutboundForUpdate, arg.TenantID, arg.ID)
	var i GetOutboundForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.OutboundNo,
		&i.OutboundType,
		&i.RefType,
		&i.RefID,
		&i.RefNo,
		&i.CustomerName,
		&i.Status,
		&i.OperatorID,
		&i.OperatorName,
		&i.Remark,
	)
	return i, err
}

const listOutbounds = `-- name: ListOutbounds :many
SELECT
    o.id, o.outbound_no, o.outbound_type, o.ref_type, o.ref_id, o.ref_no,
    o.customer_name, o.status, o.operator_id, o.operator_name, o.remark,
    o.cancelled_reason, o.confirmed_at, o.created_at,
    (SELECT count(*) FROM outbound_items i WHERE i.outbound_id = o.id) AS item_count,
    coalesce((SELECT sum(i.qty) FROM outbound_items i WHERE i.outbound_id = o.id), 0)::text AS total_qty,
    count(*) OVER () AS total
FROM outbounds o
WHERE o.tenant_id = $1::bigint
  AND ($2::text = '' OR o.status = $2::text)
  AND ($3::text = ''
       OR o.outbound_no ILIKE '%' || $3::text || '%'
       OR o.ref_no ILIKE '%' || $3::text || '%'
       OR o.customer_name ILIKE '%' || $3::text || '%')
ORDER BY o.created_at DESC, o.id DESC
LIMIT $5::int OFFSET $4::int
`

type ListOutboundsParams struct {
	TenantID  int64
	Status    string
	Keyword   string
	RowOffset int32
	RowLimit  int32
}

type ListOutboundsRow struct {
	ID              int64
	OutboundNo      string
	OutboundType    string
	RefType         string
	RefID           int64
	RefNo           string
	CustomerName    string
	Status          string
	OperatorID      int64
	OperatorName    string
	Remark          string
	CancelledReason string
	ConfirmedAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	ItemCount       int64
	TotalQty        string
	Total           int64
}

func (q *Queries) ListOutbounds(ctx context.Context, arg ListOutboundsParams) ([]ListOutboundsRow, error) {
	rows, err := q.db.Query(ctx, listOutbounds,
		arg.TenantID,
		arg.Status,
		arg.Keyword,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOutboundsRow
	for rows.Next() {
		var i ListOutboundsRow
		if err := rows.Scan(
			&i.ID,
			&i.OutboundNo,
			&i.OutboundType,
			&i.RefType,
			&i.RefID,
			&i.RefNo,
			&i.CustomerName,
			&i.Status,
			&i.OperatorID,
			&i.OperatorName,
			&i.Remark,
			&i.CancelledReason,
			&i.ConfirmedAt,
			&i.CreatedAt,
			&i.ItemCount,
			&i.TotalQty,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShippableContracts = `-- name: ListShippableContracts :many
SELECT
    r.ref_id AS contract_id,
    max(r.ref_no)::text        AS contract_no,
    max(r.customer_name)::text AS customer_name,
    max(r.delivery_date)::text AS delivery_date,
    count(*)             AS line_count,
    sum(r.demand_qty)::text                              AS demand_qty,
    sum(r.reserved_qty - r.locked_qty - r.shipped_qty)::text AS ready_qty,
    sum(r.shortage_qty)::text                            AS shortage_qty,
    sum(r.locked_qty)::text                              AS locked_qty,
    sum(r.shipped_qty)::text                             AS shipped_qty,
    count(*) OVER () AS total
FROM stock_reservations r
WHERE r.tenant_id = $1::bigint
  AND r.ref_type = 'CONTRACT'
  AND r.status = 'ACTIVE'
  AND ($2::text = ''
       OR r.ref_no ILIKE '%' || $2::text || '%'
       OR r.customer_name ILIKE '%' || $2::text || '%')
GROUP BY r.ref_id
ORDER BY max(r.delivery_date), r.ref_id
LIMIT $4::int OFFSET $3::int
`

type ListShippableContractsParams struct {
	TenantID  int64
	Keyword   string
	RowOffset int32
	RowLimit  int32
}

type ListShippableContractsRow struct {
	ContractID   int64
	ContractNo   string
	CustomerName string
	DeliveryDate string
	LineCount    int64
	DemandQty    string
	ReadyQty     string
	ShortageQty  string
	LockedQty    string
	ShippedQty   string
	Total        int64
}

// Contracts with something still owed. A line is done when everything it was
// promised has shipped, so a contract drops off this list on its own.
func (q *Queries) ListShippableContracts(ctx context.Context, arg ListShippableContractsParams) ([]ListShippableContractsRow, error) {
	rows, err := q.db.Query(ctx, listShippableContracts,
		arg.TenantID,
		arg.Keyword,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShippableContractsRow
	for rows.Next() {
		var i ListShippableContractsRow
		if err := rows.Scan(
			&i.ContractID,
			&i.ContractNo,
			&i.CustomerName,
			&i.DeliveryDate,
			&i.LineCount,
			&i.DemandQty,
			&i.ReadyQty,
			&i.ShortageQty,
			&i.LockedQty,
			&i.ShippedQty,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockReservationQty = `-- name: LockReservationQty :exec
UPDATE stock_reservations
SET locked_qty = locked_qty + $1::text::numeric, updated_at = now()
WHERE tenant_id = $2::bigint AND id = $3::bigint
`

type LockReservationQtyParams struct {
	Qty      string
	TenantID int64
	ID       int64
}

func (q *Queries) LockReservationQty(ctx context.Context, arg LockReservationQtyParams) error {
	_, err := q.db.Exec(ctx, lockReservationQty, arg.Qty, arg.TenantID, arg.ID)
	return err
}

const outboundItemStocksOf = `-- name: OutboundItemStocksOf :many
SELECT id, reservation_line_id, stock_id, warehouse_id, qty::text AS qty
FROM outbound_item_stocks
WHERE tenant_id = $1::bigint
  AND outbound_item_id = $2::bigint
ORDER BY id
`

type OutboundItemStocksOfParams struct {
	TenantID       int64
	OutboundItemID int64
}

type OutboundItemStocksOfRow struct {
	ID                int64
	ReservationLineID int64
	StockID           int64
	WarehouseID       int64
	Qty               string
}

func (q *Queries) OutboundItemStocksOf(ctx context.Context, arg OutboundItemStocksOfParams) ([]OutboundItemStocksOfRow, error) {
	rows, err := q.db.Query(ctx, outboundItemStocksOf, arg.TenantID, arg.OutboundItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboundItemStocksOfRow
	for rows.Next() {
		var i OutboundItemStocksOfRow
		if err := rows.Scan(
			&i.ID,
			&i.ReservationLineID,
			&i.StockID,
			&i.WarehouseID,
			&i.Qty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const outboundItemsOf = `-- name: OutboundItemsOf :many
SELECT id, reservation_id, ref_line_id, product_id, sku_id,
       product_code, product_name, uom_code, qty::text AS qty
FROM outbound_items
WHERE tenant_id = $1::bigint
  AND outbound_id = $2::bigint
ORDER BY id
`

type OutboundItemsOfParams struct {
	TenantID   int64
	OutboundID int64
}

type OutboundItemsOfRow struct {
	ID            int64
	ReservationID int64
	RefLineID     int64
	ProductID     int64
	SkuID         int64
	ProductCode   string
	ProductName   string
	UomCode       string
	Qty           string
}

func (q *Queries) OutboundItemsOf(ctx context.Context, arg OutboundItemsOfParams) ([]OutboundItemsOfRow, error) {
	rows, err := q.db.Query(ctx, outboundItemsOf, arg.TenantID, arg.OutboundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboundItemsOfRow
	for rows.Next() {
		var i OutboundItemsOfRow
		if err := rows.Scan(
			&i.ID,
			&i.ReservationID,
			&i.RefLineID,
			&i.ProductID,
			&i.SkuID,
			&i.ProductCode,
			&i.ProductName,
			&i.UomCode,
			&i.Qty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshReservationSnapshot = `-- name: RefreshReservationSnapshot :exec
UPDATE stock_reservations SET
    ref_no        = $1::text,
    version_id    = $2::bigint,
    version_no    = $3::int,
    customer_name = $4::text,
    delivery_date = $5::text,
    product_code  = $6::text,
    product_name  = $7::text,
    uom_id        = $8::bigint,
    uom_code      = $9::text
WHERE tenant_id = $10::bigint AND id = $11::bigint
`

type RefreshReservationSnapshotParams struct {
	RefNo        string
	VersionID    int64
	VersionNo    int32
	CustomerName string
	DeliveryDate string
	ProductCode  string
	ProductName  string
	UomID        int64
	UomCode      string
	TenantID     int64
	ID           int64
}

// A redelivered contract event must not reserve twice, but it may well carry
// a fresher description than the one already stored. Quantities are pointedly
// absent: this only refreshes the labels.
func (q *Queries) RefreshReservationSnapshot(ctx context.Context, arg RefreshReservationSnapshotParams) error {
	_, err := q.db.Exec(ctx, refreshReservationSnapshot,
		arg.RefNo,
		arg.VersionID,
		arg.VersionNo,
		arg.CustomerName,
		arg.DeliveryDate,
		arg.ProductCode,
		arg.ProductName,
		arg.UomID,
		arg.UomCode,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const releaseLockToReserve = `-- name: ReleaseLockToReserve :one
UPDATE stocks SET
    locked_qty   = locked_qty - $1::text::numeric,
    reserved_qty = reserved_qty + $1::text::numeric,
    updated_at   = now()
WHERE tenant_id = $2::bigint AND id = $3::bigint
RETURNING on_hand_qty::text AS on_hand_qty, available_qty::text AS available_qty,
          avg_cost::text AS avg_cost
`

type ReleaseLockToReserveParams struct {
	Qty      string
	TenantID int64
	ID       int64
}

type ReleaseLockToReserveRow struct {
	OnHandQty    string
	AvailableQty string
	AvgCost      string
}

func (q *Queries) ReleaseLockToReserve(ctx context.Context, arg ReleaseLockToReserveParams) (ReleaseLockToReserveRow, error) {
	row := q.db.QueryRow(ctx, releaseLockToReserve, arg.Qty, arg.TenantID, arg.ID)
	var i ReleaseLockToReserveRow
	err := row.Scan(&i.OnHandQty, &i.AvailableQty, &i.AvgCost)
	return i, err
}

const reservationForUpdate = `-- name: ReservationForUpdate :one

SELECT
    id, ref_line_id, ref_no, product_id, sku_id, product_code, product_name,
    uom_id, uom_code, version_id, version_no, customer_name, delivery_date,
    demand_qty::text    AS demand_qty,
    reserved_qty::text  AS reserved_qty,
    locked_qty::text    AS locked_qty,
    shipped_qty::text   AS shipped_qty,
    shortage_qty::text  AS shortage_qty,
    status
FROM stock_reservations
WHERE tenant_id = $1::bigint
  AND ref_type = $2::text
  AND ref_id = $3::bigint
  AND ref_line_id = $4::bigint
FOR UPDATE
`

type ReservationForUpdateParams struct {
	TenantID  int64
	RefType   string
	RefID     int64
	RefLineID int64
}

type ReservationForUpdateRow struct {
	ID           int64
	RefLineID    int64
	RefNo        string
	ProductID    int64
	SkuID        int64
	ProductCode  string
	ProductName  string
	UomID        int64
	UomCode      string
	VersionID    int64
	VersionNo    int32
	CustomerName string
	DeliveryDate string
	DemandQty    string
	ReservedQty  string
	LockedQty    string
	ShippedQty   string
	ShortageQty  string
	Status       string
}

// Outbound. Same rule as the rest of this service: quantities cross the
// boundary as text, never float64.
// The row that decides whether anything may leave the building for this
// contract line. Locked because two pickers must not both commit the same
// reserved quantity.
func (q *Queries) ReservationForUpdate(ctx context.Context, arg ReservationForUpdateParams) (ReservationForUpdateRow, error) {
	row := q.db.QueryRow(ctx, reservationForUpdate,
		arg.TenantID,
		arg.RefType,
		arg.RefID,
		arg.RefLineID,
	)
	var i ReservationForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.RefLineID,
		&i.RefNo,
		&i.ProductID,
		&i.SkuID,
		&i.ProductCode,
		&i.ProductName,
		&i.UomID,
		&i.UomCode,
		&i.VersionID,
		&i.VersionNo,
		&i.CustomerName,
		&i.DeliveryDate,
		&i.DemandQty,
		&i.ReservedQty,
		&i.LockedQty,
		&i.ShippedQty,
		&i.ShortageQty,
		&i.Status,
	)
	return i, err
}

const reservationLinesForUpdate = `-- name: ReservationLinesForUpdate :many
SELECT
    id, stock_id, warehouse_id,
    (qty - committed_qty)::text AS remaining_qty
FROM stock_reservation_lines
WHERE tenant_id = $1::bigint
  AND reservation_id = $2::bigint
  AND qty > committed_qty
ORDER BY id
FOR UPDATE
`

type ReservationLinesForUpdateParams struct {
	TenantID      int64
	ReservationID int64
}

type ReservationLinesForUpdateRow struct {
	ID           int64
	StockID      int64
	WarehouseID  int64
	RemainingQty string
}

// Warehouse rows this reservation still has uncommitted quantity on.
func (q *Queries) ReservationLinesForUpdate(ctx context.Context, arg ReservationLinesForUpdateParams) ([]ReservationLinesForUpdateRow, error) {
	rows, err := q.db.Query(ctx, reservationLinesForUpdate, arg.TenantID, arg.ReservationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReservationLinesForUpdateRow
	for rows.Next() {
		var i ReservationLinesForUpdateRow
		if err := rows.Scan(
			&i.ID,
			&i.StockID,
			&i.WarehouseID,
			&i.RemainingQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reservationsOfContract = `-- name: ReservationsOfContract :many
SELECT
    id, ref_line_id, ref_no, product_id, sku_id, product_code, product_name,
    uom_id, uom_code, version_id, version_no, customer_name, delivery_date,
    demand_qty::text   AS demand_qty,
    reserved_qty::text AS reserved_qty,
    shortage_qty::text AS shortage_qty
FROM stock_reservations
WHERE tenant_id = $1::bigint
  AND ref_type = $2::text
  AND ref_id = $3::bigint
  AND status <> 'RELEASED'
ORDER BY ref_line_id
`

type ReservationsOfContractParams struct {
	TenantID int64
	RefType  string
	RefID    int64
}

type ReservationsOfContractRow struct {
	ID           int64
	RefLineID    int64
	RefNo        string
	ProductID    int64
	SkuID        int64
	ProductCode  string
	ProductName  string
	UomID        int64
	UomCode      string
	VersionID    int64
	VersionNo    int32
	CustomerName string
	DeliveryDate string
	DemandQty    string
	ReservedQty  string
	ShortageQty  string
}

// Everything a contract holds, in the shape the allocation event needs. Used
// to re-publish StockAllocated after a top-up so procurement can shrink or
// close the requirement it raised.
func (q *Queries) ReservationsOfContract(ctx context.Context, arg ReservationsOfContractParams) ([]ReservationsOfContractRow, error) {
	rows, err := q.db.Query(ctx, reservationsOfContract, arg.TenantID, arg.RefType, arg.RefID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReservationsOfContractRow
	for rows.Next() {
		var i ReservationsOfContractRow
		if err := rows.Scan(
			&i.ID,
			&i.RefLineID,
			&i.RefNo,
			&i.ProductID,
			&i.SkuID,
			&i.ProductCode,
			&i.ProductName,
			&i.UomID,
			&i.UomCode,
			&i.VersionID,
			&i.VersionNo,
			&i.CustomerName,
			&i.DeliveryDate,
			&i.DemandQty,
			&i.ReservedQty,
			&i.ShortageQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOutboundCancelled = `-- name: SetOutboundCancelled :exec
UPDATE outbounds SET status = 'CANCELLED', cancelled_reason = $1::text
WHERE tenant_id = $2::bigint AND id = $3::bigint
`

type SetOutboundCancelledParams struct {
	Reason   string
	TenantID int64
	ID       int64
}

func (q *Queries) SetOutboundCancelled(ctx context.Context, arg SetOutboundCancelledParams) error {
	_, err := q.db.Exec(ctx, setOutboundCancelled, arg.Reason, arg.TenantID, arg.ID)
	return err
}

const setOutboundConfirmed = `-- name: SetOutboundConfirmed :exec
UPDATE outbounds SET status = 'CONFIRMED', confirmed_at = now()
WHERE tenant_id = $1::bigint AND id = $2::bigint
`

type SetOutboundConfirmedParams struct {
	TenantID int64
	ID       int64
}

func (q *Queries) SetOutboundConfirmed(ctx context.Context, arg SetOutboundConfirmedParams) error {
	_, err := q.db.Exec(ctx, setOutboundConfirmed, arg.TenantID, arg.ID)
	return err
}

const shipReservationQty = `-- name: ShipReservationQty :one
UPDATE stock_reservations SET
    locked_qty  = locked_qty - $1::text::numeric,
    shipped_qty = shipped_qty + $1::text::numeric,
    status      = CASE
                      WHEN shipped_qty + $1::text::numeric >= demand_qty
                      THEN 'SHIPPED' ELSE status
                  END,
    updated_at  = now()
WHERE tenant_id = $2::bigint AND id = $3::bigint
RETURNING shipped_qty::text AS shipped_qty, status
`

type ShipReservationQtyParams struct {
	Qty      string
	TenantID int64
	ID       int64
}

type ShipReservationQtyRow struct {
	ShippedQty string
	Status     string
}

// Locked becomes shipped. A line whose whole demand has left is closed, so it
// stops appearing on the shippable list.
func (q *Queries) ShipReservationQty(ctx context.Context, arg ShipReservationQtyParams) (ShipReservationQtyRow, error) {
	row := q.db.QueryRow(ctx, shipReservationQty, arg.Qty, arg.TenantID, arg.ID)
	var i ShipReservationQtyRow
	err := row.Scan(&i.ShippedQty, &i.Status)
	return i, err
}

const shippableLinesOf = `-- name: ShippableLinesOf :many
SELECT
    r.id, r.ref_line_id, r.product_id, r.sku_id, r.product_code, r.product_name,
    r.uom_code, r.status,
    r.demand_qty::text   AS demand_qty,
    r.reserved_qty::text AS reserved_qty,
    r.locked_qty::text   AS locked_qty,
    r.shipped_qty::text  AS shipped_qty,
    r.shortage_qty::text AS shortage_qty,
    (r.reserved_qty - r.locked_qty - r.shipped_qty)::text AS ready_qty,
    -- What could still be taken from the shelf right now if the shortage were
    -- topped up on the spot. Shown so the page can say "3 of the 8 missing
    -- have arrived" instead of a flat refusal.
    coalesce((
        SELECT sum(s.available_qty) FROM stocks s
        WHERE s.tenant_id = r.tenant_id
          AND s.product_id = r.product_id AND s.sku_id = r.sku_id
    ), 0)::text AS available_qty
FROM stock_reservations r
WHERE r.tenant_id = $1::bigint
  AND r.ref_type = 'CONTRACT'
  AND r.ref_id = $2::bigint
  AND r.status <> 'RELEASED'
ORDER BY r.ref_line_id
`

type ShippableLinesOfParams struct {
	TenantID int64
	RefID    int64
}

type ShippableLinesOfRow struct {
	ID           int64
	RefLineID    int64
	ProductID    int64
	SkuID        int64
	ProductCode  string
	ProductName  string
	UomCode      string
	Status       string
	DemandQty    string
	ReservedQty  string
	LockedQty    string
	ShippedQty   string
	ShortageQty  string
	ReadyQty     string
	AvailableQty string
}

// One row per contract line, with the four numbers a picker needs: what was
// sold, what stock is holding for it, what is already on a picking list, and
// what is missing. ready_qty is the only quantity an outbound may draw on.
func (q *Queries) ShippableLinesOf(ctx context.Context, arg ShippableLinesOfParams) ([]ShippableLinesOfRow, error) {
	rows, err := q.db.Query(ctx, shippableLinesOf, arg.TenantID, arg.RefID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShippableLinesOfRow
	for rows.Next() {
		var i ShippableLinesOfRow
		if err := rows.Scan(
			&i.ID,
			&i.RefLineID,
			&i.ProductID,
			&i.SkuID,
			&i.ProductCode,
			&i.ProductName,
			&i.UomCode,
			&i.Status,
			&i.DemandQty,
			&i.ReservedQty,
			&i.LockedQty,
			&i.ShippedQty,
			&i.ShortageQty,
			&i.ReadyQty,
			&i.AvailableQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const supersededReservationsOf = `-- name: SupersededReservationsOf :many
SELECT id, ref_line_id, ref_no, product_id, sku_id, version_no,
       reserved_qty::text AS reserved_qty,
       locked_qty::text   AS locked_qty,
       shipped_qty::text  AS shipped_qty
FROM stock_reservations
WHERE tenant_id = $1::bigint
  AND ref_type = $2::text
  AND ref_id = $3::bigint
  AND status = 'ACTIVE'
  AND version_id < $4::bigint
ORDER BY id
FOR UPDATE
`

type SupersededReservationsOfParams struct {
	TenantID      int64
	RefType       string
	RefID         int64
	KeepVersionID int64
}

type SupersededReservationsOfRow struct {
	ID          int64
	RefLineID   int64
	RefNo       string
	ProductID   int64
	SkuID       int64
	VersionNo   int32
	ReservedQty string
	LockedQty   string
	ShippedQty  string
}

// Reservations left behind by an earlier version of a contract that has since
// been changed. locked and shipped come along because they decide whether the
// quantity can simply be handed back or whether a person has to look at it.
func (q *Queries) SupersededReservationsOf(ctx context.Context, arg SupersededReservationsOfParams) ([]SupersededReservationsOfRow, error) {
	rows, err := q.db.Query(ctx, supersededReservationsOf,
		arg.TenantID,
		arg.RefType,
		arg.RefID,
		arg.KeepVersionID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupersededReservationsOfRow
	for rows.Next() {
		var i SupersededReservationsOfRow
		if err := rows.Scan(
			&i.ID,
			&i.RefLineID,
			&i.RefNo,
			&i.ProductID,
			&i.SkuID,
			&i.VersionNo,
			&i.ReservedQty,
			&i.LockedQty,
			&i.ShippedQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const uncommitReservationLine = `-- name: UncommitReservationLine :exec
UPDATE stock_reservation_lines
SET committed_qty = committed_qty - $1::text::numeric
WHERE tenant_id = $2::bigint AND id = $3::bigint
`

type UncommitReservationLineParams struct {
	Qty      string
	TenantID int64
	ID       int64
}

func (q *Queries) UncommitReservationLine(ctx context.Context, arg UncommitReservationLineParams) error {
	_, err := q.db.Exec(ctx, uncommitReservationLine, arg.Qty, arg.TenantID, arg.ID)
	return err
}

const unlockReservationQty = `-- name: UnlockReservationQty :exec
UPDATE stock_reservations
SET locked_qty = locked_qty - $1::text::numeric, updated_at = now()
WHERE tenant_id = $2::bigint AND id = $3::bigint
`

type UnlockReservationQtyParams struct {
	Qty      string
	TenantID int64
	ID       int64
}

func (q *Queries) UnlockReservationQty(ctx context.Context, arg UnlockReservationQtyParams) error {
	_, err := q.db.Exec(ctx, unlockReservationQty, arg.Qty, arg.TenantID, arg.ID)
	return err
}

const waitingReservationsForItem = `-- name: WaitingReservationsForItem :many
SELECT
    id, ref_id, ref_line_id, ref_no, product_id, sku_id,
    shortage_qty::text AS shortage_qty
FROM stock_reservations
WHERE tenant_id = $1::bigint
  AND ref_type = 'CONTRACT'
  AND status = 'ACTIVE'
  AND product_id = $2::bigint
  AND sku_id = $3::bigint
  AND shortage_qty > 0
ORDER BY delivery_date, id
FOR UPDATE
`

type WaitingReservationsForItemParams struct {
	TenantID  int64
	ProductID int64
	SkuID     int64
}

type WaitingReservationsForItemRow struct {
	ID          int64
	RefID       int64
	RefLineID   int64
	RefNo       string
	ProductID   int64
	SkuID       int64
	ShortageQty string
}

// Contract lines still short of this item, soonest delivery first.
//
// Order matters and is a business rule, not a detail: when a part shipment
// arrives it goes to whoever is due first. Ordering by id instead would hand
// it to whoever signed first, which is not the same thing and is wrong every
// time an early contract has a late delivery date.
func (q *Queries) WaitingReservationsForItem(ctx context.Context, arg WaitingReservationsForItemParams) ([]WaitingReservationsForItemRow, error) {
	rows, err := q.db.Query(ctx, waitingReservationsForItem, arg.TenantID, arg.ProductID, arg.SkuID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WaitingReservationsForItemRow
	for rows.Next() {
		var i WaitingReservationsForItemRow
		if err := rows.Scan(
			&i.ID,
			&i.RefID,
			&i.RefLineID,
			&i.RefNo,
			&i.ProductID,
			&i.SkuID,
			&i.ShortageQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
