#!/bin/sh
# All the knobs in one place. Every other script in this directory sources
# this file; nothing else defines names, sizes or regions. Change here, and
# the change is what every script sees — two scripts with their own copy of
# a name is how one of them quietly builds in the wrong region.
#
# Nothing in this file is secret. Secrets are GENERATED by the scripts and
# written to ./secrets/ (gitignored), never into this file and never into
# the repository.
set -eu

# ---------------------------------------------------------------- identity
REGION=us-west-2
PROJECT=erp

# The bucket name is global across every AWS customer, so it cannot have a
# default — pick one and export it before running 01-s3.sh:
#   export ERP_BUCKET=erp-files-<your-suffix>
BUCKET="${ERP_BUCKET:-}"

# Where the browser loads the app from.
#
# Needed because uploads go straight from the browser to the bucket, which
# makes them cross-origin: the page is served from here and the PUT goes to
# s3.amazonaws.com. A browser answers that by sending a preflight first, and
# S3 refuses every preflight unless the bucket names this origin. Getting it
# wrong does not fail at deploy time — it fails the first time somebody tries
# to attach a file.
APP_ORIGIN="${ERP_APP_ORIGIN:-https://mercova.ip-ddns.com}"

# ---------------------------------------------------------------- sizes
# t3.xlarge: 4 vCPU / 16 GB. The 11 Go services are light; the sizing is for
# Kafka's fixed 1 GB heap plus mail-sync concurrency. ~$120/month on-demand.
EC2_TYPE=t3.xlarge
ROOT_VOL_GB=100

# db.t4g.medium single-AZ ~$55/month. Data safety comes from backups and
# point-in-time recovery, not from Multi-AZ — that is a deliberate pilot
# trade-off, and flipping to Multi-AZ later is one command.
RDS_CLASS=db.t4g.medium
RDS_STORAGE_GB=50
RDS_ENGINE_VERSION=16

# ---------------------------------------------------------------- plumbing
SECRETS_DIR="$(cd "$(dirname "$0")" && pwd)/secrets"
TAGS="Key=Project,Value=$PROJECT"

# The CLI pipes long output through a pager and stops to wait for a
# keypress, which inside a script reads as "hung".
export AWS_PAGER=""
export AWS_DEFAULT_REGION="$REGION"

# Fail before doing anything if the operator's setup is not ready. Every
# script calls this first: half-configured credentials should produce this
# message, not a half-built environment.
require_aws() {
  command -v aws >/dev/null 2>&1 || {
    echo "aws CLI 未安装：https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html" >&2
    exit 1
  }
  aws sts get-caller-identity >/dev/null 2>&1 || {
    echo "aws CLI 未配置或凭证无效：先运行 aws configure（区域填 $REGION）" >&2
    exit 1
  }
  mkdir -p "$SECRETS_DIR"
  chmod 700 "$SECRETS_DIR"
}

require_bucket_name() {
  [ -n "$BUCKET" ] || {
    echo "先设置桶名（全球唯一，起个带后缀的）：export ERP_BUCKET=erp-files-你的后缀" >&2
    exit 1
  }
}
