// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: excel.sql

package store

import (
	"context"
)

const claimExcelJob = `-- name: ClaimExcelJob :one
WITH candidate AS (
  SELECT id
  FROM mail_excel_jobs
  WHERE status='PENDING'
     OR (status='PROCESSING' AND started_at < now() - interval '15 minutes')
  ORDER BY created_at, id
  FOR UPDATE SKIP LOCKED
  LIMIT 1
)
UPDATE mail_excel_jobs j SET
  status='PROCESSING', attempt_count=attempt_count+1,
  started_at=now(), completed_at=NULL,
  error_code='', error_message='', updated_at=now()
FROM candidate
WHERE j.id=candidate.id
RETURNING j.id, j.tenant_id, j.owner_id, j.inbound_id, j.attachment_id, j.selected_text, j.locale, j.status, j.attempt_count, j.file_name, j.file_data, j.workbook_json, j.model, j.error_code, j.error_message, j.created_at, j.started_at, j.completed_at, j.updated_at
`

func (q *Queries) ClaimExcelJob(ctx context.Context) (MailExcelJob, error) {
	row := q.db.QueryRow(ctx, claimExcelJob)
	var i MailExcelJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OwnerID,
		&i.InboundID,
		&i.AttachmentID,
		&i.SelectedText,
		&i.Locale,
		&i.Status,
		&i.AttemptCount,
		&i.FileName,
		&i.FileData,
		&i.WorkbookJson,
		&i.Model,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeExcelJob = `-- name: CompleteExcelJob :execrows
UPDATE mail_excel_jobs SET
  status='COMPLETED', file_name=$1, file_data=$2,
  workbook_json=$3, model=$4,
  error_code='', error_message='', completed_at=now(), updated_at=now()
WHERE id=$5 AND status='PROCESSING'
`

type CompleteExcelJobParams struct {
	FileName     string
	FileData     []byte
	WorkbookJson []byte
	Model        string
	ID           int64
}

func (q *Queries) CompleteExcelJob(ctx context.Context, arg CompleteExcelJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeExcelJob,
		arg.FileName,
		arg.FileData,
		arg.WorkbookJson,
		arg.Model,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createExcelJob = `-- name: CreateExcelJob :one
INSERT INTO mail_excel_jobs (
  tenant_id, owner_id, inbound_id, attachment_id, selected_text, locale
) VALUES (
  $1, $2, $3,
  $4, $5, $6
)
RETURNING id, tenant_id, owner_id, inbound_id, attachment_id, selected_text, locale, status, attempt_count, file_name, file_data, workbook_json, model, error_code, error_message, created_at, started_at, completed_at, updated_at
`

type CreateExcelJobParams struct {
	TenantID     int64
	OwnerID      int64
	InboundID    int64
	AttachmentID *int64
	SelectedText *string
	Locale       string
}

func (q *Queries) CreateExcelJob(ctx context.Context, arg CreateExcelJobParams) (MailExcelJob, error) {
	row := q.db.QueryRow(ctx, createExcelJob,
		arg.TenantID,
		arg.OwnerID,
		arg.InboundID,
		arg.AttachmentID,
		arg.SelectedText,
		arg.Locale,
	)
	var i MailExcelJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OwnerID,
		&i.InboundID,
		&i.AttachmentID,
		&i.SelectedText,
		&i.Locale,
		&i.Status,
		&i.AttemptCount,
		&i.FileName,
		&i.FileData,
		&i.WorkbookJson,
		&i.Model,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failExcelJob = `-- name: FailExcelJob :execrows
UPDATE mail_excel_jobs SET
  status='FAILED', file_data=NULL, workbook_json=NULL,
  error_code=$1, error_message=$2,
  completed_at=now(), updated_at=now()
WHERE id=$3 AND status='PROCESSING'
`

type FailExcelJobParams struct {
	ErrorCode    string
	ErrorMessage string
	ID           int64
}

func (q *Queries) FailExcelJob(ctx context.Context, arg FailExcelJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, failExcelJob, arg.ErrorCode, arg.ErrorMessage, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getExcelJob = `-- name: GetExcelJob :one
SELECT id, tenant_id, owner_id, inbound_id, attachment_id, selected_text, locale, status, attempt_count, file_name, file_data, workbook_json, model, error_code, error_message, created_at, started_at, completed_at, updated_at FROM mail_excel_jobs
WHERE tenant_id=$1 AND owner_id=$2 AND id=$3
`

type GetExcelJobParams struct {
	TenantID int64
	OwnerID  int64
	ID       int64
}

func (q *Queries) GetExcelJob(ctx context.Context, arg GetExcelJobParams) (MailExcelJob, error) {
	row := q.db.QueryRow(ctx, getExcelJob, arg.TenantID, arg.OwnerID, arg.ID)
	var i MailExcelJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OwnerID,
		&i.InboundID,
		&i.AttachmentID,
		&i.SelectedText,
		&i.Locale,
		&i.Status,
		&i.AttemptCount,
		&i.FileName,
		&i.FileData,
		&i.WorkbookJson,
		&i.Model,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}
