// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: export.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countExports = `-- name: CountExports :one
SELECT count(*)::bigint FROM mail_export_log
WHERE tenant_id = $1::bigint
  AND ($2::bool
       OR employee_id = ANY($3::bigint[]))
`

type CountExportsParams struct {
	TenantID   int64
	VisibleAll bool
	VisibleIds []int64
}

func (q *Queries) CountExports(ctx context.Context, arg CountExportsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countExports, arg.TenantID, arg.VisibleAll, arg.VisibleIds)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listExports = `-- name: ListExports :many
SELECT id, employee_id, employee_name, thread_key, subject, counterparty,
       turn_count, byte_size, format, client_ip, exported_at
FROM mail_export_log
WHERE tenant_id = $1::bigint
  AND ($2::bool
       OR employee_id = ANY($3::bigint[]))
ORDER BY exported_at DESC, id DESC
LIMIT $5::int OFFSET $4::int
`

type ListExportsParams struct {
	TenantID   int64
	VisibleAll bool
	VisibleIds []int64
	RowOffset  int32
	RowLimit   int32
}

type ListExportsRow struct {
	ID           int64
	EmployeeID   int64
	EmployeeName string
	ThreadKey    string
	Subject      string
	Counterparty string
	TurnCount    int32
	ByteSize     int64
	Format       string
	ClientIp     string
	ExportedAt   pgtype.Timestamptz
}

// Newest first: the question this log answers is almost always about the
// recent past. Scoped through the same visibility the team mail view uses, so
// a sales manager sees their own team and nobody else's.
func (q *Queries) ListExports(ctx context.Context, arg ListExportsParams) ([]ListExportsRow, error) {
	rows, err := q.db.Query(ctx, listExports,
		arg.TenantID,
		arg.VisibleAll,
		arg.VisibleIds,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExportsRow
	for rows.Next() {
		var i ListExportsRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.EmployeeName,
			&i.ThreadKey,
			&i.Subject,
			&i.Counterparty,
			&i.TurnCount,
			&i.ByteSize,
			&i.Format,
			&i.ClientIp,
			&i.ExportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadForExport = `-- name: ListThreadForExport :many

SELECT 'OUT' AS direction, m.id, m.subject,
       m.body AS body_html, ''::text AS body_text, m.body_format,
       m.to_email AS counterparty, m.sender_name AS who,
       coalesce(m.sent_at, m.queued_at) AS at
FROM email_messages m
WHERE m.tenant_id = $1::bigint
  AND m.sender_id = $2::bigint
  AND m.thread_key = $3::text
UNION ALL
SELECT 'IN' AS direction, i.id, i.subject,
       i.body_html, i.body_text,
       CASE WHEN i.body_html <> '' THEN 'HTML' ELSE 'TEXT' END AS body_format,
       i.from_email AS counterparty, i.from_name AS who,
       coalesce(i.sent_at, i.received_at) AS at
FROM email_inbound i
WHERE i.tenant_id = $1::bigint
  AND i.owner_id = $2::bigint
  AND i.thread_key = $3::text
  AND NOT i.is_bounce
  -- Same duplicate-silencing as ListThread, for the same reason: an export
  -- of a conversation must not carry every ERP-sent reply twice. See the
  -- comment there for the anatomy of a SENT-folder mirror copy.
  AND NOT (i.folder = 'SENT' AND i.message_id <> '' AND (
    EXISTS (
      SELECT 1 FROM email_messages sent
      WHERE sent.tenant_id = i.tenant_id AND sent.sender_id = i.owner_id
        AND sent.message_key::text = split_part(i.message_id, '@', 1)
    )
    OR EXISTS (
      SELECT 1 FROM email_inbound twin
      WHERE twin.tenant_id = i.tenant_id AND twin.owner_id = i.owner_id
        AND twin.thread_key = i.thread_key AND twin.message_id = i.message_id
        AND twin.id <> i.id AND twin.folder <> 'SENT' AND NOT twin.is_bounce
    )
  ))
ORDER BY at
`

type ListThreadForExportParams struct {
	TenantID  int64
	OwnerID   int64
	ThreadKey string
}

type ListThreadForExportRow struct {
	Direction    string
	ID           int64
	Subject      string
	BodyHtml     string
	BodyText     string
	BodyFormat   string
	Counterparty string
	Who          string
	At           pgtype.Timestamptz
}

// Exporting a conversation, and the record of having done it.
// One conversation, both directions, oldest first — the same union as
// ListThread and owner-scoped for the same reason, but carrying the sender's
// own plain-text alternative alongside the HTML.
//
// ListThread prefers the HTML because it is feeding a browser. An export
// prefers the text, and the difference matters: when a mail was sent as
// multipart/alternative the text part was written by the sender's own client,
// which lays out a quoted reply chain and a price table far better than any
// tag-stripper of ours will. HTMLToText is the fallback, not the first choice.
func (q *Queries) ListThreadForExport(ctx context.Context, arg ListThreadForExportParams) ([]ListThreadForExportRow, error) {
	rows, err := q.db.Query(ctx, listThreadForExport, arg.TenantID, arg.OwnerID, arg.ThreadKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListThreadForExportRow
	for rows.Next() {
		var i ListThreadForExportRow
		if err := rows.Scan(
			&i.Direction,
			&i.ID,
			&i.Subject,
			&i.BodyHtml,
			&i.BodyText,
			&i.BodyFormat,
			&i.Counterparty,
			&i.Who,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadInboundFiles = `-- name: ListThreadInboundFiles :many
SELECT a.inbound_id AS message_id, a.file_name, a.file_size
FROM email_inbound_attachments a
JOIN email_inbound i
  ON i.id = a.inbound_id AND i.tenant_id = a.tenant_id
WHERE i.tenant_id = $1::bigint
  AND i.owner_id = $2::bigint
  AND i.thread_key = $3::text
ORDER BY a.inbound_id, a.id
`

type ListThreadInboundFilesParams struct {
	TenantID  int64
	OwnerID   int64
	ThreadKey string
}

type ListThreadInboundFilesRow struct {
	MessageID int64
	FileName  string
	FileSize  int64
}

// Every file that arrived in this conversation, keyed to the message it came
// with. Names and sizes only: the export lists what was attached, it does not
// carry the bytes. A transcript that silently omitted "并附上签署版合同.pdf"
// would read as though no contract was ever sent.
func (q *Queries) ListThreadInboundFiles(ctx context.Context, arg ListThreadInboundFilesParams) ([]ListThreadInboundFilesRow, error) {
	rows, err := q.db.Query(ctx, listThreadInboundFiles, arg.TenantID, arg.OwnerID, arg.ThreadKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListThreadInboundFilesRow
	for rows.Next() {
		var i ListThreadInboundFilesRow
		if err := rows.Scan(&i.MessageID, &i.FileName, &i.FileSize); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadSentFiles = `-- name: ListThreadSentFiles :many
SELECT m.id AS message_id, a.file_name, a.file_size
FROM email_messages m
JOIN email_attachments a
  ON a.campaign_id = m.campaign_id AND a.tenant_id = m.tenant_id
WHERE m.tenant_id = $1::bigint
  AND m.sender_id = $2::bigint
  AND m.thread_key = $3::text
ORDER BY m.id, a.id
`

type ListThreadSentFilesParams struct {
	TenantID  int64
	OwnerID   int64
	ThreadKey string
}

type ListThreadSentFilesRow struct {
	MessageID int64
	FileName  string
	FileSize  int64
}

// The same for our side. Outbound attachments hang off the campaign rather
// than the message — one upload, many recipients — so this joins back through
// it to say which of our sends carried which file.
func (q *Queries) ListThreadSentFiles(ctx context.Context, arg ListThreadSentFilesParams) ([]ListThreadSentFilesRow, error) {
	rows, err := q.db.Query(ctx, listThreadSentFiles, arg.TenantID, arg.OwnerID, arg.ThreadKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListThreadSentFilesRow
	for rows.Next() {
		var i ListThreadSentFilesRow
		if err := rows.Scan(&i.MessageID, &i.FileName, &i.FileSize); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordExport = `-- name: RecordExport :one
INSERT INTO mail_export_log (
    tenant_id, employee_id, employee_name, thread_key, subject,
    counterparty, turn_count, byte_size, format, client_ip
) VALUES (
    $1::bigint,
    $2::bigint,
    $3::text,
    $4::text,
    $5::text,
    $6::text,
    $7::int,
    $8::bigint,
    $9::text,
    $10::text
)
RETURNING id, exported_at
`

type RecordExportParams struct {
	TenantID     int64
	EmployeeID   int64
	EmployeeName string
	ThreadKey    string
	Subject      string
	Counterparty string
	TurnCount    int32
	ByteSize     int64
	Format       string
	ClientIp     string
}

type RecordExportRow struct {
	ID         int64
	ExportedAt pgtype.Timestamptz
}

// Written before the document is handed over, never after. An export whose
// record could not be written must not happen at all — see ExportMailThread.
func (q *Queries) RecordExport(ctx context.Context, arg RecordExportParams) (RecordExportRow, error) {
	row := q.db.QueryRow(ctx, recordExport,
		arg.TenantID,
		arg.EmployeeID,
		arg.EmployeeName,
		arg.ThreadKey,
		arg.Subject,
		arg.Counterparty,
		arg.TurnCount,
		arg.ByteSize,
		arg.Format,
		arg.ClientIp,
	)
	var i RecordExportRow
	err := row.Scan(&i.ID, &i.ExportedAt)
	return i, err
}
