// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inboundimages.sql

package store

import (
	"context"
)

const insertInboundImage = `-- name: InsertInboundImage :exec
INSERT INTO email_inbound_images (
    tenant_id, inbound_id, source_url, url_hash, object_key, content_type, byte_size
) VALUES (
    $1::bigint,
    $2::bigint,
    $3::text,
    $4::bytea,
    $5::text,
    $6::text,
    $7::bigint
)
ON CONFLICT (tenant_id, inbound_id, url_hash) DO NOTHING
`

type InsertInboundImageParams struct {
	TenantID    int64
	InboundID   int64
	SourceUrl   string
	UrlHash     []byte
	ObjectKey   string
	ContentType string
	ByteSize    int64
}

// ON CONFLICT DO NOTHING: the same message can be passed over twice after a
// restart, and the second run must not fail on a picture already stored.
func (q *Queries) InsertInboundImage(ctx context.Context, arg InsertInboundImageParams) error {
	_, err := q.db.Exec(ctx, insertInboundImage,
		arg.TenantID,
		arg.InboundID,
		arg.SourceUrl,
		arg.UrlHash,
		arg.ObjectKey,
		arg.ContentType,
		arg.ByteSize,
	)
	return err
}

const listImageKeysForPurge = `-- name: ListImageKeysForPurge :many
SELECT object_key FROM email_inbound_images
WHERE tenant_id = $1::bigint
  AND inbound_id = $2::bigint
  AND object_key <> ''
`

type ListImageKeysForPurgeParams struct {
	TenantID  int64
	InboundID int64
}

// The object keys behind one message, read before the row goes. The cascade
// removes the rows; nothing removes the bytes unless we name them first.
func (q *Queries) ListImageKeysForPurge(ctx context.Context, arg ListImageKeysForPurgeParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listImageKeysForPurge, arg.TenantID, arg.InboundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var object_key string
		if err := rows.Scan(&object_key); err != nil {
			return nil, err
		}
		items = append(items, object_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInboundImages = `-- name: ListInboundImages :many
SELECT source_url, object_key, content_type
FROM email_inbound_images
WHERE tenant_id = $1::bigint
  AND inbound_id = $2::bigint
`

type ListInboundImagesParams struct {
	TenantID  int64
	InboundID int64
}

type ListInboundImagesRow struct {
	SourceUrl   string
	ObjectKey   string
	ContentType string
}

// What the read path substitutes into one message's body.
func (q *Queries) ListInboundImages(ctx context.Context, arg ListInboundImagesParams) ([]ListInboundImagesRow, error) {
	rows, err := q.db.Query(ctx, listInboundImages, arg.TenantID, arg.InboundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInboundImagesRow
	for rows.Next() {
		var i ListInboundImagesRow
		if err := rows.Scan(&i.SourceUrl, &i.ObjectKey, &i.ContentType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInboundNeedingImages = `-- name: ListInboundNeedingImages :many

SELECT id, body_html
FROM email_inbound
WHERE tenant_id = $1::bigint
  AND images_cached_at IS NULL
ORDER BY id
LIMIT $2::int
`

type ListInboundNeedingImagesParams struct {
	TenantID int64
	RowLimit int32
}

type ListInboundNeedingImagesRow struct {
	ID       int64
	BodyHtml string
}

// Caching the pictures a received mail points at.
// The work queue for the caching pass, oldest first so a mailbox fills in the
// order it arrived rather than newest-first and then stalling.
//
// Only messages with an HTML body can reference a remote picture, but the
// pass stamps everything it looks at either way — a text-only mail that kept
// coming back would spin the loop for ever.
func (q *Queries) ListInboundNeedingImages(ctx context.Context, arg ListInboundNeedingImagesParams) ([]ListInboundNeedingImagesRow, error) {
	rows, err := q.db.Query(ctx, listInboundNeedingImages, arg.TenantID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInboundNeedingImagesRow
	for rows.Next() {
		var i ListInboundNeedingImagesRow
		if err := rows.Scan(&i.ID, &i.BodyHtml); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadImages = `-- name: ListThreadImages :many
SELECT g.inbound_id, g.source_url, g.object_key, g.content_type
FROM email_inbound_images g
JOIN email_inbound i ON i.id = g.inbound_id AND i.tenant_id = g.tenant_id
WHERE g.tenant_id = $1::bigint
  AND i.owner_id = $2::bigint
  AND i.thread_key = $3::text
`

type ListThreadImagesParams struct {
	TenantID  int64
	OwnerID   int64
	ThreadKey string
}

type ListThreadImagesRow struct {
	InboundID   int64
	SourceUrl   string
	ObjectKey   string
	ContentType string
}

// The same for a whole conversation, in one query rather than one per turn.
// A sixteen-message thread would otherwise be sixteen round trips before the
// first byte reaches the browser.
func (q *Queries) ListThreadImages(ctx context.Context, arg ListThreadImagesParams) ([]ListThreadImagesRow, error) {
	rows, err := q.db.Query(ctx, listThreadImages, arg.TenantID, arg.OwnerID, arg.ThreadKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListThreadImagesRow
	for rows.Next() {
		var i ListThreadImagesRow
		if err := rows.Scan(
			&i.InboundID,
			&i.SourceUrl,
			&i.ObjectKey,
			&i.ContentType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markImagesCached = `-- name: MarkImagesCached :exec
UPDATE email_inbound
SET images_cached_at = now()
WHERE tenant_id = $1::bigint AND id = $2::bigint
`

type MarkImagesCachedParams struct {
	TenantID int64
	ID       int64
}

// Stamped whatever the outcome. A message whose pictures could not be fetched
// has still been looked at, and retrying it on every pass would mean a dead
// host holds up the whole queue.
func (q *Queries) MarkImagesCached(ctx context.Context, arg MarkImagesCachedParams) error {
	_, err := q.db.Exec(ctx, markImagesCached, arg.TenantID, arg.ID)
	return err
}
