// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mailbox.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpSendCounter = `-- name: BumpSendCounter :one
INSERT INTO mail_send_counters (tenant_id, account_id, window_at, sent_count)
VALUES ($1::bigint, $2::bigint,
        date_trunc('hour', now()), 1)
ON CONFLICT (tenant_id, account_id, window_at)
DO UPDATE SET sent_count = mail_send_counters.sent_count + 1
RETURNING sent_count
`

type BumpSendCounterParams struct {
	TenantID  int64
	AccountID int64
}

// Counts one accepted message into the current hour and returns the new
// total. The caller compares it against the quota; going over is possible
// only by the width of one message, which is the right trade against holding
// a lock across a network call to the mail host.
func (q *Queries) BumpSendCounter(ctx context.Context, arg BumpSendCounterParams) (int32, error) {
	row := q.db.QueryRow(ctx, bumpSendCounter, arg.TenantID, arg.AccountID)
	var sent_count int32
	err := row.Scan(&sent_count)
	return sent_count, err
}

const claimFlagOps = `-- name: ClaimFlagOps :many
SELECT id, tenant_id, account_id, employee_id, folder, imap_uid, flag, op, message_id, attempts
FROM mail_flag_ops
WHERE tenant_id = $1::bigint
  AND next_try_at <= now()
ORDER BY next_try_at
LIMIT $2::int
FOR UPDATE SKIP LOCKED
`

type ClaimFlagOpsParams struct {
	TenantID int64
	RowLimit int32
}

type ClaimFlagOpsRow struct {
	ID         int64
	TenantID   int64
	AccountID  int64
	EmployeeID int64
	Folder     string
	ImapUid    int64
	Flag       string
	Op         string
	MessageID  string
	Attempts   int32
}

// Due work, oldest first, locked so two workers cannot publish the same
// change twice. SKIP LOCKED rather than waiting: another worker holding a row
// means it is already being handled.
func (q *Queries) ClaimFlagOps(ctx context.Context, arg ClaimFlagOpsParams) ([]ClaimFlagOpsRow, error) {
	rows, err := q.db.Query(ctx, claimFlagOps, arg.TenantID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimFlagOpsRow
	for rows.Next() {
		var i ClaimFlagOpsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AccountID,
			&i.EmployeeID,
			&i.Folder,
			&i.ImapUid,
			&i.Flag,
			&i.Op,
			&i.MessageID,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countFolder = `-- name: CountFolder :one
SELECT count(*)::bigint FROM email_inbound
WHERE tenant_id = $1::bigint
  AND account_id = $2::bigint
  AND folder = $3::text
`

type CountFolderParams struct {
	TenantID  int64
	AccountID int64
	Folder    string
}

// How much of a folder we hold, for the backfill cap.
func (q *Queries) CountFolder(ctx context.Context, arg CountFolderParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFolder, arg.TenantID, arg.AccountID, arg.Folder)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countInbound = `-- name: CountInbound :one
SELECT count(*)::bigint FROM email_inbound
WHERE tenant_id = $1::bigint
  AND owner_id = $2::bigint
  AND CASE $3::text
        WHEN 'JUNK'  THEN folder = 'JUNK' AND NOT not_junk
        -- The trash holds mail deleted from anywhere, junk included.
        WHEN 'TRASH' THEN folder IN ('INBOX', 'JUNK')
        ELSE (folder = 'INBOX' OR (folder = 'JUNK' AND not_junk))
      END
  AND NOT is_bounce
  AND CASE $3::text
        WHEN 'STARRED' THEN is_starred AND deleted_at IS NULL
        WHEN 'ARCHIVE' THEN archived_at IS NOT NULL AND deleted_at IS NULL
        WHEN 'TRASH'   THEN deleted_at IS NOT NULL
        WHEN 'JUNK'    THEN deleted_at IS NULL
        ELSE archived_at IS NULL AND deleted_at IS NULL
      END
  AND ($4::text = ''
       OR subject ILIKE '%' || $4::text || '%'
       OR from_email ILIKE '%' || $4::text || '%'
       OR from_name ILIKE '%' || $4::text || '%')
`

type CountInboundParams struct {
	TenantID int64
	OwnerID  int64
	View     string
	Keyword  string
}

func (q *Queries) CountInbound(ctx context.Context, arg CountInboundParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInbound,
		arg.TenantID,
		arg.OwnerID,
		arg.View,
		arg.Keyword,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countInboundThreads = `-- name: CountInboundThreads :one
SELECT count(DISTINCT coalesce(nullif(thread_key, ''), 'm:' || id::text))::bigint
FROM email_inbound
WHERE tenant_id = $1::bigint
  AND owner_id = $2::bigint
  AND CASE $3::text
        WHEN 'JUNK'  THEN folder = 'JUNK' AND NOT not_junk
        -- The trash holds mail deleted from anywhere, junk included.
        WHEN 'TRASH' THEN folder IN ('INBOX', 'JUNK')
        ELSE (folder = 'INBOX' OR (folder = 'JUNK' AND not_junk))
      END
  AND NOT is_bounce
  AND CASE $3::text
        WHEN 'STARRED' THEN is_starred AND deleted_at IS NULL
        WHEN 'ARCHIVE' THEN archived_at IS NOT NULL AND deleted_at IS NULL
        WHEN 'TRASH'   THEN deleted_at IS NOT NULL
        WHEN 'JUNK'    THEN deleted_at IS NULL
        ELSE archived_at IS NULL AND deleted_at IS NULL
      END
  AND ($4::text = ''
       OR subject ILIKE '%' || $4::text || '%'
       OR from_email ILIKE '%' || $4::text || '%'
       OR from_name ILIKE '%' || $4::text || '%')
`

type CountInboundThreadsParams struct {
	TenantID int64
	OwnerID  int64
	View     string
	Keyword  string
}

// Conversations, not messages: the pager has to count what the list shows.
func (q *Queries) CountInboundThreads(ctx context.Context, arg CountInboundThreadsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInboundThreads,
		arg.TenantID,
		arg.OwnerID,
		arg.View,
		arg.Keyword,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countPendingFlagOps = `-- name: CountPendingFlagOps :one
SELECT count(*)::bigint FROM mail_flag_ops
WHERE tenant_id = $1::bigint
  AND account_id = $2::bigint
`

type CountPendingFlagOpsParams struct {
	TenantID  int64
	AccountID int64
}

func (q *Queries) CountPendingFlagOps(ctx context.Context, arg CountPendingFlagOpsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingFlagOps, arg.TenantID, arg.AccountID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countSentInWindow = `-- name: CountSentInWindow :one
SELECT
    coalesce(sum(sent_count) FILTER (WHERE window_at >= date_trunc('hour', now())), 0)::int AS this_hour,
    coalesce(sum(sent_count) FILTER (WHERE window_at >= now() - interval '24 hours'), 0)::int AS last_24h
FROM mail_send_counters
WHERE tenant_id = $1::bigint
  AND account_id = $2::bigint
`

type CountSentInWindowParams struct {
	TenantID  int64
	AccountID int64
}

type CountSentInWindowRow struct {
	ThisHour int32
	Last24h  int32
}

// Hour and day totals in one round trip, so the pacing check before a send
// is a single query rather than two.
func (q *Queries) CountSentInWindow(ctx context.Context, arg CountSentInWindowParams) (CountSentInWindowRow, error) {
	row := q.db.QueryRow(ctx, countSentInWindow, arg.TenantID, arg.AccountID)
	var i CountSentInWindowRow
	err := row.Scan(&i.ThisHour, &i.Last24h)
	return i, err
}

const countSentUnified = `-- name: CountSentUnified :one
WITH erp AS (
    SELECT m.to_email, m.subject, coalesce(m.sent_at, m.queued_at) AS at
    FROM email_messages m
    WHERE m.tenant_id = $2::bigint
      AND m.sender_id = $3::bigint
      AND m.sent_at IS NOT NULL
), host AS (
    SELECT i.to_email, i.subject
    FROM email_inbound i
    WHERE i.tenant_id = $2::bigint
      AND i.owner_id = $3::bigint
      AND i.folder = 'SENT'
      AND NOT EXISTS (
          SELECT 1 FROM erp e
          WHERE lower(e.to_email) = lower(i.to_email)
            AND e.subject = i.subject
            AND abs(extract(epoch FROM (e.at - coalesce(i.sent_at, i.received_at)))) < 600
      )
)
SELECT count(*)::bigint FROM (
    SELECT to_email, subject FROM erp
    UNION ALL
    SELECT to_email, subject FROM host
) u
WHERE ($1::text = ''
       OR subject ILIKE '%' || $1::text || '%'
       OR to_email ILIKE '%' || $1::text || '%')
`

type CountSentUnifiedParams struct {
	Keyword  string
	TenantID int64
	OwnerID  int64
}

// The same set, counted. Repeats the CTEs rather than sharing them because
// the pager has to agree with the list, and a count that skipped the dedup
// would promise pages that are not there.
func (q *Queries) CountSentUnified(ctx context.Context, arg CountSentUnifiedParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSentUnified, arg.Keyword, arg.TenantID, arg.OwnerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countUnread = `-- name: CountUnread :one
SELECT count(*)::bigint FROM email_inbound
WHERE tenant_id = $1::bigint
  AND owner_id = $2::bigint
  AND (folder = 'INBOX' OR (folder = 'JUNK' AND not_junk))
  AND NOT is_bounce AND NOT is_read
  AND archived_at IS NULL AND deleted_at IS NULL
`

type CountUnreadParams struct {
	TenantID int64
	OwnerID  int64
}

// The badge counts what the inbox proper shows: archived and trashed mail
// has been dealt with, so it stops demanding attention.
func (q *Queries) CountUnread(ctx context.Context, arg CountUnreadParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnread, arg.TenantID, arg.OwnerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteFlagOp = `-- name: DeleteFlagOp :exec
DELETE FROM mail_flag_ops WHERE id = $1::bigint
`

func (q *Queries) DeleteFlagOp(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteFlagOp, id)
	return err
}

const deleteInboundForAccount = `-- name: DeleteInboundForAccount :exec
DELETE FROM email_inbound
WHERE tenant_id = $1::bigint AND account_id = $2::bigint
`

type DeleteInboundForAccountParams struct {
	TenantID  int64
	AccountID int64
}

// Rebinding to a different mailbox makes every stored message and UID
// meaningless; attachments go with their messages via the cascade.
func (q *Queries) DeleteInboundForAccount(ctx context.Context, arg DeleteInboundForAccountParams) error {
	_, err := q.db.Exec(ctx, deleteInboundForAccount, arg.TenantID, arg.AccountID)
	return err
}

const deleteSyncStateForAccount = `-- name: DeleteSyncStateForAccount :exec
DELETE FROM mail_sync_state
WHERE tenant_id = $1::bigint AND account_id = $2::bigint
`

type DeleteSyncStateForAccountParams struct {
	TenantID  int64
	AccountID int64
}

func (q *Queries) DeleteSyncStateForAccount(ctx context.Context, arg DeleteSyncStateForAccountParams) error {
	_, err := q.db.Exec(ctx, deleteSyncStateForAccount, arg.TenantID, arg.AccountID)
	return err
}

const enqueueFlagOp = `-- name: EnqueueFlagOp :exec
INSERT INTO mail_flag_ops (tenant_id, account_id, employee_id, folder, imap_uid, flag, op, message_id)
VALUES (
    $1::bigint, $2::bigint,
    $3::bigint,
    $4::text, $5::bigint,
    $6::text, $7::text, $8::text
)
ON CONFLICT (tenant_id, account_id, folder, imap_uid, flag) DO UPDATE SET
    op = excluded.op,
    message_id = excluded.message_id,
    attempts = 0,
    last_error = '',
    next_try_at = now()
`

type EnqueueFlagOpParams struct {
	TenantID   int64
	AccountID  int64
	EmployeeID int64
	Folder     string
	ImapUid    int64
	Flag       string
	Op         string
	MessageID  string
}

// The intent to publish one flag change. Conflicting intents collapse: the
// newest wins, because that is the state the person last chose.
func (q *Queries) EnqueueFlagOp(ctx context.Context, arg EnqueueFlagOpParams) error {
	_, err := q.db.Exec(ctx, enqueueFlagOp,
		arg.TenantID,
		arg.AccountID,
		arg.EmployeeID,
		arg.Folder,
		arg.ImapUid,
		arg.Flag,
		arg.Op,
		arg.MessageID,
	)
	return err
}

const failFlagOp = `-- name: FailFlagOp :exec
UPDATE mail_flag_ops
SET attempts = attempts + 1,
    last_error = $1::text,
    next_try_at = now() + (least(attempts + 1, 6) * interval '2 minutes')
WHERE id = $2::bigint
`

type FailFlagOpParams struct {
	LastError string
	ID        int64
}

// Backs off so a mailbox that is refusing connections is retried at a
// widening interval rather than hammered every cycle.
func (q *Queries) FailFlagOp(ctx context.Context, arg FailFlagOpParams) error {
	_, err := q.db.Exec(ctx, failFlagOp, arg.LastError, arg.ID)
	return err
}

const findMessageByKey = `-- name: FindMessageByKey :one
SELECT id, message_key::text AS message_key, thread_key, to_email, campaign_id, sender_id
FROM email_messages
WHERE tenant_id = $1::bigint
  AND message_key::text = $2::text
`

type FindMessageByKeyParams struct {
	TenantID   int64
	MessageKey string
}

type FindMessageByKeyRow struct {
	ID         int64
	MessageKey string
	ThreadKey  string
	ToEmail    string
	CampaignID *int64
	SenderID   int64
}

func (q *Queries) FindMessageByKey(ctx context.Context, arg FindMessageByKeyParams) (FindMessageByKeyRow, error) {
	row := q.db.QueryRow(ctx, findMessageByKey, arg.TenantID, arg.MessageKey)
	var i FindMessageByKeyRow
	err := row.Scan(
		&i.ID,
		&i.MessageKey,
		&i.ThreadKey,
		&i.ToEmail,
		&i.CampaignID,
		&i.SenderID,
	)
	return i, err
}

const findMessageByKeyAnyTenant = `-- name: FindMessageByKeyAnyTenant :one
SELECT id, tenant_id, to_email FROM email_messages
WHERE message_key::text = $1::text
`

type FindMessageByKeyAnyTenantRow struct {
	ID       int64
	TenantID int64
	ToEmail  string
}

// The tracking pixel is fetched by a recipient's mail client, which carries
// no session and therefore no tenant. The key is a random UUID, so it is the
// only identifier available — and knowing one tells you nothing beyond the
// message it belongs to.
func (q *Queries) FindMessageByKeyAnyTenant(ctx context.Context, messageKey string) (FindMessageByKeyAnyTenantRow, error) {
	row := q.db.QueryRow(ctx, findMessageByKeyAnyTenant, messageKey)
	var i FindMessageByKeyAnyTenantRow
	err := row.Scan(&i.ID, &i.TenantID, &i.ToEmail)
	return i, err
}

const getInbound = `-- name: GetInbound :one
SELECT id, account_id, owner_id, message_id, thread_key, reply_to_id,
       from_email, from_name, to_email, subject, body_html, body_text,
       raw_key, raw_size, is_read, has_attachments, received_at, sent_at
FROM email_inbound
WHERE tenant_id = $1::bigint AND id = $2::bigint
`

type GetInboundParams struct {
	TenantID int64
	ID       int64
}

type GetInboundRow struct {
	ID             int64
	AccountID      int64
	OwnerID        int64
	MessageID      string
	ThreadKey      string
	ReplyToID      *int64
	FromEmail      string
	FromName       string
	ToEmail        string
	Subject        string
	BodyHtml       string
	BodyText       string
	RawKey         string
	RawSize        int64
	IsRead         bool
	HasAttachments bool
	ReceivedAt     pgtype.Timestamptz
	SentAt         pgtype.Timestamptz
}

func (q *Queries) GetInbound(ctx context.Context, arg GetInboundParams) (GetInboundRow, error) {
	row := q.db.QueryRow(ctx, getInbound, arg.TenantID, arg.ID)
	var i GetInboundRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.OwnerID,
		&i.MessageID,
		&i.ThreadKey,
		&i.ReplyToID,
		&i.FromEmail,
		&i.FromName,
		&i.ToEmail,
		&i.Subject,
		&i.BodyHtml,
		&i.BodyText,
		&i.RawKey,
		&i.RawSize,
		&i.IsRead,
		&i.HasAttachments,
		&i.ReceivedAt,
		&i.SentAt,
	)
	return i, err
}

const getInboundForCompose = `-- name: GetInboundForCompose :one
SELECT id, owner_id, message_id, references_ids, thread_key
FROM email_inbound
WHERE tenant_id = $1::bigint AND id = $2::bigint
`

type GetInboundForComposeParams struct {
	TenantID int64
	ID       int64
}

type GetInboundForComposeRow struct {
	ID            int64
	OwnerID       int64
	MessageID     string
	ReferencesIds string
	ThreadKey     string
}

// The reply/forward context: the owner (for the caller check), the
// Message-ID being answered, the chain above it, and the thread this
// conversation lives in.
func (q *Queries) GetInboundForCompose(ctx context.Context, arg GetInboundForComposeParams) (GetInboundForComposeRow, error) {
	row := q.db.QueryRow(ctx, getInboundForCompose, arg.TenantID, arg.ID)
	var i GetInboundForComposeRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.MessageID,
		&i.ReferencesIds,
		&i.ThreadKey,
	)
	return i, err
}

const getInboundForPurge = `-- name: GetInboundForPurge :one
SELECT id, raw_key, account_id, folder, imap_uid, message_id
FROM email_inbound
WHERE tenant_id = $1::bigint
  AND owner_id = $2::bigint
  AND id = $3::bigint
  AND deleted_at IS NOT NULL
`

type GetInboundForPurgeParams struct {
	TenantID int64
	OwnerID  int64
	ID       int64
}

type GetInboundForPurgeRow struct {
	ID        int64
	RawKey    string
	AccountID int64
	Folder    string
	ImapUid   int64
	MessageID string
}

// Only a mail already in the trash qualifies: permanent deletion is a second
// step after a soft delete, never a first action on a live mail.
func (q *Queries) GetInboundForPurge(ctx context.Context, arg GetInboundForPurgeParams) (GetInboundForPurgeRow, error) {
	row := q.db.QueryRow(ctx, getInboundForPurge, arg.TenantID, arg.OwnerID, arg.ID)
	var i GetInboundForPurgeRow
	err := row.Scan(
		&i.ID,
		&i.RawKey,
		&i.AccountID,
		&i.Folder,
		&i.ImapUid,
		&i.MessageID,
	)
	return i, err
}

const getMailAccountSecret = `-- name: GetMailAccountSecret :one
SELECT id, email, username, auth_kind, secret_enc, oauth_refresh_enc, key_version, is_active
FROM mail_accounts
WHERE tenant_id = $1::bigint
  AND employee_id = $2::bigint
`

type GetMailAccountSecretParams struct {
	TenantID   int64
	EmployeeID int64
}

type GetMailAccountSecretRow struct {
	ID              int64
	Email           string
	Username        string
	AuthKind        string
	SecretEnc       []byte
	OauthRefreshEnc []byte
	KeyVersion      int32
	IsActive        bool
}

// The only query that returns ciphertext. Used by the sender and the IMAP
// sync, never by anything that answers an HTTP request.
func (q *Queries) GetMailAccountSecret(ctx context.Context, arg GetMailAccountSecretParams) (GetMailAccountSecretRow, error) {
	row := q.db.QueryRow(ctx, getMailAccountSecret, arg.TenantID, arg.EmployeeID)
	var i GetMailAccountSecretRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.AuthKind,
		&i.SecretEnc,
		&i.OauthRefreshEnc,
		&i.KeyVersion,
		&i.IsActive,
	)
	return i, err
}

const getMailHost = `-- name: GetMailHost :one
SELECT domain, smtp_host, smtp_port, smtp_security,
       imap_host, imap_port, imap_security,
       hourly_quota, daily_quota
FROM mail_hosts
WHERE tenant_id = $1::bigint
`

type GetMailHostRow struct {
	Domain       string
	SmtpHost     string
	SmtpPort     int32
	SmtpSecurity string
	ImapHost     string
	ImapPort     int32
	ImapSecurity string
	HourlyQuota  int32
	DailyQuota   int32
}

func (q *Queries) GetMailHost(ctx context.Context, tenantID int64) (GetMailHostRow, error) {
	row := q.db.QueryRow(ctx, getMailHost, tenantID)
	var i GetMailHostRow
	err := row.Scan(
		&i.Domain,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpSecurity,
		&i.ImapHost,
		&i.ImapPort,
		&i.ImapSecurity,
		&i.HourlyQuota,
		&i.DailyQuota,
	)
	return i, err
}

const getMyMailAccount = `-- name: GetMyMailAccount :one
SELECT id, email, username, auth_kind, verified_at, last_error, is_active, updated_at
FROM mail_accounts
WHERE tenant_id = $1::bigint
  AND employee_id = $2::bigint
`

type GetMyMailAccountParams struct {
	TenantID   int64
	EmployeeID int64
}

type GetMyMailAccountRow struct {
	ID         int64
	Email      string
	Username   string
	AuthKind   string
	VerifiedAt pgtype.Timestamptz
	LastError  string
	IsActive   bool
	UpdatedAt  pgtype.Timestamptz
}

// Deliberately does NOT select secret_enc. This is what the settings page
// reads, and a credential that is never returned to a browser cannot be
// leaked by one.
func (q *Queries) GetMyMailAccount(ctx context.Context, arg GetMyMailAccountParams) (GetMyMailAccountRow, error) {
	row := q.db.QueryRow(ctx, getMyMailAccount, arg.TenantID, arg.EmployeeID)
	var i GetMyMailAccountRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.AuthKind,
		&i.VerifiedAt,
		&i.LastError,
		&i.IsActive,
		&i.UpdatedAt,
	)
	return i, err
}

const getSyncState = `-- name: GetSyncState :one
SELECT uid_validity, last_uid, low_uid, last_synced_at, last_error
FROM mail_sync_state
WHERE tenant_id = $1::bigint
  AND account_id = $2::bigint
  AND folder = $3::text
`

type GetSyncStateParams struct {
	TenantID  int64
	AccountID int64
	Folder    string
}

type GetSyncStateRow struct {
	UidValidity  int64
	LastUid      int64
	LowUid       int64
	LastSyncedAt pgtype.Timestamptz
	LastError    string
}

func (q *Queries) GetSyncState(ctx context.Context, arg GetSyncStateParams) (GetSyncStateRow, error) {
	row := q.db.QueryRow(ctx, getSyncState, arg.TenantID, arg.AccountID, arg.Folder)
	var i GetSyncStateRow
	err := row.Scan(
		&i.UidValidity,
		&i.LastUid,
		&i.LowUid,
		&i.LastSyncedAt,
		&i.LastError,
	)
	return i, err
}

const insertInbound = `-- name: InsertInbound :one
INSERT INTO email_inbound (
    tenant_id, account_id, owner_id, folder, imap_uid,
    message_id, in_reply_to, references_ids, thread_key, reply_to_id,
    from_email, from_name, to_email, subject, body_html, body_text, snippet,
    raw_key, raw_size, is_bounce, has_attachments, is_read, sent_at, received_at
) VALUES (
    $1::bigint, $2::bigint, $3::bigint,
    $4::text, $5::bigint,
    $6::text, $7::text, $8::text,
    $9::text, $10::bigint,
    $11::text, $12::text, $13::text,
    $14::text, $15::text, $16::text,
    $17::text, $18::text, $19::bigint,
    $20::boolean, $21::boolean,
    $22::boolean,
    $23::timestamptz,
    -- When the mail host says it arrived, not when we happened to fetch it.
    -- Stamping now() here made 收到时间 mean "last time this row was written",
    -- so a resync rewrote every timestamp in the mailbox to the same minute.
    coalesce($24::timestamptz, now())
)
ON CONFLICT (tenant_id, account_id, folder, imap_uid) DO NOTHING
RETURNING id
`

type InsertInboundParams struct {
	TenantID       int64
	AccountID      int64
	OwnerID        int64
	Folder         string
	ImapUid        int64
	MessageID      string
	InReplyTo      string
	ReferencesIds  string
	ThreadKey      string
	ReplyToID      *int64
	FromEmail      string
	FromName       string
	ToEmail        string
	Subject        string
	BodyHtml       string
	BodyText       string
	Snippet        string
	RawKey         string
	RawSize        int64
	IsBounce       bool
	HasAttachments bool
	IsRead         bool
	SentAt         pgtype.Timestamptz
	ReceivedAt     pgtype.Timestamptz
}

// ON CONFLICT DO NOTHING plus a returned id of 0 is how a repeated fetch of
// the same UID becomes a no-op rather than a duplicate row or an error.
func (q *Queries) InsertInbound(ctx context.Context, arg InsertInboundParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertInbound,
		arg.TenantID,
		arg.AccountID,
		arg.OwnerID,
		arg.Folder,
		arg.ImapUid,
		arg.MessageID,
		arg.InReplyTo,
		arg.ReferencesIds,
		arg.ThreadKey,
		arg.ReplyToID,
		arg.FromEmail,
		arg.FromName,
		arg.ToEmail,
		arg.Subject,
		arg.BodyHtml,
		arg.BodyText,
		arg.Snippet,
		arg.RawKey,
		arg.RawSize,
		arg.IsBounce,
		arg.HasAttachments,
		arg.IsRead,
		arg.SentAt,
		arg.ReceivedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertInboundAttachment = `-- name: InsertInboundAttachment :exec
INSERT INTO email_inbound_attachments (
    tenant_id, inbound_id, file_name, content_type, file_size, file_key
) VALUES (
    $1::bigint, $2::bigint, $3::text,
    $4::text, $5::bigint, $6::text
)
`

type InsertInboundAttachmentParams struct {
	TenantID    int64
	InboundID   int64
	FileName    string
	ContentType string
	FileSize    int64
	FileKey     string
}

func (q *Queries) InsertInboundAttachment(ctx context.Context, arg InsertInboundAttachmentParams) error {
	_, err := q.db.Exec(ctx, insertInboundAttachment,
		arg.TenantID,
		arg.InboundID,
		arg.FileName,
		arg.ContentType,
		arg.FileSize,
		arg.FileKey,
	)
	return err
}

const listExpiredTrash = `-- name: ListExpiredTrash :many
SELECT id, owner_id, raw_key, account_id, folder, imap_uid, message_id
FROM email_inbound
WHERE tenant_id = $1::bigint
  AND deleted_at IS NOT NULL
  AND deleted_at < $2::timestamptz
ORDER BY id
LIMIT $3::int
`

type ListExpiredTrashParams struct {
	TenantID int64
	Cutoff   pgtype.Timestamptz
	RowLimit int32
}

type ListExpiredTrashRow struct {
	ID        int64
	OwnerID   int64
	RawKey    string
	AccountID int64
	Folder    string
	ImapUid   int64
	MessageID string
}

// Trash old enough to clear out by itself. Tenant-wide and owner-agnostic
// because the sweeper runs for everybody at once; the owner comes back on
// each row so the delete stays owner-scoped like every other one.
func (q *Queries) ListExpiredTrash(ctx context.Context, arg ListExpiredTrashParams) ([]ListExpiredTrashRow, error) {
	rows, err := q.db.Query(ctx, listExpiredTrash, arg.TenantID, arg.Cutoff, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiredTrashRow
	for rows.Next() {
		var i ListExpiredTrashRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.RawKey,
			&i.AccountID,
			&i.Folder,
			&i.ImapUid,
			&i.MessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInbound = `-- name: ListInbound :many
SELECT id, from_email, from_name, subject, snippet, thread_key,
       is_read, is_starred, has_attachments, received_at, sent_at
FROM email_inbound
WHERE tenant_id = $1::bigint
  AND owner_id = $2::bigint
  AND CASE $3::text
        WHEN 'JUNK'  THEN folder = 'JUNK' AND NOT not_junk
        -- The trash holds mail deleted from anywhere, junk included.
        WHEN 'TRASH' THEN folder IN ('INBOX', 'JUNK')
        ELSE (folder = 'INBOX' OR (folder = 'JUNK' AND not_junk))
      END
  AND NOT is_bounce
  AND CASE $3::text
        WHEN 'STARRED' THEN is_starred AND deleted_at IS NULL
        WHEN 'ARCHIVE' THEN archived_at IS NOT NULL AND deleted_at IS NULL
        WHEN 'TRASH'   THEN deleted_at IS NOT NULL
        WHEN 'JUNK'    THEN deleted_at IS NULL
        ELSE archived_at IS NULL AND deleted_at IS NULL
      END
  AND ($4::text = ''
       OR subject ILIKE '%' || $4::text || '%'
       OR from_email ILIKE '%' || $4::text || '%'
       OR from_name ILIKE '%' || $4::text || '%')
ORDER BY coalesce(sent_at, received_at) DESC
LIMIT $6::int OFFSET $5::int
`

type ListInboundParams struct {
	TenantID  int64
	OwnerID   int64
	View      string
	Keyword   string
	RowOffset int32
	RowLimit  int32
}

type ListInboundRow struct {
	ID             int64
	FromEmail      string
	FromName       string
	Subject        string
	Snippet        string
	ThreadKey      string
	IsRead         bool
	IsStarred      bool
	HasAttachments bool
	ReceivedAt     pgtype.Timestamptz
	SentAt         pgtype.Timestamptz
}

// A bounce is machinery, not correspondence, so it is kept out of the inbox
// and surfaced through the needs-attention queue instead.
// The view decides which slice of the mailbox this is: the inbox proper
// (not archived, not trashed), starred (wherever it lives, except trash),
// the archive, or the trash.
//
// Every view but the trash is scoped to the inbox — junk is its own place and
// only rejoins the mailbox once somebody rescues it. The trash is the one
// exception, and has to be: mail deleted out of the junk folder is still
// deleted mail. Scoping the trash the same way as the rest left it invisible
// — soft-deleted in the database, absent from every screen, and plainly
// sitting in the host's own trash, which reads as the ERP having lost it.
// Emptying the trash purged those rows regardless, so the count above the
// list and the number the button deleted disagreed.
func (q *Queries) ListInbound(ctx context.Context, arg ListInboundParams) ([]ListInboundRow, error) {
	rows, err := q.db.Query(ctx, listInbound,
		arg.TenantID,
		arg.OwnerID,
		arg.View,
		arg.Keyword,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInboundRow
	for rows.Next() {
		var i ListInboundRow
		if err := rows.Scan(
			&i.ID,
			&i.FromEmail,
			&i.FromName,
			&i.Subject,
			&i.Snippet,
			&i.ThreadKey,
			&i.IsRead,
			&i.IsStarred,
			&i.HasAttachments,
			&i.ReceivedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInboundAttachments = `-- name: ListInboundAttachments :many
SELECT id, file_name, content_type, file_size, file_key
FROM email_inbound_attachments
WHERE tenant_id = $1::bigint
  AND inbound_id = $2::bigint
ORDER BY id
`

type ListInboundAttachmentsParams struct {
	TenantID  int64
	InboundID int64
}

type ListInboundAttachmentsRow struct {
	ID          int64
	FileName    string
	ContentType string
	FileSize    int64
	FileKey     string
}

func (q *Queries) ListInboundAttachments(ctx context.Context, arg ListInboundAttachmentsParams) ([]ListInboundAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, listInboundAttachments, arg.TenantID, arg.InboundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInboundAttachmentsRow
	for rows.Next() {
		var i ListInboundAttachmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.ContentType,
			&i.FileSize,
			&i.FileKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInboundThreads = `-- name: ListInboundThreads :many
WITH visible AS (
    SELECT id, from_email, from_name, subject, snippet, thread_key,
           is_read, is_starred, has_attachments, received_at, sent_at,
           coalesce(nullif(thread_key, ''), 'm:' || id::text) AS group_key,
           received_at AS at
    FROM email_inbound
    WHERE tenant_id = $4::bigint
      AND owner_id = $5::bigint
      AND CASE $6::text
            WHEN 'JUNK'  THEN folder = 'JUNK' AND NOT not_junk
            -- The trash holds mail deleted from anywhere, junk included.
            WHEN 'TRASH' THEN folder IN ('INBOX', 'JUNK')
            ELSE (folder = 'INBOX' OR (folder = 'JUNK' AND not_junk))
          END
      AND NOT is_bounce
      AND CASE $6::text
            WHEN 'STARRED' THEN is_starred AND deleted_at IS NULL
            WHEN 'ARCHIVE' THEN archived_at IS NOT NULL AND deleted_at IS NULL
            WHEN 'TRASH'   THEN deleted_at IS NOT NULL
            WHEN 'JUNK'    THEN deleted_at IS NULL
            ELSE archived_at IS NULL AND deleted_at IS NULL
          END
      AND ($7::text = ''
           OR subject ILIKE '%' || $7::text || '%'
           OR from_email ILIKE '%' || $7::text || '%'
           OR from_name ILIKE '%' || $7::text || '%')
), ranked AS (
    SELECT visible.id, visible.from_email, visible.from_name, visible.subject, visible.snippet, visible.thread_key, visible.is_read, visible.is_starred, visible.has_attachments, visible.received_at, visible.sent_at, visible.group_key, visible.at,
           row_number() OVER (PARTITION BY group_key ORDER BY at DESC, id DESC) AS rn,
           count(*)          OVER (PARTITION BY group_key) AS thread_count,
           bool_or(NOT is_read)      OVER (PARTITION BY group_key) AS any_unread,
           bool_or(is_starred)       OVER (PARTITION BY group_key) AS any_starred,
           bool_or(has_attachments)  OVER (PARTITION BY group_key) AS any_attachment
    FROM visible
)
SELECT id, from_email, from_name, subject, snippet, thread_key,
       (NOT any_unread)::boolean   AS is_read,
       any_starred::boolean        AS is_starred,
       any_attachment::boolean     AS has_attachments,
       received_at, sent_at,
       thread_count::int           AS thread_count
FROM ranked
WHERE rn = 1
  -- Row comparison, so ties on the timestamp fall back to the id and no two
  -- conversations can ever occupy the same cursor position.
  AND ($1::timestamptz IS NULL
       OR (at, id) < ($1::timestamptz, $2::bigint))
ORDER BY at DESC, id DESC
LIMIT $3::int
`

type ListInboundThreadsParams struct {
	CursorAt pgtype.Timestamptz
	CursorID int64
	RowLimit int32
	TenantID int64
	OwnerID  int64
	View     string
	Keyword  string
}

type ListInboundThreadsRow struct {
	ID             int64
	FromEmail      string
	FromName       string
	Subject        string
	Snippet        string
	ThreadKey      string
	IsRead         bool
	IsStarred      bool
	HasAttachments bool
	ReceivedAt     pgtype.Timestamptz
	SentAt         pgtype.Timestamptz
	ThreadCount    int32
}

// The same slice of the mailbox as ListInbound, but one row per conversation
// instead of one row per message — Gmail's list, where "客户回了三次" is one
// line with a (3) rather than three lines to scan past.
//
// Grouping happens inside the filtered set, which is what makes a thread
// appear in exactly the views it belongs to: archive one conversation and it
// leaves the inbox list whole, rather than the archived message vanishing and
// its siblings staying behind.
//
// A message with no thread key is its own conversation ('m:<id>'), so mail
// that never got a reply is not silently merged with other loose mail.
// The row stands for the whole conversation: the newest message supplies the
// text and the time, the flags are the conversation's own. Unread if ANY
// message is unread — a thread with an unanswered question in it must not
// look handled because the last line happened to be read.
//
// Keyset, not OFFSET: the page starts strictly after the last row of the
// previous one, so mail arriving mid-read cannot push a conversation across
// the page boundary and make it appear twice or not at all, and page 50
// costs the same as page 2. The price is that there is no jumping to page N
// — the same trade Gmail makes with its 上一页 / 下一页.
func (q *Queries) ListInboundThreads(ctx context.Context, arg ListInboundThreadsParams) ([]ListInboundThreadsRow, error) {
	rows, err := q.db.Query(ctx, listInboundThreads,
		arg.CursorAt,
		arg.CursorID,
		arg.RowLimit,
		arg.TenantID,
		arg.OwnerID,
		arg.View,
		arg.Keyword,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInboundThreadsRow
	for rows.Next() {
		var i ListInboundThreadsRow
		if err := rows.Scan(
			&i.ID,
			&i.FromEmail,
			&i.FromName,
			&i.Subject,
			&i.Snippet,
			&i.ThreadKey,
			&i.IsRead,
			&i.IsStarred,
			&i.HasAttachments,
			&i.ReceivedAt,
			&i.SentAt,
			&i.ThreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentForReconcile = `-- name: ListRecentForReconcile :many
SELECT id, imap_uid, message_id, is_read, is_starred, archived_at, deleted_at
FROM email_inbound
WHERE tenant_id = $1::bigint
  AND account_id = $2::bigint
  AND folder = $3::text
ORDER BY imap_uid DESC
LIMIT $4::int
`

type ListRecentForReconcileParams struct {
	TenantID  int64
	AccountID int64
	Folder    string
	RowLimit  int32
}

type ListRecentForReconcileRow struct {
	ID         int64
	ImapUid    int64
	MessageID  string
	IsRead     bool
	IsStarred  bool
	ArchivedAt pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
}

// The newest slice of one folder with everything the reconcile pass needs to
// decide what happened to each message.
func (q *Queries) ListRecentForReconcile(ctx context.Context, arg ListRecentForReconcileParams) ([]ListRecentForReconcileRow, error) {
	rows, err := q.db.Query(ctx, listRecentForReconcile,
		arg.TenantID,
		arg.AccountID,
		arg.Folder,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentForReconcileRow
	for rows.Next() {
		var i ListRecentForReconcileRow
		if err := rows.Scan(
			&i.ID,
			&i.ImapUid,
			&i.MessageID,
			&i.IsRead,
			&i.IsStarred,
			&i.ArchivedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentUIDs = `-- name: ListRecentUIDs :many
SELECT imap_uid, is_read, is_starred
FROM email_inbound
WHERE tenant_id = $1::bigint
  AND account_id = $2::bigint
  AND folder = $3::text
ORDER BY imap_uid DESC
LIMIT $4::int
`

type ListRecentUIDsParams struct {
	TenantID  int64
	AccountID int64
	Folder    string
	RowLimit  int32
}

type ListRecentUIDsRow struct {
	ImapUid   int64
	IsRead    bool
	IsStarred bool
}

// The newest slice of one folder, for reconciling flags against the host.
// Bounded: re-reading a whole mailbox every cycle would cost more than the
// disagreement it is looking for.
func (q *Queries) ListRecentUIDs(ctx context.Context, arg ListRecentUIDsParams) ([]ListRecentUIDsRow, error) {
	rows, err := q.db.Query(ctx, listRecentUIDs,
		arg.TenantID,
		arg.AccountID,
		arg.Folder,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentUIDsRow
	for rows.Next() {
		var i ListRecentUIDsRow
		if err := rows.Scan(&i.ImapUid, &i.IsRead, &i.IsStarred); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSentUnified = `-- name: ListSentUnified :many


WITH erp AS (
    SELECT m.id, m.to_email, m.to_name, m.subject,
           left(coalesce(nullif(m.body_text, ''), CASE WHEN m.body_format = 'HTML' THEN '' ELSE m.body END), 200) AS snippet,
           coalesce(m.sent_at, m.queued_at) AS at,
           m.status,
           m.opened_at,
           EXISTS (
               SELECT 1 FROM email_attachments a
               WHERE a.tenant_id = m.tenant_id AND a.campaign_id = m.campaign_id
           ) AS has_attachments
    FROM email_messages m
    WHERE m.tenant_id = $4::bigint
      AND m.sender_id = $5::bigint
      -- Sent means sent. A queued or failed one is not in anybody's Sent
      -- folder yet, and the needs-attention view is where those belong.
      AND m.sent_at IS NOT NULL
), host AS (
    SELECT i.id, i.to_email, '' AS to_name, i.subject, i.snippet,
           coalesce(i.sent_at, i.received_at) AS at,
           '' AS status,
           NULL::timestamptz AS opened_at,
           i.has_attachments
    FROM email_inbound i
    WHERE i.tenant_id = $4::bigint
      AND i.owner_id = $5::bigint
      AND i.folder = 'SENT'
      AND NOT EXISTS (
          SELECT 1 FROM erp e
          WHERE lower(e.to_email) = lower(i.to_email)
            AND e.subject = i.subject
            AND abs(extract(epoch FROM (e.at - coalesce(i.sent_at, i.received_at)))) < 600
      )
)
SELECT kind, id, to_email, to_name, subject, snippet, at, status, opened_at, has_attachments
FROM (
    SELECT 'ERP'::text AS kind, id, to_email, to_name, subject, snippet, at, status, opened_at, has_attachments FROM erp
    UNION ALL
    SELECT 'HOST'::text AS kind, id, to_email, to_name, subject, snippet, at, status, opened_at, has_attachments FROM host
) u
WHERE ($1::text = ''
       OR subject ILIKE '%' || $1::text || '%'
       OR to_email ILIKE '%' || $1::text || '%')
ORDER BY at DESC
LIMIT $3::int OFFSET $2::int
`

type ListSentUnifiedParams struct {
	Keyword   string
	RowOffset int32
	RowLimit  int32
	TenantID  int64
	OwnerID   int64
}

type ListSentUnifiedRow struct {
	Kind           string
	ID             int64
	ToEmail        string
	ToName         string
	Subject        string
	Snippet        string
	At             pgtype.Timestamptz
	Status         string
	OpenedAt       pgtype.Timestamptz
	HasAttachments bool
}

// The host's Sent folder alone used to be the answer here. It is not: see
// ListSentUnified, which merges it with the ERP's own record of what it
// sent, because each on its own leaves mail out.
// The Sent folder, from both places a sent mail is recorded.
//
// There are two, and they cannot be reconciled. The ERP writes its own record
// with per-recipient delivery status and open tracking; the host keeps a copy
// in its Sent folder. Joining them by Message-ID looks obvious and does not
// work: Gmail rewrites the header on the way out, so the id the ERP wrote
// (<uuid@gmail.com>) is not the id that comes back (CAANWAZy…@mail.gmail.com).
// Verified on live data — 18 ERP sends, 0 matches.
//
// Showing one source loses mail either way. The ERP's list misses anything
// sent from the mail app directly; the host's Sent folder misses whatever it
// has not echoed back yet, which for a mail sent a minute ago is all of it.
// So both, merged by time.
//
// Duplicates are removed on recipient + subject + within ten minutes, and
// deliberately only then: a near-miss shows the mail twice, which is a
// confusing list. A greedy match would hide a mail somebody sent, which is
// worse than a confusing list.
//
// kind tells the caller which record a row is, because they open different
// pages — the ERP one knows about delivery, the host one has the raw message.
func (q *Queries) ListSentUnified(ctx context.Context, arg ListSentUnifiedParams) ([]ListSentUnifiedRow, error) {
	rows, err := q.db.Query(ctx, listSentUnified,
		arg.Keyword,
		arg.RowOffset,
		arg.RowLimit,
		arg.TenantID,
		arg.OwnerID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSentUnifiedRow
	for rows.Next() {
		var i ListSentUnifiedRow
		if err := rows.Scan(
			&i.Kind,
			&i.ID,
			&i.ToEmail,
			&i.ToName,
			&i.Subject,
			&i.Snippet,
			&i.At,
			&i.Status,
			&i.OpenedAt,
			&i.HasAttachments,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSentWithEngagement = `-- name: ListSentWithEngagement :many
SELECT m.id, m.message_key::text AS message_key, m.subject, m.to_email, m.to_name,
       m.status, m.thread_key, m.sent_at, m.queued_at, m.opened_at,
       (SELECT count(*) FROM email_inbound i
         WHERE i.tenant_id = m.tenant_id AND i.thread_key = m.thread_key
           AND NOT i.is_bounce)::int AS reply_count
FROM email_messages m
WHERE m.tenant_id = $1::bigint
  AND m.sender_id = $2::bigint
ORDER BY coalesce(m.sent_at, m.queued_at) DESC
LIMIT $4::int OFFSET $3::int
`

type ListSentWithEngagementParams struct {
	TenantID  int64
	SenderID  int64
	RowOffset int32
	RowLimit  int32
}

type ListSentWithEngagementRow struct {
	ID         int64
	MessageKey string
	Subject    string
	ToEmail    string
	ToName     string
	Status     string
	ThreadKey  string
	SentAt     pgtype.Timestamptz
	QueuedAt   pgtype.Timestamptz
	OpenedAt   pgtype.Timestamptz
	ReplyCount int32
}

// The sent list with what little we know about what happened next.
//
// reply_count comes from real inbound messages threaded onto this send, which
// is the only unambiguous evidence a person read it. opened_at comes from the
// tracking pixel and is presented as a maybe.
func (q *Queries) ListSentWithEngagement(ctx context.Context, arg ListSentWithEngagementParams) ([]ListSentWithEngagementRow, error) {
	rows, err := q.db.Query(ctx, listSentWithEngagement,
		arg.TenantID,
		arg.SenderID,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSentWithEngagementRow
	for rows.Next() {
		var i ListSentWithEngagementRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageKey,
			&i.Subject,
			&i.ToEmail,
			&i.ToName,
			&i.Status,
			&i.ThreadKey,
			&i.SentAt,
			&i.QueuedAt,
			&i.OpenedAt,
			&i.ReplyCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncableMailAccounts = `-- name: ListSyncableMailAccounts :many
SELECT id, employee_id, email, username, secret_enc, key_version
FROM mail_accounts
WHERE tenant_id = $1::bigint AND is_active
ORDER BY id
`

type ListSyncableMailAccountsRow struct {
	ID         int64
	EmployeeID int64
	Email      string
	Username   string
	SecretEnc  []byte
	KeyVersion int32
}

// What the IMAP sync walks. Ordered by id so the rotation is stable and one
// mailbox cannot starve another.
func (q *Queries) ListSyncableMailAccounts(ctx context.Context, tenantID int64) ([]ListSyncableMailAccountsRow, error) {
	rows, err := q.db.Query(ctx, listSyncableMailAccounts, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSyncableMailAccountsRow
	for rows.Next() {
		var i ListSyncableMailAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.Email,
			&i.Username,
			&i.SecretEnc,
			&i.KeyVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThread = `-- name: ListThread :many
SELECT 'OUT' AS direction, m.id, m.subject, m.body, m.body_format,
       m.to_email AS counterparty, m.sender_name AS who,
       coalesce(m.sent_at, m.queued_at) AS at
FROM email_messages m
WHERE m.tenant_id = $1::bigint
  AND m.sender_id = $2::bigint
  AND m.thread_key = $3::text
UNION ALL
SELECT 'IN' AS direction, i.id, i.subject,
       CASE WHEN i.body_html <> '' THEN i.body_html ELSE i.body_text END AS body,
       CASE WHEN i.body_html <> '' THEN 'HTML' ELSE 'TEXT' END AS body_format,
       i.from_email AS counterparty, i.from_name AS who,
       coalesce(i.sent_at, i.received_at) AS at
FROM email_inbound i
WHERE i.tenant_id = $1::bigint
  AND i.owner_id = $2::bigint
  AND i.thread_key = $3::text
  AND NOT i.is_bounce
ORDER BY at
`

type ListThreadParams struct {
	TenantID  int64
	OwnerID   int64
	ThreadKey string
}

type ListThreadRow struct {
	Direction    string
	ID           int64
	Subject      string
	Body         string
	BodyFormat   string
	Counterparty string
	Who          string
	At           pgtype.Timestamptz
}

// Both sides of one conversation, in the order they happened. Sent and
// received come from different tables, so the union is what makes a thread
// read as a dialogue instead of two separate lists. Owner-scoped on both
// legs: a thread key is guessable, whose mail it opens must not be.
func (q *Queries) ListThread(ctx context.Context, arg ListThreadParams) ([]ListThreadRow, error) {
	rows, err := q.db.Query(ctx, listThread, arg.TenantID, arg.OwnerID, arg.ThreadKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListThreadRow
	for rows.Next() {
		var i ListThreadRow
		if err := rows.Scan(
			&i.Direction,
			&i.ID,
			&i.Subject,
			&i.Body,
			&i.BodyFormat,
			&i.Counterparty,
			&i.Who,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadForPurge = `-- name: ListThreadForPurge :many
SELECT id, raw_key, account_id, folder, imap_uid, message_id
FROM email_inbound
WHERE tenant_id = $1::bigint
  AND owner_id = $2::bigint
  AND thread_key = $3::text
  AND thread_key <> ''
  AND deleted_at IS NOT NULL
ORDER BY id
`

type ListThreadForPurgeParams struct {
	TenantID  int64
	OwnerID   int64
	ThreadKey string
}

type ListThreadForPurgeRow struct {
	ID        int64
	RawKey    string
	AccountID int64
	Folder    string
	ImapUid   int64
	MessageID string
}

// Every trashed message of one conversation. Permanent deletion follows the
// same conversation semantics as the rest of the list: the trash row stands
// for the exchange, so confirming deletes the exchange. Only trashed rows —
// a live message of the same thread is not swept up by this.
func (q *Queries) ListThreadForPurge(ctx context.Context, arg ListThreadForPurgeParams) ([]ListThreadForPurgeRow, error) {
	rows, err := q.db.Query(ctx, listThreadForPurge, arg.TenantID, arg.OwnerID, arg.ThreadKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListThreadForPurgeRow
	for rows.Next() {
		var i ListThreadForPurgeRow
		if err := rows.Scan(
			&i.ID,
			&i.RawKey,
			&i.AccountID,
			&i.Folder,
			&i.ImapUid,
			&i.MessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashForPurge = `-- name: ListTrashForPurge :many
SELECT id, raw_key, account_id, folder, imap_uid, message_id
FROM email_inbound
WHERE tenant_id = $1::bigint
  AND owner_id = $2::bigint
  AND deleted_at IS NOT NULL
ORDER BY id
`

type ListTrashForPurgeParams struct {
	TenantID int64
	OwnerID  int64
}

type ListTrashForPurgeRow struct {
	ID        int64
	RawKey    string
	AccountID int64
	Folder    string
	ImapUid   int64
	MessageID string
}

// Everything in one person's trash, for emptying it in one go.
func (q *Queries) ListTrashForPurge(ctx context.Context, arg ListTrashForPurgeParams) ([]ListTrashForPurgeRow, error) {
	rows, err := q.db.Query(ctx, listTrashForPurge, arg.TenantID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTrashForPurgeRow
	for rows.Next() {
		var i ListTrashForPurgeRow
		if err := rows.Scan(
			&i.ID,
			&i.RawKey,
			&i.AccountID,
			&i.Folder,
			&i.ImapUid,
			&i.MessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInboundRead = `-- name: MarkInboundRead :many
UPDATE email_inbound SET is_read = TRUE
WHERE tenant_id = $1::bigint
  AND owner_id = $2::bigint
  AND id = $3::bigint
  AND NOT is_read
RETURNING account_id, folder, imap_uid
`

type MarkInboundReadParams struct {
	TenantID int64
	OwnerID  int64
	ID       int64
}

type MarkInboundReadRow struct {
	AccountID int64
	Folder    string
	ImapUid   int64
}

func (q *Queries) MarkInboundRead(ctx context.Context, arg MarkInboundReadParams) ([]MarkInboundReadRow, error) {
	rows, err := q.db.Query(ctx, markInboundRead, arg.TenantID, arg.OwnerID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarkInboundReadRow
	for rows.Next() {
		var i MarkInboundReadRow
		if err := rows.Scan(&i.AccountID, &i.Folder, &i.ImapUid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMailAccountFailed = `-- name: MarkMailAccountFailed :exec
UPDATE mail_accounts
SET last_error = $1::text, updated_at = now()
WHERE tenant_id = $2::bigint AND id = $3::bigint
`

type MarkMailAccountFailedParams struct {
	LastError string
	TenantID  int64
	ID        int64
}

func (q *Queries) MarkMailAccountFailed(ctx context.Context, arg MarkMailAccountFailedParams) error {
	_, err := q.db.Exec(ctx, markMailAccountFailed, arg.LastError, arg.TenantID, arg.ID)
	return err
}

const markMailAccountVerified = `-- name: MarkMailAccountVerified :exec
UPDATE mail_accounts
SET verified_at = now(), last_error = '', updated_at = now()
WHERE tenant_id = $1::bigint AND id = $2::bigint
`

type MarkMailAccountVerifiedParams struct {
	TenantID int64
	ID       int64
}

func (q *Queries) MarkMailAccountVerified(ctx context.Context, arg MarkMailAccountVerifiedParams) error {
	_, err := q.db.Exec(ctx, markMailAccountVerified, arg.TenantID, arg.ID)
	return err
}

const markOpened = `-- name: MarkOpened :exec
UPDATE email_messages
SET opened_at = coalesce(opened_at, now())
WHERE tenant_id = $1::bigint AND id = $2::bigint
`

type MarkOpenedParams struct {
	TenantID int64
	ID       int64
}

// First open only. A later fetch appends an event but must not overwrite the
// original timestamp: "when did they first look at it" is the useful figure,
// and Apple Mail's prefetching would otherwise keep moving it forward.
func (q *Queries) MarkOpened(ctx context.Context, arg MarkOpenedParams) error {
	_, err := q.db.Exec(ctx, markOpened, arg.TenantID, arg.ID)
	return err
}

const markSyncFailed = `-- name: MarkSyncFailed :exec
INSERT INTO mail_sync_state (tenant_id, account_id, folder, last_error)
VALUES ($1::bigint, $2::bigint,
        $3::text, $4::text)
ON CONFLICT (tenant_id, account_id, folder) DO UPDATE SET
    last_error = excluded.last_error
`

type MarkSyncFailedParams struct {
	TenantID  int64
	AccountID int64
	Folder    string
	LastError string
}

func (q *Queries) MarkSyncFailed(ctx context.Context, arg MarkSyncFailedParams) error {
	_, err := q.db.Exec(ctx, markSyncFailed,
		arg.TenantID,
		arg.AccountID,
		arg.Folder,
		arg.LastError,
	)
	return err
}

const markViewRead = `-- name: MarkViewRead :many
UPDATE email_inbound
SET is_read = TRUE
WHERE tenant_id = $1::bigint
  AND owner_id = $2::bigint
  AND NOT is_read
  AND CASE $3::text
        WHEN 'JUNK'  THEN folder = 'JUNK' AND NOT not_junk
        -- The trash holds mail deleted from anywhere, junk included.
        WHEN 'TRASH' THEN folder IN ('INBOX', 'JUNK')
        ELSE (folder = 'INBOX' OR (folder = 'JUNK' AND not_junk))
      END
  AND NOT is_bounce
  AND CASE $3::text
        WHEN 'STARRED' THEN is_starred AND deleted_at IS NULL
        WHEN 'ARCHIVE' THEN archived_at IS NOT NULL AND deleted_at IS NULL
        WHEN 'TRASH'   THEN deleted_at IS NOT NULL
        WHEN 'JUNK'    THEN deleted_at IS NULL
        ELSE archived_at IS NULL AND deleted_at IS NULL
      END
RETURNING account_id, folder, imap_uid
`

type MarkViewReadParams struct {
	TenantID int64
	OwnerID  int64
	View     string
}

type MarkViewReadRow struct {
	AccountID int64
	Folder    string
	ImapUid   int64
}

// Marks everything the current view shows as read, and nothing else.
//
// Scoped by the same filters as the list because that is what the button
// promises: "全部已读" in the junk view must not touch the inbox, and it must
// never reach into the archive or the trash from either. Every row it changes
// comes back so the caller can tell the mail host too: reading a mailbox in
// the ERP has to leave it read in Gmail, one button or one message at a time.
func (q *Queries) MarkViewRead(ctx context.Context, arg MarkViewReadParams) ([]MarkViewReadRow, error) {
	rows, err := q.db.Query(ctx, markViewRead, arg.TenantID, arg.OwnerID, arg.View)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarkViewReadRow
	for rows.Next() {
		var i MarkViewReadRow
		if err := rows.Scan(&i.AccountID, &i.Folder, &i.ImapUid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mirrorHostArchive = `-- name: MirrorHostArchive :exec
UPDATE email_inbound
SET archived_at = coalesce(archived_at, now())
WHERE tenant_id = $1::bigint
  AND account_id = $2::bigint
  AND folder = $3::text
  AND imap_uid = $4::bigint
`

type MirrorHostArchiveParams struct {
	TenantID  int64
	AccountID int64
	Folder    string
	ImapUid   int64
}

func (q *Queries) MirrorHostArchive(ctx context.Context, arg MirrorHostArchiveParams) error {
	_, err := q.db.Exec(ctx, mirrorHostArchive,
		arg.TenantID,
		arg.AccountID,
		arg.Folder,
		arg.ImapUid,
	)
	return err
}

const mirrorHostDelete = `-- name: MirrorHostDelete :exec
UPDATE email_inbound
SET deleted_at = coalesce(deleted_at, now())
WHERE tenant_id = $1::bigint
  AND account_id = $2::bigint
  AND folder = $3::text
  AND imap_uid = $4::bigint
`

type MirrorHostDeleteParams struct {
	TenantID  int64
	AccountID int64
	Folder    string
	ImapUid   int64
}

// Somebody deleted this mail elsewhere. Mirrored as a soft delete, never a
// hard one: our copy may be the only one left, and the ERP trash gives thirty
// days to notice a mistake. The sweeper finishes the job afterwards.
func (q *Queries) MirrorHostDelete(ctx context.Context, arg MirrorHostDeleteParams) error {
	_, err := q.db.Exec(ctx, mirrorHostDelete,
		arg.TenantID,
		arg.AccountID,
		arg.Folder,
		arg.ImapUid,
	)
	return err
}

const pruneSendCounters = `-- name: PruneSendCounters :exec
DELETE FROM mail_send_counters
WHERE window_at < now() - interval '7 days'
`

// Counters older than the widest window we ever ask about are dead weight.
func (q *Queries) PruneSendCounters(ctx context.Context) error {
	_, err := q.db.Exec(ctx, pruneSendCounters)
	return err
}

const purgeInbound = `-- name: PurgeInbound :execrows
DELETE FROM email_inbound
WHERE tenant_id = $1::bigint
  AND owner_id = $2::bigint
  AND id = $3::bigint
  AND deleted_at IS NOT NULL
`

type PurgeInboundParams struct {
	TenantID int64
	OwnerID  int64
	ID       int64
}

// The attachment rows go with the mail via ON DELETE CASCADE; their object
// storage copies are removed by the caller before this runs.
func (q *Queries) PurgeInbound(ctx context.Context, arg PurgeInboundParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeInbound, arg.TenantID, arg.OwnerID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const repointInbound = `-- name: RepointInbound :exec
UPDATE email_inbound
SET folder = $1::text,
    imap_uid = $2::bigint,
    not_junk = FALSE
WHERE tenant_id = $3::bigint
  AND account_id = $4::bigint
  AND folder = $5::text
  AND imap_uid = $6::bigint
`

type RepointInboundParams struct {
	NewFolder string
	NewUid    int64
	TenantID  int64
	AccountID int64
	OldFolder string
	OldUid    int64
}

// Follows a message the ERP itself moved on the host: same mail, new folder,
// new UID. Without this the row would still name a UID that belongs to
// nothing, and the next sync would fetch the message again as though it were
// newly arrived — one mail, two rows.
func (q *Queries) RepointInbound(ctx context.Context, arg RepointInboundParams) error {
	_, err := q.db.Exec(ctx, repointInbound,
		arg.NewFolder,
		arg.NewUid,
		arg.TenantID,
		arg.AccountID,
		arg.OldFolder,
		arg.OldUid,
	)
	return err
}

const setInboundFlags = `-- name: SetInboundFlags :many
UPDATE email_inbound
SET is_read    = coalesce($1::boolean, is_read),
    is_starred = coalesce($2::boolean, is_starred),
    not_junk   = coalesce($3::boolean, not_junk),
    archived_at = CASE
        WHEN $4::boolean IS NULL THEN archived_at
        WHEN $4::boolean THEN coalesce(archived_at, now())
        ELSE NULL END,
    deleted_at = CASE
        WHEN $5::boolean IS NULL THEN deleted_at
        WHEN $5::boolean THEN coalesce(deleted_at, now())
        ELSE NULL END
WHERE tenant_id = $6::bigint
  AND owner_id = $7::bigint
  AND id = $8::bigint
RETURNING account_id, folder, imap_uid, is_read, is_starred, message_id, archived_at, deleted_at, not_junk
`

type SetInboundFlagsParams struct {
	Read     *bool
	Starred  *bool
	NotJunk  *bool
	Archived *bool
	Deleted  *bool
	TenantID int64
	OwnerID  int64
	ID       int64
}

type SetInboundFlagsRow struct {
	AccountID  int64
	Folder     string
	ImapUid    int64
	IsRead     bool
	IsStarred  bool
	MessageID  string
	ArchivedAt pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
	NotJunk    bool
}

// One statement for all four flags; an absent argument leaves that flag
// alone. Owner-scoped in the WHERE, so marking somebody else's mail is a
// no-op rather than a decision.
func (q *Queries) SetInboundFlags(ctx context.Context, arg SetInboundFlagsParams) ([]SetInboundFlagsRow, error) {
	rows, err := q.db.Query(ctx, setInboundFlags,
		arg.Read,
		arg.Starred,
		arg.NotJunk,
		arg.Archived,
		arg.Deleted,
		arg.TenantID,
		arg.OwnerID,
		arg.ID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SetInboundFlagsRow
	for rows.Next() {
		var i SetInboundFlagsRow
		if err := rows.Scan(
			&i.AccountID,
			&i.Folder,
			&i.ImapUid,
			&i.IsRead,
			&i.IsStarred,
			&i.MessageID,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.NotJunk,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setInboundReadByUID = `-- name: SetInboundReadByUID :exec

UPDATE email_inbound
SET is_read = $1::boolean
WHERE tenant_id = $2::bigint
  AND account_id = $3::bigint
  AND folder = $4::text
  AND imap_uid = $5::bigint
`

type SetInboundReadByUIDParams struct {
	IsRead    bool
	TenantID  int64
	AccountID int64
	Folder    string
	ImapUid   int64
}

// Stars used to be taken one UID at a time here, alongside the read state.
// SyncStarredFromHost replaced that: the host can name every starred message
// in a folder in one search, so there is nothing left for a per-message
// version to do.
// Server state winning over ours, for one message. Used only by the
// reconcile pass, and only once the write-back queue is empty for this
// account — otherwise it would overwrite a local change still on its way up.
func (q *Queries) SetInboundReadByUID(ctx context.Context, arg SetInboundReadByUIDParams) error {
	_, err := q.db.Exec(ctx, setInboundReadByUID,
		arg.IsRead,
		arg.TenantID,
		arg.AccountID,
		arg.Folder,
		arg.ImapUid,
	)
	return err
}

const setMailAccountActive = `-- name: SetMailAccountActive :exec
UPDATE mail_accounts
SET is_active = $1::boolean, updated_at = now()
WHERE tenant_id = $2::bigint AND id = $3::bigint
`

type SetMailAccountActiveParams struct {
	IsActive bool
	TenantID int64
	ID       int64
}

func (q *Queries) SetMailAccountActive(ctx context.Context, arg SetMailAccountActiveParams) error {
	_, err := q.db.Exec(ctx, setMailAccountActive, arg.IsActive, arg.TenantID, arg.ID)
	return err
}

const setMailAccountOAuth = `-- name: SetMailAccountOAuth :exec
UPDATE mail_accounts
SET auth_kind = 'OAUTH',
    oauth_refresh_enc = $1::bytea,
    secret_enc = ''::bytea,
    key_version = $2::int,
    verified_at = now(),
    last_error = '',
    is_active = TRUE,
    updated_at = now()
WHERE tenant_id = $3::bigint AND id = $4::bigint
`

type SetMailAccountOAuthParams struct {
	OauthRefreshEnc []byte
	KeyVersion      int32
	TenantID        int64
	ID              int64
}

// Binding via Google replaces whatever was there: the password ciphertext is
// cleared because keeping a stale second credential around only widens what a
// leak could do. Verified immediately — the owner literally just signed in.
func (q *Queries) SetMailAccountOAuth(ctx context.Context, arg SetMailAccountOAuthParams) error {
	_, err := q.db.Exec(ctx, setMailAccountOAuth,
		arg.OauthRefreshEnc,
		arg.KeyVersion,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const setMailAccountSecret = `-- name: SetMailAccountSecret :exec
UPDATE mail_accounts
SET secret_enc = $1::bytea,
    key_version = $2::int,
    auth_kind = 'PASSWORD',
    oauth_refresh_enc = ''::bytea,
    verified_at = NULL,
    last_error = '',
    updated_at = now()
WHERE tenant_id = $3::bigint AND id = $4::bigint
`

type SetMailAccountSecretParams struct {
	SecretEnc  []byte
	KeyVersion int32
	TenantID   int64
	ID         int64
}

// Storing a new secret invalidates any previous verification: the code may
// be wrong, and claiming a mailbox works because an older one did is exactly
// the kind of stale green tick that stops people trusting the indicator.
// Typing a code also decides how this account authenticates from now on:
// auth_kind flips back to PASSWORD and any Google grant is dropped — the
// mirror image of SetMailAccountOAuth clearing secret_enc.
func (q *Queries) SetMailAccountSecret(ctx context.Context, arg SetMailAccountSecretParams) error {
	_, err := q.db.Exec(ctx, setMailAccountSecret,
		arg.SecretEnc,
		arg.KeyVersion,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const setThreadFlags = `-- name: SetThreadFlags :many
UPDATE email_inbound
SET is_read    = coalesce($1::boolean, is_read),
    is_starred = coalesce($2::boolean, is_starred),
    not_junk   = coalesce($3::boolean, not_junk),
    archived_at = CASE
        WHEN $4::boolean IS NULL THEN archived_at
        WHEN $4::boolean THEN coalesce(archived_at, now())
        ELSE NULL END,
    deleted_at = CASE
        WHEN $5::boolean IS NULL THEN deleted_at
        WHEN $5::boolean THEN coalesce(deleted_at, now())
        ELSE NULL END
WHERE tenant_id = $6::bigint
  AND owner_id = $7::bigint
  AND thread_key = $8::text
  AND thread_key <> ''
RETURNING account_id, folder, imap_uid, is_read, is_starred, message_id, archived_at, deleted_at, not_junk
`

type SetThreadFlagsParams struct {
	Read      *bool
	Starred   *bool
	NotJunk   *bool
	Archived  *bool
	Deleted   *bool
	TenantID  int64
	OwnerID   int64
	ThreadKey string
}

type SetThreadFlagsRow struct {
	AccountID  int64
	Folder     string
	ImapUid    int64
	IsRead     bool
	IsStarred  bool
	MessageID  string
	ArchivedAt pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
	NotJunk    bool
}

// Housekeeping applied to a whole conversation. Archiving from a page that
// shows the entire exchange has to move the entire exchange; otherwise the
// thread stays in the inbox one message lighter, which reads as a bug.
// Owner-scoped: thread keys are guessable, so this must never reach further
// than the caller's own mail.
func (q *Queries) SetThreadFlags(ctx context.Context, arg SetThreadFlagsParams) ([]SetThreadFlagsRow, error) {
	rows, err := q.db.Query(ctx, setThreadFlags,
		arg.Read,
		arg.Starred,
		arg.NotJunk,
		arg.Archived,
		arg.Deleted,
		arg.TenantID,
		arg.OwnerID,
		arg.ThreadKey,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SetThreadFlagsRow
	for rows.Next() {
		var i SetThreadFlagsRow
		if err := rows.Scan(
			&i.AccountID,
			&i.Folder,
			&i.ImapUid,
			&i.IsRead,
			&i.IsStarred,
			&i.MessageID,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.NotJunk,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncStarredFromHost = `-- name: SyncStarredFromHost :execrows
UPDATE email_inbound
SET is_starred = (imap_uid = ANY($1::bigint[]))
WHERE tenant_id = $2::bigint
  AND account_id = $3::bigint
  AND folder = $4::text
  AND NOT not_junk
  AND is_starred <> (imap_uid = ANY($1::bigint[]))
`

type SyncStarredFromHostParams struct {
	StarredUids []int64
	TenantID    int64
	AccountID   int64
	Folder      string
}

// Makes the ERP's stars agree with the host's, over the whole folder at once.
//
// Stars used to ride along with the read-state reconcile, which fetches flags
// for the newest 200 UIDs. That window is a few days of a busy mailbox, so a
// star put on anything older in Gmail simply never arrived — the symptom was
// a mailbox full of stars showing exactly one in the ERP.
//
// A single UID SEARCH FLAGGED answers the question for the entire folder in
// one round trip, which is why this can be a plain assignment rather than a
// per-message comparison: starred is "in the set the host just named".
//
// Rescued junk is left alone. Those rows still carry their old JUNK folder and
// UID while the message itself has moved to the host's inbox, so the search
// would not name them and this would quietly unstar them.
//
// The final predicate keeps the update to rows that actually change, so a
// mailbox with no star activity costs nothing every two minutes.
func (q *Queries) SyncStarredFromHost(ctx context.Context, arg SyncStarredFromHostParams) (int64, error) {
	result, err := q.db.Exec(ctx, syncStarredFromHost,
		arg.StarredUids,
		arg.TenantID,
		arg.AccountID,
		arg.Folder,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const trashJunkView = `-- name: TrashJunkView :many
UPDATE email_inbound
SET deleted_at = now()
WHERE tenant_id = $1::bigint
  AND owner_id = $2::bigint
  AND folder = 'JUNK'
  AND NOT not_junk
  AND deleted_at IS NULL
RETURNING id, account_id, folder, imap_uid, message_id
`

type TrashJunkViewParams struct {
	TenantID int64
	OwnerID  int64
}

type TrashJunkViewRow struct {
	ID        int64
	AccountID int64
	Folder    string
	ImapUid   int64
	MessageID string
}

// Empties the junk view into the trash in one go.
//
// Scoped exactly like the junk list: a mail somebody has already rescued with
// 「这不是垃圾」 is not junk any more and must not be swept up with the rest.
// Every touched row comes back so the deletion can be carried to the host too,
// the same as deleting one by hand.
func (q *Queries) TrashJunkView(ctx context.Context, arg TrashJunkViewParams) ([]TrashJunkViewRow, error) {
	rows, err := q.db.Query(ctx, trashJunkView, arg.TenantID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrashJunkViewRow
	for rows.Next() {
		var i TrashJunkViewRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Folder,
			&i.ImapUid,
			&i.MessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMailAccountShell = `-- name: UpsertMailAccountShell :one
INSERT INTO mail_accounts (
    tenant_id, employee_id, email, username, secret_enc, key_version, updated_at
) VALUES (
    $1::bigint, $2::bigint,
    $3::text, $4::text, ''::bytea, 0, now()
)
ON CONFLICT (tenant_id, employee_id) DO UPDATE SET
    email = excluded.email,
    username = excluded.username,
    updated_at = now()
RETURNING id
`

type UpsertMailAccountShellParams struct {
	TenantID   int64
	EmployeeID int64
	Email      string
	Username   string
}

// Creates or updates everything except the secret, and returns the id.
//
// Split from the secret write because the ciphertext is bound to the row id
// (see AccountAAD), which does not exist until the row does. Insert first,
// seal against the real id, then store — rather than inventing the id
// client-side or binding to something weaker.
func (q *Queries) UpsertMailAccountShell(ctx context.Context, arg UpsertMailAccountShellParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertMailAccountShell,
		arg.TenantID,
		arg.EmployeeID,
		arg.Email,
		arg.Username,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertMailHost = `-- name: UpsertMailHost :exec
INSERT INTO mail_hosts (
    tenant_id, domain, smtp_host, smtp_port, smtp_security,
    imap_host, imap_port, imap_security, hourly_quota, daily_quota, updated_at
) VALUES (
    $1::bigint, $2::text,
    $3::text, $4::int, $5::text,
    $6::text, $7::int, $8::text,
    $9::int, $10::int, now()
)
ON CONFLICT (tenant_id) DO UPDATE SET
    domain = excluded.domain,
    smtp_host = excluded.smtp_host,
    smtp_port = excluded.smtp_port,
    smtp_security = excluded.smtp_security,
    imap_host = excluded.imap_host,
    imap_port = excluded.imap_port,
    imap_security = excluded.imap_security,
    hourly_quota = excluded.hourly_quota,
    daily_quota = excluded.daily_quota,
    updated_at = now()
`

type UpsertMailHostParams struct {
	TenantID     int64
	Domain       string
	SmtpHost     string
	SmtpPort     int32
	SmtpSecurity string
	ImapHost     string
	ImapPort     int32
	ImapSecurity string
	HourlyQuota  int32
	DailyQuota   int32
}

func (q *Queries) UpsertMailHost(ctx context.Context, arg UpsertMailHostParams) error {
	_, err := q.db.Exec(ctx, upsertMailHost,
		arg.TenantID,
		arg.Domain,
		arg.SmtpHost,
		arg.SmtpPort,
		arg.SmtpSecurity,
		arg.ImapHost,
		arg.ImapPort,
		arg.ImapSecurity,
		arg.HourlyQuota,
		arg.DailyQuota,
	)
	return err
}

const upsertSyncState = `-- name: UpsertSyncState :exec
INSERT INTO mail_sync_state (tenant_id, account_id, folder, uid_validity, last_uid, low_uid, last_synced_at, last_error)
VALUES ($1::bigint, $2::bigint, $3::text,
        $4::bigint, $5::bigint, $6::bigint, now(), '')
ON CONFLICT (tenant_id, account_id, folder) DO UPDATE SET
    uid_validity = excluded.uid_validity,
    last_uid = excluded.last_uid,
    low_uid = CASE
        WHEN mail_sync_state.low_uid = 0 THEN excluded.low_uid
        WHEN excluded.low_uid = 0 THEN mail_sync_state.low_uid
        ELSE LEAST(mail_sync_state.low_uid, excluded.low_uid)
    END,
    last_synced_at = now(),
    last_error = ''
`

type UpsertSyncStateParams struct {
	TenantID    int64
	AccountID   int64
	Folder      string
	UidValidity int64
	LastUid     int64
	LowUid      int64
}

// low_uid only ever moves down: 0 means backfill has not started, so the
// first write sets it and later writes keep the minimum.
func (q *Queries) UpsertSyncState(ctx context.Context, arg UpsertSyncStateParams) error {
	_, err := q.db.Exec(ctx, upsertSyncState,
		arg.TenantID,
		arg.AccountID,
		arg.Folder,
		arg.UidValidity,
		arg.LastUid,
		arg.LowUid,
	)
	return err
}
