<template>
  <main class="daily-page">
    <WorkflowPageHeader :title="t('dailyPrice.title')" :description="t('dailyPrice.description')">
      <template #actions>
        <el-button v-if="canManage" @click="openConfig">{{ t('dailyPrice.manage') }}</el-button>
        <el-date-picker v-model="selectedDate" type="date" value-format="YYYY-MM-DD" :clearable="false" :aria-label="t('dailyPrice.date')" style="width:152px" />
      </template>
    </WorkflowPageHeader>
    <el-alert v-if="!activeProducts.length || !activeSuppliers.length" :title="t('dailyPrice.setupHint')" type="info" :closable="false" show-icon class="notice" />

    <section v-loading="loading" class="panel">
      <div class="section-head"><div><h2>{{ t('dailyPrice.matrix') }}</h2><p>{{ t('dailyPrice.matrixHint') }}</p></div><div class="actions"><el-tag v-if="priceDirty.size" type="warning" effect="plain">{{ t('dailyPrice.unsavedCount',{count:priceDirty.size}) }}</el-tag><el-button type="primary" :disabled="!priceDirty.size" :loading="savingPrices" @click="savePrices">{{ t('dailyPrice.savePrices') }}</el-button></div></div>
      <div class="matrix-scroll"><table class="price-matrix"><thead><tr><th class="row-label">{{ t('dailyPrice.product') }}</th><th v-for="supplier in activeSuppliers" :key="supplier.id">{{ supplier.name }}</th></tr></thead><tbody><tr v-for="product in activeProducts" :key="product.id"><th class="row-label">{{ product.name }}</th><td v-for="supplier in activeSuppliers" :key="supplier.id" :class="{changed:priceDirty.has(cellKey(product.id,supplier.id))}"><div class="cell-edit"><el-input :model-value="priceCell(product.id,supplier.id).price" type="number" min="0" step="0.0001" :disabled="!editablePrice(product.id,supplier.id)" :placeholder="t('dailyPrice.empty')" @update:model-value="(v:string)=>editPrice(product.id,supplier.id,String(v),'price')" @keydown.enter.prevent="focusNext($event)" /><el-popover trigger="click" placement="bottom" :width="230"><template #reference><el-button text size="small" :disabled="!editablePrice(product.id,supplier.id)" :class="{hasRemark:!!priceCell(product.id,supplier.id).remark}">✎</el-button></template><label class="remark-label">{{ t('dailyPrice.remark') }}<el-input :model-value="priceCell(product.id,supplier.id).remark" maxlength="500" @update:model-value="(v:string)=>editPrice(product.id,supplier.id,String(v),'remark')" /></label></el-popover></div><div v-if="priceCell(product.id,supplier.id).price && priceCell(product.id,supplier.id).previousPrice" class="change" :class="changeClass(priceCell(product.id,supplier.id))" :title="changeTitle(priceCell(product.id,supplier.id))">{{ changeLabel(priceCell(product.id,supplier.id)) }}</div></td></tr></tbody></table></div>
      <p class="helper">{{ t('dailyPrice.blankHint') }}</p>
    </section>

    <section class="panel">
      <div class="section-head"><div><h2>{{ t('dailyPrice.spread') }}</h2><p>{{ t('dailyPrice.spreadHint') }}</p></div><div class="actions"><el-tag v-if="spreadDirty.size" type="warning" effect="plain">{{ t('dailyPrice.unsavedCount',{count:spreadDirty.size}) }}</el-tag><el-button type="primary" :disabled="!spreadDirty.size" :loading="savingSpreads" @click="saveSpreads">{{ t('dailyPrice.saveSpreads') }}</el-button></div></div>
      <div class="matrix-scroll"><table class="spread-table"><thead><tr><th>{{ t('dailyPrice.product') }}</th><th>{{ t('dailyPrice.spot') }}</th><th>{{ t('dailyPrice.futures') }}</th><th>{{ t('dailyPrice.basis') }}</th><th>{{ t('dailyPrice.basisPercent') }}</th></tr></thead><tbody><tr v-for="product in activeSpreads" :key="product.id" :class="{changed:spreadDirty.has(product.id)}"><th>{{ product.name }}</th><td><el-input :model-value="spreadCell(product.id).spot" type="number" min="0" step="0.0001" :disabled="!editableSpread(product.id)" @update:model-value="(v:string)=>editSpread(product.id,String(v),'spot')" @keydown.enter.prevent="focusNext($event)" /></td><td><el-input :model-value="spreadCell(product.id).futures" type="number" min="0" step="0.0001" :disabled="!editableSpread(product.id)" @update:model-value="(v:string)=>editSpread(product.id,String(v),'futures')" @keydown.enter.prevent="focusNext($event)" /></td><td>{{ basis(product.id) }}</td><td>{{ basisPercent(product.id) }}</td></tr></tbody></table></div>
      <p v-if="activeSpreads.length" class="helper">{{ t('dailyPrice.zeroHint') }}</p>
    </section>

    <section class="panel"><div class="section-head"><div><h2>{{ t('dailyPrice.priceTrend') }}</h2><p>{{ t('dailyPrice.trendHint') }}</p></div></div><div class="filters"><el-select v-model="trendProduct" filterable :placeholder="t('dailyPrice.product')"><el-option v-for="item in products" :key="item.id" :label="item.name" :value="item.id" /></el-select><el-select v-model="trendSuppliers" multiple :multiple-limit="6" collapse-tags filterable :placeholder="t('dailyPrice.suppliers')"><el-option v-for="item in suppliers" :key="item.id" :label="item.name" :value="item.id" /></el-select><el-select v-model="rangePreset" @change="applyRange"><el-option v-for="item in rangeOptions" :key="item.value" :label="t(item.label)" :value="item.value" /></el-select><el-date-picker v-if="rangePreset==='custom'" v-model="customRange" type="daterange" value-format="YYYY-MM-DD" :start-placeholder="t('dailyPrice.from')" :end-placeholder="t('dailyPrice.to')" @change="loadTrend" /></div><DailyTrendChart :title="t('dailyPrice.priceTrend')" :lines="priceLines" :empty-label="t('dailyPrice.noTrend')" /></section>

    <section class="panel"><div class="section-head"><div><h2>{{ t('dailyPrice.spreadTrend') }}</h2></div></div><div class="filters"><el-select v-model="trendSpread" filterable :placeholder="t('dailyPrice.product')"><el-option v-for="item in spreadProducts" :key="item.id" :label="item.name" :value="item.id" /></el-select><el-checkbox-group v-model="spreadMetrics"><el-checkbox value="spot">{{ t('dailyPrice.spot') }}</el-checkbox><el-checkbox value="futures">{{ t('dailyPrice.futures') }}</el-checkbox><el-checkbox value="basis">{{ t('dailyPrice.basis') }}</el-checkbox></el-checkbox-group></div><DailyTrendChart :title="t('dailyPrice.spreadTrend')" :lines="spreadLines" :empty-label="t('dailyPrice.noTrend')" /></section>

    <section class="panel"><div class="section-head"><div><h2>{{ t('dailyPrice.history') }}</h2><p>{{ t('dailyPrice.historyHint') }}</p></div></div><el-date-picker v-model="historyDate" type="date" value-format="YYYY-MM-DD" :clearable="false" :aria-label="t('dailyPrice.historyDate')" /><el-table :data="historyPrices" size="small" class="history-table"><el-table-column prop="productName" :label="t('dailyPrice.product')" /><el-table-column prop="supplierName" :label="t('dailyPrice.supplier')" /><el-table-column prop="price" :label="t('dailyPrice.price')" /><el-table-column prop="remark" :label="t('dailyPrice.remark')" /><el-table-column prop="createdByName" :label="t('dailyPrice.author')" /><el-table-column :label="t('dailyPrice.updatedAt')"><template #default="scope">{{ formatTime(scope.row.updatedAt) }}</template></el-table-column><el-table-column v-if="canDelete" :label="t('dailyPrice.actions')" width="75"><template #default="scope"><el-button text type="danger" @click="removeRecord('prices',scope.row.id)">{{ t('dailyPrice.delete') }}</el-button></template></el-table-column></el-table><h3>{{ t('dailyPrice.spread') }}</h3><el-table :data="historySpreads" size="small"><el-table-column prop="productName" :label="t('dailyPrice.product')" /><el-table-column prop="spot" :label="t('dailyPrice.spot')" /><el-table-column prop="futures" :label="t('dailyPrice.futures')" /><el-table-column prop="basis" :label="t('dailyPrice.basis')" /><el-table-column prop="basisPercent" :label="t('dailyPrice.basisPercent')" /><el-table-column prop="createdByName" :label="t('dailyPrice.author')" /><el-table-column :label="t('dailyPrice.updatedAt')"><template #default="scope">{{ formatTime(scope.row.updatedAt) }}</template></el-table-column><el-table-column v-if="canDelete" :label="t('dailyPrice.actions')" width="75"><template #default="scope"><el-button text type="danger" @click="removeRecord('spreads',scope.row.id)">{{ t('dailyPrice.delete') }}</el-button></template></el-table-column></el-table></section>

    <el-dialog v-model="configOpen" :title="t('dailyPrice.manage')" width="min(640px,95vw)"><div class="config-form"><el-select v-model="configKind"><el-option :label="t('dailyPrice.product')" value="PRODUCT" /><el-option :label="t('dailyPrice.supplier')" value="SUPPLIER" /><el-option :label="t('dailyPrice.spreadProduct')" value="SPREAD" /></el-select><el-select v-if="configKind!=='SPREAD'" v-model="configMaster" filterable remote :remote-method="searchMaster" clearable :placeholder="t('dailyPrice.selectMaster')"><el-option v-for="item in masterOptions" :key="item.id" :label="item.name" :value="item.id" /></el-select><el-input v-model="configName" :placeholder="t('dailyPrice.customName')" :disabled="!!configMaster" /><el-button type="primary" :loading="configSaving" @click="addConfig">{{ t('dailyPrice.add') }}</el-button></div><p class="helper">{{ t('dailyPrice.configHint') }}</p><el-table :data="configRows" size="small"><el-table-column prop="name" :label="t('dailyPrice.name')" /><el-table-column :label="t('dailyPrice.display')" width="110"><template #default="scope"><el-switch :model-value="scope.row.active" @change="(v:boolean)=>toggleConfig(scope.row,Boolean(v))" /></template></el-table-column></el-table></el-dialog>
  </main>
</template>
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from 'vue'
import { onBeforeRouteLeave } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useI18n } from 'vue-i18n'
import { get, put, del } from '../api'
import { useAuthStore } from '../stores/auth'
import WorkflowPageHeader from '../components/WorkflowPageHeader.vue'
import DailyTrendChart, { type TrendLine } from '../components/DailyTrendChart.vue'
type Dimension = { id:number;kind:'PRODUCT'|'SUPPLIER'|'SPREAD';masterId:number;name:string;sortOrder:number;active:boolean }
type Price = { id:number;date:string;productId:number;productName:string;supplierId:number;supplierName:string;price:string;previousPrice:string;remark:string;createdBy:number;createdByName:string;updatedAt:string }
type Spread = { id:number;date:string;productId:number;productName:string;spot:string|null;futures:string|null;basis:string|null;basisPercent:string|null;createdBy:number;createdByName:string;updatedAt:string }
const auth=useAuthStore(),{t,locale}=useI18n()
const canWrite=computed(()=>auth.can('procurement:daily-price:write'))
const canManage=computed(()=>auth.can('procurement:daily-price:manage'))
const canDelete=computed(()=>auth.can('procurement:daily-price:delete'))
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const selectedDate=ref(today()),historyDate=ref(today()),loadedDate=ref(today())
const dimensions=ref<Dimension[]>([]),dayPrices=ref<Price[]>([]),daySpreads=ref<Spread[]>([]),historyPrices=ref<Price[]>([]),historySpreads=ref<Spread[]>([]),trendPrices=ref<Price[]>([]),trendSpreads=ref<Spread[]>([])
const priceDraft=ref<Record<string,{price:string;remark:string;previousPrice:string}>>({}),spreadDraft=ref<Record<number,{spot:string;futures:string}>>({})
const priceDirty=ref(new Set<string>()),spreadDirty=ref(new Set<number>())
const loading=ref(false),savingPrices=ref(false),savingSpreads=ref(false),configOpen=ref(false),configSaving=ref(false)
const products=computed(()=>dimensions.value.filter(x=>x.kind==='PRODUCT')),suppliers=computed(()=>dimensions.value.filter(x=>x.kind==='SUPPLIER')),spreadProducts=computed(()=>dimensions.value.filter(x=>x.kind==='SPREAD'))
const activeProducts=computed(()=>products.value.filter(x=>x.active||dayPrices.value.some(p=>p.productId===x.id))),activeSuppliers=computed(()=>suppliers.value.filter(x=>x.active||dayPrices.value.some(p=>p.supplierId===x.id))),activeSpreads=computed(()=>spreadProducts.value.filter(x=>x.active||daySpreads.value.some(p=>p.productId===x.id)))
const cellKey=(productId:number,supplierId:number)=>`${productId}:${supplierId}`
const priceCell=(p:number,s:number)=>priceDraft.value[cellKey(p,s)]||{price:'',remark:'',previousPrice:''}
const spreadCell=(p:number)=>spreadDraft.value[p]||{spot:'',futures:''}
function editablePrice(p:number,s:number){const current=dayPrices.value.find(x=>x.productId===p&&x.supplierId===s);return canWrite.value&&(!current||canManage.value||String(current.createdBy)===String(auth.employeeId))}
function editableSpread(p:number){const current=daySpreads.value.find(x=>x.productId===p);return canWrite.value&&(!current||canManage.value||String(current.createdBy)===String(auth.employeeId))}
function editPrice(p:number,s:number,value:string,field:'price'|'remark'){const key=cellKey(p,s);priceDraft.value[key]={...priceCell(p,s),[field]:value};priceDirty.value=new Set([...priceDirty.value,key])}
function editSpread(p:number,value:string,field:'spot'|'futures'){spreadDraft.value[p]={...spreadCell(p),[field]:value};spreadDirty.value=new Set([...spreadDirty.value,p])}
function focusNext(event:KeyboardEvent){const inputs=[...document.querySelectorAll<HTMLInputElement>('.daily-page .price-matrix input:not([disabled]),.daily-page .spread-table input:not([disabled])')];const i=inputs.indexOf(event.target as HTMLInputElement);inputs[i+1]?.focus()}
function changeValue(cell:{price:string;previousPrice:string}){return Number(cell.price)-Number(cell.previousPrice)}
function changeClass(cell:{price:string;previousPrice:string}){const v=changeValue(cell);return v>0?'up':v<0?'down':'flat'}
function changeLabel(cell:{price:string;previousPrice:string}){const v=changeValue(cell);return v>0?`↑ +${v.toFixed(2)}`:v<0?`↓ ${v.toFixed(2)}`:'0'}
function changeTitle(cell:{price:string;previousPrice:string}){const old=Number(cell.previousPrice),v=changeValue(cell);return t('dailyPrice.changeTooltip',{previous:cell.previousPrice,current:cell.price,change:`${v>=0?'+':''}${v.toFixed(2)}`,percent:old?`${(v/old*100).toFixed(2)}%`:'—'})}
function basis(p:number){const x=spreadCell(p);return x.spot!==''&&x.futures!==''?(Number(x.spot)-Number(x.futures)).toFixed(2):'—'}
function basisPercent(p:number){const x=spreadCell(p);return x.spot!==''&&x.futures!==''&&Number(x.futures)!==0?`${((Number(x.spot)-Number(x.futures))/Number(x.futures)*100).toFixed(2)}%`:'—'}
const dirty=computed(()=>priceDirty.value.size+spreadDirty.value.size>0)
async function confirmDiscard(){if(!dirty.value)return true;try{await ElMessageBox.confirm(t('dailyPrice.unsavedWarning'),t('dailyPrice.unsavedTitle'),{type:'warning'});return true}catch{return false}}
onBeforeRouteLeave(async()=>await confirmDiscard())
function beforeUnload(event:BeforeUnloadEvent){if(dirty.value){event.preventDefault();event.returnValue=''}}
async function loadConfig(){const d=await get<{dimensions:Dimension[]}>('/daily-prices/config');dimensions.value=d.dimensions||[];trendProduct.value ||= products.value[0]?.id||0;if(!trendSuppliers.value.length)trendSuppliers.value=activeSuppliers.value.slice(0,3).map(x=>x.id);trendSpread.value ||= spreadProducts.value[0]?.id||0}
async function loadDay(date:string){loading.value=true;try{const d=await get<{prices:Price[];spreads:Spread[];previous:Record<string,string>}>('/daily-prices/day',{date});dayPrices.value=d.prices||[];daySpreads.value=d.spreads||[];priceDraft.value={};spreadDraft.value={};for(const [key,previousPrice] of Object.entries(d.previous||{}))priceDraft.value[key]={price:'',remark:'',previousPrice};for(const p of dayPrices.value)priceDraft.value[cellKey(p.productId,p.supplierId)]={price:p.price,remark:p.remark,previousPrice:p.previousPrice};for(const p of daySpreads.value)spreadDraft.value[p.productId]={spot:p.spot??'',futures:p.futures??''};priceDirty.value=new Set();spreadDirty.value=new Set();loadedDate.value=date}catch{selectedDate.value=loadedDate.value}finally{loading.value=false}}
async function loadHistory(){const d=await get<{prices:Price[];spreads:Spread[]}>('/daily-prices/day',{date:historyDate.value});historyPrices.value=d.prices||[];historySpreads.value=d.spreads||[]}
watch(selectedDate,async(value,old)=>{if(!value||value===loadedDate.value)return;if(!await confirmDiscard()){selectedDate.value=old;return}await loadDay(value)})
watch(historyDate,loadHistory)
async function savePrices(){savingPrices.value=true;try{const prices=[...priceDirty.value].map(key=>{const [productId,supplierId]=key.split(':').map(Number);return{productId,supplierId,...priceCell(productId,supplierId)}}).map(({productId,supplierId,price,remark})=>({productId,supplierId,price,remark}));await put('/daily-prices/prices',{date:selectedDate.value,prices});await loadDay(selectedDate.value);if(historyDate.value===selectedDate.value)await loadHistory();await loadTrend();ElMessage.success(t('dailyPrice.saved'))}finally{savingPrices.value=false}}
async function saveSpreads(){savingSpreads.value=true;try{const spreads=[...spreadDirty.value].map(productId=>({productId,...spreadCell(productId)}));await put('/daily-prices/spreads',{date:selectedDate.value,spreads});await loadDay(selectedDate.value);if(historyDate.value===selectedDate.value)await loadHistory();await loadTrend();ElMessage.success(t('dailyPrice.saved'))}finally{savingSpreads.value=false}}
const rangeOptions=[{value:'7',label:'dailyPrice.last7'},{value:'30',label:'dailyPrice.last30'},{value:'90',label:'dailyPrice.last90'},{value:'custom',label:'dailyPrice.custom'}]
const rangePreset=ref('30'),customRange=ref<string[]>([]),trendProduct=ref(0),trendSuppliers=ref<number[]>([]),trendSpread=ref(0),spreadMetrics=ref(['spot','futures','basis'])
function rangeDates(){if(rangePreset.value==='custom')return customRange.value.length===2?customRange.value:null;const to=today(),d=new Date(`${to}T12:00:00`);d.setDate(d.getDate()-Number(rangePreset.value)+1);return [`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,to]}
function applyRange(){void loadTrend()}
async function loadTrend(){const range=rangeDates();if(!range)return;const d=await get<{prices:Price[];spreads:Spread[]}>('/daily-prices/trend',{from:range[0],to:range[1],productId:trendProduct.value,supplierId:trendSuppliers.value,spreadProductId:trendSpread.value});trendPrices.value=d.prices||[];trendSpreads.value=d.spreads||[]}
watch([trendProduct,trendSuppliers,trendSpread],()=>{void loadTrend()},{deep:true})
const colors=['#087fb3','#22a96b','#ea8a28','#9061cb','#df6371','#657e98']
const priceLines=computed<TrendLine[]>(()=>trendSuppliers.value.map((id,i)=>({name:suppliers.value.find(x=>x.id===id)?.name||String(id),color:colors[i%colors.length],points:trendPrices.value.filter(p=>p.productId===trendProduct.value&&p.supplierId===id).map(p=>({date:p.date,value:Number(p.price),change:p.previousPrice?changeLabel(p):''}))})).filter(x=>x.points.length))
const spreadLines=computed<TrendLine[]>(()=>spreadMetrics.value.map((metric,i)=>({name:t(`dailyPrice.${metric}`),color:colors[i%colors.length],points:trendSpreads.value.filter(p=>p.productId===trendSpread.value&&p[metric as 'spot'|'futures'|'basis']!=null).map(p=>({date:p.date,value:Number(p[metric as 'spot'|'futures'|'basis'])}))})).filter(x=>x.points.length))
const configKind=ref<'PRODUCT'|'SUPPLIER'|'SPREAD'>('PRODUCT'),configMaster=ref<number|undefined>(),configName=ref(''),masterOptions=ref<{id:number;name:string}[]>([])
const configRows=computed(()=>dimensions.value.filter(x=>x.kind===configKind.value))
async function searchMaster(keyword:string){if(configKind.value==='SPREAD')return;const path=configKind.value==='PRODUCT'?'/products':'/suppliers';const data=await get<{products?:{id:string;name:string}[];suppliers?:{id:string;name:string}[]}>(path,{keyword,page:1,page_size:100,status:'ACTIVE'});masterOptions.value=(data.products||data.suppliers||[]).map(x=>({id:Number(x.id),name:x.name}))}
function openConfig(){configOpen.value=true;void searchMaster('')}
watch(configKind,()=>{configMaster.value=undefined;configName.value='';void searchMaster('')})
async function addConfig(){configSaving.value=true;try{await put('/daily-prices/config',{kind:configKind.value,masterId:configMaster.value||0,name:configName.value.trim(),sortOrder:configRows.value.length});configName.value='';configMaster.value=undefined;await loadConfig();ElMessage.success(t('dailyPrice.saved'))}finally{configSaving.value=false}}
async function toggleConfig(row:Dimension,active:boolean){await put('/daily-prices/config',{id:row.id,kind:row.kind,active,sortOrder:row.sortOrder});await loadConfig()}
async function removeRecord(kind:'prices'|'spreads',id:number){try{await ElMessageBox.confirm(t('dailyPrice.deleteConfirm'),t('dailyPrice.delete'),{type:'warning'})}catch{return}await del(`/daily-prices/${kind}/${id}`);await loadHistory();if(historyDate.value===selectedDate.value)await loadDay(selectedDate.value);await loadTrend()}
function formatTime(value:string){return value?new Date(value).toLocaleString(locale.value):'—'}
onMounted(async()=>{window.addEventListener('beforeunload',beforeUnload);await loadConfig();await Promise.all([loadDay(selectedDate.value),loadHistory(),loadTrend()])})
onUnmounted(()=>window.removeEventListener('beforeunload',beforeUnload))
</script>
<style scoped>
.daily-page{max-width:1700px;margin:auto;padding-bottom:30px}.panel{background:#fff;border:1px solid #dce8f2;border-radius:14px;padding:16px 20px;margin-bottom:18px;box-shadow:0 8px 20px #1b527208}.notice{margin-bottom:16px}.section-head{display:flex;align-items:center;justify-content:space-between;gap:14px;margin-bottom:14px}.section-head h2{font-size:18px;margin:0 0 3px;color:#163347}.section-head p,.helper{font-size:12px;color:#7a8c99;margin:0}.actions,.filters{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.filters{margin-bottom:12px}.filters :deep(.el-select){width:200px}.matrix-scroll{overflow:auto;border:1px solid #dce8f2;border-radius:10px}.price-matrix,.spread-table{width:100%;border-collapse:collapse;table-layout:fixed;font-size:13px}.price-matrix{min-width:max-content}.price-matrix th,.price-matrix td,.spread-table th,.spread-table td{border-bottom:1px solid #e2edf4;border-right:1px solid #e9f0f5;padding:8px;text-align:center;min-width:148px}.price-matrix thead th,.spread-table thead th{background:#f1faff;color:#294558;font-weight:650}.price-matrix .row-label{position:sticky;left:0;min-width:190px;background:#f7fbfd;z-index:1;text-align:left}.price-matrix thead .row-label{z-index:2;background:#f1faff}.price-matrix td.changed,.spread-table tr.changed td{background:#fff9e8}.cell-edit{display:flex;align-items:center;gap:2px}.cell-edit :deep(.el-input){width:112px}.cell-edit :deep(.el-button){padding:3px}.hasRemark{color:#1685b8}.change{font-size:11px;margin-top:3px}.up{color:#d55d38}.down{color:#20946a}.flat{color:#8193a2}.helper{margin-top:9px}.spread-table th,.spread-table td{min-width:130px}.spread-table th:first-child{text-align:left}.spread-table td :deep(.el-input){max-width:180px}.history-table{margin-top:12px}.panel h3{font-size:15px;margin:22px 0 8px;color:#294558}.config-form{display:grid;grid-template-columns:120px 1fr 1fr auto;gap:8px}.remark-label{font-size:12px;color:#607789}
@media(max-width:800px){.config-form{grid-template-columns:1fr}.section-head{align-items:flex-start;flex-direction:column}}
</style>
