<template><div v-loading="loading">
  <div class="page-head"><div><el-button link @click="router.push('/shipping')">← {{ t('shipping.back') }}</el-button><h2>{{ schedule?.scheduleNo }}</h2></div><div v-if="schedule"><el-tag :type="statusTag(schedule.status)">{{ t(`shipping.statuses.${schedule.status}`) }}</el-tag><el-tag v-if="schedule.delayDays>0" :type="schedule.delayDays>=4?'danger':'warning'">+{{schedule.delayDays}}天</el-tag><el-tag v-if="schedule.hasTemporaryCall" type="warning">临时挂港</el-tag><el-button v-if="basicWritable" @click="editOpen=true">编辑基础信息</el-button><el-button v-if="progressWritable" type="primary" @click="progressOpen=true">更新船期进度</el-button><el-button v-if="basicWritable" @click="openStatus">{{ t('shipping.changeStatus') }}</el-button><el-button v-if="basicWritable&&schedule.status!=='ARRIVED'" type="danger" plain @click="cancelSchedule">{{ t('shipping.cancelSchedule') }}</el-button></div></div>
  <el-card v-if="schedule" shadow="never"><el-tabs>
    <el-tab-pane label="基础信息"><el-descriptions :column="2" border><el-descriptions-item :label="t('shipping.contractNo')">{{schedule.contractNo||'—'}}</el-descriptions-item><el-descriptions-item :label="t('shipping.customer')">{{schedule.customerName||'—'}}</el-descriptions-item><el-descriptions-item :label="t('shipping.carrier')">{{schedule.carrierForwarder||'—'}}</el-descriptions-item><el-descriptions-item :label="t('shipping.responsible')">{{schedule.responsibleName}}</el-descriptions-item><el-descriptions-item :label="t('shipping.vessel')">{{schedule.vesselName}}</el-descriptions-item><el-descriptions-item :label="t('shipping.voyage')">{{schedule.voyageNo}}</el-descriptions-item><el-descriptions-item label="原始ETA">{{schedule.originalEta}}</el-descriptions-item><el-descriptions-item label="最新ETA"><span :class="delayClass">{{schedule.eta}}</span><span v-if="schedule.delayDays>0">（+{{schedule.delayDays}}天）</span></el-descriptions-item><el-descriptions-item label="当前进度">{{schedule.currentProgress||'—'}}</el-descriptions-item><el-descriptions-item :label="t('shipping.remark')">{{schedule.remark||'—'}}</el-descriptions-item><el-descriptions-item :label="t('shipping.createdBy')">{{schedule.createdByName}} · {{formatTime(schedule.createdAt)}}</el-descriptions-item><el-descriptions-item :label="t('shipping.updatedBy')">{{schedule.updatedByName}} · {{formatTime(schedule.updatedAt)}}</el-descriptions-item></el-descriptions></el-tab-pane>
    <el-tab-pane label="港口路线">
      <div class="route-head"><div><strong>{{schedule.currentProgress}}</strong><span class="muted"> · 路线版本 {{schedule.routeVersion}}</span></div><el-button v-if="routeWritable" type="primary" plain @click="routeOpen=true">新增港口</el-button></div>
      <el-timeline class="route-timeline"><el-timeline-item v-for="(node,index) in routeNodes" :key="node.id" :type="nodeColor(node)" :hollow="node.nodeStatus==='PLANNED'" placement="top">
        <el-card shadow="never" :class="['route-node',node.nodeType==='TEMPORARY'?'temporary':'']"><div class="node-title"><div><strong>{{node.portName}}</strong><el-tag size="small" :type="node.nodeType==='TEMPORARY'?'warning':'info'">{{nodeTypeText(node.nodeType)}}</el-tag><el-tag v-if="node.nodeType==='TEMPORARY'" size="small" type="warning">临时挂港</el-tag></div><div v-if="routeWritable&&['TRANSIT','TEMPORARY'].includes(node.nodeType)"><el-button link :disabled="index<=1" @click="moveNode(index,-1)">上移</el-button><el-button link :disabled="index>=routeNodes.length-2" @click="moveNode(index,1)">下移</el-button></div></div><div class="times"><span>预计到港：{{formatNodeTime(node.latestEtaAt,node.timezone)}}</span><span>实际到港：{{formatNodeTime(node.actualArrivalAt,node.timezone)}}</span><span>预计离港：{{formatNodeTime(node.latestEtdAt,node.timezone)}}</span><span>实际离港：{{formatNodeTime(node.actualDepartureAt,node.timezone)}}</span></div><div v-if="node.remark" class="muted">{{node.remark}}</div></el-card></el-timeline-item>
      </el-timeline>
      <el-divider content-position="left">延误记录</el-divider>
      <el-table :data="delayEvents" size="small"><el-table-column prop="createdAt" label="时间" width="170"><template #default="{row}">{{formatTime(row.createdAt)}}</template></el-table-column><el-table-column label="ETA变化" width="190"><template #default="{row}">{{row.oldEta}} → {{row.newEta}}</template></el-table-column><el-table-column label="本次变化" width="100"><template #default="{row}"><span :class="row.changeDays>0?'danger-text':'success-text'">{{row.changeDays>0?'+':''}}{{row.changeDays}}天</span></template></el-table-column><el-table-column label="累计" width="100"><template #default="{row}">+{{row.cumulativeDelayDays}}天</template></el-table-column><el-table-column prop="reason" label="原因"/><el-table-column prop="operatorName" label="操作人" width="110"/></el-table>
    </el-tab-pane>
    <el-tab-pane label="单证附件"><el-empty :description="t('shipping.documentsD2')" /></el-tab-pane>
    <el-tab-pane label="变更记录"><el-timeline v-if="changes.length"><el-timeline-item v-for="change in changes" :key="change.id" :timestamp="formatTime(change.createdAt)" placement="top"><strong>{{change.operatorName}} · {{change.changeType}}</strong><div>{{change.fieldName}}：{{change.oldValue||'—'}} → {{change.newValue||'—'}}</div><div class="reason">{{change.reason}}</div></el-timeline-item></el-timeline><el-empty v-else :description="t('shipping.noChanges')" /></el-tab-pane>
  </el-tabs></el-card>
  <ShippingScheduleDialog v-if="schedule" v-model="editOpen" :schedule="schedule" @saved="load" />
  <ShippingRouteNodeDialog v-if="schedule" v-model="routeOpen" :schedule-id="schedule.id" :route-version="schedule.routeVersion" :nodes="routeNodes" @saved="load" />
  <ShippingProgressDialog v-if="schedule" v-model="progressOpen" :schedule-id="schedule.id" :route-version="schedule.routeVersion" :nodes="routeNodes" @saved="load" />
  <el-dialog v-model="statusOpen" :title="t('shipping.changeStatus')" width="480px"><el-form label-width="100px"><el-form-item :label="t('common.status')"><el-select v-model="statusForm.status"><el-option v-for="s in nextStatuses" :key="s" :value="s" :label="t(`shipping.statuses.${s}`)" /></el-select></el-form-item><el-form-item :label="t('shipping.reason')"><el-input v-model="statusForm.reason" type="textarea" :rows="3" /></el-form-item></el-form><template #footer><el-button @click="statusOpen=false">{{t('common.cancel')}}</el-button><el-button type="primary" :loading="saving" @click="saveStatus">{{t('common.save')}}</el-button></template></el-dialog>
</div></template>
<script setup lang="ts">
import { computed,onMounted,reactive,ref } from 'vue';import { ElMessage,ElMessageBox } from 'element-plus';import { useI18n } from 'vue-i18n';import { useRoute,useRouter } from 'vue-router';import { get,post,put } from '../api';import ShippingScheduleDialog from '../components/ShippingScheduleDialog.vue';import ShippingRouteNodeDialog from '../components/ShippingRouteNodeDialog.vue';import ShippingProgressDialog from '../components/ShippingProgressDialog.vue';import { statusTag,type ScheduleChange,type ShippingSchedule,type ShippingRouteNode,type ShippingDelayEvent } from '../shipping';import { useAuthStore } from '../stores/auth'
const {t}=useI18n();const route=useRoute();const router=useRouter();const auth=useAuthStore();const schedule=ref<ShippingSchedule>();const changes=ref<ScheduleChange[]>([]);const routeNodes=ref<ShippingRouteNode[]>([]);const delayEvents=ref<ShippingDelayEvent[]>([]);const loading=ref(false);const saving=ref(false);const editOpen=ref(false);const routeOpen=ref(false);const progressOpen=ref(false);const statusOpen=ref(false);const statusForm=reactive({status:'',reason:''});const transitions:Record<string,string[]>={PLANNED:['SAILED','DELAYED'],SAILED:['IN_TRANSIT','DELAYED'],IN_TRANSIT:['ARRIVED','DELAYED'],DELAYED:['PLANNED','SAILED','IN_TRANSIT','ARRIVED'],ARRIVED:['COMPLETED']};const nextStatuses=computed(()=>transitions[schedule.value?.status??'']??[]);const basicWritable=computed(()=>auth.can('shipping:schedule:write')&&!['COMPLETED','CANCELLED'].includes(schedule.value?.status??''));const routeWritable=computed(()=>auth.can('shipping:route:write')&&basicWritable.value);const progressWritable=computed(()=>auth.can('shipping:progress:write')&&basicWritable.value);const delayClass=computed(()=>schedule.value?.delayDays? schedule.value.delayDays>=4?'danger-text':'warning-text':'success-text')
async function load(){loading.value=true;try{const data=await get<{schedule:ShippingSchedule;changes:ScheduleChange[];routeNodes:ShippingRouteNode[];delayEvents:ShippingDelayEvent[]}>(`/shipping/schedules/${route.params.id}`);schedule.value=data.schedule;changes.value=data.changes;routeNodes.value=data.routeNodes;delayEvents.value=data.delayEvents}finally{loading.value=false}}
function formatTime(v:string){return v?new Date(v).toLocaleString():'—'}function formatNodeTime(v:string,timezone:string){if(!v)return '—';try{return new Intl.DateTimeFormat('zh-CN',{timeZone:timezone||'UTC',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}catch{return formatTime(v)}}function nodeTypeText(v:string){return({ORIGIN:'起运港',TRANSIT:'中转港',TEMPORARY:'临时挂靠港',DESTINATION:'目的港'} as Record<string,string>)[v]??v}function nodeColor(n:ShippingRouteNode){if(n.nodeType==='TEMPORARY')return 'warning';if(['ARRIVED','DEPARTED'].includes(n.nodeStatus))return 'success';return 'primary'}
async function moveNode(index:number,direction:number){if(!schedule.value)return;const reordered=[...routeNodes.value];const [node]=reordered.splice(index,1);reordered.splice(index+direction,0,node);const {value}=await ElMessageBox.prompt('请输入调整路线顺序的原因','调整路线',{inputValidator:v=>!!v.trim()||'原因必填'});await put(`/shipping/schedules/${schedule.value.id}/route/order`,{nodeIds:reordered.map(n=>n.id),reason:value,routeVersion:schedule.value.routeVersion});ElMessage.success('路线顺序已更新');await load()}
function openStatus(){statusForm.status=nextStatuses.value[0]??'';statusForm.reason='';statusOpen.value=true}async function saveStatus(){if(!statusForm.status||!statusForm.reason.trim()){ElMessage.warning(t('shipping.reasonRequired'));return}saving.value=true;try{await post(`/shipping/schedules/${route.params.id}/status`,statusForm);ElMessage.success(t('shipping.statusUpdated'));statusOpen.value=false;await load()}finally{saving.value=false}}async function cancelSchedule(){const {value}=await ElMessageBox.prompt(t('shipping.cancelReasonPrompt'),t('shipping.cancelSchedule'),{inputValidator:v=>!!v.trim()||t('shipping.reasonRequired'),type:'warning'});await post(`/shipping/schedules/${route.params.id}/cancel`,{reason:value});ElMessage.success(t('shipping.cancelled'));await load()}onMounted(load)
</script>
<style scoped>.page-head{display:flex;align-items:flex-end;justify-content:space-between;margin-bottom:16px}.page-head h2{display:inline-block;margin:0 18px 0 8px}.page-head>div{display:flex;align-items:center;gap:10px}.route-head,.node-title{display:flex;align-items:center;justify-content:space-between}.route-head{margin-bottom:18px}.route-timeline{max-width:900px}.route-node.temporary{border-color:var(--el-color-warning)}.node-title>div{display:flex;align-items:center;gap:8px}.times{display:grid;grid-template-columns:repeat(2,minmax(220px,1fr));gap:8px;margin:12px 0;color:var(--el-text-color-regular)}.muted,.reason{color:var(--el-text-color-secondary)}.reason{margin-top:5px}.danger-text{color:var(--el-color-danger);font-weight:600}.warning-text{color:var(--el-color-warning);font-weight:600}.success-text{color:var(--el-color-success);font-weight:600}@media(max-width:700px){.times{grid-template-columns:1fr}.page-head{align-items:flex-start}.page-head>div:last-child{flex-wrap:wrap;justify-content:flex-end}}</style>
