<template><div v-loading="loading">
  <div class="page-head"><div><el-button link @click="router.push('/shipping')">← {{ t('shipping.back') }}</el-button><h2>{{ schedule?.scheduleNo }}</h2></div><div v-if="schedule"><el-tag :type="statusTag(schedule.status)">{{ t(`shipping.statuses.${schedule.status}`) }}</el-tag><el-button v-if="writable" @click="editOpen=true">{{ t('common.edit') }}</el-button><el-button v-if="writable" type="primary" @click="openStatus">{{ t('shipping.changeStatus') }}</el-button><el-button v-if="writable&&schedule.status!=='ARRIVED'" type="danger" plain @click="cancelSchedule">{{ t('shipping.cancelSchedule') }}</el-button></div></div>
  <el-card v-if="schedule" shadow="never"><el-tabs>
    <el-tab-pane :label="t('shipping.basicInfo')"><el-descriptions :column="2" border><el-descriptions-item :label="t('shipping.contractNo')">{{schedule.contractNo||'—'}}</el-descriptions-item><el-descriptions-item :label="t('shipping.customer')">{{schedule.customerName||'—'}}</el-descriptions-item><el-descriptions-item :label="t('shipping.carrier')">{{schedule.carrierForwarder||'—'}}</el-descriptions-item><el-descriptions-item :label="t('shipping.responsible')">{{schedule.responsibleName}}</el-descriptions-item><el-descriptions-item :label="t('shipping.vessel')">{{schedule.vesselName}}</el-descriptions-item><el-descriptions-item :label="t('shipping.voyage')">{{schedule.voyageNo}}</el-descriptions-item><el-descriptions-item :label="t('shipping.loadingPort')">{{schedule.portOfLoading}}</el-descriptions-item><el-descriptions-item :label="t('shipping.dischargePort')">{{schedule.portOfDischarge}}</el-descriptions-item><el-descriptions-item label="ETD">{{schedule.etd}}</el-descriptions-item><el-descriptions-item label="ATD">{{schedule.atd||'—'}}</el-descriptions-item><el-descriptions-item label="ETA">{{schedule.eta}}</el-descriptions-item><el-descriptions-item label="ATA">{{schedule.ata||'—'}}</el-descriptions-item><el-descriptions-item :label="t('shipping.remark')" :span="2">{{schedule.remark||'—'}}</el-descriptions-item><el-descriptions-item :label="t('shipping.createdBy')">{{schedule.createdByName}} · {{formatTime(schedule.createdAt)}}</el-descriptions-item><el-descriptions-item :label="t('shipping.updatedBy')">{{schedule.updatedByName}} · {{formatTime(schedule.updatedAt)}}</el-descriptions-item></el-descriptions></el-tab-pane>
    <el-tab-pane :label="t('shipping.documents')"><el-empty :description="t('shipping.documentsD2')" /></el-tab-pane>
    <el-tab-pane :label="t('shipping.operationLog')"><el-timeline v-if="changes.length"><el-timeline-item v-for="change in changes" :key="change.id" :timestamp="formatTime(change.createdAt)" placement="top"><strong>{{change.operatorName}} · {{t(`shipping.changeTypes.${change.changeType}`)}}</strong><div>{{change.fieldName}}: {{change.oldValue||'—'}} → {{change.newValue||'—'}}</div><div class="reason">{{change.reason}}</div></el-timeline-item></el-timeline><el-empty v-else :description="t('shipping.noChanges')" /></el-tab-pane>
  </el-tabs></el-card>
  <ShippingScheduleDialog v-if="schedule" v-model="editOpen" :schedule="schedule" @saved="load" />
  <el-dialog v-model="statusOpen" :title="t('shipping.changeStatus')" width="480px"><el-form label-width="100px"><el-form-item :label="t('common.status')"><el-select v-model="statusForm.status"><el-option v-for="s in nextStatuses" :key="s" :value="s" :label="t(`shipping.statuses.${s}`)" /></el-select></el-form-item><el-form-item :label="t('shipping.reason')"><el-input v-model="statusForm.reason" type="textarea" :rows="3" /></el-form-item></el-form><template #footer><el-button @click="statusOpen=false">{{t('common.cancel')}}</el-button><el-button type="primary" :loading="saving" @click="saveStatus">{{t('common.save')}}</el-button></template></el-dialog>
</div></template>
<script setup lang="ts">
import { computed,onMounted,reactive,ref } from 'vue';import { ElMessage,ElMessageBox } from 'element-plus';import { useI18n } from 'vue-i18n';import { useRoute,useRouter } from 'vue-router';import { get,post } from '../api';import ShippingScheduleDialog from '../components/ShippingScheduleDialog.vue';import { statusTag,type ScheduleChange,type ShippingSchedule } from '../shipping';import { useAuthStore } from '../stores/auth'
const {t}=useI18n();const route=useRoute();const router=useRouter();const auth=useAuthStore();const schedule=ref<ShippingSchedule>();const changes=ref<ScheduleChange[]>([]);const loading=ref(false);const saving=ref(false);const editOpen=ref(false);const statusOpen=ref(false);const statusForm=reactive({status:'',reason:''});const transitions:Record<string,string[]>={PLANNED:['SAILED','DELAYED'],SAILED:['IN_TRANSIT','DELAYED'],IN_TRANSIT:['ARRIVED','DELAYED'],DELAYED:['PLANNED','SAILED','IN_TRANSIT','ARRIVED'],ARRIVED:['COMPLETED']};const nextStatuses=computed(()=>transitions[schedule.value?.status??'']??[]);const writable=computed(()=>auth.can('shipping:schedule:write')&&!['COMPLETED','CANCELLED'].includes(schedule.value?.status??''))
async function load(){loading.value=true;try{const data=await get<{schedule:ShippingSchedule;changes:ScheduleChange[]}>(`/shipping/schedules/${route.params.id}`);schedule.value=data.schedule;changes.value=data.changes}finally{loading.value=false}}function formatTime(v:string){return v?new Date(v).toLocaleString():'—'}function openStatus(){statusForm.status=nextStatuses.value[0]??'';statusForm.reason='';statusOpen.value=true}async function saveStatus(){if(!statusForm.status||!statusForm.reason.trim()){ElMessage.warning(t('shipping.reasonRequired'));return}saving.value=true;try{await post(`/shipping/schedules/${route.params.id}/status`,statusForm);ElMessage.success(t('shipping.statusUpdated'));statusOpen.value=false;await load()}finally{saving.value=false}}async function cancelSchedule(){const {value}=await ElMessageBox.prompt(t('shipping.cancelReasonPrompt'),t('shipping.cancelSchedule'),{inputValidator:v=>!!v.trim()||t('shipping.reasonRequired'),type:'warning'});await post(`/shipping/schedules/${route.params.id}/cancel`,{reason:value});ElMessage.success(t('shipping.cancelled'));await load()}onMounted(load)
</script>
<style scoped>.page-head{display:flex;align-items:flex-end;justify-content:space-between;margin-bottom:16px}.page-head h2{display:inline-block;margin:0 18px 0 8px}.page-head>div{display:flex;align-items:center;gap:10px}.reason{color:var(--el-text-color-secondary);margin-top:5px}</style>
