<template>
  <div class="detail-page" v-loading="loading">
    <div class="back-row">
      <el-button link class="back" @click="router.push('/sourcing-cases')">← 返回采购询价项目</el-button>
      <el-button link @click="router.push('/procurement')">返回采购工作台</el-button>
    </div>
    <template v-if="detail">
      <header class="hero">
        <div><small>{{ detail.caseNo }}</small><h1>{{ detail.customerName || detail.title }}</h1><p>{{ detail.title }} · 联系人 {{ detail.contactName || detail.contactEmail || '—' }} · 负责人 {{ detail.ownerName || '—' }}</p></div>
        <div class="hero-actions"><el-button v-if="detail.sourceMailId" @click="openSourceMail">查看来源邮件</el-button><el-tag size="large" effect="dark">{{ statusLabel(detail.status) }}</el-tag></div>
      </header>
      <section class="progress-card">
        <div v-for="(item,index) in stages" :key="item.key" :class="['stage',{active:index<=stageIndex}]"><b>{{ index+1 }}</b><span>{{ item.label }}</span></div>
        <aside><small>当前待办</small><strong>{{ waitingText }}</strong></aside>
      </section>

      <section class="content-card">
        <el-tabs v-model="tab" @tab-change="loadTab">
          <el-tab-pane label="产品规范" name="products">
            <div class="section-head"><div><h2>产品规范确认</h2><p>只有完成内部产品匹配并确认的明细才能发送工厂 RFQ。</p></div><el-button v-if="canWrite" type="success" :disabled="!selectedConfirmable.length" @click="batchConfirm">批量确认（{{ selectedConfirmable.length }}）</el-button></div>
            <el-table :data="detail.lines" @selection-change="selected=$event" row-key="id">
              <el-table-column type="selection" width="48" :selectable="row=>row.decision!=='CONFIRMED'&&Number(row.productId)>0" />
              <el-table-column prop="lineNo" label="#" width="55" />
              <el-table-column label="产品与标准" min-width="260"><template #default="{row}"><strong>{{ row.extracted.product||'未填写产品' }}</strong><small>{{ [row.extracted.materialStandard,row.extracted.grade].filter(Boolean).join(' / ')||'标准信息缺失' }}</small><el-tag v-if="missingFields(row).length" class="missing-tag" size="small" type="warning" effect="plain">缺少 {{ missingFields(row).join('、') }}</el-tag></template></el-table-column>
              <el-table-column label="规格" min-width="190"><template #default="{row}">{{ sizeOf(row.extracted) }}</template></el-table-column>
              <el-table-column label="数量" width="130"><template #default="{row}">{{ row.extracted.quantity||'—' }} {{ row.extracted.quantityUnit }}</template></el-table-column>
              <el-table-column label="匹配结果" width="150"><template #default="{row}"><el-tag :type="Number(row.productId)>0?'success':'warning'" effect="plain">{{ Number(row.productId)>0?'已匹配内部产品':'尚未匹配' }}</el-tag></template></el-table-column>
              <el-table-column label="确认状态" width="130"><template #default="{row}"><el-tag :type="decisionType(row.decision)">{{ decisionLabel(row.decision) }}</el-tag><small v-if="row.revisionNo>1">版本 {{ row.revisionNo }}</small></template></el-table-column>
              <el-table-column label="操作" width="100" fixed="right"><template #default="{row}"><el-button v-if="canWrite" link type="primary" @click="openReview(row)">{{ row.decision==='CONFIRMED'?'更正规范':'复核' }}</el-button></template></el-table-column>
            </el-table>
          </el-tab-pane>

          <el-tab-pane label="工厂 RFQ" name="rfqs">
            <div class="section-head"><div><h2>具体工厂询价</h2><p>每份 RFQ 同时锁定供应商、合作工厂、联系人和回复期限。</p></div><el-button v-if="canWrite" type="primary" :disabled="detail.lines.some(x=>x.decision==='PENDING')||!detail.lines.some(x=>x.decision==='CONFIRMED')" @click="openRFQ">新建工厂 RFQ</el-button></div>
            <el-table :data="rfqs">
              <el-table-column prop="rfqNo" label="RFQ 编号" width="185" />
              <el-table-column label="供应商 / 工厂" min-width="230"><template #default="{row}"><strong>{{ row.supplierName }}</strong><small>{{ row.factoryName||'历史数据：未指定工厂' }}</small></template></el-table-column>
              <el-table-column prop="contactEmail" label="联系人邮箱" min-width="210" />
              <el-table-column prop="responseDueAt" label="回复期限" width="130" />
              <el-table-column label="状态" width="130"><template #default="{row}"><el-tag :type="rfqType(row)">{{ rfqLabel(row) }}</el-tag></template></el-table-column>
              <el-table-column label="操作" width="410"><template #default="{row}"><el-button link @click="downloadRFQ(row)">下载 RFQ</el-button><el-button v-if="canWrite" link @click="openEditRFQ(row)">修改</el-button><el-button v-if="canSend&&!['CLOSED','CANCELLED'].includes(row.status)" link type="primary" @click="sendRFQ(row)">{{ row.status==='DRAFT'?'发送':'重新发送' }}</el-button><el-button v-if="canPrice" link type="success" @click="openQuote(row)">录入报价</el-button><el-button v-if="canPrice" link type="success" @click="openImport(row)">导入 Excel</el-button></template></el-table-column>
            </el-table>
          </el-tab-pane>

          <el-tab-pane label="报价跟踪" name="quotes">
            <div class="section-head"><div><h2>工厂报价跟踪</h2><p>本阶段跟踪回复和报价版本；完整横向比价将在 P7 实现。</p></div></div>
            <div class="quote-summary"><div><b>{{ rfqs.length }}</b><span>已发起 RFQ</span></div><div><b>{{ quotedRfqCount }}</b><span>已收到报价</span></div><div><b>{{ overdueCount }}</b><span>已逾期</span></div></div>
            <el-table :data="quoteLines"><el-table-column prop="supplierQuoteNo" label="报价编号" width="180"/><el-table-column prop="supplierName" label="供应商" min-width="180"/><el-table-column label="产品行" width="90"><template #default="{row}">#{{ sourceLineNo(row.sourcingLineId) }}</template></el-table-column><el-table-column label="报价" width="150"><template #default="{row}">{{ row.currency }} {{ row.unitPrice }}</template></el-table-column><el-table-column prop="leadTime" label="交期"/><el-table-column prop="validUntil" label="有效期" width="130"/></el-table>
          </el-tab-pane>

          <el-tab-pane label="成本方案" name="costs">
            <div class="section-head"><div><h2>成本方案</h2><p>保留现有成本测算与客户报价能力；横向比价和版本优化将在 P7 完成。</p></div><el-button v-if="canPrice&&quoteLines.length" type="primary" plain @click="openCostScenario">新建成本方案</el-button></div>
            <el-table :data="costs" @row-click="openCostDetail"><el-table-column prop="scenarioNo" label="方案编号" width="190"/><el-table-column prop="currency" label="币种" width="90"/><el-table-column prop="productTotal" label="产品成本"/><el-table-column prop="chargeTotal" label="费用"/><el-table-column prop="customerTotal" label="客户报价"/><el-table-column label="状态" width="120"><template #default="{row}"><el-tag>{{ row.status }}</el-tag></template></el-table-column><el-table-column label="操作" width="190"><template #default="{row}"><el-button v-if="canApprove&&row.status==='DRAFT'" link type="success" @click.stop="confirmCostScenario(row)">确认方案</el-button><el-button v-if="canApprove&&canCreateQuotation&&row.status==='CONFIRMED'" link type="primary" @click.stop="createCustomerQuotation(row)">{{ Number(row.customerQuotationId||0)>0?'打开客户报价':'生成客户报价' }}</el-button></template></el-table-column></el-table>
          </el-tab-pane>

          <el-tab-pane label="变更记录" name="changes">
            <div class="section-head"><div><h2>统一变更记录</h2><p>产品规范、RFQ、报价和状态变化在这里按时间追溯。</p></div></div>
            <el-timeline><el-timeline-item v-for="item in changes" :key="item.id" :timestamp="formatTime(item.createdAt)" placement="top"><div class="change"><strong>{{ item.summary }}</strong><p>{{ item.operatorName||'系统' }} · {{ item.section }} / {{ item.action }}</p><p v-if="item.reason">原因：{{ item.reason }}</p></div></el-timeline-item></el-timeline>
            <el-empty v-if="!changes.length" description="暂无变更记录" />
          </el-tab-pane>
        </el-tabs>
      </section>
    </template>

    <el-dialog v-model="reviewOpen" :title="reviewing?.decision==='CONFIRMED'?'更正已确认产品规范':'复核产品规范'" width="820px">
      <el-alert v-if="reviewing?.decision==='CONFIRMED'" type="warning" :closable="false" title="本次更正会生成新版本并保留修改前内容。" />
      <el-form label-width="105px" class="review-form"><el-form-item label="内部产品" required><el-select v-model="review.productId" filterable @change="loadSkus"><el-option v-for="p in products" :key="p.id" :value="Number(p.id)" :label="`${p.code} · ${p.name}`"/></el-select></el-form-item><el-form-item label="SKU"><el-select v-model="review.skuId" clearable><el-option v-for="s in skus" :key="s.id" :value="Number(s.id)" :label="`${s.code} · ${s.spec||'—'}`"/></el-select></el-form-item><div class="review-grid"><el-form-item v-for="f in fields" :key="f" :label="fieldLabel(f)"><el-input v-model="review.extracted[f]"/></el-form-item></div><el-form-item v-if="reviewing?.decision==='CONFIRMED'" label="更正原因" required><el-input v-model="review.reason" type="textarea"/></el-form-item></el-form>
      <template #footer><el-button @click="reviewOpen=false">取消</el-button><el-button @click="saveReview('NO_MATCH')">标记未匹配</el-button><el-button type="success" @click="saveReview('CONFIRMED')">确认规范</el-button></template>
    </el-dialog>

    <el-dialog v-model="rfqOpen" title="新建具体工厂 RFQ" width="620px"><el-form label-width="110px"><el-form-item label="供应商 / 工厂" required><SupplierFactorySelect v-model:supplier-id="rfq.supplierId" v-model:factory-id="rfq.factoryId" @factory-selected="factorySelected"/></el-form-item><el-form-item label="联系人邮箱"><el-input v-model="rfq.contactEmail" placeholder="默认读取工厂主联系人，可人工覆盖"/></el-form-item><el-form-item label="币种"><el-input v-model="rfq.currency" maxlength="3"/></el-form-item><el-form-item label="回复期限"><el-date-picker v-model="rfq.responseDueAt" value-format="YYYY-MM-DD"/></el-form-item></el-form><template #footer><el-button @click="rfqOpen=false">取消</el-button><el-button type="primary" @click="createRFQ">创建 RFQ</el-button></template></el-dialog>
    <el-dialog v-model="editRfqOpen" title="修改 RFQ" width="520px"><el-form label-width="100px"><el-form-item label="联系人邮箱"><el-input v-model="editRfq.contactEmail"/></el-form-item><el-form-item label="回复期限"><el-date-picker v-model="editRfq.responseDueAt" value-format="YYYY-MM-DD"/></el-form-item><el-form-item label="修改原因" required><el-input v-model="editRfq.reason" type="textarea"/></el-form-item></el-form><template #footer><el-button @click="editRfqOpen=false">取消</el-button><el-button type="primary" @click="saveRFQ">保存并记录</el-button></template></el-dialog>

    <el-dialog v-model="quoteOpen" title="手工录入工厂报价" width="900px"><el-form inline><el-form-item label="币种"><el-input v-model="quoteForm.currency" style="width:90px"/></el-form-item><el-form-item label="报价日期"><el-date-picker v-model="quoteForm.quotedAt" value-format="YYYY-MM-DD"/></el-form-item><el-form-item label="有效期至"><el-date-picker v-model="quoteForm.validUntil" value-format="YYYY-MM-DD"/></el-form-item><el-form-item label="交期"><el-input v-model="quoteForm.delivery"/></el-form-item><el-form-item label="付款条件"><el-input v-model="quoteForm.paymentTerms"/></el-form-item></el-form><el-table :data="quoteRows" border><el-table-column prop="product" label="产品" min-width="170"/><el-table-column prop="qty" label="数量" width="110"/><el-table-column label="单价" width="140"><template #default="{row}"><el-input v-model="row.unitPrice"/></template></el-table-column><el-table-column label="MOQ" width="120"><template #default="{row}"><el-input v-model="row.moq"/></template></el-table-column><el-table-column label="生产周期" min-width="150"><template #default="{row}"><el-input v-model="row.leadTime"/></template></el-table-column></el-table><template #footer><el-button @click="quoteOpen=false">取消</el-button><el-button type="primary" :loading="saving" @click="saveQuote">保存报价</el-button></template></el-dialog>

    <el-dialog v-model="importOpen" title="导入工厂报价 Excel" width="650px"><el-alert type="info" :closable="false" title="请使用本 RFQ 下载的报价模板，不要修改 RFQ 编号、行 ID、数量或单位。"/><el-form label-width="100px" class="dialog-form"><el-form-item label="报价文件" required><input type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" @change="selectQuoteFile"/></el-form-item><el-form-item label="币种"><el-input v-model="importForm.currency" maxlength="3"/></el-form-item><el-form-item label="报价日期"><el-date-picker v-model="importForm.quotedAt" value-format="YYYY-MM-DD"/></el-form-item><el-form-item label="有效期至"><el-date-picker v-model="importForm.validUntil" value-format="YYYY-MM-DD"/></el-form-item><el-form-item label="交期"><el-input v-model="importForm.delivery"/></el-form-item><el-form-item label="付款条件"><el-input v-model="importForm.paymentTerms"/></el-form-item></el-form><template #footer><el-button @click="importOpen=false">取消</el-button><el-button type="primary" :loading="saving" @click="importQuote">导入报价</el-button></template></el-dialog>

    <el-dialog v-model="costOpen" title="新建成本方案" width="min(1100px,95vw)"><el-form inline><el-form-item label="币种"><el-input v-model="costForm.currency" maxlength="3" style="width:90px"/></el-form-item><el-form-item label="费用分摊"><el-select v-model="costForm.allocationBasis" style="width:170px"><el-option value="TONS" label="按吨数"/><el-option value="PRODUCT_AMOUNT" label="按产品金额"/></el-select></el-form-item><el-form-item label="利润规则"><el-select v-model="costForm.marginType" style="width:170px"><el-option value="PERCENT" label="百分比"/><el-option value="FIXED_PER_TON" label="每吨固定利润"/></el-select></el-form-item><el-form-item label="利润值"><el-input v-model="costForm.marginValue" style="width:110px"/></el-form-item></el-form><h4>为每条产品选择工厂报价</h4><el-table :data="costSelections" border><el-table-column prop="lineNo" label="产品行" width="90"/><el-table-column prop="product" label="产品" min-width="170"/><el-table-column label="选中报价" min-width="430"><template #default="{row}"><el-select v-model="row.quoteLineId" style="width:100%"><el-option v-for="item in quotesForLine(row.sourcingLineId)" :key="item.quoteLineId" :value="item.quoteLineId" :label="`${item.supplierName} · ${item.currency} ${item.unitPrice} × ${item.qty}`"/></el-select></template></el-table-column></el-table><div class="section-head cost-head"><h4>附加费用</h4><el-button @click="addCharge">添加费用</el-button></div><el-table :data="costCharges" border><el-table-column label="费用类型" width="180"><template #default="{row}"><el-select v-model="row.chargeType"><el-option v-for="item in chargeTypes" :key="item" :value="item" :label="item"/></el-select></template></el-table-column><el-table-column label="计费方式" width="160"><template #default="{row}"><el-select v-model="row.basis"><el-option v-for="item in chargeBases" :key="item" :value="item" :label="item"/></el-select></template></el-table-column><el-table-column label="金额" width="130"><template #default="{row}"><el-input v-model="row.amount"/></template></el-table-column><el-table-column label="币种" width="100"><template #default="{row}"><el-input v-model="row.currency"/></template></el-table-column><el-table-column label="来源"><template #default="{row}"><el-input v-model="row.source"/></template></el-table-column></el-table><template #footer><el-button @click="costOpen=false">取消</el-button><el-button type="primary" :loading="saving" @click="createCostScenario">创建方案</el-button></template></el-dialog>

    <el-dialog v-model="costDetailOpen" title="成本方案详情" width="800px"><el-descriptions v-if="costDetail" :column="3" border><el-descriptions-item label="方案编号">{{ costDetail.scenarioNo }}</el-descriptions-item><el-descriptions-item label="状态">{{ costDetail.status }}</el-descriptions-item><el-descriptions-item label="客户报价">{{ costDetail.currency }} {{ costDetail.customerTotal }}</el-descriptions-item></el-descriptions><el-table :data="costDetail?.lines||[]"><el-table-column prop="productName" label="产品"/><el-table-column prop="supplierName" label="供应商"/><el-table-column prop="landedCost" label="落地成本"/><el-table-column prop="customerAmount" label="客户金额"/></el-table></el-dialog>

    <el-dialog v-model="customerMapOpen" title="关联内部客户" width="520px"><el-alert type="info" :closable="false" title="该询盘尚未关联内部客户档案，请先选择客户。"/><el-select v-model="mappedCustomerId" filterable style="width:100%;margin-top:16px"><el-option v-for="item in customers" :key="item.id" :value="item.id" :label="`${item.code} · ${item.name}`"/></el-select><template #footer><el-button @click="customerMapOpen=false">取消</el-button><el-button type="primary" @click="submitMappedCustomer">继续生成报价</el-button></template></el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed,onMounted,reactive,ref } from 'vue';import { useRoute,useRouter } from 'vue-router';import { ElMessage,ElMessageBox } from 'element-plus';import { download,get,post,put,saveBlob } from '../api';import { useAuthStore } from '../stores/auth';import SupplierFactorySelect from '../components/masterdata/SupplierFactorySelect.vue'
type AnyRow=Record<string,any>;const route=useRoute(),router=useRouter(),auth=useAuthStore(),id=String(route.params.id);const canWrite=auth.can('procurement:sourcing:write'),canSend=auth.can('procurement:sourcing:send'),canPrice=auth.can('procurement:sourcing:price'),canApprove=auth.can('procurement:sourcing:approve'),canCreateQuotation=auth.can('export:quotation:write');const loading=ref(false),saving=ref(false),detail=ref<AnyRow>(),rfqs=ref<AnyRow[]>([]),quoteLines=ref<AnyRow[]>([]),costs=ref<AnyRow[]>([]),changes=ref<AnyRow[]>([]),tab=ref('products'),selected=ref<AnyRow[]>([]),products=ref<AnyRow[]>([]),skus=ref<AnyRow[]>([]),reviewOpen=ref(false),reviewing=ref<AnyRow>(),rfqOpen=ref(false),editRfqOpen=ref(false),editingRfq=ref<AnyRow>(),quoteOpen=ref(false),quotingRfq=ref<AnyRow>(),quoteRows=ref<AnyRow[]>([]),importOpen=ref(false),importingRfq=ref<AnyRow>(),quoteFile=ref<File|null>(null),costOpen=ref(false),costDetailOpen=ref(false),costDetail=ref<AnyRow>(),customers=ref<AnyRow[]>([]),customerMapOpen=ref(false),mappedCustomerId=ref(''),pendingCostScenario=ref<AnyRow>()
const blank=()=>({product:'',materialStandard:'',grade:'',thickness:'',width:'',lengthOrForm:'',surfaceRequirement:'',coating:'',tolerance:'',coilWeight:'',coilId:'',packaging:'',delivery:'',paymentTerms:'',incoterm:'',port:'',quantityUnit:'',remarks:'',quantity:''});const review=reactive<any>({productId:0,skuId:0,extracted:blank(),reason:''}),rfq=reactive<any>({supplierId:'',factoryId:'',factoryCode:'',factoryName:'',contactEmail:'',currency:'USD',responseDueAt:''}),editRfq=reactive({contactEmail:'',responseDueAt:'',reason:''}),quoteForm=reactive({currency:'USD',quotedAt:'',validUntil:'',delivery:'',paymentTerms:''}),importForm=reactive({currency:'USD',quotedAt:'',validUntil:'',delivery:'',paymentTerms:''}),costForm=reactive({currency:'USD',allocationBasis:'TONS',marginType:'PERCENT',marginValue:'8'}),costSelections=ref<AnyRow[]>([]),costCharges=reactive<AnyRow[]>([]);const chargeTypes=['ORIGIN_TERMINAL','DESTINATION_TERMINAL','OCEAN_FREIGHT','INSURANCE','DOCUMENT','FINANCE','OTHER'],chargeBases=['PER_TON','PER_CONTAINER','PER_SHIPMENT','FIXED'];const fields=['product','materialStandard','grade','thickness','width','lengthOrForm','surfaceRequirement','packaging','delivery','paymentTerms','incoterm','port','quantityUnit','quantity','remarks'];const stages=[{key:'REVIEWING',label:'规范确认'},{key:'SOURCING',label:'工厂询价'},{key:'QUOTES_RECEIVED',label:'报价跟踪'},{key:'COSTING',label:'成本方案'},{key:'CUSTOMER_QUOTE_CREATED',label:'客户报价'}];const stageIndex=computed(()=>stages.findIndex(x=>x.key===detail.value?.status)),selectedConfirmable=computed(()=>selected.value.filter(x=>x.decision!=='CONFIRMED'&&Number(x.productId)>0)),quotedRfqCount=computed(()=>new Set(quoteLines.value.map(x=>String(x.factoryRfqId))).size),overdueCount=computed(()=>rfqs.value.filter(isOverdue).length),waitingText=computed(()=>({REVIEWING:'确认产品规范',SOURCING:'等待工厂报价',QUOTES_RECEIVED:'完成报价比较',COSTING:'确认成本方案',CUSTOMER_QUOTE_CREATED:'客户确认',CANCELLED:'项目已取消'} as any)[detail.value?.status]||'处理中')
async function load(){loading.value=true;try{const [a,b,c,d]=await Promise.all([get<any>(`/sourcing-cases/${id}`),get<any>(`/sourcing-cases/${id}/factory-rfqs`),get<any>(`/sourcing-cases/${id}/supplier-quotes`),get<any>(`/sourcing-cases/${id}/cost-scenarios`)]);detail.value=a.sourcingCase;rfqs.value=b.factoryRfqs||[];quoteLines.value=c.lines||[];costs.value=d.costScenarios||[]}finally{loading.value=false}}
async function loadTab(name:any){if(name==='changes')changes.value=(await get<any>(`/sourcing-cases/${id}/changes`)).changes||[]}
function statusLabel(v:string){return ({REVIEWING:'规范确认中',SOURCING:'工厂询价中',QUOTES_RECEIVED:'已收到报价',COSTING:'成本测算中',CUSTOMER_QUOTE_CREATED:'已生成客户报价',CANCELLED:'已取消'} as any)[v]||v}function decisionLabel(v:string){return ({PENDING:'待确认',CONFIRMED:'已确认',NO_MATCH:'未匹配',SKIPPED:'暂不采购'} as any)[v]||v}function decisionType(v:string){return v==='CONFIRMED'?'success':v==='PENDING'?'warning':'info'}function sizeOf(x:any){return [x.thickness,x.width,x.lengthOrForm].filter(Boolean).join(' × ')||'—'}function fieldLabel(v:string){return ({product:'产品',materialStandard:'材质/标准',grade:'牌号',thickness:'厚度',width:'宽度',lengthOrForm:'长度/形式',surfaceRequirement:'表面要求',packaging:'包装',delivery:'交期',paymentTerms:'付款条件',incoterm:'贸易术语',port:'港口',quantityUnit:'单位',quantity:'数量',remarks:'备注'} as any)[v]||v}function missingFields(row:any){const names:{[key:string]:string}={product:'产品',quantity:'数量',quantityUnit:'单位'};return Object.entries(names).filter(([key])=>!String(row.extracted?.[key]||'').trim()).map(([,name])=>name)}function formatTime(v:string){return v?new Date(v).toLocaleString():'—'}function sourceLineNo(v:string){return detail.value?.lines.find((x:any)=>String(x.id)===String(v))?.lineNo||v}function isOverdue(x:any){return ['SENT','PARTIALLY_QUOTED'].includes(x.status)&&x.responseDueAt&&new Date(x.responseDueAt).getTime()<Date.now()}function rfqLabel(x:any){return isOverdue(x)?'已逾期':({DRAFT:'草稿',SENT:'已发送',PARTIALLY_QUOTED:'部分报价',QUOTED:'已报价',CLOSED:'已关闭',CANCELLED:'已取消'} as any)[x.status]||x.status}function rfqType(x:any){return isOverdue(x)?'danger':x.status==='QUOTED'?'success':'info'}function openSourceMail(){void router.push({path:'/emails',query:{message:detail.value?.sourceMailId}})}
async function openReview(row:any){if(!products.value.length)products.value=(await get<any>('/products',{page_size:200,status:'ACTIVE'})).products||[];reviewing.value=row;Object.assign(review,{productId:Number(row.productId||0),skuId:Number(row.skuId||0),extracted:{...blank(),...row.extracted},reason:''});await loadSkus(true);reviewOpen.value=true}async function loadSkus(keep=false){const old=keep?review.skuId:0;review.skuId=0;skus.value=review.productId?(await get<any>(`/products/${review.productId}/skus`)).skus?.filter((x:any)=>x.status==='ACTIVE')||[]:[];if(old&&skus.value.some(x=>Number(x.id)===old))review.skuId=old}async function saveReview(decision:string){if(decision==='CONFIRMED'&&!review.productId){ElMessage.warning('请先匹配内部产品');return}if(reviewing.value?.decision==='CONFIRMED'&&!review.reason.trim()){ElMessage.warning('请填写更正原因');return}const d=await put<any>(`/sourcing-cases/${id}/lines/${reviewing.value.id}`,{product_id:review.productId,sku_id:review.skuId,extracted:review.extracted,decision,reason:review.reason});detail.value=d.sourcingCase;reviewOpen.value=false;ElMessage.success('产品规范已保存')}
async function batchConfirm(){await post(`/sourcing-cases/${id}/confirm-lines`,{sourcing_line_ids:selectedConfirmable.value.map(x=>Number(x.id))});await load();ElMessage.success('所选产品规范已确认')}
function openRFQ(){Object.assign(rfq,{supplierId:'',factoryId:'',factoryCode:'',factoryName:'',contactEmail:'',currency:'USD',responseDueAt:''});rfqOpen.value=true}async function factorySelected(factory:any){rfq.factoryCode=factory?.code||'';rfq.factoryName=factory?.nameZh||factory?.nameEn||'';rfq.contactEmail='';if(factory?.id){const d=await get<any>(`/factories/${factory.id}/contacts`);rfq.contactEmail=(d.contacts||[]).find((x:any)=>x.isPrimary&&x.status==='ACTIVE')?.email||''}}async function createRFQ(){if(!rfq.supplierId||!rfq.factoryId){ElMessage.warning('请选择供应商和具体合作工厂');return}await post(`/sourcing-cases/${id}/factory-rfqs`,{supplier_id:Number(rfq.supplierId),factory_id:Number(rfq.factoryId),factory_code:rfq.factoryCode,factory_name:rfq.factoryName,contact_email:rfq.contactEmail,currency:rfq.currency,response_due_at:rfq.responseDueAt,sourcing_line_ids:detail.value.lines.filter((x:any)=>x.decision==='CONFIRMED').map((x:any)=>Number(x.id))});rfqOpen.value=false;await load();ElMessage.success('工厂 RFQ 已创建')}
function openEditRFQ(row:any){editingRfq.value=row;Object.assign(editRfq,{contactEmail:row.contactEmail,responseDueAt:row.responseDueAt,reason:''});editRfqOpen.value=true}async function saveRFQ(){if(!editRfq.reason.trim()){ElMessage.warning('请填写修改原因');return}await put(`/factory-rfqs/${editingRfq.value.id}`,{contact_email:editRfq.contactEmail,response_due_at:editRfq.responseDueAt,reason:editRfq.reason});editRfqOpen.value=false;await load();ElMessage.success('RFQ 已修改并记录')}
async function sendRFQ(row:any){if(!row.contactEmail){ElMessage.warning('当前工厂没有可用的询价联系人，请先修改收件邮箱');return}await ElMessageBox.confirm(`确认发送 ${row.rfqNo} 到 ${row.contactEmail}？`);await post(`/factory-rfqs/${row.id}/send`,{recipient_email:row.contactEmail});await load();ElMessage.success('RFQ 已发送')}async function downloadRFQ(row:any){const f=await download(`/factory-rfqs/${row.id}/workbook`);saveBlob(f.blob,f.fileName||`${row.rfqNo}.xlsx`)}

// openQuote 根据 RFQ 包含的产品行创建录入表格，避免员工把报价填到错误产品上。
function openQuote(row:any){quotingRfq.value=row;Object.assign(quoteForm,{currency:row.currency||'USD',quotedAt:'',validUntil:'',delivery:'',paymentTerms:''});const included=new Set((row.sourcingLineIds||[]).map(String));quoteRows.value=(detail.value?.lines||[]).filter((line:any)=>included.has(String(line.id))).map((line:any)=>({sourcingLineId:line.id,product:line.extracted.product,qty:line.extracted.quantity,unitPrice:'',moq:'',leadTime:''}));quoteOpen.value=true}
async function saveQuote(){if(!quotingRfq.value||quoteRows.value.some(row=>row.unitPrice===''||Number(row.unitPrice)<0)){ElMessage.warning('请填写全部产品的有效单价');return}saving.value=true;try{await post(`/factory-rfqs/${quotingRfq.value.id}/supplier-quotes`,{quoted_at:quoteForm.quotedAt,valid_until:quoteForm.validUntil,currency:quoteForm.currency,payment_terms:quoteForm.paymentTerms,delivery:quoteForm.delivery,source:'MANUAL',lines:quoteRows.value.map(row=>({sourcing_line_id:Number(row.sourcingLineId),qty:row.qty,unit_price:row.unitPrice,moq:row.moq,lead_time:row.leadTime}))});quoteOpen.value=false;await load();ElMessage.success('工厂报价已保存')}finally{saving.value=false}}
function openImport(row:any){importingRfq.value=row;quoteFile.value=null;Object.assign(importForm,{currency:row.currency||'USD',quotedAt:'',validUntil:'',delivery:'',paymentTerms:''});importOpen.value=true}
function selectQuoteFile(event:Event){quoteFile.value=(event.target as HTMLInputElement).files?.[0]??null}
async function fileBase64(file:File){const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(binary)}
async function importQuote(){if(!importingRfq.value||!quoteFile.value){ElMessage.warning('请选择工厂回传的 XLSX 报价文件');return}if(quoteFile.value.size>2*1024*1024){ElMessage.warning('报价文件不能超过 2 MB');return}saving.value=true;try{await post(`/factory-rfqs/${importingRfq.value.id}/supplier-quotes/import`,{file_data:await fileBase64(quoteFile.value),quoted_at:importForm.quotedAt,valid_until:importForm.validUntil,currency:importForm.currency,payment_terms:importForm.paymentTerms,delivery:importForm.delivery});importOpen.value=false;await load();ElMessage.success('工厂报价已导入')}finally{saving.value=false}}

function quotesForLine(lineID:string){return quoteLines.value.filter(item=>String(item.sourcingLineId)===String(lineID))}
function openCostScenario(){Object.assign(costForm,{currency:'USD',allocationBasis:'TONS',marginType:'PERCENT',marginValue:'8'});costSelections.value=(detail.value?.lines||[]).filter((line:any)=>line.decision==='CONFIRMED').map((line:any)=>({sourcingLineId:line.id,lineNo:line.lineNo,product:line.extracted.product,quoteLineId:quotesForLine(line.id)[0]?.quoteLineId||''}));costCharges.splice(0);addCharge();costOpen.value=true}
function addCharge(){costCharges.push({chargeType:'ORIGIN_TERMINAL',basis:'PER_TON',amount:'',currency:costForm.currency,source:''})}
async function createCostScenario(){if(costSelections.value.some(line=>!line.quoteLineId)){ElMessage.warning('请为每条产品选择一个工厂报价');return}if(costCharges.some(item=>item.amount===''||Number(item.amount)<0)){ElMessage.warning('请填写有效的费用金额');return}saving.value=true;try{await post(`/sourcing-cases/${id}/cost-scenarios`,{currency:costForm.currency,allocation_basis:costForm.allocationBasis,margin_type:costForm.marginType,margin_value:costForm.marginValue,selections:costSelections.value.map(line=>({sourcing_line_id:Number(line.sourcingLineId),supplier_quote_line_id:Number(line.quoteLineId)})),charges:costCharges.map(item=>({charge_type:item.chargeType,basis:item.basis,amount:item.amount,currency:item.currency,source:item.source}))});costOpen.value=false;await load();ElMessage.success('成本方案已创建')}finally{saving.value=false}}
async function openCostDetail(row:any){costDetail.value=(await get<any>(`/cost-scenarios/${row.id}`)).costScenario;costDetailOpen.value=true}
async function confirmCostScenario(row:any){await post(`/cost-scenarios/${row.id}/confirm`);await load();ElMessage.success('成本方案已确认')}
async function createCustomerQuotation(row:any){if(Number(row.customerQuotationId||0)>0){await router.push({path:'/quotations',query:{quote:row.customerQuotationId}});return}if(!Number(detail.value?.customerId||0)){customers.value=(await get<any>('/customers',{page_size:200,status:'ACTIVE'})).customers||[];pendingCostScenario.value=row;mappedCustomerId.value='';customerMapOpen.value=true;return}await performCreateCustomerQuotation(row,detail.value.customerId)}
async function submitMappedCustomer(){if(!pendingCostScenario.value||!mappedCustomerId.value){ElMessage.warning('请选择内部客户');return}customerMapOpen.value=false;await performCreateCustomerQuotation(pendingCostScenario.value,mappedCustomerId.value)}
async function performCreateCustomerQuotation(row:any,customerID:string){saving.value=true;try{const response=await post<any>(`/cost-scenarios/${row.id}/create-customer-quotation`,{customer_id:Number(customerID)});ElMessage.success(`客户报价 ${response.quoteNo} 已生成`);await router.push({path:'/quotations',query:{quote:response.quotationId}})}finally{saving.value=false}}
onMounted(load)
</script>
<style scoped>
.detail-page{padding:22px;background:#f5f7fa;min-height:calc(100vh - 60px)}.back{margin-bottom:12px}.hero,.progress-card,.content-card{background:#fff;border:1px solid #dce5ec;border-radius:14px}.hero{display:flex;justify-content:space-between;align-items:center;padding:24px 28px;background:linear-gradient(135deg,#f6fbfb,#fff)}.hero small{color:#61788d}.hero h1{margin:5px 0;color:#17324d}.hero p{margin:0;color:#738397}.hero-actions{display:flex;gap:10px;align-items:center}.progress-card{display:flex;align-items:center;margin:14px 0;padding:18px 22px}.stage{display:flex;align-items:center;gap:8px;color:#9aa6b2;flex:1}.stage:after{content:'';height:2px;background:#dfe6eb;flex:1}.stage:last-of-type:after{display:none}.stage b{display:grid;place-items:center;width:25px;height:25px;border-radius:50%;background:#e9eef2}.stage.active{color:#087f77}.stage.active b{background:#0f9d8a;color:white}.progress-card aside{border-left:1px solid #e3e8ed;padding-left:22px;min-width:170px}.progress-card aside small,.progress-card aside strong{display:block}.content-card{padding:8px 24px 24px}.section-head{display:flex;justify-content:space-between;align-items:center;margin:8px 0 16px}.section-head h2{margin:0;color:#17324d;font-size:19px}.section-head p{margin:5px 0 0;color:#7a8998}.el-table small{display:block;color:#8795a3;margin-top:4px}.missing-tag{margin-top:6px}.quote-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-bottom:16px}.quote-summary div{padding:16px;border-radius:10px;background:#f4f9f8}.quote-summary b,.quote-summary span{display:block}.quote-summary b{font-size:24px;color:#087f77}.change{padding:13px;border:1px solid #e1e8ee;border-radius:9px}.change p{margin:5px 0 0;color:#768696}.review-form,.dialog-form{margin-top:14px}.review-form .el-select{width:100%}.review-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 12px}.cost-head{margin-top:18px}@media(max-width:850px){.hero,.section-head{align-items:flex-start;gap:12px;flex-direction:column}.progress-card{overflow:auto}.stage{min-width:140px}.progress-card aside{display:none}.review-grid{grid-template-columns:1fr}}
</style>
