$ErrorActionPreference='Stop'
$base='http://127.0.0.1:28382'
$password='D5-Acceptance-2026!'
function Login([string]$email,[string]$loginPassword=$password){Invoke-RestMethod "$base/api/auth/login" -Method Post -ContentType 'application/json' -Body (@{email=$email;password=$loginPassword}|ConvertTo-Json) -SessionVariable loginSession|Out-Null;return $loginSession}
function Request($session,[string]$method,[string]$path,$body){$headers=@{};foreach($cookie in $session.Cookies.GetCookies([uri]$base)){if($cookie.Name-eq'erp_csrf'){$headers['X-CSRF-Token']=$cookie.Value}};$args=@{Uri="$base/api$path";Method=$method;WebSession=$session;Headers=$headers;ContentType='application/json'};if($null-ne$body){$args.Body=$body|ConvertTo-Json -Depth 20 -Compress};return (Invoke-RestMethod @args).data}
$buyerId=(docker exec erp-gap-20260913-postgres-1 psql -U erp_iam -d erp_iam -At -c "SELECT id FROM employees WHERE tenant_id=1 AND code='D5-P1'").Trim()
$salesId=(docker exec erp-gap-20260913-postgres-1 psql -U erp_iam -d erp_iam -At -c "SELECT id FROM employees WHERE tenant_id=1 AND code='D5-S1'").Trim()
if(!$buyerId-or!$salesId){throw 'Acceptance accounts are missing'}
$sql="DO `$`$ DECLARE r bigint; p bigint; BEGIN IF NOT EXISTS(SELECT 1 FROM purchase_orders WHERE tenant_id=1 AND po_no='PO-GAP-MANUAL-001') THEN INSERT INTO purchase_requirements(tenant_id,contract_id,contract_no,contract_version_id,contract_item_id,product_id,product_code,product_name,uom_id,uom_code,required_qty,ordered_qty,status,owner_id) VALUES(1,9711,'CT-GAP-MANUAL',1,9711,112,'PIPE-M','人工验收钢管',1,'MT',10,10,'ORDERED',$salesId) RETURNING id INTO r; INSERT INTO purchase_orders(tenant_id,po_no,supplier_id,supplier_code,supplier_name,currency,total_amount,expected_date,status,buyer_id,buyer_name,ordered_at,business_type) VALUES(1,'PO-GAP-MANUAL-001',912,'GAP-M01','人工验收工厂','CNY',20000,'2026-10-20','ORDERED',$buyerId,'P1',now(),'PROCUREMENT') RETURNING id INTO p; INSERT INTO purchase_order_items(tenant_id,po_id,requirement_id,product_id,product_code,product_name,spec,uom_id,uom_code,qty,unit_price,amount) VALUES(1,p,r,112,'PIPE-M','人工验收钢管','Q235 / 60mm',1,'MT',10,2000,20000); ELSE UPDATE purchase_orders SET buyer_id=$buyerId,buyer_name='P1',status='ORDERED',business_type='PROCUREMENT' WHERE tenant_id=1 AND po_no='PO-GAP-MANUAL-001'; END IF; END `$`$;"
docker exec erp-gap-20260913-postgres-1 psql -v ON_ERROR_STOP=1 -U erp_procurement -d erp_procurement -c $sql|Out-Null
$poId=(docker exec erp-gap-20260913-postgres-1 psql -U erp_procurement -d erp_procurement -At -c "SELECT id FROM purchase_orders WHERE tenant_id=1 AND po_no='PO-GAP-MANUAL-001'").Trim()
$applySql="DO `$`$ DECLARE r1 bigint; r2 bigint; p bigint; BEGIN IF NOT EXISTS(SELECT 1 FROM purchase_orders WHERE tenant_id=1 AND po_no='PO-GAP-APPLY-001') THEN INSERT INTO purchase_requirements(tenant_id,contract_id,contract_no,contract_version_id,contract_item_id,product_id,product_code,product_name,uom_id,uom_code,required_qty,ordered_qty,status,owner_id) VALUES(1,9712,'CT-GAP-APPLY',1,97121,113,'PLATE-M','人工验收钢板',1,'MT',6,6,'ORDERED',$salesId) RETURNING id INTO r1; INSERT INTO purchase_requirements(tenant_id,contract_id,contract_no,contract_version_id,contract_item_id,product_id,product_code,product_name,uom_id,uom_code,required_qty,ordered_qty,status,owner_id) VALUES(1,9712,'CT-GAP-APPLY',1,97122,114,'COIL-M','人工验收钢卷',1,'MT',4,4,'ORDERED',$salesId) RETURNING id INTO r2; INSERT INTO purchase_orders(tenant_id,po_no,supplier_id,supplier_code,supplier_name,currency,total_amount,expected_date,status,buyer_id,buyer_name,ordered_at,business_type) VALUES(1,'PO-GAP-APPLY-001',913,'GAP-M02','整单质检验收工厂','CNY',23000,'2026-10-22','ORDERED',$buyerId,'P1',now(),'PROCUREMENT') RETURNING id INTO p; INSERT INTO purchase_order_items(tenant_id,po_id,requirement_id,product_id,product_code,product_name,spec,uom_id,uom_code,qty,unit_price,amount) VALUES(1,p,r1,113,'PLATE-M','人工验收钢板','Q235 / 8mm',1,'MT',6,2500,15000),(1,p,r2,114,'COIL-M','人工验收钢卷','SPCC / 1mm',1,'MT',4,2000,8000); ELSE UPDATE purchase_orders SET buyer_id=$buyerId,buyer_name='P1',status='ORDERED',business_type='PROCUREMENT' WHERE tenant_id=1 AND po_no='PO-GAP-APPLY-001'; END IF; END `$`$;"
docker exec erp-gap-20260913-postgres-1 psql -v ON_ERROR_STOP=1 -U erp_procurement -d erp_procurement -c $applySql|Out-Null
$applyPoId=(docker exec erp-gap-20260913-postgres-1 psql -U erp_procurement -d erp_procurement -At -c "SELECT id FROM purchase_orders WHERE tenant_id=1 AND po_no='PO-GAP-APPLY-001'").Trim()
$applyCleanup="BEGIN; DELETE FROM quality_inspection_files WHERE tenant_id=1 AND task_id IN (SELECT id FROM quality_inspection_tasks WHERE tenant_id=1 AND po_id=$applyPoId); DELETE FROM quality_inspection_round_lines WHERE tenant_id=1 AND round_id IN (SELECT r.id FROM quality_inspection_rounds r JOIN quality_inspection_tasks t ON t.id=r.task_id AND t.tenant_id=r.tenant_id WHERE t.tenant_id=1 AND t.po_id=$applyPoId); DELETE FROM quality_inspection_rounds WHERE tenant_id=1 AND task_id IN (SELECT id FROM quality_inspection_tasks WHERE tenant_id=1 AND po_id=$applyPoId); DELETE FROM quality_inspection_task_lines WHERE tenant_id=1 AND task_id IN (SELECT id FROM quality_inspection_tasks WHERE tenant_id=1 AND po_id=$applyPoId); DELETE FROM quality_inspection_tasks WHERE tenant_id=1 AND po_id=$applyPoId; COMMIT;"
docker exec erp-gap-20260913-postgres-1 psql -v ON_ERROR_STOP=1 -U erp_procurement -d erp_procurement -c $applyCleanup|Out-Null
$cleanup="BEGIN; DELETE FROM quality_inspection_files WHERE tenant_id=1 AND task_id IN (SELECT id FROM quality_inspection_tasks WHERE tenant_id=1 AND po_id=$poId); DELETE FROM quality_inspection_round_lines WHERE tenant_id=1 AND round_id IN (SELECT r.id FROM quality_inspection_rounds r JOIN quality_inspection_tasks t ON t.id=r.task_id AND t.tenant_id=r.tenant_id WHERE t.tenant_id=1 AND t.po_id=$poId); DELETE FROM quality_inspection_rounds WHERE tenant_id=1 AND task_id IN (SELECT id FROM quality_inspection_tasks WHERE tenant_id=1 AND po_id=$poId); DELETE FROM quality_inspection_task_lines WHERE tenant_id=1 AND task_id IN (SELECT id FROM quality_inspection_tasks WHERE tenant_id=1 AND po_id=$poId); DELETE FROM quality_inspection_tasks WHERE tenant_id=1 AND po_id=$poId; COMMIT;"
docker exec erp-gap-20260913-postgres-1 psql -v ON_ERROR_STOP=1 -U erp_procurement -d erp_procurement -c $cleanup|Out-Null
$buyer=Login 'p1@d5.example.test';$quality=Login 'q1@d5.example.test';$other=Login 'd6.p1@d5.example.test' 'D6-Acceptance-2026!'
$task=(Request $buyer POST "/purchase-orders/$poId/quality-inspections" @{inspectionLocation='人工验收工厂';expectedDate='2026-09-16';contactName='王师傅';contactPhone='13800000000';remark='整张采购单一次性送检'}).task
$repeat=(Request $buyer POST "/purchase-orders/$poId/quality-inspections" @{inspectionLocation='不应新建第二批'}).task
if($repeat.id-ne$task.id){throw 'Repeated apply created a second task'}
$lineId=$task.lines[0].id
$task=(Request $quality POST "/quality/tasks/$($task.id)/rounds" @{inspectionLocation='人工验收工厂';remark='人工验收示例：留待采购处理';lines=@(@{taskLineId=$lineId;result='PARTIAL';inspectedQty='10';qualifiedQty='8';unqualifiedQty='2';issueDescription='2 MT 表面划痕';handlingSuggestion='联系工厂返工后复检'})}).task
$presign=Request $quality POST "/quality/tasks/$($task.id)/files/presign" @{fileName='人工验收质检说明.txt'}
$tmp=Join-Path $env:TEMP '人工验收质检说明.txt';[IO.File]::WriteAllText($tmp,'PO-GAP-MANUAL-001：10 MT 整单质检，8 MT 合格，2 MT 表面划痕待返工。',[Text.UTF8Encoding]::new($false));& curl.exe --silent --show-error --fail -X PUT -H 'Content-Type: text/plain; charset=utf-8' --upload-file $tmp $presign.uploadUrl;if($LASTEXITCODE){throw 'Attachment upload failed'}
$task=(Request $quality POST "/quality/tasks/$($task.id)/files" @{roundId=$task.rounds[0].id;taskLineId=$lineId;category='REPORT';fileKey=$presign.fileKey;fileName='人工验收质检说明.txt';contentType='text/plain';sizeBytes=(Get-Item $tmp).Length}).task
$ownerTodos=@((Request $buyer GET '/quality/procurement-todos' $null).tasks);$otherTodos=@((Request $other GET '/quality/procurement-todos' $null).tasks)
if(!($ownerTodos|Where-Object poNo -eq 'PO-GAP-MANUAL-001')){throw 'P1 acceptance todo missing'}
if($otherTodos|Where-Object poNo -eq 'PO-GAP-MANUAL-001'){throw 'Unrelated purchaser can see acceptance todo'}
$evidence=[ordered]@{readyToApplyOrder='PO-GAP-APPLY-001 (6 MT + 4 MT)';purchaseOrder='PO-GAP-MANUAL-001';taskNo=$task.taskNo;taskId=$task.id;requestedQty=$task.lines[0].requestedQty;qualifiedQty=$task.lines[0].qualifiedQty;unresolvedQty=$task.lines[0].unresolvedQty;owner='P1';todo='PENDING';repeatApply='returned original task';attachment=$task.files[0].fileName;preparedAt=(Get-Date).ToString('o')}
$evidence|ConvertTo-Json -Depth 6|Set-Content (Join-Path $PSScriptRoot 'manual-acceptance-evidence.json') -Encoding utf8
$evidence|ConvertTo-Json -Compress
