// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApprovalDefinition struct {
	ID        int64
	TenantID  int64
	BizType   string
	Name      string
	Version   int32
	Status    string
	CreatedAt pgtype.Timestamptz
}

type ApprovalInstance struct {
	ID            int64
	TenantID      int64
	DefinitionID  int64
	BizType       string
	BizID         int64
	BizNo         string
	BizSummary    []byte
	SubmitterID   int64
	SubmitterName string
	Status        string
	CurrentSeq    int32
	SubmittedAt   pgtype.Timestamptz
	FinishedAt    pgtype.Timestamptz
}

type ApprovalNode struct {
	ID           int64
	TenantID     int64
	DefinitionID int64
	Seq          int32
	Name         string
	ApproverType string
	ApproverRef  int64
	ApproveMode  string
}

type ApprovalTask struct {
	ID         int64
	TenantID   int64
	InstanceID int64
	NodeSeq    int32
	NodeName   string
	AssigneeID int64
	Status     string
	Comment    string
	ActedAt    pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type OutboxEvent struct {
	ID            int64
	TenantID      int64
	AggregateType string
	AggregateID   string
	EventType     string
	Payload       []byte
	TraceID       *string
	CreatedAt     pgtype.Timestamptz
	PublishedAt   pgtype.Timestamptz
	Attempts      int32
	LastError     *string
}

type ProcessedEvent struct {
	EventID       string
	ConsumerGroup string
	ProcessedAt   pgtype.Timestamptz
}
