// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AttributeDef struct {
	ID            int64
	TenantID      int64
	TemplateID    int64
	Key           string
	Label         string
	DataType      string
	Unit          string
	EnumValues    []byte
	MatchStrategy string
	TolerancePct  pgtype.Numeric
	Level         string
	IsMatchable   bool
	IsRequired    bool
	SortOrder     int32
}

type AttributeTemplate struct {
	ID         int64
	TenantID   int64
	CategoryID int64
	Name       string
	CreatedAt  pgtype.Timestamptz
}

type Product struct {
	ID                int64
	TenantID          int64
	Code              string
	Name              string
	NameEn            string
	CategoryID        int64
	ProductType       string
	Brand             string
	BaseUomID         int64
	ReferencePrice    pgtype.Numeric
	ReferenceCurrency string
	HsCode            string
	TaxRate           pgtype.Numeric
	ExportRebateRate  pgtype.Numeric
	Description       string
	Status            string
	CreatedAt         pgtype.Timestamptz
	CreatedBy         int64
	UpdatedAt         pgtype.Timestamptz
	UpdatedBy         int64
	Attributes        []byte
}

type ProductAttachment struct {
	ID          int64
	TenantID    int64
	ProductID   int64
	FileName    string
	FileKey     string
	FileSize    int64
	ContentType string
	UploadedBy  int64
	UploadedAt  pgtype.Timestamptz
}

type ProductCategory struct {
	ID        int64
	TenantID  int64
	Code      string
	Name      string
	ParentID  *int64
	Path      string
	Level     int32
	SortOrder int32
	Status    string
}

type Sku struct {
	ID            int64
	TenantID      int64
	ProductID     int64
	Code          string
	Spec          string
	Attributes    []byte
	Status        string
	CreatedAt     pgtype.Timestamptz
	AttrSignature string
}

type Uom struct {
	ID       int64
	TenantID int64
	Code     string
	Name     string
	UomType  string
	Status   string
}
