// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product.sql

package store

import (
	"context"
)

const activateProduct = `-- name: ActivateProduct :execrows
UPDATE products SET status = 'ACTIVE', updated_at = now(), updated_by = $3
WHERE tenant_id = $1 AND id = $2 AND status = 'INACTIVE'
`

type ActivateProductParams struct {
	TenantID  int64
	ID        int64
	UpdatedBy int64
}

func (q *Queries) ActivateProduct(ctx context.Context, arg ActivateProductParams) (int64, error) {
	result, err := q.db.Exec(ctx, activateProduct, arg.TenantID, arg.ID, arg.UpdatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countCategories = `-- name: CountCategories :one
SELECT count(*)::bigint FROM product_categories WHERE tenant_id = $1
`

func (q *Queries) CountCategories(ctx context.Context, tenantID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countCategories, tenantID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countProductsInCategory = `-- name: CountProductsInCategory :one
SELECT count(*) FROM products WHERE tenant_id = $1 AND category_id = $2
`

type CountProductsInCategoryParams struct {
	TenantID   int64
	CategoryID int64
}

func (q *Queries) CountProductsInCategory(ctx context.Context, arg CountProductsInCategoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProductsInCategory, arg.TenantID, arg.CategoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUoms = `-- name: CountUoms :one

SELECT count(*)::bigint FROM uoms WHERE tenant_id = $1
`

// 下面四条只服务「新公司开张时补上默认单位和分类」，见 app/catalogseed.go。
// 任何状态都算：「一条都没有」和「有但都停用了」是两件事。
func (q *Queries) CountUoms(ctx context.Context, tenantID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUoms, tenantID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO product_attachments (
    tenant_id, product_id, file_name, file_key, file_size, content_type, uploaded_by
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, product_id, file_name, file_key, file_size, content_type, uploaded_by, uploaded_at
`

type CreateAttachmentParams struct {
	TenantID    int64
	ProductID   int64
	FileName    string
	FileKey     string
	FileSize    int64
	ContentType string
	UploadedBy  int64
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (ProductAttachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.TenantID,
		arg.ProductID,
		arg.FileName,
		arg.FileKey,
		arg.FileSize,
		arg.ContentType,
		arg.UploadedBy,
	)
	var i ProductAttachment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProductID,
		&i.FileName,
		&i.FileKey,
		&i.FileSize,
		&i.ContentType,
		&i.UploadedBy,
		&i.UploadedAt,
	)
	return i, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO product_categories (tenant_id, code, name, parent_id, path, level, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, code, name, parent_id, path, level, sort_order, status
`

type CreateCategoryParams struct {
	TenantID  int64
	Code      string
	Name      string
	ParentID  *int64
	Path      string
	Level     int32
	SortOrder int32
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (ProductCategory, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.ParentID,
		arg.Path,
		arg.Level,
		arg.SortOrder,
	)
	var i ProductCategory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.ParentID,
		&i.Path,
		&i.Level,
		&i.SortOrder,
		&i.Status,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    tenant_id, code, name, name_en, category_id, product_type, brand, base_uom_id,
    reference_price, reference_currency, hs_code, tax_rate, export_rebate_rate,
    description, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    nullif($13::text, '')::numeric,
    $9, $10,
    nullif($14::text, '')::numeric,
    nullif($15::text, '')::numeric,
    $11, $12, $12
)
RETURNING id
`

type CreateProductParams struct {
	TenantID          int64
	Code              string
	Name              string
	NameEn            string
	CategoryID        int64
	ProductType       string
	Brand             string
	BaseUomID         int64
	ReferenceCurrency string
	HsCode            string
	Description       string
	CreatedBy         int64
	ReferencePrice    string
	TaxRate           string
	ExportRebateRate  string
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (int64, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.NameEn,
		arg.CategoryID,
		arg.ProductType,
		arg.Brand,
		arg.BaseUomID,
		arg.ReferenceCurrency,
		arg.HsCode,
		arg.Description,
		arg.CreatedBy,
		arg.ReferencePrice,
		arg.TaxRate,
		arg.ExportRebateRate,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createSku = `-- name: CreateSku :one
INSERT INTO skus (tenant_id, product_id, code, spec, attributes, attr_signature)
VALUES ($1, $2, $3, $4, $5::jsonb, $6::text)
RETURNING id, tenant_id, product_id, code, spec, attributes, status, created_at, attr_signature
`

type CreateSkuParams struct {
	TenantID      int64
	ProductID     int64
	Code          string
	Spec          string
	Attributes    []byte
	AttrSignature string
}

func (q *Queries) CreateSku(ctx context.Context, arg CreateSkuParams) (Sku, error) {
	row := q.db.QueryRow(ctx, createSku,
		arg.TenantID,
		arg.ProductID,
		arg.Code,
		arg.Spec,
		arg.Attributes,
		arg.AttrSignature,
	)
	var i Sku
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProductID,
		&i.Code,
		&i.Spec,
		&i.Attributes,
		&i.Status,
		&i.CreatedAt,
		&i.AttrSignature,
	)
	return i, err
}

const createUom = `-- name: CreateUom :one
INSERT INTO uoms (tenant_id, code, name, uom_type) VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, code, name, uom_type, status
`

type CreateUomParams struct {
	TenantID int64
	Code     string
	Name     string
	UomType  string
}

func (q *Queries) CreateUom(ctx context.Context, arg CreateUomParams) (Uom, error) {
	row := q.db.QueryRow(ctx, createUom,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.UomType,
	)
	var i Uom
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.UomType,
		&i.Status,
	)
	return i, err
}

const deactivateCategory = `-- name: DeactivateCategory :execrows
UPDATE product_categories SET status = 'INACTIVE'
WHERE tenant_id = $1 AND id = $2 AND status = 'ACTIVE'
`

type DeactivateCategoryParams struct {
	TenantID int64
	ID       int64
}

func (q *Queries) DeactivateCategory(ctx context.Context, arg DeactivateCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateCategory, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deactivateProduct = `-- name: DeactivateProduct :execrows
UPDATE products SET status = 'INACTIVE', updated_at = now(), updated_by = $3
WHERE tenant_id = $1 AND id = $2 AND status <> 'INACTIVE'
`

type DeactivateProductParams struct {
	TenantID  int64
	ID        int64
	UpdatedBy int64
}

func (q *Queries) DeactivateProduct(ctx context.Context, arg DeactivateProductParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateProduct, arg.TenantID, arg.ID, arg.UpdatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deactivateSku = `-- name: DeactivateSku :execrows
UPDATE skus SET status = 'INACTIVE'
WHERE tenant_id = $1 AND id = $2 AND status = 'ACTIVE'
`

type DeactivateSkuParams struct {
	TenantID int64
	ID       int64
}

func (q *Queries) DeactivateSku(ctx context.Context, arg DeactivateSkuParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateSku, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAttachment = `-- name: DeleteAttachment :execrows
DELETE FROM product_attachments WHERE tenant_id = $1 AND id = $2
`

type DeleteAttachmentParams struct {
	TenantID int64
	ID       int64
}

func (q *Queries) DeleteAttachment(ctx context.Context, arg DeleteAttachmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAttachment, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAttachment = `-- name: GetAttachment :one
SELECT id, tenant_id, product_id, file_name, file_key, file_size, content_type, uploaded_by, uploaded_at FROM product_attachments WHERE tenant_id = $1 AND id = $2
`

type GetAttachmentParams struct {
	TenantID int64
	ID       int64
}

func (q *Queries) GetAttachment(ctx context.Context, arg GetAttachmentParams) (ProductAttachment, error) {
	row := q.db.QueryRow(ctx, getAttachment, arg.TenantID, arg.ID)
	var i ProductAttachment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProductID,
		&i.FileName,
		&i.FileKey,
		&i.FileSize,
		&i.ContentType,
		&i.UploadedBy,
		&i.UploadedAt,
	)
	return i, err
}

const getCategory = `-- name: GetCategory :one
SELECT id, tenant_id, code, name, parent_id, path, level, sort_order, status FROM product_categories WHERE tenant_id = $1 AND id = $2
`

type GetCategoryParams struct {
	TenantID int64
	ID       int64
}

func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (ProductCategory, error) {
	row := q.db.QueryRow(ctx, getCategory, arg.TenantID, arg.ID)
	var i ProductCategory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.ParentID,
		&i.Path,
		&i.Level,
		&i.SortOrder,
		&i.Status,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT
    p.id, p.tenant_id, p.code, p.name, p.name_en, p.category_id, p.product_type,
    p.brand, p.base_uom_id,
    -- coalesce, not a bare cast: NULL::text is still NULL, and sqlc infers a
    -- non-nullable string from the cast alone. A product saved without a
    -- reference price then breaks every read of it.
    coalesce(p.reference_price::text, '')::text     AS reference_price,
    p.reference_currency, p.hs_code,
    coalesce(p.tax_rate::text, '')::text            AS tax_rate,
    coalesce(p.export_rebate_rate::text, '')::text  AS export_rebate_rate,
    p.description, p.status, p.attributes,
    c.name AS category_name, u.code AS base_uom_code
FROM products p
JOIN product_categories c ON c.id = p.category_id AND c.tenant_id = p.tenant_id
JOIN uoms u ON u.id = p.base_uom_id AND u.tenant_id = p.tenant_id
WHERE p.tenant_id = $1 AND p.id = $2
`

type GetProductParams struct {
	TenantID int64
	ID       int64
}

type GetProductRow struct {
	ID                int64
	TenantID          int64
	Code              string
	Name              string
	NameEn            string
	CategoryID        int64
	ProductType       string
	Brand             string
	BaseUomID         int64
	ReferencePrice    string
	ReferenceCurrency string
	HsCode            string
	TaxRate           string
	ExportRebateRate  string
	Description       string
	Status            string
	Attributes        []byte
	CategoryName      string
	BaseUomCode       string
}

func (q *Queries) GetProduct(ctx context.Context, arg GetProductParams) (GetProductRow, error) {
	row := q.db.QueryRow(ctx, getProduct, arg.TenantID, arg.ID)
	var i GetProductRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.NameEn,
		&i.CategoryID,
		&i.ProductType,
		&i.Brand,
		&i.BaseUomID,
		&i.ReferencePrice,
		&i.ReferenceCurrency,
		&i.HsCode,
		&i.TaxRate,
		&i.ExportRebateRate,
		&i.Description,
		&i.Status,
		&i.Attributes,
		&i.CategoryName,
		&i.BaseUomCode,
	)
	return i, err
}

const insertCategoryIfAbsent = `-- name: InsertCategoryIfAbsent :execrows
INSERT INTO product_categories (tenant_id, code, name, path, level, sort_order)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (tenant_id, code) DO NOTHING
`

type InsertCategoryIfAbsentParams struct {
	TenantID  int64
	Code      string
	Name      string
	Path      string
	Level     int32
	SortOrder int32
}

func (q *Queries) InsertCategoryIfAbsent(ctx context.Context, arg InsertCategoryIfAbsentParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertCategoryIfAbsent,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.Path,
		arg.Level,
		arg.SortOrder,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertUomIfAbsent = `-- name: InsertUomIfAbsent :execrows
INSERT INTO uoms (tenant_id, code, name, uom_type) VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, code) DO NOTHING
`

type InsertUomIfAbsentParams struct {
	TenantID int64
	Code     string
	Name     string
	UomType  string
}

func (q *Queries) InsertUomIfAbsent(ctx context.Context, arg InsertUomIfAbsentParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertUomIfAbsent,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.UomType,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAttachments = `-- name: ListAttachments :many
SELECT id, tenant_id, product_id, file_name, file_key, file_size, content_type, uploaded_by, uploaded_at FROM product_attachments
WHERE tenant_id = $1 AND product_id = $2
ORDER BY uploaded_at DESC
`

type ListAttachmentsParams struct {
	TenantID  int64
	ProductID int64
}

func (q *Queries) ListAttachments(ctx context.Context, arg ListAttachmentsParams) ([]ProductAttachment, error) {
	rows, err := q.db.Query(ctx, listAttachments, arg.TenantID, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductAttachment
	for rows.Next() {
		var i ProductAttachment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProductID,
			&i.FileName,
			&i.FileKey,
			&i.FileSize,
			&i.ContentType,
			&i.UploadedBy,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many

SELECT id, tenant_id, code, name, parent_id, path, level, sort_order, status FROM product_categories
WHERE tenant_id = $1 AND ($2::text = '' OR status = $2)
ORDER BY sort_order, code
`

type ListCategoriesParams struct {
	TenantID int64
	Column2  string
}

// Numeric columns travel as text on purpose: Go keeps decimal strings so a
// price never passes through float64. See pkg/money.
func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]ProductCategory, error) {
	rows, err := q.db.Query(ctx, listCategories, arg.TenantID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductCategory
	for rows.Next() {
		var i ProductCategory
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.ParentID,
			&i.Path,
			&i.Level,
			&i.SortOrder,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT
    p.id, p.tenant_id, p.code, p.name, p.name_en, p.category_id, p.product_type,
    p.brand, p.base_uom_id,
    -- coalesce, not a bare cast: NULL::text is still NULL, and sqlc infers a
    -- non-nullable string from the cast alone. A product saved without a
    -- reference price then breaks every read of it.
    coalesce(p.reference_price::text, '')::text     AS reference_price,
    p.reference_currency, p.hs_code,
    coalesce(p.tax_rate::text, '')::text            AS tax_rate,
    coalesce(p.export_rebate_rate::text, '')::text  AS export_rebate_rate,
    p.description, p.status, p.attributes,
    c.name AS category_name, u.code AS base_uom_code,
    count(*) OVER () AS total
FROM products p
JOIN product_categories c ON c.id = p.category_id AND c.tenant_id = p.tenant_id
JOIN uoms u ON u.id = p.base_uom_id AND u.tenant_id = p.tenant_id
WHERE p.tenant_id = $1
  AND ($2::text = 'ALL' OR p.status = coalesce(nullif($2::text, ''), 'ACTIVE'))
  AND ($3::bigint = 0 OR p.category_id = $3::bigint)
  AND ($4::text = ''
       OR p.name ILIKE '%' || $4::text || '%'
       OR p.name_en ILIKE '%' || $4::text || '%'
       OR p.code ILIKE '%' || $4::text || '%')
ORDER BY p.id DESC
LIMIT $6::int OFFSET $5::int
`

type ListProductsParams struct {
	TenantID   int64
	Status     string
	CategoryID int64
	Keyword    string
	RowOffset  int32
	RowLimit   int32
}

type ListProductsRow struct {
	ID                int64
	TenantID          int64
	Code              string
	Name              string
	NameEn            string
	CategoryID        int64
	ProductType       string
	Brand             string
	BaseUomID         int64
	ReferencePrice    string
	ReferenceCurrency string
	HsCode            string
	TaxRate           string
	ExportRebateRate  string
	Description       string
	Status            string
	Attributes        []byte
	CategoryName      string
	BaseUomCode       string
	Total             int64
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.TenantID,
		arg.Status,
		arg.CategoryID,
		arg.Keyword,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.NameEn,
			&i.CategoryID,
			&i.ProductType,
			&i.Brand,
			&i.BaseUomID,
			&i.ReferencePrice,
			&i.ReferenceCurrency,
			&i.HsCode,
			&i.TaxRate,
			&i.ExportRebateRate,
			&i.Description,
			&i.Status,
			&i.Attributes,
			&i.CategoryName,
			&i.BaseUomCode,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkus = `-- name: ListSkus :many
SELECT id, tenant_id, product_id, code, spec, attributes, status, created_at, attr_signature FROM skus WHERE tenant_id = $1 AND product_id = $2 ORDER BY id
`

type ListSkusParams struct {
	TenantID  int64
	ProductID int64
}

func (q *Queries) ListSkus(ctx context.Context, arg ListSkusParams) ([]Sku, error) {
	rows, err := q.db.Query(ctx, listSkus, arg.TenantID, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sku
	for rows.Next() {
		var i Sku
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProductID,
			&i.Code,
			&i.Spec,
			&i.Attributes,
			&i.Status,
			&i.CreatedAt,
			&i.AttrSignature,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUoms = `-- name: ListUoms :many
SELECT id, tenant_id, code, name, uom_type, status FROM uoms WHERE tenant_id = $1 AND status = 'ACTIVE' ORDER BY uom_type, code
`

func (q *Queries) ListUoms(ctx context.Context, tenantID int64) ([]Uom, error) {
	rows, err := q.db.Query(ctx, listUoms, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Uom
	for rows.Next() {
		var i Uom
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.UomType,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE product_categories SET name = $3, sort_order = $4
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, code, name, parent_id, path, level, sort_order, status
`

type UpdateCategoryParams struct {
	TenantID  int64
	ID        int64
	Name      string
	SortOrder int32
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (ProductCategory, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.TenantID,
		arg.ID,
		arg.Name,
		arg.SortOrder,
	)
	var i ProductCategory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.ParentID,
		&i.Path,
		&i.Level,
		&i.SortOrder,
		&i.Status,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :execrows
UPDATE products SET
    name = $3, name_en = $4, category_id = $5, product_type = $6, brand = $7,
    base_uom_id = $8,
    reference_price = nullif($13::text, '')::numeric,
    reference_currency = $9, hs_code = $10,
    tax_rate = nullif($14::text, '')::numeric,
    export_rebate_rate = nullif($15::text, '')::numeric,
    description = $11, updated_at = now(), updated_by = $12
WHERE tenant_id = $1 AND id = $2
`

type UpdateProductParams struct {
	TenantID          int64
	ID                int64
	Name              string
	NameEn            string
	CategoryID        int64
	ProductType       string
	Brand             string
	BaseUomID         int64
	ReferenceCurrency string
	HsCode            string
	Description       string
	UpdatedBy         int64
	ReferencePrice    string
	TaxRate           string
	ExportRebateRate  string
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProduct,
		arg.TenantID,
		arg.ID,
		arg.Name,
		arg.NameEn,
		arg.CategoryID,
		arg.ProductType,
		arg.Brand,
		arg.BaseUomID,
		arg.ReferenceCurrency,
		arg.HsCode,
		arg.Description,
		arg.UpdatedBy,
		arg.ReferencePrice,
		arg.TaxRate,
		arg.ExportRebateRate,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
