// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contract.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addContractItem = `-- name: AddContractItem :exec
INSERT INTO contract_items (
    tenant_id, contract_version_id, line_no, product_id, sku_id, product_code,
    product_name, spec, qty, uom_id, uom_code, unit_price, amount, hs_code, remark
) VALUES (
    $1::bigint,
    $2::bigint,
    $3::int,
    $4::bigint,
    $5::bigint,
    $6::text,
    $7::text,
    $8::text,
    $9::text::numeric,
    $10::bigint,
    $11::text,
    $12::text::numeric,
    $13::text::numeric,
    $14::text,
    $15::text
)
`

type AddContractItemParams struct {
	TenantID          int64
	ContractVersionID int64
	LineNo            int32
	ProductID         int64
	SkuID             *int64
	ProductCode       string
	ProductName       string
	Spec              string
	Qty               string
	UomID             int64
	UomCode           string
	UnitPrice         string
	Amount            string
	HsCode            string
	Remark            string
}

func (q *Queries) AddContractItem(ctx context.Context, arg AddContractItemParams) error {
	_, err := q.db.Exec(ctx, addContractItem,
		arg.TenantID,
		arg.ContractVersionID,
		arg.LineNo,
		arg.ProductID,
		arg.SkuID,
		arg.ProductCode,
		arg.ProductName,
		arg.Spec,
		arg.Qty,
		arg.UomID,
		arg.UomCode,
		arg.UnitPrice,
		arg.Amount,
		arg.HsCode,
		arg.Remark,
	)
	return err
}

const addExistingContractCorrection = `-- name: AddExistingContractCorrection :exec
INSERT INTO contract_corrections (
    tenant_id, contract_id, contract_version_id, before_data, after_data,
    corrected_by, corrected_by_name
) VALUES (
    $1::bigint, $2::bigint,
    $3::bigint, $4::jsonb,
    $5::jsonb, $6::bigint,
    $7::text
)
`

type AddExistingContractCorrectionParams struct {
	TenantID          int64
	ContractID        int64
	ContractVersionID int64
	BeforeData        []byte
	AfterData         []byte
	CorrectedBy       int64
	CorrectedByName   string
}

func (q *Queries) AddExistingContractCorrection(ctx context.Context, arg AddExistingContractCorrectionParams) error {
	_, err := q.db.Exec(ctx, addExistingContractCorrection,
		arg.TenantID,
		arg.ContractID,
		arg.ContractVersionID,
		arg.BeforeData,
		arg.AfterData,
		arg.CorrectedBy,
		arg.CorrectedByName,
	)
	return err
}

const addExistingContractItem = `-- name: AddExistingContractItem :one
INSERT INTO contract_items (
    tenant_id, contract_version_id, line_no, product_id, sku_id, product_code,
    product_name, spec, qty, uom_id, uom_code, unit_price, amount, hs_code, remark,
    opening_procured_qty, opening_arrived_qty, opening_shipped_qty
) VALUES (
    $1::bigint,
    $2::bigint,
    $3::int,
    $4::bigint,
    $5::bigint,
    $6::text,
    $7::text,
    $8::text,
    $9::text::numeric,
    $10::bigint,
    $11::text,
    $12::text::numeric,
    $13::text::numeric,
    $14::text,
    $15::text,
    $16::text::numeric,
    $17::text::numeric,
    $18::text::numeric
)
RETURNING id
`

type AddExistingContractItemParams struct {
	TenantID           int64
	ContractVersionID  int64
	LineNo             int32
	ProductID          int64
	SkuID              *int64
	ProductCode        string
	ProductName        string
	Spec               string
	Qty                string
	UomID              int64
	UomCode            string
	UnitPrice          string
	Amount             string
	HsCode             string
	Remark             string
	OpeningProcuredQty string
	OpeningArrivedQty  string
	OpeningShippedQty  string
}

func (q *Queries) AddExistingContractItem(ctx context.Context, arg AddExistingContractItemParams) (int64, error) {
	row := q.db.QueryRow(ctx, addExistingContractItem,
		arg.TenantID,
		arg.ContractVersionID,
		arg.LineNo,
		arg.ProductID,
		arg.SkuID,
		arg.ProductCode,
		arg.ProductName,
		arg.Spec,
		arg.Qty,
		arg.UomID,
		arg.UomCode,
		arg.UnitPrice,
		arg.Amount,
		arg.HsCode,
		arg.Remark,
		arg.OpeningProcuredQty,
		arg.OpeningArrivedQty,
		arg.OpeningShippedQty,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const clearContractFilePending = `-- name: ClearContractFilePending :exec
UPDATE contracts SET file_pending = FALSE, updated_at = now()
WHERE tenant_id = $1::bigint AND id = $2::bigint
`

type ClearContractFilePendingParams struct {
	TenantID int64
	ID       int64
}

func (q *Queries) ClearContractFilePending(ctx context.Context, arg ClearContractFilePendingParams) error {
	_, err := q.db.Exec(ctx, clearContractFilePending, arg.TenantID, arg.ID)
	return err
}

const correctExistingContractHeader = `-- name: CorrectExistingContractHeader :execrows
UPDATE contracts SET
    external_contract_no = $1::text,
    signed_at = $2::text::date,
    effective_at = $3::text::date,
    receivable_due_date = nullif($4::text, '')::date,
    updated_at = now(), updated_by = $5::bigint
WHERE tenant_id = $6::bigint
  AND id = $7::bigint
  AND entry_source = 'EXISTING_CONTRACT'
  AND status <> 'CANCELLED'
`

type CorrectExistingContractHeaderParams struct {
	ExternalContractNo string
	SignedDate         string
	EffectiveDate      string
	ReceivableDueDate  string
	UpdatedBy          int64
	TenantID           int64
	ID                 int64
}

func (q *Queries) CorrectExistingContractHeader(ctx context.Context, arg CorrectExistingContractHeaderParams) (int64, error) {
	result, err := q.db.Exec(ctx, correctExistingContractHeader,
		arg.ExternalContractNo,
		arg.SignedDate,
		arg.EffectiveDate,
		arg.ReceivableDueDate,
		arg.UpdatedBy,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const correctExistingContractVersion = `-- name: CorrectExistingContractVersion :execrows
WITH correction_enabled AS (
    SELECT set_config('erp.contract_correction', 'on', true)
)
UPDATE contract_versions SET
    buyer_name = $1::text,
    buyer_address = $2::text,
    seller_name = $3::text,
    seller_address = $4::text,
    incoterm = $5::text,
    port_of_loading = $6::text,
    port_of_discharge = $7::text,
    payment_method = $8::text,
    delivery_date = nullif($9::text, '')::date,
    terms = $10::text
FROM correction_enabled
WHERE tenant_id = $11::bigint
  AND id = $12::bigint
  AND status = 'APPROVED'
`

type CorrectExistingContractVersionParams struct {
	BuyerName       string
	BuyerAddress    string
	SellerName      string
	SellerAddress   string
	Incoterm        string
	PortOfLoading   string
	PortOfDischarge string
	PaymentMethod   string
	DeliveryDate    string
	Terms           string
	TenantID        int64
	ID              int64
}

func (q *Queries) CorrectExistingContractVersion(ctx context.Context, arg CorrectExistingContractVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, correctExistingContractVersion,
		arg.BuyerName,
		arg.BuyerAddress,
		arg.SellerName,
		arg.SellerAddress,
		arg.Incoterm,
		arg.PortOfLoading,
		arg.PortOfDischarge,
		arg.PaymentMethod,
		arg.DeliveryDate,
		arg.Terms,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countSignedAttachments = `-- name: CountSignedAttachments :one
SELECT count(*) FROM contract_attachments
WHERE tenant_id = $1 AND contract_version_id = $2
  AND kind = 'SIGNED'
`

type CountSignedAttachmentsParams struct {
	TenantID          int64
	ContractVersionID *int64
}

// Evidence that a specific version came back countersigned. Scoped to the
// version on purpose: a scan of v1 says nothing about the v2 that replaced it.
func (q *Queries) CountSignedAttachments(ctx context.Context, arg CountSignedAttachmentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSignedAttachments, arg.TenantID, arg.ContractVersionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createContract = `-- name: CreateContract :one

INSERT INTO contracts (
    tenant_id, contract_no, quotation_id, quote_no, customer_id, customer_name,
    sales_employee_id, sales_employee, receivable_due_date, created_by, updated_by
) VALUES (
    $1::bigint,
    $2::text,
    nullif($3::bigint, 0),
    $4::text,
    $5::bigint,
    $6::text,
    $7::bigint,
    $8::text,
    -- 应收到期日：这份合同的钱什么时候该收回来。**建合同的人填**，可空。
    -- 不再从客户主数据的账期推——同一个客户这一单谈 60 天、下一单要求
    -- 预付，都是常事。
    nullif($9::text, '')::date,
    $10::bigint,
    $10::bigint
)
RETURNING id
`

type CreateContractParams struct {
	TenantID          int64
	ContractNo        string
	QuotationID       int64
	QuoteNo           string
	CustomerID        int64
	CustomerName      string
	SalesEmployeeID   int64
	SalesEmployee     string
	ReceivableDueDate string
	CreatedBy         int64
}

// Money crosses this boundary as text, same rule as quotations: Go holds
// decimal strings and never a float64. See pkg/money.
//
// Statements that mix casts with parameters use named arguments throughout;
// interleaving them with positional $n leaves sqlc unable to infer a type.
func (q *Queries) CreateContract(ctx context.Context, arg CreateContractParams) (int64, error) {
	row := q.db.QueryRow(ctx, createContract,
		arg.TenantID,
		arg.ContractNo,
		arg.QuotationID,
		arg.QuoteNo,
		arg.CustomerID,
		arg.CustomerName,
		arg.SalesEmployeeID,
		arg.SalesEmployee,
		arg.ReceivableDueDate,
		arg.CreatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createContractAttachment = `-- name: CreateContractAttachment :one
INSERT INTO contract_attachments (
    tenant_id, contract_id, contract_version_id, kind, file_name, file_key,
    content_type, size_bytes, uploaded_by, uploader_name, source
) VALUES (
    $1::bigint,
    $2::bigint,
    nullif($3::bigint, 0),
    $4::text,
    $5::text,
    $6::text,
    $7::text,
    $8::bigint,
    $9::bigint,
    $10::text,
    $11::text
)
RETURNING id
`

type CreateContractAttachmentParams struct {
	TenantID          int64
	ContractID        int64
	ContractVersionID int64
	Kind              string
	FileName          string
	FileKey           string
	ContentType       string
	SizeBytes         int64
	UploadedBy        int64
	UploaderName      string
	Source            string
}

func (q *Queries) CreateContractAttachment(ctx context.Context, arg CreateContractAttachmentParams) (int64, error) {
	row := q.db.QueryRow(ctx, createContractAttachment,
		arg.TenantID,
		arg.ContractID,
		arg.ContractVersionID,
		arg.Kind,
		arg.FileName,
		arg.FileKey,
		arg.ContentType,
		arg.SizeBytes,
		arg.UploadedBy,
		arg.UploaderName,
		arg.Source,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createContractVersion = `-- name: CreateContractVersion :one
INSERT INTO contract_versions (
    tenant_id, contract_id, version_no, buyer_name, buyer_address,
    seller_name, seller_address, currency, incoterm,
    port_of_loading, port_of_discharge, payment_method,
    delivery_date, terms, total_amount, base_amount,
    fx_rate, fx_rate_at, fx_source, fx_base_currency, change_reason, created_by
) VALUES (
    $1::bigint,
    $2::bigint,
    $3::int,
    $4::text,
    $5::text,
    $6::text,
    $7::text,
    $8::text,
    $9::text,
    $10::text,
    $11::text,
    $12::text,
    nullif($13::text, '')::date,
    $14::text,
    $15::text::numeric,
    $16::text::numeric,
    $17::text::numeric,
    $18::timestamptz,
    $19::text,
    $20::text,
    $21::text,
    $22::bigint
)
RETURNING id
`

type CreateContractVersionParams struct {
	TenantID        int64
	ContractID      int64
	VersionNo       int32
	BuyerName       string
	BuyerAddress    string
	SellerName      string
	SellerAddress   string
	Currency        string
	Incoterm        string
	PortOfLoading   string
	PortOfDischarge string
	PaymentMethod   string
	DeliveryDate    string
	Terms           string
	TotalAmount     string
	BaseAmount      string
	FxRate          string
	FxRateAt        pgtype.Timestamptz
	FxSource        string
	FxBaseCurrency  string
	ChangeReason    string
	CreatedBy       int64
}

func (q *Queries) CreateContractVersion(ctx context.Context, arg CreateContractVersionParams) (int64, error) {
	row := q.db.QueryRow(ctx, createContractVersion,
		arg.TenantID,
		arg.ContractID,
		arg.VersionNo,
		arg.BuyerName,
		arg.BuyerAddress,
		arg.SellerName,
		arg.SellerAddress,
		arg.Currency,
		arg.Incoterm,
		arg.PortOfLoading,
		arg.PortOfDischarge,
		arg.PaymentMethod,
		arg.DeliveryDate,
		arg.Terms,
		arg.TotalAmount,
		arg.BaseAmount,
		arg.FxRate,
		arg.FxRateAt,
		arg.FxSource,
		arg.FxBaseCurrency,
		arg.ChangeReason,
		arg.CreatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createExistingContract = `-- name: CreateExistingContract :one
INSERT INTO contracts (
    tenant_id, contract_no, external_contract_no, entry_source,
    customer_id, customer_name, status, sales_employee_id, sales_employee,
    receivable_due_date, opening_received_amount, file_pending,
    signed_at, effective_at, signature_source, created_by, updated_by
) VALUES (
    $1::bigint,
    $2::text,
    $3::text,
    'EXISTING_CONTRACT',
    $4::bigint,
    $5::text,
    'EXECUTING',
    $6::bigint,
    $7::text,
    nullif($8::text, '')::date,
    $9::text::numeric,
    $10::bool,
    $11::text::date,
    $12::text::date,
    'MANUAL',
    $13::bigint,
    $13::bigint
)
RETURNING id
`

type CreateExistingContractParams struct {
	TenantID              int64
	ContractNo            string
	ExternalContractNo    string
	CustomerID            int64
	CustomerName          string
	SalesEmployeeID       int64
	SalesEmployee         string
	ReceivableDueDate     string
	OpeningReceivedAmount string
	FilePending           bool
	SignedDate            string
	EffectiveDate         string
	CreatedBy             int64
}

func (q *Queries) CreateExistingContract(ctx context.Context, arg CreateExistingContractParams) (int64, error) {
	row := q.db.QueryRow(ctx, createExistingContract,
		arg.TenantID,
		arg.ContractNo,
		arg.ExternalContractNo,
		arg.CustomerID,
		arg.CustomerName,
		arg.SalesEmployeeID,
		arg.SalesEmployee,
		arg.ReceivableDueDate,
		arg.OpeningReceivedAmount,
		arg.FilePending,
		arg.SignedDate,
		arg.EffectiveDate,
		arg.CreatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteContractAttachment = `-- name: DeleteContractAttachment :execrows
DELETE FROM contract_attachments WHERE tenant_id = $1 AND id = $2
`

type DeleteContractAttachmentParams struct {
	TenantID int64
	ID       int64
}

func (q *Queries) DeleteContractAttachment(ctx context.Context, arg DeleteContractAttachmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteContractAttachment, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteContractItems = `-- name: DeleteContractItems :exec
DELETE FROM contract_items WHERE tenant_id = $1 AND contract_version_id = $2
`

type DeleteContractItemsParams struct {
	TenantID          int64
	ContractVersionID int64
}

func (q *Queries) DeleteContractItems(ctx context.Context, arg DeleteContractItemsParams) error {
	_, err := q.db.Exec(ctx, deleteContractItems, arg.TenantID, arg.ContractVersionID)
	return err
}

const finalizeExistingContract = `-- name: FinalizeExistingContract :exec
UPDATE contracts SET current_version_id = $1::bigint,
    updated_at = now(), updated_by = $2::bigint
WHERE tenant_id = $3::bigint AND id = $4::bigint
`

type FinalizeExistingContractParams struct {
	VersionID int64
	UpdatedBy int64
	TenantID  int64
	ID        int64
}

func (q *Queries) FinalizeExistingContract(ctx context.Context, arg FinalizeExistingContractParams) error {
	_, err := q.db.Exec(ctx, finalizeExistingContract,
		arg.VersionID,
		arg.UpdatedBy,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const getContract = `-- name: GetContract :one
SELECT
    id, tenant_id, contract_no, coalesce(quotation_id, 0)::bigint AS quotation_id, quote_no,
    customer_id, customer_name, coalesce(current_version_id, 0)::bigint AS current_version_id,
    status, status_before_approval, sales_employee_id, sales_employee,
    coalesce(receivable_due_date::text, '')::text AS receivable_due_date,
    signature_source, signed_at, effective_at, completed_at, created_at,
    coalesce(condition_confirmed_at::text,'')::text AS condition_confirmed_at,
    condition_confirmation_note, coalesce(condition_confirmed_by,0)::bigint AS condition_confirmed_by,
    condition_confirmed_by_name, external_contract_no, entry_source,
    opening_received_amount::text AS opening_received_amount, file_pending
FROM contracts
WHERE tenant_id = $1 AND id = $2
`

type GetContractParams struct {
	TenantID int64
	ID       int64
}

type GetContractRow struct {
	ID                        int64
	TenantID                  int64
	ContractNo                string
	QuotationID               int64
	QuoteNo                   string
	CustomerID                int64
	CustomerName              string
	CurrentVersionID          int64
	Status                    string
	StatusBeforeApproval      string
	SalesEmployeeID           int64
	SalesEmployee             string
	ReceivableDueDate         string
	SignatureSource           string
	SignedAt                  pgtype.Timestamptz
	EffectiveAt               pgtype.Timestamptz
	CompletedAt               pgtype.Timestamptz
	CreatedAt                 pgtype.Timestamptz
	ConditionConfirmedAt      string
	ConditionConfirmationNote string
	ConditionConfirmedBy      int64
	ConditionConfirmedByName  string
	ExternalContractNo        string
	EntrySource               string
	OpeningReceivedAmount     string
	FilePending               bool
}

func (q *Queries) GetContract(ctx context.Context, arg GetContractParams) (GetContractRow, error) {
	row := q.db.QueryRow(ctx, getContract, arg.TenantID, arg.ID)
	var i GetContractRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ContractNo,
		&i.QuotationID,
		&i.QuoteNo,
		&i.CustomerID,
		&i.CustomerName,
		&i.CurrentVersionID,
		&i.Status,
		&i.StatusBeforeApproval,
		&i.SalesEmployeeID,
		&i.SalesEmployee,
		&i.ReceivableDueDate,
		&i.SignatureSource,
		&i.SignedAt,
		&i.EffectiveAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.ConditionConfirmedAt,
		&i.ConditionConfirmationNote,
		&i.ConditionConfirmedBy,
		&i.ConditionConfirmedByName,
		&i.ExternalContractNo,
		&i.EntrySource,
		&i.OpeningReceivedAmount,
		&i.FilePending,
	)
	return i, err
}

const getContractAttachment = `-- name: GetContractAttachment :one
SELECT
    a.id, a.contract_id,
    coalesce(a.contract_version_id, 0)::bigint AS contract_version_id,
    coalesce(v.version_no, 0)::int AS version_no,
    a.kind, a.source, a.file_name, a.file_key, a.content_type, a.size_bytes,
    a.uploaded_at, a.uploaded_by, a.uploader_name
FROM contract_attachments a
LEFT JOIN contract_versions v ON v.id = a.contract_version_id
WHERE a.tenant_id = $1 AND a.id = $2
`

type GetContractAttachmentParams struct {
	TenantID int64
	ID       int64
}

type GetContractAttachmentRow struct {
	ID                int64
	ContractID        int64
	ContractVersionID int64
	VersionNo         int32
	Kind              string
	Source            string
	FileName          string
	FileKey           string
	ContentType       string
	SizeBytes         int64
	UploadedAt        pgtype.Timestamptz
	UploadedBy        int64
	UploaderName      string
}

func (q *Queries) GetContractAttachment(ctx context.Context, arg GetContractAttachmentParams) (GetContractAttachmentRow, error) {
	row := q.db.QueryRow(ctx, getContractAttachment, arg.TenantID, arg.ID)
	var i GetContractAttachmentRow
	err := row.Scan(
		&i.ID,
		&i.ContractID,
		&i.ContractVersionID,
		&i.VersionNo,
		&i.Kind,
		&i.Source,
		&i.FileName,
		&i.FileKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.UploadedAt,
		&i.UploadedBy,
		&i.UploaderName,
	)
	return i, err
}

const getContractVersion = `-- name: GetContractVersion :one
SELECT
    id, contract_id, version_no, buyer_name, buyer_address, seller_name, seller_address,
    currency, incoterm, port_of_loading, port_of_discharge, payment_method,
    coalesce(delivery_date::text, '')::text AS delivery_date, terms,
    total_amount::text AS total_amount, base_amount::text AS base_amount,
    fx_rate::text AS fx_rate, fx_rate_at, fx_source, fx_base_currency,
    change_reason, status, created_at, created_by
FROM contract_versions
WHERE tenant_id = $1 AND id = $2
`

type GetContractVersionParams struct {
	TenantID int64
	ID       int64
}

type GetContractVersionRow struct {
	ID              int64
	ContractID      int64
	VersionNo       int32
	BuyerName       string
	BuyerAddress    string
	SellerName      string
	SellerAddress   string
	Currency        string
	Incoterm        string
	PortOfLoading   string
	PortOfDischarge string
	PaymentMethod   string
	DeliveryDate    string
	Terms           string
	TotalAmount     string
	BaseAmount      string
	FxRate          string
	FxRateAt        pgtype.Timestamptz
	FxSource        string
	FxBaseCurrency  string
	ChangeReason    string
	Status          string
	CreatedAt       pgtype.Timestamptz
	CreatedBy       int64
}

func (q *Queries) GetContractVersion(ctx context.Context, arg GetContractVersionParams) (GetContractVersionRow, error) {
	row := q.db.QueryRow(ctx, getContractVersion, arg.TenantID, arg.ID)
	var i GetContractVersionRow
	err := row.Scan(
		&i.ID,
		&i.ContractID,
		&i.VersionNo,
		&i.BuyerName,
		&i.BuyerAddress,
		&i.SellerName,
		&i.SellerAddress,
		&i.Currency,
		&i.Incoterm,
		&i.PortOfLoading,
		&i.PortOfDischarge,
		&i.PaymentMethod,
		&i.DeliveryDate,
		&i.Terms,
		&i.TotalAmount,
		&i.BaseAmount,
		&i.FxRate,
		&i.FxRateAt,
		&i.FxSource,
		&i.FxBaseCurrency,
		&i.ChangeReason,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const latestContractVersionID = `-- name: LatestContractVersionID :one
SELECT id FROM contract_versions
WHERE tenant_id = $1 AND contract_id = $2
ORDER BY version_no DESC
LIMIT 1
`

type LatestContractVersionIDParams struct {
	TenantID   int64
	ContractID int64
}

// Only the id, so callers go through GetContractVersion and there is one
// row shape for a version rather than two that must be kept in step.
func (q *Queries) LatestContractVersionID(ctx context.Context, arg LatestContractVersionIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, latestContractVersionID, arg.TenantID, arg.ContractID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listContractAttachments = `-- name: ListContractAttachments :many
SELECT
    a.id, a.contract_id,
    coalesce(a.contract_version_id, 0)::bigint AS contract_version_id,
    coalesce(v.version_no, 0)::int AS version_no,
    a.kind, a.source, a.file_name, a.file_key, a.content_type, a.size_bytes,
    a.uploaded_at, a.uploaded_by, a.uploader_name
FROM contract_attachments a
LEFT JOIN contract_versions v ON v.id = a.contract_version_id
WHERE a.tenant_id = $1 AND a.contract_id = $2
ORDER BY a.uploaded_at DESC
`

type ListContractAttachmentsParams struct {
	TenantID   int64
	ContractID int64
}

type ListContractAttachmentsRow struct {
	ID                int64
	ContractID        int64
	ContractVersionID int64
	VersionNo         int32
	Kind              string
	Source            string
	FileName          string
	FileKey           string
	ContentType       string
	SizeBytes         int64
	UploadedAt        pgtype.Timestamptz
	UploadedBy        int64
	UploaderName      string
}

func (q *Queries) ListContractAttachments(ctx context.Context, arg ListContractAttachmentsParams) ([]ListContractAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, listContractAttachments, arg.TenantID, arg.ContractID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContractAttachmentsRow
	for rows.Next() {
		var i ListContractAttachmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ContractID,
			&i.ContractVersionID,
			&i.VersionNo,
			&i.Kind,
			&i.Source,
			&i.FileName,
			&i.FileKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.UploadedAt,
			&i.UploadedBy,
			&i.UploaderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContractExecution = `-- name: ListContractExecution :many
SELECT
    c.id, c.contract_no, c.customer_id, c.customer_name,
    c.sales_employee_id, c.sales_employee, c.status,
    coalesce(c.effective_at::date::text, '')::text  AS effective_date,
    coalesce(c.receivable_due_date::text, '')::text AS due_date,
    coalesce((current_date - c.receivable_due_date), 0)::int AS overdue_days,
    (c.receivable_due_date IS NULL)::bool            AS due_unset,
    coalesce(v.currency, '')::text                   AS currency,
    coalesce(v.total_amount, 0)::text                AS total_amount,
    (coalesce(o.opening_shipped_amount, 0) + coalesce(s.shipped_amount, 0))::text AS shipped_amount,
    (CASE WHEN c.opening_received_amount = 0 THEN coalesce(r.received, 0)
          ELSE c.opening_received_amount + coalesce(r.received, 0) END)::text AS received_amount,
    count(*) OVER () AS total
FROM contracts c
JOIN contract_versions v ON v.id = c.current_version_id
LEFT JOIN LATERAL (
    -- Imported contracts may already have shipped goods. Value the opening
    -- snapshot without fabricating historical outbound documents.
    SELECT round(sum(i.opening_shipped_qty * i.unit_price), 2) AS opening_shipped_amount
    FROM contract_items i
    WHERE i.tenant_id = c.tenant_id
      AND i.contract_version_id = c.current_version_id
) o ON true
LEFT JOIN LATERAL (
    -- 已出运折成金额，按产品配对——和 ShipmentProgressOf 同一个口径，理由
    -- 也一样：改版会重写明细行的 id，按行配对会让改版前发出去的货凭空消失。
    --
    -- 单价取生效版本的加权均价（同一产品occasionally 落在两行上），和收款用
    -- 生效版本总额是同一个立场：合同改了，按改后的算。
    --
    -- 已出运可能超过合同金额——改版把量调小、而货已经发了。不夹紧，露出来。
    -- 反过来，改版把某个产品整个删掉、而它已经发过货，那部分在这里算不出
    -- 金额（没有单价可依），点进合同详情按产品看得见。
    -- 折到分。除法算出来的均价带一长串小数，原样冒出去会在页面上显示成
    -- 25000.00000000000000000000；两位与合同金额、已收款同一个刻度。
    SELECT round(sum(sh.shipped * li.unit_price), 2) AS shipped_amount
    FROM (
        SELECT cs.product_id, coalesce(cs.sku_id, 0) AS sku_id,
               CASE WHEN cs.product_id = 0 THEN ci.product_name ELSE '' END AS fallback_product_name,
               CASE WHEN cs.product_id = 0 THEN ci.uom_code ELSE '' END AS fallback_uom_code,
               sum(cs.qty) AS shipped
        FROM contract_shipments cs
        LEFT JOIN contract_items ci
          ON ci.tenant_id = cs.tenant_id AND ci.id = cs.contract_item_id
        WHERE cs.tenant_id = c.tenant_id AND cs.contract_id = c.id
        GROUP BY cs.product_id, coalesce(cs.sku_id, 0),
                 CASE WHEN cs.product_id = 0 THEN ci.product_name ELSE '' END,
                 CASE WHEN cs.product_id = 0 THEN ci.uom_code ELSE '' END
    ) sh
    JOIN (
        SELECT product_id, coalesce(sku_id, 0) AS sku_id,
               CASE WHEN product_id = 0 THEN product_name ELSE '' END AS fallback_product_name,
               CASE WHEN product_id = 0 THEN uom_code ELSE '' END AS fallback_uom_code,
               CASE WHEN sum(qty) > 0 THEN sum(amount) / sum(qty) ELSE 0 END AS unit_price
        FROM contract_items
        WHERE tenant_id = c.tenant_id AND contract_version_id = c.current_version_id
        GROUP BY product_id, coalesce(sku_id, 0),
                 CASE WHEN product_id = 0 THEN product_name ELSE '' END,
                 CASE WHEN product_id = 0 THEN uom_code ELSE '' END
    ) li ON li.product_id = sh.product_id
        AND li.sku_id = sh.sku_id
        AND li.fallback_product_name = sh.fallback_product_name
        AND li.fallback_uom_code = sh.fallback_uom_code
) s ON true
LEFT JOIN (
    SELECT contract_id, sum(amount + fee_amount) AS received
    FROM receipt_allocations
    WHERE tenant_id = $1::bigint
    GROUP BY contract_id
) r ON r.contract_id = c.id
WHERE c.tenant_id = $1::bigint
  -- 数据范围沿用合同列表那道围栏：看得见这张合同，才看得见它的进度。
  AND ($2::bool OR c.sales_employee_id = ANY($3::bigint[]))
  -- 默认只看在跑的。签之前没什么进程可言，作废的也不必占地方。
  AND ($4::text <> '' OR c.status IN ('EFFECTIVE', 'EXECUTING', 'COMPLETED'))
  AND ($4::text = '' OR c.status = $4::text
 OR ($4::text='PENDING_APPROVAL' AND c.status='DRAFT')
 OR ($4::text='EXECUTING' AND c.status='EFFECTIVE'))
 AND ($5::bigint=0 OR c.sales_employee_id=$5::bigint)
  AND ($6::bigint = 0 OR c.customer_id = $6::bigint)
  AND ($7::text = ''
       OR c.contract_no ILIKE '%' || $7::text || '%'
       OR c.external_contract_no ILIKE '%' || $7::text || '%'
       OR c.customer_name ILIKE '%' || $7::text || '%')
ORDER BY c.effective_at DESC NULLS LAST, c.id DESC
LIMIT $9::int OFFSET $8::int
`

type ListContractExecutionParams struct {
	TenantID        int64
	ScopeAll        bool
	EmployeeIds     []int64
	Status          string
	SalesEmployeeID int64
	CustomerID      int64
	Keyword         string
	RowOffset       int32
	RowLimit        int32
}

type ListContractExecutionRow struct {
	ID              int64
	ContractNo      string
	CustomerID      int64
	CustomerName    string
	SalesEmployeeID int64
	SalesEmployee   string
	Status          string
	EffectiveDate   string
	DueDate         string
	OverdueDays     int32
	DueUnset        bool
	Currency        string
	TotalAmount     string
	ShippedAmount   string
	ReceivedAmount  string
	Total           int64
}

// 一行一合同的执行进程（D2）：钱谈成了多少、货走了多少、款收了多少。
//
// 「这单到哪了」现在要翻四个页面：合同看金额、采购看订没订、出运看走没走、
// 银行流水看收没收。四份答案分散在四个人手里，没有一个人看得见整件事。
//
// 三条腿在同一个库里，所以一条 SQL 就够，不会有 N+1：合同、已出运、已收款。
// 另外两条（采购下没下单、船到哪了）在别的服务，由网关按这一页的合同批量取
// 回来拼上——一页两次调用，不是一行两次。
//
// 出运和收款都折成金额，是为了让两个数直接可比：走了六成货、收了三成款，
// 一眼看得出钱和货脱节。数量做不到这一点——一张合同上 100 吨和 50 件加不
// 起来。
func (q *Queries) ListContractExecution(ctx context.Context, arg ListContractExecutionParams) ([]ListContractExecutionRow, error) {
	rows, err := q.db.Query(ctx, listContractExecution,
		arg.TenantID,
		arg.ScopeAll,
		arg.EmployeeIds,
		arg.Status,
		arg.SalesEmployeeID,
		arg.CustomerID,
		arg.Keyword,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContractExecutionRow
	for rows.Next() {
		var i ListContractExecutionRow
		if err := rows.Scan(
			&i.ID,
			&i.ContractNo,
			&i.CustomerID,
			&i.CustomerName,
			&i.SalesEmployeeID,
			&i.SalesEmployee,
			&i.Status,
			&i.EffectiveDate,
			&i.DueDate,
			&i.OverdueDays,
			&i.DueUnset,
			&i.Currency,
			&i.TotalAmount,
			&i.ShippedAmount,
			&i.ReceivedAmount,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContractItems = `-- name: ListContractItems :many
SELECT
    id, contract_version_id, line_no, product_id, sku_id, product_code, product_name,
    spec, qty::text AS qty, uom_id, uom_code,
    unit_price::text AS unit_price, amount::text AS amount, hs_code, remark,
    opening_procured_qty::text AS opening_procured_qty,
    opening_arrived_qty::text AS opening_arrived_qty,
    opening_shipped_qty::text AS opening_shipped_qty
FROM contract_items
WHERE tenant_id = $1 AND contract_version_id = $2
ORDER BY line_no
`

type ListContractItemsParams struct {
	TenantID          int64
	ContractVersionID int64
}

type ListContractItemsRow struct {
	ID                 int64
	ContractVersionID  int64
	LineNo             int32
	ProductID          int64
	SkuID              *int64
	ProductCode        string
	ProductName        string
	Spec               string
	Qty                string
	UomID              int64
	UomCode            string
	UnitPrice          string
	Amount             string
	HsCode             string
	Remark             string
	OpeningProcuredQty string
	OpeningArrivedQty  string
	OpeningShippedQty  string
}

func (q *Queries) ListContractItems(ctx context.Context, arg ListContractItemsParams) ([]ListContractItemsRow, error) {
	rows, err := q.db.Query(ctx, listContractItems, arg.TenantID, arg.ContractVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContractItemsRow
	for rows.Next() {
		var i ListContractItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.ContractVersionID,
			&i.LineNo,
			&i.ProductID,
			&i.SkuID,
			&i.ProductCode,
			&i.ProductName,
			&i.Spec,
			&i.Qty,
			&i.UomID,
			&i.UomCode,
			&i.UnitPrice,
			&i.Amount,
			&i.HsCode,
			&i.Remark,
			&i.OpeningProcuredQty,
			&i.OpeningArrivedQty,
			&i.OpeningShippedQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContractVersions = `-- name: ListContractVersions :many
SELECT
    id, contract_id, version_no, currency,
    total_amount::text AS total_amount, base_amount::text AS base_amount,
    coalesce(delivery_date::text, '')::text AS delivery_date,
    change_reason, status, created_at, created_by
FROM contract_versions
WHERE tenant_id = $1 AND contract_id = $2
ORDER BY version_no DESC
`

type ListContractVersionsParams struct {
	TenantID   int64
	ContractID int64
}

type ListContractVersionsRow struct {
	ID           int64
	ContractID   int64
	VersionNo    int32
	Currency     string
	TotalAmount  string
	BaseAmount   string
	DeliveryDate string
	ChangeReason string
	Status       string
	CreatedAt    pgtype.Timestamptz
	CreatedBy    int64
}

func (q *Queries) ListContractVersions(ctx context.Context, arg ListContractVersionsParams) ([]ListContractVersionsRow, error) {
	rows, err := q.db.Query(ctx, listContractVersions, arg.TenantID, arg.ContractID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContractVersionsRow
	for rows.Next() {
		var i ListContractVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ContractID,
			&i.VersionNo,
			&i.Currency,
			&i.TotalAmount,
			&i.BaseAmount,
			&i.DeliveryDate,
			&i.ChangeReason,
			&i.Status,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContracts = `-- name: ListContracts :many
SELECT
    c.id, c.contract_no, c.quote_no, c.customer_id, c.customer_name, c.status,
    c.sales_employee_id, c.sales_employee, c.signed_at, c.effective_at, c.created_at, c.updated_at,
    c.external_contract_no, c.entry_source,
    coalesce(c.receivable_due_date::text, '')::text AS receivable_due_date,
    coalesce(v.currency, '')::text AS currency,
    coalesce(v.total_amount, 0)::text AS total_amount,
    coalesce(v.base_amount, 0)::text AS base_amount,
    coalesce(v.version_no, 0)::int AS version_no,
    count(*) OVER () AS total
FROM contracts c
LEFT JOIN LATERAL (
    SELECT version_no, currency, total_amount, base_amount
    FROM contract_versions
    WHERE contract_id = c.id
    ORDER BY version_no DESC
    LIMIT 1
) v ON true
WHERE c.tenant_id = $1::bigint
  -- Data scope. An empty id list with visible_all = false means "nothing",
  -- which is the right answer for someone with no scope at all; it must not
  -- silently widen to everything.
  AND ($2::bool
       OR c.sales_employee_id = ANY($3::bigint[])
       -- Documents this person was asked to approve are visible whatever the
       -- scope says; an approver who cannot read the contract cannot approve it.
       OR c.id = ANY($4::bigint[]))
  AND ($5::text = '' OR c.status = $5::text
 OR ($5::text='PENDING_APPROVAL' AND c.status='DRAFT')
 OR ($5::text='EXECUTING' AND c.status='EFFECTIVE'))
 AND ($6::bigint=0 OR c.sales_employee_id=$6::bigint)
  AND ($7::bigint = 0 OR c.customer_id = $7::bigint)
  AND ($8::text = ''
       OR c.contract_no ILIKE '%' || $8::text || '%'
       OR c.external_contract_no ILIKE '%' || $8::text || '%'
       OR c.customer_name ILIKE '%' || $8::text || '%')
ORDER BY c.id DESC
LIMIT $10::int OFFSET $9::int
`

type ListContractsParams struct {
	TenantID        int64
	VisibleAll      bool
	VisibleIds      []int64
	InvolvedIds     []int64
	Status          string
	SalesEmployeeID int64
	CustomerID      int64
	Keyword         string
	RowOffset       int32
	RowLimit        int32
}

type ListContractsRow struct {
	ID                 int64
	ContractNo         string
	QuoteNo            string
	CustomerID         int64
	CustomerName       string
	Status             string
	SalesEmployeeID    int64
	SalesEmployee      string
	SignedAt           pgtype.Timestamptz
	EffectiveAt        pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	ExternalContractNo string
	EntrySource        string
	ReceivableDueDate  string
	Currency           string
	TotalAmount        string
	BaseAmount         string
	VersionNo          int32
	Total              int64
}

// The newest version, not the in-force one: a list must still show a contract
// that has never been signed.
func (q *Queries) ListContracts(ctx context.Context, arg ListContractsParams) ([]ListContractsRow, error) {
	rows, err := q.db.Query(ctx, listContracts,
		arg.TenantID,
		arg.VisibleAll,
		arg.VisibleIds,
		arg.InvolvedIds,
		arg.Status,
		arg.SalesEmployeeID,
		arg.CustomerID,
		arg.Keyword,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContractsRow
	for rows.Next() {
		var i ListContractsRow
		if err := rows.Scan(
			&i.ID,
			&i.ContractNo,
			&i.QuoteNo,
			&i.CustomerID,
			&i.CustomerName,
			&i.Status,
			&i.SalesEmployeeID,
			&i.SalesEmployee,
			&i.SignedAt,
			&i.EffectiveAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExternalContractNo,
			&i.EntrySource,
			&i.ReceivableDueDate,
			&i.Currency,
			&i.TotalAmount,
			&i.BaseAmount,
			&i.VersionNo,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnershipTransfers = `-- name: ListOwnershipTransfers :many
SELECT
    id, biz_type, biz_id, biz_no,
    from_employee_id, from_employee, to_employee_id, to_employee,
    reason, transferred_by, transferred_by_name, transferred_at
FROM ownership_transfers
WHERE tenant_id = $1 AND biz_type = $2 AND biz_id = $3
ORDER BY transferred_at DESC, id DESC
`

type ListOwnershipTransfersParams struct {
	TenantID int64
	BizType  string
	BizID    int64
}

type ListOwnershipTransfersRow struct {
	ID                int64
	BizType           string
	BizID             int64
	BizNo             string
	FromEmployeeID    int64
	FromEmployee      string
	ToEmployeeID      int64
	ToEmployee        string
	Reason            string
	TransferredBy     int64
	TransferredByName string
	TransferredAt     pgtype.Timestamptz
}

func (q *Queries) ListOwnershipTransfers(ctx context.Context, arg ListOwnershipTransfersParams) ([]ListOwnershipTransfersRow, error) {
	rows, err := q.db.Query(ctx, listOwnershipTransfers, arg.TenantID, arg.BizType, arg.BizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOwnershipTransfersRow
	for rows.Next() {
		var i ListOwnershipTransfersRow
		if err := rows.Scan(
			&i.ID,
			&i.BizType,
			&i.BizID,
			&i.BizNo,
			&i.FromEmployeeID,
			&i.FromEmployee,
			&i.ToEmployeeID,
			&i.ToEmployee,
			&i.Reason,
			&i.TransferredBy,
			&i.TransferredByName,
			&i.TransferredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const liveContractForQuotation = `-- name: LiveContractForQuotation :one
SELECT id, contract_no, status, sales_employee_id, sales_employee
FROM contracts
WHERE tenant_id = $1 AND quotation_id = $2 AND status <> 'CANCELLED'
`

type LiveContractForQuotationParams struct {
	TenantID    int64
	QuotationID *int64
}

type LiveContractForQuotationRow struct {
	ID              int64
	ContractNo      string
	Status          string
	SalesEmployeeID int64
	SalesEmployee   string
}

// The one contract a quotation may still have; cancelled ones are excluded by
// the same rule as the unique index, because a cancelled contract does not
// block a new one.
func (q *Queries) LiveContractForQuotation(ctx context.Context, arg LiveContractForQuotationParams) (LiveContractForQuotationRow, error) {
	row := q.db.QueryRow(ctx, liveContractForQuotation, arg.TenantID, arg.QuotationID)
	var i LiveContractForQuotationRow
	err := row.Scan(
		&i.ID,
		&i.ContractNo,
		&i.Status,
		&i.SalesEmployeeID,
		&i.SalesEmployee,
	)
	return i, err
}

const lockContract = `-- name: LockContract :one
SELECT id, status, coalesce(current_version_id, 0)::bigint AS current_version_id
FROM contracts
WHERE tenant_id = $1 AND id = $2
FOR UPDATE
`

type LockContractParams struct {
	TenantID int64
	ID       int64
}

type LockContractRow struct {
	ID               int64
	Status           string
	CurrentVersionID int64
}

func (q *Queries) LockContract(ctx context.Context, arg LockContractParams) (LockContractRow, error) {
	row := q.db.QueryRow(ctx, lockContract, arg.TenantID, arg.ID)
	var i LockContractRow
	err := row.Scan(&i.ID, &i.Status, &i.CurrentVersionID)
	return i, err
}

const markContractPendingApproval = `-- name: MarkContractPendingApproval :one
UPDATE contracts SET
    status = 'PENDING_APPROVAL',
    status_before_approval = status,
    updated_at = now(), updated_by = $1::bigint
WHERE tenant_id = $2::bigint AND id = $3::bigint
RETURNING status_before_approval
`

type MarkContractPendingApprovalParams struct {
	UpdatedBy int64
	TenantID  int64
	ID        int64
}

// Remembers where the contract stood, so a rejection can put it back there
// rather than guessing between "still a draft" and "already running".
func (q *Queries) MarkContractPendingApproval(ctx context.Context, arg MarkContractPendingApprovalParams) (string, error) {
	row := q.db.QueryRow(ctx, markContractPendingApproval, arg.UpdatedBy, arg.TenantID, arg.ID)
	var status_before_approval string
	err := row.Scan(&status_before_approval)
	return status_before_approval, err
}

const markContractSigned = `-- name: MarkContractSigned :exec
UPDATE contracts SET
    signature_source = $2::text,
    updated_by       = $3,
    updated_at       = now()
WHERE tenant_id = $1 AND id = $4
`

type MarkContractSignedParams struct {
	TenantID        int64
	SignatureSource string
	UpdatedBy       int64
	ID              int64
}

func (q *Queries) MarkContractSigned(ctx context.Context, arg MarkContractSignedParams) error {
	_, err := q.db.Exec(ctx, markContractSigned,
		arg.TenantID,
		arg.SignatureSource,
		arg.UpdatedBy,
		arg.ID,
	)
	return err
}

const recordContractConditionConfirmation = `-- name: RecordContractConditionConfirmation :exec
UPDATE contracts SET condition_confirmed_at=$1::text::timestamptz,
 condition_confirmation_note=$2, condition_confirmed_by=$3,
 condition_confirmed_by_name=$4, updated_at=now(),updated_by=$3
WHERE tenant_id=$5 AND id=$6
`

type RecordContractConditionConfirmationParams struct {
	ConfirmedAt     string
	Note            string
	ConfirmedBy     *int64
	ConfirmedByName string
	TenantID        int64
	ID              int64
}

func (q *Queries) RecordContractConditionConfirmation(ctx context.Context, arg RecordContractConditionConfirmationParams) error {
	_, err := q.db.Exec(ctx, recordContractConditionConfirmation,
		arg.ConfirmedAt,
		arg.Note,
		arg.ConfirmedBy,
		arg.ConfirmedByName,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const recordOwnershipTransfer = `-- name: RecordOwnershipTransfer :one
INSERT INTO ownership_transfers (
    tenant_id, biz_type, biz_id, biz_no,
    from_employee_id, from_employee, to_employee_id, to_employee,
    reason, transferred_by, transferred_by_name
) VALUES ($1, $2, $3, $4,
          $5, $6,
          $7, $8,
          $9, $10, $11)
RETURNING id, biz_type, biz_id, biz_no,
          from_employee_id, from_employee, to_employee_id, to_employee,
          reason, transferred_by, transferred_by_name, transferred_at
`

type RecordOwnershipTransferParams struct {
	TenantID          int64
	BizType           string
	BizID             int64
	BizNo             string
	FromEmployeeID    int64
	FromEmployee      string
	ToEmployeeID      int64
	ToEmployee        string
	Reason            string
	TransferredBy     int64
	TransferredByName string
}

type RecordOwnershipTransferRow struct {
	ID                int64
	BizType           string
	BizID             int64
	BizNo             string
	FromEmployeeID    int64
	FromEmployee      string
	ToEmployeeID      int64
	ToEmployee        string
	Reason            string
	TransferredBy     int64
	TransferredByName string
	TransferredAt     pgtype.Timestamptz
}

// Returns the same shape as ListOwnershipTransfers so a caller can report
// exactly what it moved without reading the log back.
func (q *Queries) RecordOwnershipTransfer(ctx context.Context, arg RecordOwnershipTransferParams) (RecordOwnershipTransferRow, error) {
	row := q.db.QueryRow(ctx, recordOwnershipTransfer,
		arg.TenantID,
		arg.BizType,
		arg.BizID,
		arg.BizNo,
		arg.FromEmployeeID,
		arg.FromEmployee,
		arg.ToEmployeeID,
		arg.ToEmployee,
		arg.Reason,
		arg.TransferredBy,
		arg.TransferredByName,
	)
	var i RecordOwnershipTransferRow
	err := row.Scan(
		&i.ID,
		&i.BizType,
		&i.BizID,
		&i.BizNo,
		&i.FromEmployeeID,
		&i.FromEmployee,
		&i.ToEmployeeID,
		&i.ToEmployee,
		&i.Reason,
		&i.TransferredBy,
		&i.TransferredByName,
		&i.TransferredAt,
	)
	return i, err
}

const recordShipment = `-- name: RecordShipment :execrows
INSERT INTO contract_shipments (
    tenant_id, contract_id, contract_item_id, product_id, sku_id, outbound_no, qty
) VALUES (
    $1::bigint,
    $2::bigint,
    $3::bigint,
    $4::bigint,
    $5::bigint,
    $6::text,
    $7::text::numeric
)
ON CONFLICT (tenant_id, outbound_no, contract_item_id) DO NOTHING
`

type RecordShipmentParams struct {
	TenantID       int64
	ContractID     int64
	ContractItemID int64
	ProductID      int64
	SkuID          int64
	OutboundNo     string
	Qty            string
}

// Goods left the warehouse against a contract line. Conflicts are dropped
// silently: a redelivered outbound event is the normal case, not an error.
func (q *Queries) RecordShipment(ctx context.Context, arg RecordShipmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordShipment,
		arg.TenantID,
		arg.ContractID,
		arg.ContractItemID,
		arg.ProductID,
		arg.SkuID,
		arg.OutboundNo,
		arg.Qty,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setContractCurrentVersion = `-- name: SetContractCurrentVersion :exec
UPDATE contracts SET
    current_version_id = $1::bigint,
    updated_at = now(), updated_by = $2::bigint
WHERE tenant_id = $3::bigint AND id = $4::bigint
`

type SetContractCurrentVersionParams struct {
	VersionID int64
	UpdatedBy int64
	TenantID  int64
	ID        int64
}

func (q *Queries) SetContractCurrentVersion(ctx context.Context, arg SetContractCurrentVersionParams) error {
	_, err := q.db.Exec(ctx, setContractCurrentVersion,
		arg.VersionID,
		arg.UpdatedBy,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const setContractOwner = `-- name: SetContractOwner :execrows
UPDATE contracts SET
    sales_employee_id = $2,
    sales_employee    = $3,
    updated_by        = $4,
    updated_at        = now()
WHERE tenant_id = $1 AND id = $5
`

type SetContractOwnerParams struct {
	TenantID  int64
	OwnerID   int64
	OwnerName string
	UpdatedBy int64
	ID        int64
}

func (q *Queries) SetContractOwner(ctx context.Context, arg SetContractOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, setContractOwner,
		arg.TenantID,
		arg.OwnerID,
		arg.OwnerName,
		arg.UpdatedBy,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setContractStatus = `-- name: SetContractStatus :one
UPDATE contracts SET
    status = $1::text,
    status_before_approval = CASE WHEN $1::text = 'PENDING_APPROVAL'
                                  THEN status_before_approval ELSE '' END,
    signed_at = CASE WHEN $1::text = 'EFFECTIVE' AND signed_at IS NULL
                     THEN now() ELSE signed_at END,
    effective_at = CASE WHEN $1::text = 'EFFECTIVE' AND effective_at IS NULL
                        THEN now() ELSE effective_at END,
    completed_at = CASE WHEN $1::text = 'COMPLETED'
                        THEN now() ELSE completed_at END,
    updated_at = now(), updated_by = $2::bigint
WHERE tenant_id = $3::bigint AND id = $4::bigint
RETURNING status
`

type SetContractStatusParams struct {
	NewStatus string
	UpdatedBy int64
	TenantID  int64
	ID        int64
}

func (q *Queries) SetContractStatus(ctx context.Context, arg SetContractStatusParams) (string, error) {
	row := q.db.QueryRow(ctx, setContractStatus,
		arg.NewStatus,
		arg.UpdatedBy,
		arg.TenantID,
		arg.ID,
	)
	var status string
	err := row.Scan(&status)
	return status, err
}

const setContractVersionStatus = `-- name: SetContractVersionStatus :exec
UPDATE contract_versions SET status = $1::text
WHERE tenant_id = $2::bigint AND id = $3::bigint
`

type SetContractVersionStatusParams struct {
	NewStatus string
	TenantID  int64
	ID        int64
}

func (q *Queries) SetContractVersionStatus(ctx context.Context, arg SetContractVersionStatusParams) error {
	_, err := q.db.Exec(ctx, setContractVersionStatus, arg.NewStatus, arg.TenantID, arg.ID)
	return err
}

const shipmentProgressOf = `-- name: ShipmentProgressOf :many
WITH current_items AS (
    SELECT i.id, i.tenant_id, i.contract_version_id, i.line_no, i.product_id, i.sku_id, i.product_code, i.product_name, i.spec, i.qty, i.uom_id, i.uom_code, i.unit_price, i.amount, i.hs_code, i.remark, i.opening_procured_qty, i.opening_arrived_qty, i.opening_shipped_qty,
           CASE WHEN i.product_id = 0 THEN i.product_name ELSE '' END AS fallback_product_name,
           CASE WHEN i.product_id = 0 THEN i.uom_code ELSE '' END AS fallback_uom_code
    FROM contract_items i
    WHERE i.tenant_id = $1::bigint
      AND i.contract_version_id = $2::bigint
), shipped AS (
    SELECT cs.product_id, coalesce(cs.sku_id, 0) AS sku_id,
           CASE WHEN cs.product_id = 0 THEN ci.product_name ELSE '' END AS fallback_product_name,
           CASE WHEN cs.product_id = 0 THEN ci.uom_code ELSE '' END AS fallback_uom_code,
           sum(cs.qty) AS shipped
    FROM contract_shipments cs
    LEFT JOIN contract_items ci
      ON ci.tenant_id = cs.tenant_id AND ci.id = cs.contract_item_id
    WHERE cs.tenant_id = $1::bigint
      AND cs.contract_id = $3::bigint
    GROUP BY cs.product_id, coalesce(cs.sku_id, 0),
             CASE WHEN cs.product_id = 0 THEN ci.product_name ELSE '' END,
             CASE WHEN cs.product_id = 0 THEN ci.uom_code ELSE '' END
)
SELECT
    min(i.line_no)::int         AS line_no,
    i.product_id,
    coalesce(i.sku_id, 0)::bigint AS sku_id,
    max(i.product_code)::text   AS product_code,
    max(i.product_name)::text   AS product_name,
    max(i.uom_code)::text       AS uom_code,
    sum(i.qty)::text            AS qty,
    (sum(i.opening_shipped_qty) + coalesce(max(sh.shipped), 0))::text AS shipped_qty,
    (sum(i.qty) - sum(i.opening_shipped_qty) - coalesce(max(sh.shipped), 0))::text AS remaining_qty
FROM current_items i
LEFT JOIN shipped sh
  ON sh.product_id = i.product_id
 AND sh.sku_id = coalesce(i.sku_id, 0)
 AND sh.fallback_product_name = i.fallback_product_name
 AND sh.fallback_uom_code = i.fallback_uom_code
GROUP BY i.product_id, coalesce(i.sku_id, 0), i.fallback_product_name, i.fallback_uom_code
ORDER BY min(i.line_no)
`

type ShipmentProgressOfParams struct {
	TenantID          int64
	ContractVersionID int64
	ContractID        int64
}

type ShipmentProgressOfRow struct {
	LineNo       int32
	ProductID    int64
	SkuID        int64
	ProductCode  string
	ProductName  string
	UomCode      string
	Qty          string
	ShippedQty   string
	RemainingQty string
}

// How much of each product on a contract has shipped.
//
// Grouped by product rather than by contract line, and that is deliberate. A
// contract change rewrites the lines with new ids, so shipments made against
// the old version would show as zero on the new one — the goods physically
// left and the page would say nothing had. The customer bought a product; a
// version changes the terms, not what is in the crate.
//
// remaining_qty can go negative, and that is the most useful thing this query
// produces: it means the contract was reduced after goods had already
// shipped. No automatic rule gets that right, so it is surfaced rather than
// clamped to zero and quietly forgotten.
func (q *Queries) ShipmentProgressOf(ctx context.Context, arg ShipmentProgressOfParams) ([]ShipmentProgressOfRow, error) {
	rows, err := q.db.Query(ctx, shipmentProgressOf, arg.TenantID, arg.ContractVersionID, arg.ContractID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShipmentProgressOfRow
	for rows.Next() {
		var i ShipmentProgressOfRow
		if err := rows.Scan(
			&i.LineNo,
			&i.ProductID,
			&i.SkuID,
			&i.ProductCode,
			&i.ProductName,
			&i.UomCode,
			&i.Qty,
			&i.ShippedQty,
			&i.RemainingQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const shipmentsOfContract = `-- name: ShipmentsOfContract :many
SELECT outbound_no, contract_item_id, qty::text AS qty, shipped_at
FROM contract_shipments
WHERE tenant_id = $1::bigint AND contract_id = $2::bigint
ORDER BY shipped_at DESC, id DESC
`

type ShipmentsOfContractParams struct {
	TenantID   int64
	ContractID int64
}

type ShipmentsOfContractRow struct {
	OutboundNo     string
	ContractItemID int64
	Qty            string
	ShippedAt      pgtype.Timestamptz
}

func (q *Queries) ShipmentsOfContract(ctx context.Context, arg ShipmentsOfContractParams) ([]ShipmentsOfContractRow, error) {
	rows, err := q.db.Query(ctx, shipmentsOfContract, arg.TenantID, arg.ContractID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShipmentsOfContractRow
	for rows.Next() {
		var i ShipmentsOfContractRow
		if err := rows.Scan(
			&i.OutboundNo,
			&i.ContractItemID,
			&i.Qty,
			&i.ShippedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const supersedeOtherVersions = `-- name: SupersedeOtherVersions :exec
UPDATE contract_versions SET status = 'SUPERSEDED'
WHERE tenant_id = $1::bigint
  AND contract_id = $2::bigint
  AND id <> $3::bigint
  AND status = 'APPROVED'
`

type SupersedeOtherVersionsParams struct {
	TenantID   int64
	ContractID int64
	KeepID     int64
}

func (q *Queries) SupersedeOtherVersions(ctx context.Context, arg SupersedeOtherVersionsParams) error {
	_, err := q.db.Exec(ctx, supersedeOtherVersions, arg.TenantID, arg.ContractID, arg.KeepID)
	return err
}

const updateContractVersion = `-- name: UpdateContractVersion :execrows
UPDATE contract_versions SET
    buyer_name = $1::text,
    buyer_address = $2::text,
    seller_name = $3::text,
    seller_address = $4::text,
    incoterm = $5::text,
    port_of_loading = $6::text,
    port_of_discharge = $7::text,
    payment_method = $8::text,
    delivery_date = nullif($9::text, '')::date,
    terms = $10::text,
    total_amount = $11::text::numeric,
    base_amount = $12::text::numeric
WHERE tenant_id = $13::bigint AND id = $14::bigint AND status = 'DRAFT'
`

type UpdateContractVersionParams struct {
	BuyerName       string
	BuyerAddress    string
	SellerName      string
	SellerAddress   string
	Incoterm        string
	PortOfLoading   string
	PortOfDischarge string
	PaymentMethod   string
	DeliveryDate    string
	Terms           string
	TotalAmount     string
	BaseAmount      string
	TenantID        int64
	ID              int64
}

func (q *Queries) UpdateContractVersion(ctx context.Context, arg UpdateContractVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateContractVersion,
		arg.BuyerName,
		arg.BuyerAddress,
		arg.SellerName,
		arg.SellerAddress,
		arg.Incoterm,
		arg.PortOfLoading,
		arg.PortOfDischarge,
		arg.PaymentMethod,
		arg.DeliveryDate,
		arg.Terms,
		arg.TotalAmount,
		arg.BaseAmount,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
