// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quotation.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addQuotationItem = `-- name: AddQuotationItem :exec
INSERT INTO quotation_items (
    tenant_id, quotation_id, line_no, product_id, sku_id, product_code,
    product_name, spec, qty, uom_id, uom_code, unit_price, amount, remark
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $12::text::numeric, $9, $10,
    $13::text::numeric, $14::text::numeric, $11
)
`

type AddQuotationItemParams struct {
	TenantID    int64
	QuotationID int64
	LineNo      int32
	ProductID   int64
	SkuID       *int64
	ProductCode string
	ProductName string
	Spec        string
	UomID       int64
	UomCode     string
	Remark      string
	Qty         string
	UnitPrice   string
	Amount      string
}

func (q *Queries) AddQuotationItem(ctx context.Context, arg AddQuotationItemParams) error {
	_, err := q.db.Exec(ctx, addQuotationItem,
		arg.TenantID,
		arg.QuotationID,
		arg.LineNo,
		arg.ProductID,
		arg.SkuID,
		arg.ProductCode,
		arg.ProductName,
		arg.Spec,
		arg.UomID,
		arg.UomCode,
		arg.Remark,
		arg.Qty,
		arg.UnitPrice,
		arg.Amount,
	)
	return err
}

const createQuotation = `-- name: CreateQuotation :one

INSERT INTO quotations (
    tenant_id, quote_no, customer_id, customer_name, currency, incoterm,
    port_of_loading, port_of_discharge, payment_method, valid_until,
    fx_rate, fx_rate_at, fx_source, fx_base_currency,
    total_amount, base_amount, remark, sales_employee_id, sales_employee,
    created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    nullif($16::text, '')::date,
    $17::text::numeric, $18::timestamptz,
    $10, $11,
    $19::text::numeric, $20::text::numeric,
    $12, $13, $14, $15, $15
)
RETURNING id
`

type CreateQuotationParams struct {
	TenantID        int64
	QuoteNo         string
	CustomerID      int64
	CustomerName    string
	Currency        string
	Incoterm        string
	PortOfLoading   string
	PortOfDischarge string
	PaymentMethod   string
	FxSource        string
	FxBaseCurrency  string
	Remark          string
	SalesEmployeeID int64
	SalesEmployee   string
	CreatedBy       int64
	ValidUntil      string
	FxRate          string
	FxRateAt        pgtype.Timestamptz
	TotalAmount     string
	BaseAmount      string
}

// Money and rates cross this boundary as text: Go holds decimal strings and
// never a float64. See pkg/money.
func (q *Queries) CreateQuotation(ctx context.Context, arg CreateQuotationParams) (int64, error) {
	row := q.db.QueryRow(ctx, createQuotation,
		arg.TenantID,
		arg.QuoteNo,
		arg.CustomerID,
		arg.CustomerName,
		arg.Currency,
		arg.Incoterm,
		arg.PortOfLoading,
		arg.PortOfDischarge,
		arg.PaymentMethod,
		arg.FxSource,
		arg.FxBaseCurrency,
		arg.Remark,
		arg.SalesEmployeeID,
		arg.SalesEmployee,
		arg.CreatedBy,
		arg.ValidUntil,
		arg.FxRate,
		arg.FxRateAt,
		arg.TotalAmount,
		arg.BaseAmount,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteQuotationItems = `-- name: DeleteQuotationItems :exec
DELETE FROM quotation_items WHERE tenant_id = $1 AND quotation_id = $2
`

type DeleteQuotationItemsParams struct {
	TenantID    int64
	QuotationID int64
}

func (q *Queries) DeleteQuotationItems(ctx context.Context, arg DeleteQuotationItemsParams) error {
	_, err := q.db.Exec(ctx, deleteQuotationItems, arg.TenantID, arg.QuotationID)
	return err
}

const getQuotation = `-- name: GetQuotation :one
SELECT
    id, tenant_id, quote_no, customer_id, customer_name, currency, incoterm,
    port_of_loading, port_of_discharge, payment_method,
    coalesce(valid_until::text, '')::text AS valid_until,
    fx_rate::text AS fx_rate, fx_rate_at, fx_source, fx_base_currency,
    total_amount::text AS total_amount, base_amount::text AS base_amount,
    remark, status, sales_employee_id, sales_employee, sent_at, responded_at, created_at
FROM quotations
WHERE tenant_id = $1 AND id = $2
`

type GetQuotationParams struct {
	TenantID int64
	ID       int64
}

type GetQuotationRow struct {
	ID              int64
	TenantID        int64
	QuoteNo         string
	CustomerID      int64
	CustomerName    string
	Currency        string
	Incoterm        string
	PortOfLoading   string
	PortOfDischarge string
	PaymentMethod   string
	ValidUntil      string
	FxRate          string
	FxRateAt        pgtype.Timestamptz
	FxSource        string
	FxBaseCurrency  string
	TotalAmount     string
	BaseAmount      string
	Remark          string
	Status          string
	SalesEmployeeID int64
	SalesEmployee   string
	SentAt          pgtype.Timestamptz
	RespondedAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) GetQuotation(ctx context.Context, arg GetQuotationParams) (GetQuotationRow, error) {
	row := q.db.QueryRow(ctx, getQuotation, arg.TenantID, arg.ID)
	var i GetQuotationRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.QuoteNo,
		&i.CustomerID,
		&i.CustomerName,
		&i.Currency,
		&i.Incoterm,
		&i.PortOfLoading,
		&i.PortOfDischarge,
		&i.PaymentMethod,
		&i.ValidUntil,
		&i.FxRate,
		&i.FxRateAt,
		&i.FxSource,
		&i.FxBaseCurrency,
		&i.TotalAmount,
		&i.BaseAmount,
		&i.Remark,
		&i.Status,
		&i.SalesEmployeeID,
		&i.SalesEmployee,
		&i.SentAt,
		&i.RespondedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listQuotationItems = `-- name: ListQuotationItems :many
SELECT
    id, quotation_id, line_no, product_id, sku_id, product_code, product_name,
    spec, qty::text AS qty, uom_id, uom_code,
    unit_price::text AS unit_price, amount::text AS amount, remark
FROM quotation_items
WHERE tenant_id = $1 AND quotation_id = $2
ORDER BY line_no
`

type ListQuotationItemsParams struct {
	TenantID    int64
	QuotationID int64
}

type ListQuotationItemsRow struct {
	ID          int64
	QuotationID int64
	LineNo      int32
	ProductID   int64
	SkuID       *int64
	ProductCode string
	ProductName string
	Spec        string
	Qty         string
	UomID       int64
	UomCode     string
	UnitPrice   string
	Amount      string
	Remark      string
}

func (q *Queries) ListQuotationItems(ctx context.Context, arg ListQuotationItemsParams) ([]ListQuotationItemsRow, error) {
	rows, err := q.db.Query(ctx, listQuotationItems, arg.TenantID, arg.QuotationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQuotationItemsRow
	for rows.Next() {
		var i ListQuotationItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.QuotationID,
			&i.LineNo,
			&i.ProductID,
			&i.SkuID,
			&i.ProductCode,
			&i.ProductName,
			&i.Spec,
			&i.Qty,
			&i.UomID,
			&i.UomCode,
			&i.UnitPrice,
			&i.Amount,
			&i.Remark,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuotations = `-- name: ListQuotations :many
SELECT
    id, quote_no, customer_id, customer_name, currency,
    total_amount::text AS total_amount, base_amount::text AS base_amount,
    status, sales_employee, coalesce(valid_until::text, '')::text AS valid_until,
    created_at, count(*) OVER () AS total
FROM quotations
WHERE tenant_id = $1
  AND ($2::text = '' OR status = $2::text)
  AND ($3::bigint = 0 OR customer_id = $3::bigint)
  AND ($4::text = ''
       OR quote_no ILIKE '%' || $4::text || '%'
       OR customer_name ILIKE '%' || $4::text || '%')
ORDER BY id DESC
LIMIT $6::int OFFSET $5::int
`

type ListQuotationsParams struct {
	TenantID   int64
	Status     string
	CustomerID int64
	Keyword    string
	RowOffset  int32
	RowLimit   int32
}

type ListQuotationsRow struct {
	ID            int64
	QuoteNo       string
	CustomerID    int64
	CustomerName  string
	Currency      string
	TotalAmount   string
	BaseAmount    string
	Status        string
	SalesEmployee string
	ValidUntil    string
	CreatedAt     pgtype.Timestamptz
	Total         int64
}

func (q *Queries) ListQuotations(ctx context.Context, arg ListQuotationsParams) ([]ListQuotationsRow, error) {
	rows, err := q.db.Query(ctx, listQuotations,
		arg.TenantID,
		arg.Status,
		arg.CustomerID,
		arg.Keyword,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQuotationsRow
	for rows.Next() {
		var i ListQuotationsRow
		if err := rows.Scan(
			&i.ID,
			&i.QuoteNo,
			&i.CustomerID,
			&i.CustomerName,
			&i.Currency,
			&i.TotalAmount,
			&i.BaseAmount,
			&i.Status,
			&i.SalesEmployee,
			&i.ValidUntil,
			&i.CreatedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setQuotationStatus = `-- name: SetQuotationStatus :one
UPDATE quotations SET
    status = $4::text,
    sent_at = CASE WHEN $4::text = 'SENT' THEN now() ELSE sent_at END,
    responded_at = CASE WHEN $4::text IN ('ACCEPTED','REJECTED')
                        THEN now() ELSE responded_at END,
    updated_at = now(), updated_by = $3
WHERE tenant_id = $1 AND id = $2
RETURNING status
`

type SetQuotationStatusParams struct {
	TenantID  int64
	ID        int64
	UpdatedBy int64
	NewStatus string
}

func (q *Queries) SetQuotationStatus(ctx context.Context, arg SetQuotationStatusParams) (string, error) {
	row := q.db.QueryRow(ctx, setQuotationStatus,
		arg.TenantID,
		arg.ID,
		arg.UpdatedBy,
		arg.NewStatus,
	)
	var status string
	err := row.Scan(&status)
	return status, err
}

const updateQuotationHeader = `-- name: UpdateQuotationHeader :execrows
UPDATE quotations SET
    customer_id = $3, customer_name = $4, currency = $5, incoterm = $6,
    port_of_loading = $7, port_of_discharge = $8, payment_method = $9,
    valid_until = nullif($12::text, '')::date,
    total_amount = $13::text::numeric,
    base_amount = $14::text::numeric,
    remark = $10, updated_at = now(), updated_by = $11
WHERE tenant_id = $1 AND id = $2 AND status = 'DRAFT'
`

type UpdateQuotationHeaderParams struct {
	TenantID        int64
	ID              int64
	CustomerID      int64
	CustomerName    string
	Currency        string
	Incoterm        string
	PortOfLoading   string
	PortOfDischarge string
	PaymentMethod   string
	Remark          string
	UpdatedBy       int64
	ValidUntil      string
	TotalAmount     string
	BaseAmount      string
}

func (q *Queries) UpdateQuotationHeader(ctx context.Context, arg UpdateQuotationHeaderParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateQuotationHeader,
		arg.TenantID,
		arg.ID,
		arg.CustomerID,
		arg.CustomerName,
		arg.Currency,
		arg.Incoterm,
		arg.PortOfLoading,
		arg.PortOfDischarge,
		arg.PaymentMethod,
		arg.Remark,
		arg.UpdatedBy,
		arg.ValidUntil,
		arg.TotalAmount,
		arg.BaseAmount,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
