export const mailCustomerCopy = {
 zh: {
 title:'从邮件添加客户 / 联系人', help:'先核对自动识别的资料，再确认本次操作。公司名称和邮箱必填，姓名选填。',
 company:'公司名称', person:'联系人姓名', email:'联系人邮箱', companyPlaceholder:'搜索已有公司或填写新公司名称', optional:'未识别到可留空',
 checking:'正在查询基础数据…', result:'匹配结果', noMatch:'未找到有效匹配，将创建客户并添加联系人。',
 choose:'选择此公司', selected:'已选择', conflict:'邮箱已有归属，但公司信息不同。请选择正确归属，不会自动转移联系人。',
 ambiguous:'存在多个匹配结果，请先选择公司或联系人。', existing:'该邮箱已登记，将使用已有联系人。', addHint:'该公司尚未登记此邮箱，将添加联系人。',
 sameName:'该公司有同名联系人，请核对是否为同一个人。', supplement:'向此联系人补充邮箱（保留原邮箱）', newPerson:'是不同的人，另建联系人',
 stopped:'匹配到已停用公司或联系人，请到基础数据核对或恢复；这些资料不会被自动使用。', suppliers:'发现已有供应商资料', supplierConfirm:'确认同时建立客户身份，不改动供应商资料',
 more:'更多资料（选填）', phone:'电话', website:'网站', address:'地址', remark:'备注',
 create:'创建客户并添加联系人', add:'添加联系人', use:'使用已有联系人', addEmail:'补充邮箱并关联',
 createTip:'建立客户与联系人，并关联当前邮件。', addTip:'只向所选公司添加联系人，并关联当前邮件。', useTip:'关联已有资料，不重复建立客户或联系人。', supplementTip:'给所选联系人增加一个邮箱，保留原邮箱和历史资料。',
 required:'请填写公司名称和有效邮箱。', chooseRequired:'请先核对并选择匹配结果。', saved:'客户与联系人已确认，当前邮件已关联。', failed:'操作失败，填写的资料已保留，请重试。', retry:'重新查询', linked:'该邮件已有客户关联', retained:'原邮箱',
 confirmNew:'已核对候选，确实需要建立另一家公司', lookupFailed:'查询失败，请重试后再保存，避免重复建档。', contacts:'已有联系人', nameless:'姓名待补充', close:'取消',
 },
 en: {
 title:'Add customer / contact from email',help:'Review the extracted details before confirming. Company and email are required; contact name is optional.',
 company:'Company name',person:'Contact name',email:'Contact email',companyPlaceholder:'Find an existing company or enter a new name',optional:'Leave blank if unknown',checking:'Checking master data…',result:'Matches',noMatch:'No active match. A customer and contact will be created.',choose:'Select company',selected:'Selected',conflict:'This email belongs to a different company. Confirm the correct company; contacts will not be moved automatically.',ambiguous:'Multiple matches found. Select a company or contact.',existing:'This email is registered. The existing contact will be used.',addHint:'This email is new to this company. A contact will be added.',sameName:'A contact with this name exists. Confirm whether this is the same person.',supplement:'Add email to this contact (keep original)',newPerson:'Different person: create another contact',stopped:'Inactive records were found. Review or restore them in master data; they will not be used automatically.',suppliers:'Existing supplier records',supplierConfirm:'Also create a customer identity; keep supplier records unchanged',more:'More details (optional)',phone:'Phone',website:'Website',address:'Address',remark:'Notes',create:'Create customer and contact',add:'Add contact',use:'Use existing contact',addEmail:'Add email and link',createTip:'Create a customer and contact, and link this message.',addTip:'Add a contact to the selected company and link this message.',useTip:'Link existing records without creating duplicates.',supplementTip:'Add an email to this contact; keep the original email and history.',required:'Enter a company name and valid email.',chooseRequired:'Review and select the matching records first.',saved:'Customer and contact confirmed; message linked.',failed:'Operation failed. Your input is retained; please retry.',retry:'Check again',linked:'This message has a customer link',retained:'Original email',confirmNew:'I reviewed the candidates and need a separate company',lookupFailed:'Lookup failed. Retry before saving to avoid duplicates.',contacts:'Existing contacts',nameless:'Name not yet provided',close:'Cancel',
 },
 es: {
 title:'Añadir cliente / contacto desde correo',help:'Revise los datos reconocidos. Empresa y correo obligatorios; nombre del contacto opcional.',company:'Nombre de empresa',person:'Nombre del contacto',email:'Correo del contacto',companyPlaceholder:'Buscar empresa o escribir un nombre nuevo',optional:'Puede dejarse vacío',checking:'Consultando datos…',result:'Coincidencias',noMatch:'No hay coincidencia activa. Se creará un cliente y contacto.',choose:'Seleccionar empresa',selected:'Seleccionada',conflict:'El correo pertenece a otra empresa. Confirme la correcta; no se trasladarán contactos automáticamente.',ambiguous:'Hay varias coincidencias. Seleccione empresa o contacto.',existing:'El correo ya está registrado. Se usará el contacto existente.',addHint:'Se añadirá un contacto a esta empresa.',sameName:'Existe un contacto con este nombre. Confirme si es la misma persona.',supplement:'Añadir correo al contacto y conservar el original',newPerson:'Es otra persona: crear contacto',stopped:'Hay registros inactivos. Revíselos o restáurelos en datos maestros; no se usarán automáticamente.',suppliers:'Proveedores existentes',supplierConfirm:'Crear también identidad de cliente, sin modificar al proveedor',more:'Más datos (opcionales)',phone:'Teléfono',website:'Sitio web',address:'Dirección',remark:'Notas',create:'Crear cliente y contacto',add:'Añadir contacto',use:'Usar contacto existente',addEmail:'Añadir correo y vincular',createTip:'Crear cliente y contacto, y vincular el correo.',addTip:'Añadir contacto a la empresa y vincular el correo.',useTip:'Vincular registros existentes sin duplicarlos.',supplementTip:'Añadir correo conservando el original y el historial.',required:'Introduzca una empresa y un correo válido.',chooseRequired:'Revise y seleccione las coincidencias.',saved:'Cliente y contacto confirmados; correo vinculado.',failed:'Error. Los datos se conservan; vuelva a intentarlo.',retry:'Consultar de nuevo',linked:'El correo ya tiene un cliente vinculado',retained:'Correo original',confirmNew:'He revisado los candidatos y necesito otra empresa',lookupFailed:'Falló la consulta. Reintente antes de guardar.',contacts:'Contactos existentes',nameless:'Nombre pendiente',close:'Cancelar',
 },
}
